import { ElementUidEnum } from "./element";

export const AttributeUidEnum = {
  /* Бонус Анемо урона         */ AnemoDamageBonus: `${ElementUidEnum.Anemo}_damage_bonus`,
  /* Сопротивление Анемо       */ AnemoResistance: `${ElementUidEnum.Anemo}_resistance`,
  /* Сила атаки                */ Attack: "attack",
  /* Процент от силы атаки     */ AttackPercent: "attack_percent",
  /* Снижение времени отката   */ CooldownReduction: "cooldown_reduction",
  /* Крит. урон                */ CriticalDamage: "critical_damage",
  /* Шанс крит. попадания      */ CriticalRate: "critical_rate",
  /* Бонус Крио урона          */ CryoDamageBonus: `${ElementUidEnum.Cryo}_damage_bonus`,
  /* Сопротивление Крио        */ CryoResistance: `${ElementUidEnum.Cryo}_resistance`,
  /* Защита                    */ Defense: "defense",
  /* Процент от защиты         */ DefensePercent: "defense_percent",
  /* Бонус Дендро урона        */ DendroDamageBonus: `${ElementUidEnum.Dendro}_damage_bonus`,
  /* Сопротивление Дендро      */ DendroResistance: `${ElementUidEnum.Dendro}_resistance`,
  /* Бонус Электро урона       */ ElectroDamageBonus: `${ElementUidEnum.Electro}_damage_bonus`,
  /* Сопротивление Электро     */ ElectroResistance: `${ElementUidEnum.Electro}_resistance`,
  /* Мастерство стихий         */ ElementalMastery: "elemental_mastery",
  /* Восст. энергии            */ EnergyRecharge: "energy_recharge",
  /* Бонус Гео урона           */ GeoDamageBonus: `${ElementUidEnum.Geo}_damage_bonus`,
  /* Сопротивление Гео         */ GeoResistance: `${ElementUidEnum.Geo}_resistance`,
  /* Бонус лечения             */ HealingBonus: "healing_bonus",
  /* HP                        */ Health: "health",
  /* Процент от HP             */ HealthPercent: "health_percent",
  /* Бонус Гидро урона         */ HydroDamageBonus: `${ElementUidEnum.Hydro}_damage_bonus`,
  /* Сопротивление Гидро       */ HydroResistance: `${ElementUidEnum.Hydro}_resistance`,
  /* Бонус получаемого лечения */ IncomingHealingBonus: "incoming_healing_bonus",
  /* Бонус физ. урона          */ PhysicalDamageBonus: "physical_damage_bonus",
  /* Сопротивление физ.        */ PhysicalResistance: "physical_resistance",
  /* Бонус Пиро урона          */ PyroDamageBonus: `${ElementUidEnum.Pyro}_damage_bonus`,
  /* Сопротивление Пиро        */ PyroResistance: `${ElementUidEnum.Pyro}_resistance`,
  /* Прочность щита            */ ShieldStrength: "shield_strength",
  /* Выносливость              */ Stamina: "stamina",
} as const;
