export const AttributeUidEnum = {
  /* Бонус Анемо урона         */ AnemoDamageBonus: "anemo_damage_bonus",
  /* Сопротивление Анемо       */ AnemoResistance: "anemo_resistance",
  /* Сила атаки                */ Attack: "attack",
  /* Процент от силы атаки     */ AttackPercent: "attack_percent",
  /* Снижение времени отката   */ CooldownReduction: "cooldown_reduction",
  /* Крит. урон                */ CriticalDamage: "critical_damage",
  /* Шанс крит. попадания      */ CriticalRate: "critical_rate",
  /* Бонус Крио урона          */ CryoDamageBonus: "cryo_damage_bonus",
  /* Сопротивление Крио        */ CryoResistance: "cryo_resistance",
  /* Защита                    */ Defense: "defense",
  /* Процент от защиты         */ DefensePercent: "defense_percent",
  /* Бонус Дендро урона        */ DendroDamageBonus: "dendro_damage_bonus",
  /* Сопротивление Дендро      */ DendroResistance: "dendro_resistance",
  /* Бонус Электро урона       */ ElectroDamageBonus: "electro_damage_bonus",
  /* Сопротивление Электро     */ ElectroResistance: "electro_resistance",
  /* Мастерство стихий         */ ElementalMastery: "elemental_mastery",
  /* Восст. энергии            */ EnergyRecharge: "energy_recharge",
  /* Бонус Гео урона           */ GeoDamageBonus: "geo_damage_bonus",
  /* Сопротивление Гео         */ GeoResistance: "geo_resistance",
  /* Бонус лечения             */ HealingBonus: "healing_bonus",
  /* HP                        */ Health: "health",
  /* Процент от HP             */ HealthPercent: "health_percent",
  /* Бонус Гидро урона         */ HydroDamageBonus: "hydro_damage_bonus",
  /* Сопротивление Гидро       */ HydroResistance: "hydro_resistance",
  /* Бонус получаемого лечения */ IncomingHealingBonus: "incoming_healing_bonus",
  /* Бонус физ. урона          */ PhysicalDamageBonus: "physical_damage_bonus",
  /* Сопротивление физ.        */ PhysicalResistance: "physical_resistance",
  /* Бонус Пиро урона          */ PyroDamageBonus: "pyro_damage_bonus",
  /* Сопротивление Пиро        */ PyroResistance: "pyro_resistance",
  /* Прочность щита            */ ShieldStrength: "shield_strength",
  /* Выносливость              */ Stamina: "stamina",
} as const;
