export const AttributeUidEnum = {
  /* Бонус Анемо урона     */ AnemoDamageBonus: "anemo_damage_bonus",
  /* Сила атаки            */ Attack: "attack",
  /* Крит. урон            */ CriticalDamage: "critical_damage",
  /* Шанс крит. попадания  */ CriticalHitChance: "critical_hit_chance",
  /* Бонус Крио урона      */ CryoDamageBonus: "cryo_damage_bonus",
  /* Защита                */ Defense: "defense",
  /* Бонус Дендро урона    */ DendroDamageBonus: "dendro_damage_bonus",
  /* Бонус Электро урона   */ ElectroDamageBonus: "electro_damage_bonus",
  /* Мастерство стихий     */ ElementalMastery: "elemental_mastery",
  /* Восст. энергии        */ EnergyRestoration: "energy_restoration",
  /* Бонус Гео урона       */ GeoDamageBonus: "geo_damage_bonus",
  /* HP                    */ Health: "health",
  /* Бонус Гидро урона     */ HydroDamageBonus: "hydro_damage_bonus",
  /* Процент от силы атаки */ PercentageOfAttackPower: "percentage_of_attack_power",
  /* Процент от HP         */ PercentageOfHP: "percentage_of_hp",
  /* Процент от защиты     */ PercentageOfProtection: "percentage_of_protection",
  /* Бонус физ. урона      */ PhysicalDamageBonus: "physical_damage_bonus",
  /* Бонус Пиро урона      */ PyroDamageBonus: "pyro_damage_bonus",
  /* Бонус лечения         */ TreatmentBonus: "treatment_bonus",
} as const;
