export const CharacterUidEnum = {
  /* Эмбер       */ Amber: "amber",
  /* Арлекино    */ Arlecchino: "arlecchino",
  /* Барбара     */ Barbara: "barbara",
  /* Бэй Доу     */ Beidou: "beidou",
  /* Беннет      */ Bennett: "bennett",
  /* Кандакия    */ Candace: "candace",
  /* Шарлотта    */ Charlotte: "charlotte",
  /* Шеврёз      */ Chevreuse: "chevreuse",
  /* Чун Юнь     */ Chongyun: "chongyun",
  /* Коллеи      */ Collei: "collei",
  /* Сайно       */ Cyno: "cyno",
  /* Далия       */ Dahlia: "dahlia",
  /* Дэхья       */ Dehya: "dehya",
  /* Дилюк       */ Diluc: "diluc",
  /* Диона       */ Diona: "diona",
  /* Дори        */ Dori: "dori",
  /* Эскофье     */ Escoffier: "escoffier",
  /* Эола        */ Eula: "eula",
  /* Фарузан     */ Faruzan: "faruzan",
  /* Фишль       */ Fischl: "fischl",
  /* Фремине     */ Freminet: "freminet",
  /* Фурина      */ Furina: "furina",
  /* Гань Юй     */ Ganyu: "ganyu",
  /* Ху Тао      */ HuTao: "hu_tao",
  /* Иансан      */ Iansan: "iansan",
  /* Джинн       */ Jean: "jean",
  /* Кадзуха     */ KaedeharaKazuha: "kaedehara_kazuha",
  /* Кэйа        */ Kaeya: "kaeya",
  /* Аяка        */ KamisatoAyaka: "kamisato_ayaka",
  /* Аято        */ KamisatoAyato: "kamisato_ayato",
  /* Кэ Цин      */ Keqing: "keqing",
  /* Кли         */ Klee: "klee",
  /* Сара        */ KujouSara: "kujou_sara",
  /* Куки Синобу */ KukiShinobu: "kuki_shinobu",
  /* Лайла       */ Layla: "layla",
  /* Лиза        */ Lisa: "lisa",
  /* Линетт      */ Lynette: "lynette",
  /* Лини        */ Lyney: "lyney",
  /* Мавуика     */ Mavuika: "mavuika",
  /* Мика        */ Mika: "mika",
  /* Мона        */ Mona: "mona",
  /* Нахида      */ Nahida: "nahida",
  /* Нёвиллет    */ Neuvillette: "neuvillette",
  /* Нилу        */ Nilou: "nilou",
  /* Ци Ци       */ Qiqi: "qiqi",
  /* Райдэн      */ RaidenShogun: "raiden_shogun",
  /* Рэйзор      */ Razor: "razor",
  /* Розария     */ Rosaria: "rosaria",
  /* Кокоми      */ SangonomiyaKokomi: "sangonomiya_kokomi",
  /* Саю         */ Sayu: "sayu",
  /* Шэнь Хэ     */ Shenhe: "shenhe",
  /* Хэйдзо      */ ShikanoinHeizou: "shikanoin_heizou",
  /* Скирк       */ Skirk: "skirk",
  /* Сахароза    */ Sucrose: "sucrose",
  /* Тарталья    */ Tartaglia: "tartaglia",
  /* Тома        */ Thoma: "thoma",
  /* Вареса      */ Varesa: "varesa",
  /* Венти       */ Venti: "venti",
  /* Странник    */ Wanderer: "wanderer",
  /* Ризли       */ Wriothesley: "wriothesley",
  /* Сян Лин     */ Xiangling: "xiangling",
  /* Сяо         */ Xiao: "xiao",
  /* Шилонен     */ Xilonen: "xilonen",
  /* Син Цю      */ Xingqiu: "xingqiu",
  /* Синь Янь    */ Xinyan: "xinyan",
  /* Яэ Мико     */ YaeMiko: "yae_miko",
  /* Янь Фэй     */ Yanfei: "yanfei",
  /* Е Лань      */ Yelan: "yelan",
  /* Ёимия       */ Yoimiya: "yoimiya",
} as const;
