export const CharacterUidEnum = {
  /* Арлекино    */ Arlecchino: "arlecchino",
  /* Беннет      */ Bennett: "bennett",
  /* Шеврёз      */ Chevreuse: "chevreuse",
  /* Коллеи      */ Collei: "collei",
  /* Сайно       */ Cyno: "cyno",
  /* Далия       */ Dahlia: "dahlia",
  /* Эскофье     */ Escoffier: "escoffier",
  /* Фишль       */ Fischl: "fischl",
  /* Фурина      */ Furina: "furina",
  /* Иансан      */ Iansan: "iansan",
  /* Куки Синобу */ KukiShinobu: "kuki_shinobu",
  /* Лайла       */ Layla: "layla",
  /* Лини        */ Lyney: "lyney",
  /* Мавуика     */ Mavuika: "mavuika",
  /* Мика        */ Mika: "mika",
  /* Нахида      */ Nahida: "nahida",
  /* Нёвиллет    */ Neuvillette: "neuvillette",
  /* Ци Ци       */ Qiqi: "qiqi",
  /* Розария     */ Rosaria: "rosaria",
  /* Скирк       */ Skirk: "skirk",
  /* Сахароза    */ Sucrose: "sucrose",
  /* Тарталья    */ Tartaglia: "tartaglia",
  /* Вареса      */ Varesa: "varesa",
  /* Ризли       */ Wriothesley: "wriothesley",
  /* Сян Лин     */ Xiangling: "xiangling",
  /* Шилонен     */ Xilonen: "xilonen",
  /* Син Цю      */ Xingqiu: "xingqiu",
} as const;
