export const CharacterUidEnum = {
  /* Альбедо                  */ Albedo: "albedo",
  /* Аль-Хайтам               */ Alhaitham: "alhaitham",
  /* Эмбер                    */ Amber: "amber",
  /* Итто                     */ AratakiItto: "arataki_itto",
  /* Арлекино                 */ Arlecchino: "arlecchino",
  /* Бай Чжу                  */ Baizhu: "baizhu",
  /* Барбара                  */ Barbara: "barbara",
  /* Бэй Доу                  */ Beidou: "beidou",
  /* Беннет                   */ Bennett: "bennett",
  /* Кандакия                 */ Candace: "candace",
  /* Шарлотта                 */ Charlotte: "charlotte",
  /* Шеврёз                   */ Chevreuse: "chevreuse",
  /* Чун Юнь                  */ Chongyun: "chongyun",
  /* Ситлали                  */ Citlali: "citlali",
  /* Коллеи                   */ Collei: "collei",
  /* Сайно                    */ Cyno: "cyno",
  /* Далия                    */ Dahlia: "dahlia",
  /* Дэхья                    */ Dehya: "dehya",
  /* Дилюк                    */ Diluc: "diluc",
  /* Диона                    */ Diona: "diona",
  /* Дори                     */ Dori: "dori",
  /* Эскофье                  */ Escoffier: "escoffier",
  /* Эола                     */ Eula: "eula",
  /* Фарузан                  */ Faruzan: "faruzan",
  /* Фишль                    */ Fischl: "fischl",
  /* Фремине                  */ Freminet: "freminet",
  /* Фурина                   */ Furina: "furina",
  /* Гань Юй                  */ Ganyu: "ganyu",
  /* Горо                     */ Gorou: "gorou",
  /* Ху Тао                   */ HuTao: "hu_tao",
  /* Иансан                   */ Iansan: "iansan",
  /* Джинн                    */ Jean: "jean",
  /* Кадзуха                  */ KaedeharaKazuha: "kaedehara_kazuha",
  /* Кэйа                     */ Kaeya: "kaeya",
  /* Аяка                     */ KamisatoAyaka: "kamisato_ayaka",
  /* Аято                     */ KamisatoAyato: "kamisato_ayato",
  /* Кавех                    */ Kaveh: "kaveh",
  /* Кэ Цин                   */ Keqing: "keqing",
  /* Кирара                   */ Kirara: "kirara",
  /* Кли                      */ Klee: "klee",
  /* Сара                     */ KujouSara: "kujou_sara",
  /* Синобу                   */ KukiShinobu: "kuki_shinobu",
  /* Лайла                    */ Layla: "layla",
  /* Лиза                     */ Lisa: "lisa",
  /* Линетт                   */ Lynette: "lynette",
  /* Лини                     */ Lyney: "lyney",
  /* Мавуика                  */ Mavuika: "mavuika",
  /* Мика                     */ Mika: "mika",
  /* Мона                     */ Mona: "mona",
  /* Нахида                   */ Nahida: "nahida",
  /* Навия                    */ Navia: "navia",
  /* Нёвиллет                 */ Neuvillette: "neuvillette",
  /* Нилу                     */ Nilou: "nilou",
  /* Нин Гуан                 */ Ningguang: "ningguang",
  /* Ноэлль                   */ Noelle: "noelle",
  /* Оророн                   */ Ororon: "ororon",
  /* Ци Ци                    */ Qiqi: "qiqi",
  /* Райдэн                   */ RaidenShogun: "raiden_shogun",
  /* Рэйзор                   */ Razor: "razor",
  /* Розария                  */ Rosaria: "rosaria",
  /* Кокоми                   */ SangonomiyaKokomi: "sangonomiya_kokomi",
  /* Саю                      */ Sayu: "sayu",
  /* Шэнь Хэ                  */ Shenhe: "shenhe",
  /* Хэйдзо                   */ ShikanoinHeizou: "shikanoin_heizou",
  /* Скирк                    */ Skirk: "skirk",
  /* Сахароза                 */ Sucrose: "sucrose",
  /* Тарталья                 */ Tartaglia: "tartaglia",
  /* Тома                     */ Thoma: "thoma",
  /* Тигнари                  */ Tighnari: "tighnari",
  /* Путешественник (Анемо)   */ TravelerAnemo: "traveler_anemo",
  /* Путешественник (Дендро)  */ TravelerDendro: "traveler_dendro",
  /* Путешественник (Электро) */ TravelerElectro: "traveler_electro",
  /* Путешественник (Гео)     */ TravelerGeo: "traveler_geo",
  /* Путешественник (Гидро)   */ TravelerHydro: "traveler_hydro",
  /* Путешественник (Пиро)    */ TravelerPyro: "traveler_pyro",
  /* Вареса                   */ Varesa: "varesa",
  /* Венти                    */ Venti: "venti",
  /* Странник                 */ Wanderer: "wanderer",
  /* Ризли                    */ Wriothesley: "wriothesley",
  /* Сян Лин                  */ Xiangling: "xiangling",
  /* Сяо                      */ Xiao: "xiao",
  /* Шилонен                  */ Xilonen: "xilonen",
  /* Син Цю                   */ Xingqiu: "xingqiu",
  /* Синь Янь                 */ Xinyan: "xinyan",
  /* Яэ Мико                  */ YaeMiko: "yae_miko",
  /* Янь Фэй                  */ Yanfei: "yanfei",
  /* Яо Яо                    */ Yaoyao: "yaoyao",
  /* Е Лань                   */ Yelan: "yelan",
  /* Ёимия                    */ Yoimiya: "yoimiya",
  /* Юнь Цзинь                */ YunJin: "yun_jin",
  /* Чжун Ли                  */ Zhongli: "zhongli",
} as const;
