import { ElementKeys } from "./element";

export const StatKeys = {
  /* Бонус Анемо урона         */ AnemoDMGBonus: `${ElementKeys.Anemo}_dmg_bonus`,
  /* Сопротивление Анемо       */ AnemoResistance: `${ElementKeys.Anemo}_resistance`,
  /* Сила атаки                */ ATK: "atk",
  /* Процент от силы атаки     */ ATKPercentage: "atk_percentage",
  /* Снижение времени отката   */ CooldownReduction: "cooldown_reduction",
  /* Крит. урон                */ CRITDMG: "crit_dmg",
  /* Шанс крит. попадания      */ CRITRate: "crit_rate",
  /* Бонус Крио урона          */ CryoDMGBonus: `${ElementKeys.Cryo}_dmg_bonus`,
  /* Сопротивление Крио        */ CryoResistance: `${ElementKeys.Cryo}_resistance`,
  /* Защита                    */ Defense: "defense",
  /* Процент от защиты         */ DefensePercent: "defense_percent",
  /* Бонус Дендро урона        */ DendroDMGBonus: `${ElementKeys.Dendro}_dmg_bonus`,
  /* Сопротивление Дендро      */ DendroResistance: `${ElementKeys.Dendro}_resistance`,
  /* Бонус Электро урона       */ ElectroDMGBonus: `${ElementKeys.Electro}_dmg_bonus`,
  /* Сопротивление Электро     */ ElectroResistance: `${ElementKeys.Electro}_resistance`,
  /* Мастерство стихий         */ ElementalMastery: "elemental_mastery",
  /* Восст. энергии            */ EnergyRecharge: "energy_recharge",
  /* Бонус Гео урона           */ GeoDMGBonus: `${ElementKeys.Geo}_dmg_bonus`,
  /* Сопротивление Гео         */ GeoResistance: `${ElementKeys.Geo}_resistance`,
  /* Бонус лечения             */ HealingBonus: "healing_bonus",
  /* HP                        */ HP: "hp",
  /* Процент от HP             */ HPPercentage: "hp_percentage",
  /* Бонус Гидро урона         */ HydroDMGBonus: `${ElementKeys.Hydro}_dmg_bonus`,
  /* Сопротивление Гидро       */ HydroResistance: `${ElementKeys.Hydro}_resistance`,
  /* Бонус получаемого лечения */ IncomingHealingBonus: "incoming_healing_bonus",
  /* Бонус физ. урона          */ PhysicalDMGBonus: "physical_dmg_bonus",
  /* Сопротивление физ.        */ PhysicalResistance: "physical_resistance",
  /* Бонус Пиро урона          */ PyroDMGBonus: `${ElementKeys.Pyro}_dmg_bonus`,
  /* Сопротивление Пиро        */ PyroResistance: `${ElementKeys.Pyro}_resistance`,
  /* Прочность щита            */ ShieldStrength: "shield_strength",
  /* Выносливость              */ Stamina: "stamina",
} as const;
