export const WeaponUidEnum = {
  /* Тысяча ослепительных солнц            */ AThousandBlazingSuns: "a_thousand_blazing_suns",
  /* Отпущение грехов                      */ Absolution: "absolution",
  /* Акуомару                              */ Akuoumaru: "akuoumaru",
  /* Пепельный рог                         */ AshGravenDrinkingHorn: "ash_graven_drinking_horn",
  /* Лазурное сияние                       */ Azurelight: "azurelight",
  /* Баллада фьордов                       */ BalladOfTheFjords: "ballad_of_the_fjords",
  /* Маяк тростникового моря               */ BeaconOfTheReedSea: "beacon_of_the_reed_sea",
  /* Черногорский длинный меч              */ BlackcliffLongsword: "blackcliff_longsword",
  /* Черногорская пика                     */ BlackcliffPole: "blackcliff_pole",
  /* Черногорская бритва                   */ BlackcliffSlasher: "blackcliff_slasher",
  /* Бедствие Эшу                          */ CalamityOfEshu: "calamity_of_eshu",
  /* Усмиритель бед                        */ CalamityQueller: "calamity_queller",
  /* Казначейский надзор                   */ CashflowSupervision: "cashflow_supervision",
  /* Очертания алой луны                   */ CrimsonMoonsSemblance: "crimson_moons_semblance",
  /* Смертельный бой                       */ Deathmatch: "deathmatch",
  /* Диалог пустынных мудрецов             */ DialoguesOfTheDesertSages: "dialogues_of_the_desert_sages",
  /* Гроза драконов                        */ DragonsBane: "dragons_bane",
  /* Сияющая жатва                         */ EngulfingLightning: "engulfing_lightning",
  /* Вечное лунное сияние                  */ EverlastingMoonglow: "everlasting_moonglow",
  /* Клык Горного короля                   */ FangOfTheMountainKing: "fang_of_the_mountain_king",
  /* Копьё Фавония                         */ FavoniusLance: "favonius_lance",
  /* Меч Фавония                           */ FavoniusSword: "favonius_sword",
  /* Осквернённое желание                  */ FesteringDesire: "festering_desire",
  /* Грандиозный финал глубин              */ FinaleOfTheDeep: "finale_of_the_deep",
  /* Перевозчик Флёв Сандр                 */ FleuveCendreFerryman: "fleuve_cendre_ferryman",
  /* Сверкание чистых вод                  */ FlowingPurity: "flowing_purity",
  /* Харан гэппаку фуцу                    */ HaranGeppakuFutsu: "haran_geppaku_futsu",
  /* Предвестник зари                      */ HarbingerOfDawn: "harbinger_of_dawn",
  /* Великолепие лазурного свода           */ JadefallsSplendor: "jadefalls_splendor",
  /* Истина кагура                         */ KagurasVerity: "kaguras_verity",
  /* Ключ Хадж-нисут                       */ KeyOfKhajNisut: "key_of_khaj_nisut",
  /* Крест-копьё Китаин                    */ KitainCrossSpear: "kitain_cross_spear",
  /* Свет лиственного разреза              */ LightOfFoliarIncision: "light_of_foliar_incision",
  /* Каменное копьё                        */ LithicSpear: "lithic_spear",
  /* Молитва святым ветрам                 */ LostPrayerToTheSacredWinds: "lost_prayer_to_the_sacred_winds",
  /* Элегия Люмидус                        */ LumidouceElegy: "lumidouce_elegy",
  /* Благодатный владыка вод               */ LuxuriousSeaLord: "luxurious_sea_lord",
  /* Цветок в латах                        */ MailedFlower: "mailed_flower",
  /* Аквамарин Махайры                     */ MakhairaAquamarine: "makhaira_aquamarine",
  /* Копьё послания ветров                 */ MissiveWindspear: "missive_windspear",
  /* Рассекающий туман                     */ MistsplitterReforged: "mistsplitter_reforged",
  /* Песнь патруля пиков                   */ PeakPatrolSong: "peak_patrol_song",
  /* Драгоценный омут                      */ PrimordialJadeCutter: "primordial_jade_cutter",
  /* Нефритовый коршун                     */ PrimordialJadeWingedSpear: "primordial_jade_winged_spear",
  /* Бур рудоискателя                      */ ProspectorsDrill: "prospectors_drill",
  /* Прототип: Янтарь                      */ PrototypeAmber: "prototype_amber",
  /* Прототип: Архаичный                   */ PrototypeArchaic: "prototype_archaic",
  /* Краснорогий камнеруб                  */ RedhornStonethresher: "redhorn_stonethresher",
  /* Справедливая награда                  */ RightfulReward: "rightful_reward",
  /* Кольцо Яшче                           */ RingOfYaxche: "ring_of_yaxche",
  /* Жертвенный нефрит                     */ SacrificialJade: "sacrificial_jade",
  /* Церемониальный меч                    */ SacrificialSword: "sacrificial_sword",
  /* Деревянный клинок                     */ SapwoodBlade: "sapwood_blade",
  /* Меч драконьей кости                   */ SerpentSpine: "serpent_spine",
  /* Небесное величие                      */ SkywardPride: "skyward_pride",
  /* Небесная ось                          */ SkywardSpine: "skyward_spine",
  /* Песнь разбитых сосен                  */ SongOfBrokenPines: "song_of_broken_pines",
  /* Блеск тихих вод                       */ SplendorOfTranquilWaters: "splendor_of_tranquil_waters",
  /* Посох Хомы                            */ StaffOfHoma: "staff_of_homa",
  /* Посох алых песков                     */ StaffOfTheScarletSands: "staff_of_the_scarlet_sands",
  /* Кромсатель пиков                      */ SummitShaper: "summit_shaper",
  /* Лови волну                            */ SurfsUp: "surfs_up",
  /* Симфонист ароматов                    */ SymphonistOfScents: "symphonist_of_scents",
  /* Говорящая палица                      */ TalkingStick: "talking_stick",
  /* Тамаюратэй но оханаси                 */ TamayurateiNoOhanashi: "tamayuratei_no_ohanashi",
  /* Чёрный меч                            */ TheBlackSword: "the_black_sword",
  /* Верфь                                 */ TheDockhandsAssistant: "the_dockhands_assistant",
  /* Бесструнный                           */ TheStringless: "the_stringless",
  /* Некованый                             */ TheUnforged: "the_unforged",
  /* Песнь странника                       */ TheWidsith: "the_widsith",
  /* Тень волны                            */ TidalShadow: "tidal_shadow",
  /* Обряд вечного течения                 */ TomeOfTheEternalFlow: "tome_of_the_eternal_flow",
  /* Воспоминания Тулайтуллы               */ TulaytullahsRemembrance: "tulaytullahs_remembrance",
  /* «Магический супермеч высшего владыки» */ UltimateOverlordsMegaMagicSword: "ultimate_overlords_mega_magic_sword",
  /* Ураку мисугири                        */ UrakuMisugiri: "uraku_misugiri",
  /* Вердикт                               */ Verdict: "verdict",
  /* Переливающиеся чаяния                 */ VividNotions: "vivid_notions",
  /* Покоритель вихря                      */ VortexVanquisher: "vortex_vanquisher",
  /* Белая кисть                           */ WhiteTassel: "white_tassel",
  /* Волчий клык                           */ WolfFang: "wolf_fang",
  /* Волчья погибель                       */ WolfsGravestone: "wolfs_gravestone",
  /* Лунное сияние ксифоса                 */ XiphosMoonlight: "xiphos_moonlight",
} as const;
