import type { IArtifactSet } from "./types";
import type { TDungeonKey } from "../dungeons/types";
import { ArtifactSetKeys } from "./enums";
import { ArtifactSlotKeys } from "../artifact-slots/enums";
import { CArtifactSet } from "./classes";
import { DungeonKeys } from "../dungeons/enums";
import dungeons from "../dungeons/data";

const ArtifactSetSource = {
  Alchemy: "Мистическое подношение (Алхимия)",
  Dungeon: (key: TDungeonKey) => `Подземелье «${dungeons[key].name}»`,
};

export default {
  [ArtifactSetKeys.ArchaicPetra]: CArtifactSet.init([
    ArtifactSetKeys.ArchaicPetra,
    "Архаичный камень",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.DomainOfGuyun), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Гео урона на 15%.",
      4: "Подобранный элементальный осколок, образованный реакцией Кристалл, увеличивает бонус элементального урона соответствующего элемента всех членов отряда на 35% в течение 10 сек. Одновременно можно иметь бонус урона только одного элемента.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветок скальных трещин",
      [ArtifactSlotKeys.Plume]: "Перо зубчатых пиков",
      [ArtifactSlotKeys.Sands]: "Часы из прочного нефрита",
      [ArtifactSlotKeys.Goblet]: "Кубок из резного камня",
      [ArtifactSlotKeys.Circlet]: "Маска из одинокого базальта",
    },
  ]),
  [ArtifactSetKeys.BlizzardStrayer]: CArtifactSet.init([
    ArtifactSetKeys.BlizzardStrayer,
    "Заблудший в метели",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.PeakOfVindagnyr), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Крио урона на 15%.",
      4: "Атаки по противникам с эффектом Крио увеличивают шанс крит. попадания на 20%. Если противник имеет статус Заморозка, то дополнительно увеличивает шанс крит. попадания на 20%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Занесённая снегом память",
      [ArtifactSlotKeys.Plume]: "Решимость крушителя льда",
      [ArtifactSlotKeys.Sands]: "Гибель замёрзшей родины",
      [ArtifactSlotKeys.Goblet]: "Морозная гордость",
      [ArtifactSlotKeys.Circlet]: "Эхо осколков инея",
    },
  ]),
  [ArtifactSetKeys.BloodstainedChivalry]: CArtifactSet.init([
    ArtifactSetKeys.BloodstainedChivalry,
    "Рыцарь крови",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.ClearPoolAndMountainCavern), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает физ. урон на 25%.",
      4: "После победы над противником увеличивает урон заряженной атаки на 50% и обнуляет стоимость выносливости заряженной атаки на 10 сек.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Железное сердце рыцаря крови",
      [ArtifactSlotKeys.Plume]: "Перо рыцаря крови",
      [ArtifactSlotKeys.Sands]: "Час долга рыцаря крови",
      [ArtifactSlotKeys.Goblet]: "Кубок рыцаря крови",
      [ArtifactSlotKeys.Circlet]: "Железная маска рыцаря крови",
    },
  ]),
  [ArtifactSetKeys.CrimsonWitchOfFlames]: CArtifactSet.init([
    ArtifactSetKeys.CrimsonWitchOfFlames,
    "Горящая алая ведьма",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.HiddenPalaceOfZhouFormula), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Пиро урона на 15%.",
      4: "Увеличивает урон статусов Перегрузка, Горение и Цветение на 40%, а урон статусов Пар и Таяние - на 15%. Использование элементального навыка увеличивает эффекты набора из двух вещей на 50% в течение 10 сек. Может складываться до 3 раз.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Ведьмин огненный цветок",
      [ArtifactSlotKeys.Plume]: "Пылающее ведьмино перо",
      [ArtifactSlotKeys.Sands]: "Ведьмин последний час",
      [ArtifactSlotKeys.Goblet]: "Пламя ведьминого сердца",
      [ArtifactSlotKeys.Circlet]: "Тлеющая ведьмина шляпа",
    },
  ]),
  [ArtifactSetKeys.DeepwoodMemories]: CArtifactSet.init([
    ArtifactSetKeys.DeepwoodMemories,
    "Воспоминания дремучего леса",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.SpireOfSolitaryEnlightenment), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Дендро урона на 15%.",
      4: "Попадание элементальным навыком или взрывом стихии снижает Дендро сопротивление врага на 30% на 8 сек. Этот эффект срабатывает, даже если экипированный этими артефактами персонаж не на поле боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Странник лабиринта",
      [ArtifactSlotKeys.Plume]: "Мудрец лозы",
      [ArtifactSlotKeys.Sands]: "Час осмысления",
      [ArtifactSlotKeys.Goblet]: "Лампа заблудших",
      [ArtifactSlotKeys.Circlet]: "Лавровый венец",
    },
  ]),
  [ArtifactSetKeys.DesertPavilionChronicle]: CArtifactSet.init([
    ArtifactSetKeys.DesertPavilionChronicle,
    "Хроники Чертогов в пустыне",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.CityOfGold), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Анемо урона на 15%.",
      4: "Попадание заряженной атакой на 15 сек. повышает скорость обычной атаки на 10%, а урон обычной атаки, заряженной атаки и атаки в падении — на 40%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Рождение города королей",
      [ArtifactSlotKeys.Plume]: "Конец золотого царства",
      [ArtifactSlotKeys.Sands]: "Часы потерянного пути",
      [ArtifactSlotKeys.Goblet]: "Хранитель дивной мечты",
      [ArtifactSlotKeys.Circlet]: "Наследие пустынной знати",
    },
  ]),
  [ArtifactSetKeys.EchoesOfAnOffering]: CArtifactSet.init([
    ArtifactSetKeys.EchoesOfAnOffering,
    "Отголоски подношения",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.TheLostValley), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает силу атаки на 18%.",
      4: "Попадания обычной атакой с 36% шансом активируют Ритуал долины: урон обычной атаки повышается на 70% от силы атаки. Через 0,05 сек. после нанесения урона обычной атакой эффект исчезает. Если обычной атаке не удалось активировать этот эффект, шанс его активации следующим попаданием возрастает на 20%. Шанс активации возникает не чаще одного раза в 0,2 сек.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветок призрачного аромата",
      [ArtifactSlotKeys.Plume]: "Нефритовый листок",
      [ArtifactSlotKeys.Sands]: "Символ подношения",
      [ArtifactSlotKeys.Goblet]: "Чаша истока",
      [ArtifactSlotKeys.Circlet]: "Серьги текучести",
    },
  ]),
  [ArtifactSetKeys.EmblemOfSeveredFate]: CArtifactSet.init([
    ArtifactSetKeys.EmblemOfSeveredFate,
    "Эмблема рассечённой судьбы",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.MomijiDyedCourt), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает скорость восстановления энергии на 20%.",
      4: "Увеличивает урон взрыва стихий на величину, равную 25% от значения восстановления энергии. Эффект можно увеличить максимум до 75%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Великолепная цуба",
      [ArtifactSlotKeys.Plume]: "Обрезанное перо",
      [ArtifactSlotKeys.Sands]: "Клетка грозовых облаков",
      [ArtifactSlotKeys.Goblet]: "Алый сосуд",
      [ArtifactSlotKeys.Circlet]: "Украшенный кабуто",
    },
  ]),
  [ArtifactSetKeys.FinaleOfTheDeepGalleries]: CArtifactSet.init([
    ArtifactSetKeys.FinaleOfTheDeepGalleries,
    "Финал галерей глубин",
    [4, 5],
    "Подземелье «Заброшенный причал»",
    {
      2: "Даёт 15% бонус Крио урона.",
      4: "Когда энергия экипированного персонажа равна 0, урон обычной атаки и взрыва стихии повышается на 60%. После того как экипированный персонаж наносит урон обычной атакой, данный эффект на 6 сек. перестаёт применяться для взрыва стихии. После того как экипированный персонаж наносит урон взрывом стихии, данный эффект на 6 сек. перестаёт применяться для обычной атаки. Этот эффект может возникнуть, даже если экипированный персонаж вне поля боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Отголоски песни галерей глубин",
      [ArtifactSlotKeys.Plume]: "Дальние странствия галерей глубин",
      [ArtifactSlotKeys.Sands]: "Часы забвения галерей глубин",
      [ArtifactSlotKeys.Goblet]: "Ниспосланный пир галерей глубин",
      [ArtifactSlotKeys.Circlet]: "Утраченная корона галерей глубин",
    },
  ]),
  [ArtifactSetKeys.FlowerOfParadiseLost]: CArtifactSet.init([
    ArtifactSetKeys.FlowerOfParadiseLost,
    "Цветок потерянного рая",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.CityOfGold), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает мастерство стихий на 80 ед.",
      4: "Увеличивает урон реакций Бутонизация, Вегетация и Цветение экипированного этим набором персонажа на 40%. Кроме того, активация реакций Бутонизация, Вегетация и Цветение экипированным этим набором персонажем усилит этот эффект на 25%. Каждое суммирование длится 10 сек. Эффект складывается до 4 раз, может возникнуть раз в 1 сек. и активируется, даже если экипированный этим набором персонаж не активен.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Великолепие Ай-Ханум",
      [ArtifactSlotKeys.Plume]: "Угасающий пир",
      [ArtifactSlotKeys.Sands]: "Застывшее мгновение",
      [ArtifactSlotKeys.Goblet]: "Магический сосуд хранителя тайн",
      [ArtifactSlotKeys.Circlet]: "Аметистовый венец",
    },
  ]),
  [ArtifactSetKeys.FragmentOfHarmonicWhimsy]: CArtifactSet.init([
    ArtifactSetKeys.FragmentOfHarmonicWhimsy,
    "Фрагмент гармонической фантазии",
    [4, 5],
    "Подземелье «Обветшалый театр»",
    {
      2: "Увеличивает силу атаки на 18%.",
      4: "Когда значение Долга жизни увеличивается или уменьшается, наносимый персонажем урон увеличивается на 18% на 6 сек. Эффект может складываться до 3 раз.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Увертюра стройной симфонии",
      [ArtifactSlotKeys.Plume]: "Ночные раздумья древнего моря",
      [ArtifactSlotKeys.Sands]: "Скерцо поворотов судьбы",
      [ArtifactSlotKeys.Goblet]: "Неистовая рапсодия ихора",
      [ArtifactSlotKeys.Circlet]: "Вальс увядших фантазий",
    },
  ]),
  [ArtifactSetKeys.GildedDreams]: CArtifactSet.init([
    ArtifactSetKeys.GildedDreams,
    "Позолоченные сны",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.SpireOfSolitaryEnlightenment), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает мастерство стихий на 80 ед.",
      4: "На 8 сек. после вызова элементальной реакции согласно элементам других персонажей в отряде экипированный этими артефактами персонаж получает следующие усиления: сила атаки повышается на 14% за каждого персонажа с таким же элементом, как и у экипированного персонажа; мастерство стихий повышается на 50 ед. за каждого персонажа с иным элементом. Каждое из этих усилений при подсчёте включает до 3 персонажей. Эффект может возникнуть один раз в 8 сек. Срабатывает, даже если экипированный этими артефактами персонаж не на поле боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Сон железного цветка",
      [ArtifactSlotKeys.Plume]: "Перо суждения",
      [ArtifactSlotKeys.Sands]: "Золотые годы",
      [ArtifactSlotKeys.Goblet]: "Последний медовый пир",
      [ArtifactSlotKeys.Circlet]: "Тень Короля песков",
    },
  ]),
  [ArtifactSetKeys.GladiatorsFinale]: CArtifactSet.init([
    ArtifactSetKeys.GladiatorsFinale,
    "Конец гладиатора",
    [4, 5],
    [
      "Награды с босса в мире за 40 первородной смолы",
      "Награды за выполнение заданий во вкладке Опыта (главы 8 и 9)",
      "Подземелья наказания (еженедельные боссы)",
      ArtifactSetSource.Alchemy,
    ],
    {
      2: "Увеличивает силу атаки на 18%.",
      4: "Увеличивает урон обычной атаки на 35%, если персонаж использует одноручное, двуручное или древковое оружие.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Ностальгия гладиатора",
      [ArtifactSlotKeys.Plume]: "Судьба гладиатора",
      [ArtifactSlotKeys.Sands]: "Стремление гладиатора",
      [ArtifactSlotKeys.Goblet]: "Пьянство гладиатора",
      [ArtifactSlotKeys.Circlet]: "Триумф гладиатора",
    },
  ]),
  [ArtifactSetKeys.GoldenTroupe]: CArtifactSet.init([
    ArtifactSetKeys.GoldenTroupe,
    "Золотая труппа",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.DenouementOfSin), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает урон элементального навыка на 20%.",
      4: "Увеличивает урон элементального навыка на 25%. Кроме того, когда персонаж не на поле боя, урон элементального навыка дополнительно увеличивается на 25%. Через 2 сек. после вступления в бой эффект исчезает.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Вариация золотой песни",
      [ArtifactSlotKeys.Plume]: "Перо золотой птицы",
      [ArtifactSlotKeys.Sands]: "Предзнаменование золотой эпохи",
      [ArtifactSlotKeys.Goblet]: "Суета золотой ночи",
      [ArtifactSlotKeys.Circlet]: "Награда Золотой труппы",
    },
  ]),
  [ArtifactSetKeys.HeartOfDepth]: CArtifactSet.init([
    ArtifactSetKeys.HeartOfDepth,
    "Сердце глубин",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.PeakOfVindagnyr), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Гидро урона на 15%.",
      4: "Увеличивает урон обычной и заряженной атаки на 30% в течение 15 сек. после использования элементального навыка.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Позолоченная брошь",
      [ArtifactSlotKeys.Plume]: "Порыв ностальгии",
      [ArtifactSlotKeys.Sands]: "Медный компас",
      [ArtifactSlotKeys.Goblet]: "Кубок оглушающих глубин",
      [ArtifactSlotKeys.Circlet]: "Треуголка в пятнах вина",
    },
  ]),
  [ArtifactSetKeys.HuskOfOpulentDreams]: CArtifactSet.init([
    ArtifactSetKeys.HuskOfOpulentDreams,
    "Кокон сладких грёз",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.SlumberingCourt), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает защиту на 30%.",
      4: "Персонаж, экипированный этим набором артефактов, получает эффект Любопытства в следующих ситуациях: 1 уровень Любопытства даётся активному персонажу после попадания по противнику атакой Гео (не чаще чем раз в 0,3 сек.); когда персонаж находится вне поля боя, он получает 1 ур. Любопытства каждые 3 сек. Любопытство может складываться до 4 ур., каждый ур. прибавляет 6% к защите и 6% к Гео урону. Если персонаж не получает Любопытство в течение 6 сек., то он теряет 1 накопленный уровень Любопытства.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Пора расцвета",
      [ArtifactSlotKeys.Plume]: "Перо чертога",
      [ArtifactSlotKeys.Sands]: "Песнь жизни",
      [ArtifactSlotKeys.Goblet]: "Тыква пробуждения",
      [ArtifactSlotKeys.Circlet]: "Шляпа телесности",
    },
  ]),
  [ArtifactSetKeys.Instructor]: CArtifactSet.init([
    ArtifactSetKeys.Instructor,
    "Инструктор",
    [3, 4],
    ["Боссы", "Подземелья наказания (еженедельные боссы)", "Подземелья", "Сундуки", "Элитные враги"],
    {
      2: "Увеличивает мастерство стихий на 80 ед.",
      4: "Вызов элементальной реакции увеличивает мастерство стихий всех членов отряда на 120 ед. в течение 8 сек.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Брошь инструктора",
      [ArtifactSlotKeys.Plume]: "Перо инструктора",
      [ArtifactSlotKeys.Sands]: "Карманные часы инструктора",
      [ArtifactSlotKeys.Goblet]: "Чайная кружка инструктора",
      [ArtifactSlotKeys.Circlet]: "Кепка инструктора",
    },
  ]),
  [ArtifactSetKeys.Lavawalker]: CArtifactSet.init([
    ArtifactSetKeys.Lavawalker,
    "Ступающий по лаве",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.HiddenPalaceOfZhouFormula), ArtifactSetSource.Alchemy],
    {
      2: "Пиро сопротивление: +40%",
      4: "Увеличивает урон против врагов, находящихся под действием Пиро, на 35%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Решительность ступающего по лаве",
      [ArtifactSlotKeys.Plume]: "Спасение ступающего по лаве",
      [ArtifactSlotKeys.Sands]: "Муки ступающего по лаве",
      [ArtifactSlotKeys.Goblet]: "Просветление ступающего по лаве",
      [ArtifactSlotKeys.Circlet]: "Мудрость ступающего по лаве",
    },
  ]),
  [ArtifactSetKeys.LongNightsOath]: CArtifactSet.init([
    ArtifactSetKeys.LongNightsOath,
    "Клятва долгой ночи",
    [4, 5],
    "Подземелье «Заброшенный причал»",
    {
      2: "Урон атак в падении увеличивается на 25%.",
      4: "После того как атака в падении, заряженная атака или элементальный навык экипированного персонажа поражают противника, экипированный персонаж получает 1/2/2 уровня Вечного сияния. Атаки в падении, заряженные атаки и элементальные навыки могут по отдельности вызывать этот эффект один раз в 1 сек. Вечное сияние: урон атаки в падении повышается на 15%. Эффект длится 6 сек. и складывается до 5 раз. Длительность каждого уровня рассчитывается отдельно.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Клятва светоносца",
      [ArtifactSlotKeys.Plume]: "Соловьиное перо",
      [ArtifactSlotKeys.Sands]: "Скорбный колокольчик бессмертного",
      [ArtifactSlotKeys.Goblet]: "Умолкнувший рог",
      [ArtifactSlotKeys.Circlet]: "Окрашенный шлем",
    },
  ]),
  [ArtifactSetKeys.MaidenBeloved]: CArtifactSet.init([
    ArtifactSetKeys.MaidenBeloved,
    "Возлюбленная юная дева",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.ValleyOfRemembrance), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает эффективность лечения на 15%.",
      4: "Увеличивает получаемое лечение всех членов отряда на 20% в течение 10 сек. после использования элементального навыка или взрыва стихии.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Далёкая душа юной девы",
      [ArtifactSlotKeys.Plume]: "Тоска юной девы",
      [ArtifactSlotKeys.Sands]: "Уходящая молодость юной девы",
      [ArtifactSlotKeys.Goblet]: "Досуг юной девы",
      [ArtifactSlotKeys.Circlet]: "Увядающая красота юной девы",
    },
  ]),
  [ArtifactSetKeys.MarechausseeHunter]: CArtifactSet.init([
    ArtifactSetKeys.MarechausseeHunter,
    "Охотник Сумеречного двора",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.DenouementOfSin), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает урон обычной и заряженной атаки на 15%.",
      4: "Увеличивает шанс крит. попадания на 12% на 5 сек., когда текущее HP увеличивается или снижается. Эффект может складываться до 3 раз.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Брошь охотника",
      [ArtifactSlotKeys.Plume]: "Увертюра шедевра",
      [ArtifactSlotKeys.Sands]: "Мгновение правосудия",
      [ArtifactSlotKeys.Goblet]: "Забытый сосуд",
      [ArtifactSlotKeys.Circlet]: "Лик старого солдата",
    },
  ]),
  [ArtifactSetKeys.NighttimeWhispersInTheEchoingWoods]: CArtifactSet.init([
    ArtifactSetKeys.NighttimeWhispersInTheEchoingWoods,
    "Ночной шёпот в Лесу откликающегося эха",
    [4, 5],
    ArtifactSetSource.Dungeon(DungeonKeys.WaterfallWen),
    {
      2: "Увеличивает силу атаки на 18%.",
      4: "После использования элементального навыка бонус Гео урона на 10 сек. увеличивается на 20%. Если персонаж находится под защитой щита, созданного реакцией Кристалл, этот эффект увеличивается на 150%. Через 1 сек. после потери щита это дополнительное увеличение исчезает.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Бескорыстный цветок",
      [ArtifactSlotKeys.Plume]: "Искреннее перо",
      [ArtifactSlotKeys.Sands]: "Верные песочные часы",
      [ArtifactSlotKeys.Goblet]: "Великодушная чернильница",
      [ArtifactSlotKeys.Circlet]: "Милостивая шляпка",
    },
  ]),
  [ArtifactSetKeys.NoblesseOblige]: CArtifactSet.init([
    ArtifactSetKeys.NoblesseOblige,
    "Церемония древней знати",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.ClearPoolAndMountainCavern), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает урон взрыва стихии на 20%.",
      4: "Активация взрыва стихии увеличивает силу атаки всех членов отряда на 20% в течение 12 сек. Эффект не складывается.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Королевский цветок",
      [ArtifactSlotKeys.Plume]: "Королевское перо",
      [ArtifactSlotKeys.Sands]: "Королевские карманные часы",
      [ArtifactSlotKeys.Goblet]: "Королевская серебряная фляжка",
      [ArtifactSlotKeys.Circlet]: "Королевская маска",
    },
  ]),
  [ArtifactSetKeys.NymphsDream]: CArtifactSet.init([
    ArtifactSetKeys.NymphsDream,
    "Сон нимфы",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.MoltenIronFortress), ArtifactSetSource.Alchemy],
    {
      2: "Даёт 15% бонус Гидро урона.",
      4: "Попадания обычной атакой, заряженной атакой, атакой в падении, элементальным навыком и взрывом стихий по противнику на 8 сек. создаёт 1 уровень Отражения нимфы. Когда действуют 1/2/3 и более уровня Отражения нимфы, сила атаки повышается на 7%/16%/25%, а бонус Гидро урона на 4%/9%/15%. Уровни Отражения нимфы, созданные обычными атаками, заряженными атаками, атаками в падении, элементальными навыками и взрывами стихий, существуют независимо друг от друга.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветок странствий",
      [ArtifactSlotKeys.Plume]: "Перо злого мага",
      [ArtifactSlotKeys.Sands]: "Постоянство нимфы",
      [ArtifactSlotKeys.Goblet]: "Чаепитие героев",
      [ArtifactSlotKeys.Circlet]: "Монокль свирепого дракона",
    },
  ]),
  [ArtifactSetKeys.ObsidianCodex]: CArtifactSet.init([
    ArtifactSetKeys.ObsidianCodex,
    "Обсидиановый фолиант",
    [4, 5],
    "Подземелье «Святилище мириад духов»",
    {
      2: "Урон экипированного персонажа на поле в состоянии Благословения Ночного духа увеличивается на 15%.",
      4: "После того как экипированный персонаж, будучи на поле боя, расходует 1 очко Ночного духа, шанс крит. попадания увеличивается на 40% на 6 сек. Этот эффект может возникнуть один раз в 1 сек.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Ожидания инородцев",
      [ArtifactSlotKeys.Plume]: "Корень костного мозга души",
      [ArtifactSlotKeys.Sands]: "Мифы владений ночи",
      [ArtifactSlotKeys.Goblet]: "Банкет перед состязанием",
      [ArtifactSlotKeys.Circlet]: "Корона святых",
    },
  ]),
  [ArtifactSetKeys.OceanHuedClam]: CArtifactSet.init([
    ArtifactSetKeys.OceanHuedClam,
    "Моллюск морских красок",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.SlumberingCourt), ArtifactSetSource.Alchemy],
    {
      2: "Повышает бонус лечения на 15%.",
      4: "Экипированный этим набором артефактов персонаж при лечении соратников создаёт на 3 сек. Пузырь морских красок. Пузырь регистрирует восстановленное при лечении HP (в том числе избыточное, когда лечение превышает максимум здоровья). После окончания действия Пузырь взрывается и наносит окружающим врагам урон в размере 90% учтённого объёма лечения (урон рассчитывается так же, как для эффектов Заряжен и Сверхпроводник, но на него не действуют бонусы мастерства стихий, уровня и реакций). Пузырь морских красок можно создавать не чаще чем раз в 3,5 сек. Пузырь может записать до 30 000 восстановленного HP, в том числе HP избыточного лечения. Для отряда не может существовать больше одного Пузыря морских красок одновременно. Этот эффект действует, даже если персонаж, экипированный набором артефактов, не находится на поле боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветок морских красок",
      [ArtifactSlotKeys.Plume]: "Перо глубинного дворца",
      [ArtifactSlotKeys.Sands]: "Раковина разлуки",
      [ArtifactSlotKeys.Goblet]: "Жемчужная клетка",
      [ArtifactSlotKeys.Circlet]: "Корона Ватацуми",
    },
  ]),
  [ArtifactSetKeys.PaleFlame]: CArtifactSet.init([
    ArtifactSetKeys.PaleFlame,
    "Бледный огонь",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.RidgeWatch), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает физ. урон на 25%.",
      4: "Когда элементальный навык попадает по врагам, атака увеличивается на 9% в течение 7 сек. Эффект может складываться до 2 раз и возникнуть не чаще 1 раза за 0,3 сек. На 2 уровне складывания эффект набора из 2 вещей увеличивается на 100%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Незапятнанный цветок",
      [ArtifactSlotKeys.Plume]: "Перо мудрого лекаря",
      [ArtifactSlotKeys.Sands]: "Замершее мгновение",
      [ArtifactSlotKeys.Goblet]: "Превосходящая чаша",
      [ArtifactSlotKeys.Circlet]: "Смеющаяся маска",
    },
  ]),
  [ArtifactSetKeys.RetracingBolide]: CArtifactSet.init([
    ArtifactSetKeys.RetracingBolide,
    "Встречная комета",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.DomainOfGuyun), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает прочность щита на 35%.",
      4: "Под защитой щита увеличивает урон обычной и заряженной атаки на 40%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветок равноденствия",
      [ArtifactSlotKeys.Plume]: "Конец равноденствия",
      [ArtifactSlotKeys.Sands]: "Час равноденствия",
      [ArtifactSlotKeys.Goblet]: "Шар равноденствия",
      [ArtifactSlotKeys.Circlet]: "Маска равноденствия",
    },
  ]),
  [ArtifactSetKeys.ScrollOfTheHeroOfCinderCity]: CArtifactSet.init([
    ArtifactSetKeys.ScrollOfTheHeroOfCinderCity,
    "Свиток героя сожжённого города",
    [4, 5],
    "Подземелье «Святилище мириадов духов»",
    {
      2: "Когда член отряда поблизости активирует Вспышку Ночного духа, экипированный персонаж восстанавливает 6 ед. энергии.",
      4: "После того как экипированный персонаж активирует реакцию, связанную с его элементом, все члены отряда поблизости получают 12% бонус урона элементами, связанными с этой реакцией, на 15 сек. Если экипированный персонаж, активируя данный эффект, находится в состоянии Благословение Ночного духа, все персонажи отряда поблизости дополнительно получают 28% бонус урона элементами, связанными с этой реакцией, на 20 сек. Такой эффект может возникнуть, даже если персонаж не находится на поле боя. Бонусы одноимённых наборов артефактов не суммируются.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Талисман укротителя зверей",
      [ArtifactSlotKeys.Plume]: "Маячок горного патрульного",
      [ArtifactSlotKeys.Sands]: "Золотые часы мистика",
      [ArtifactSlotKeys.Goblet]: "Кубок бродячего исследователя",
      [ArtifactSlotKeys.Circlet]: "Перьевая маска воина-демона",
    },
  ]),
  [ArtifactSetKeys.ShimenawasReminiscence]: CArtifactSet.init([
    ArtifactSetKeys.ShimenawasReminiscence,
    "Воспоминания Симэнавы",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.MomijiDyedCourt), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает силу атаки на 18%.",
      4: "При использовании элементального навыка, если у персонажа 15 или более единиц энергии, он теряет 15 единиц энергии, а урон обычной атаки, заряженной атаки и атаки в падении увеличивается на 50% в течение 10 сек. Эффект нельзя активировать повторно в течение этого времени.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Опутывающий цветок",
      [ArtifactSlotKeys.Plume]: "Стрела воспоминаний",
      [ArtifactSlotKeys.Sands]: "Мгновение росы",
      [ArtifactSlotKeys.Goblet]: "Полное надежд сердце",
      [ArtifactSlotKeys.Circlet]: "Непостоянный лик",
    },
  ]),
  [ArtifactSetKeys.SongOfDaysPast]: CArtifactSet.init([
    ArtifactSetKeys.SongOfDaysPast,
    "Песнь былых времён",
    [4, 5],
    ArtifactSetSource.Dungeon(DungeonKeys.WaterfallWen),
    {
      2: "Повышает бонус лечения на 15%.",
      4: "Экипированный персонаж при лечении членов отряда на 6 сек. создаёт эффект Стремления, который регистрирует осуществлённое лечение (в том числе избыточное). С завершением длительности Стремление превращается в Волны былых времён: при попадании обычной атаки, заряженной атаки, атаки в падении, элементального навыка или взрыва стихии вашего активного персонажа по противнику наносимый урон увеличивается на 8% от общего количества лечения, зарегистрированного Стремлением. После 5 активаций или через 10 сек. эффект Волн былых времён исчезает. Однократный эффект Стремления регистрирует до 15 000 ед. HP. Одновременно может существовать только одно Стремление, но оно регистрирует лечение, предоставляемое несколькими экипированными персонажами сразу. Этот эффект активируется, даже если экипированный персонаж не на поле боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Забытая клятва былых времён",
      [ArtifactSlotKeys.Plume]: "Воспоминания о былых временах",
      [ArtifactSlotKeys.Sands]: "Отзвуки былых времён",
      [ArtifactSlotKeys.Goblet]: "Обещанный сон былых времён",
      [ArtifactSlotKeys.Circlet]: "Поэзия былых времён",
    },
  ]),
  [ArtifactSetKeys.TenacityOfTheMillelith]: CArtifactSet.init([
    ArtifactSetKeys.TenacityOfTheMillelith,
    "Стойкость Миллелита",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.RidgeWatch), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает НР на 20%",
      4: "Когда элементальный навык попадает по врагам, атака всех находящихся поблизости персонажей в отряде, увеличивается на 20%, а прочность их щита увеличивается на 30%. Эффект длится 3 сек. и может возникнуть 1 раз в 0,5 сек. Этот эффект может быть активирован, даже если персонаж, экипированный этим набором артефактов, не находится на поле боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветок почестей",
      [ArtifactSlotKeys.Plume]: "Боевое перо командира",
      [ArtifactSlotKeys.Sands]: "Золотые часы",
      [ArtifactSlotKeys.Goblet]: "Золотой кубок клятвы",
      [ArtifactSlotKeys.Circlet]: "Древний шлем генерала",
    },
  ]),
  [ArtifactSetKeys.ThunderingFury]: CArtifactSet.init([
    ArtifactSetKeys.ThunderingFury,
    "Громогласный рёв ярости",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.MidsummerCourtyard), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Электро урона на 15%.",
      4: "Увеличивает урон реакций Перегрузка, Заряжен, Сверхпроводник и Вегетация на 40%. Урон от реакции Обострение увеличивается на 20%. При активации этих реакций, а также реакции Стимуляция, время отката элементального навыка уменьшается на 1 сек. Эффект может возникнуть не чаще 1 раза в 0,8 сек.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Милосердие Громовой птицы",
      [ArtifactSlotKeys.Plume]: "Переживший катастрофу",
      [ArtifactSlotKeys.Sands]: "Песочные часы грома",
      [ArtifactSlotKeys.Goblet]: "Предвестник бури",
      [ArtifactSlotKeys.Circlet]: "Корона призывателя грома",
    },
  ]),
  [ArtifactSetKeys.Thundersoother]: CArtifactSet.init([
    ArtifactSetKeys.Thundersoother,
    "Усмиряющий гром",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.MidsummerCourtyard), ArtifactSetSource.Alchemy],
    {
      2: "Повышает Электро сопротивление на +40%.",
      4: "Увеличивает урон против врагов, находящихся под действием Электро, на 35%.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Сердце усмиряющего гром",
      [ArtifactSlotKeys.Plume]: "Перо усмиряющего гром",
      [ArtifactSlotKeys.Sands]: "Время усмиряющего гром",
      [ArtifactSlotKeys.Goblet]: "Бокал усмиряющего гром",
      [ArtifactSlotKeys.Circlet]: "Корона усмиряющего гром",
    },
  ]),
  [ArtifactSetKeys.VermillionHereafter]: CArtifactSet.init([
    ArtifactSetKeys.VermillionHereafter,
    "Киноварное загробье",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.TheLostValley), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает силу атаки на 18%.",
      4: "После активации взрыва стихии на 16 сек. создаёт Скрытое сияние, которое повышает силу атаки на 8%. Сила атаки персонажа увеличивается ещё на 10%, когда он теряет HP. Этот эффект может возникнуть максимум 4 раза и не чаще, чем раз в 0,8 сек. Скрытое сияние исчезает, когда персонаж покидает поле боя. При повторной активации взрыва стихии существующее Скрытое сияние снимается.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Цветение жизни",
      [ArtifactSlotKeys.Plume]: "Перо скрытого сияния",
      [ArtifactSlotKeys.Sands]: "Солнечная реликвия",
      [ArtifactSlotKeys.Goblet]: "Мгновение договора",
      [ArtifactSlotKeys.Circlet]: "Громогласный облик",
    },
  ]),
  [ArtifactSetKeys.ViridescentVenerer]: CArtifactSet.init([
    ArtifactSetKeys.ViridescentVenerer,
    "Изумрудная тень",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.ValleyOfRemembrance), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает бонус Анемо урона на 15%.",
      4: "Увеличивает урон Рассеивания на 60%. При взаимодействии Рассеивания с другим элементом, также понижает сопротивление противника к соответствующему элементу на 40% в течение 10 сек.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Воспоминания об изумрудных лугах",
      [ArtifactSlotKeys.Plume]: "Оперение стрелы изумрудного охотника",
      [ArtifactSlotKeys.Sands]: "Решимость изумрудного охотника",
      [ArtifactSlotKeys.Goblet]: "Сосуд изумрудного охотника",
      [ArtifactSlotKeys.Circlet]: "Венок изумрудного охотника",
    },
  ]),
  [ArtifactSetKeys.VourukashasGlow]: CArtifactSet.init([
    ArtifactSetKeys.VourukashasGlow,
    "Сияние Вурукаши",
    [4, 5],
    [ArtifactSetSource.Dungeon(DungeonKeys.MoltenIronFortress), ArtifactSetSource.Alchemy],
    {
      2: "Увеличивает HP на 20%.",
      4: "Увеличивает урон элементального навыка и взрыва стихии на 10%. Если экипированный персонаж получает урон, этот эффект повышения урона увеличивается на 80% на 5 сек. Эффект может складываться до 5 раз. Отсчёт времени каждого уровня происходит отдельно. Эти эффекты активируются, даже если экипированный персонаж не на поле боя.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Тычинка истока Хварны",
      [ArtifactSlotKeys.Plume]: "Самоцветное перо",
      [ArtifactSlotKeys.Sands]: "Древнее увядание",
      [ArtifactSlotKeys.Goblet]: "Пир необузданного веселья",
      [ArtifactSlotKeys.Circlet]: "Сердце светозарности Хварны",
    },
  ]),
  [ArtifactSetKeys.WanderersTroupe]: CArtifactSet.init([
    "WanderersTroupe",
    "Странствующий ансамбль",
    [4, 5],
    [
      "Награды с босса в мире за 40 первородной смолы",
      "Подземелья наказания (еженедельные боссы)",
      "Мистическое подношение (Алхимия)",
    ],
    {
      2: "Увеличивает мастерство стихий на 80 ед.",
      4: "Увеличивает урон заряженной атаки на 35%, если персонаж использует катализатор или стрелковое оружие.",
    },
    {
      [ArtifactSlotKeys.Flower]: "Рассвет ансамбля",
      [ArtifactSlotKeys.Plume]: "Оперение стрелы барда",
      [ArtifactSlotKeys.Sands]: "Окончание концерта",
      [ArtifactSlotKeys.Goblet]: "Фляжка странника",
      [ArtifactSlotKeys.Circlet]: "Цилиндр дирижёра",
    },
  ]),
} as Record<IArtifactSet["key"], IArtifactSet>;
