import type { Character } from "./types";
import { CharacterIds } from "./enums";
import { CharacterRoleIds } from "../character-roles/enums";
import { ElementIds } from "../elements/enums";
import { publicImageSrc } from "@/lib/utils";
import { WeaponKeys } from "@/database/weapons/enums";
import { WeaponTypeKeys } from "@/database/weapon-types/enums";

const CharacterArkhe = {
  "🟡": "Пневма",
  "🟣": "Усия",
  "🟣🟡": ["Усия", "Пневма"],
} as Record<string, NonNullable<Character["arkhe"]>>;

export class CharacterClass implements Character {
  readonly id: Character["id"];
  readonly name: Character["name"];
  readonly rarity: Character["rarity"];
  readonly weapon_type_id: Character["weapon_type_id"];
  readonly element_id: Character["element_id"];
  private _arkhe: Character["arkhe"];
  readonly role_ids: Character["role_ids"];
  readonly image_src: Character["image_src"];
  private _signature_weapon_id: Character["signature_weapon_id"];

  static PATH = "characters";

  constructor(
    id: Character["id"],
    name: Character["name"],
    rarity: Character["rarity"],
    weaponTypeId: Character["weapon_type_id"],
    elementId: Character["element_id"],
    roleIds: Character["role_ids"],
    imageName: string,
  ) {
    this.id = id;
    this.name = name;
    this.rarity = rarity;
    this.weapon_type_id = weaponTypeId;
    this.element_id = elementId;
    this.role_ids = roleIds;
    this.image_src = publicImageSrc(`${CharacterClass.PATH}/${imageName}`);
  }

  get arkhe() {
    return this._arkhe;
  }

  get signature_weapon_id() {
    return this._signature_weapon_id;
  }

  setArkhe(val: keyof typeof CharacterArkhe) {
    this._arkhe = CharacterArkhe[val];

    return this;
  }

  setSignatureWeaponId(val: NonNullable<Character["signature_weapon_id"]>) {
    this._signature_weapon_id = val;

    return this;
  }

  static init(params: ConstructorParameters<typeof CharacterClass>) {
    return new CharacterClass(...params);
  }
}

export default {
  [CharacterIds.Albedo]: CharacterClass.init([
    CharacterIds.Albedo,
    "Альбедо",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "albedo-256x256.webp",
  ]),
  [CharacterIds.Alhaitham]: CharacterClass.init([
    CharacterIds.Alhaitham,
    "Аль-Хайтам",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "alhaitham-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.LightOfFoliarIncision),
  [CharacterIds.Amber]: CharacterClass.init([
    CharacterIds.Amber,
    "Эмбер",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "amber-256x256.webp",
  ]),
  [CharacterIds.AratakiItto]: CharacterClass.init([
    CharacterIds.AratakiItto,
    "Итто",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "arataki_itto-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.RedhornStonethresher),
  [CharacterIds.Arlecchino]: CharacterClass.init([
    CharacterIds.Arlecchino,
    "Арлекино", 5,
    WeaponTypeKeys.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "arlecchino-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.CrimsonMoonsSemblance),
  [CharacterIds.Baizhu]: CharacterClass.init([
    CharacterIds.Baizhu,
    "Бай Чжу",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Dendro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "baizhu-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.JadefallsSplendor),
  [CharacterIds.Barbara]: CharacterClass.init([
    CharacterIds.Barbara,
    "Барбара", 4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "barbara-256x256.webp",
  ]),
  [CharacterIds.Beidou]: CharacterClass.init([
    CharacterIds.Beidou,
    "Бэй Доу",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "beidou-256x256.webp",
  ]),
  [CharacterIds.Bennett]: CharacterClass.init([
    CharacterIds.Bennett,
    "Беннет",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "bennett-256x256.webp",
  ]),
  [CharacterIds.Candace]: CharacterClass.init([
    CharacterIds.Candace,
    "Кандакия",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "candace-256x256.webp",
  ]),
  [CharacterIds.Charlotte]: CharacterClass.init([
    CharacterIds.Charlotte,
    "Шарлотта",
    4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "charlotte-256x256.webp",
  ]).setArkhe("🟡"),
  [CharacterIds.Chevreuse]: CharacterClass.init([
    CharacterIds.Chevreuse,
    "Шеврёз",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "chevreuse-256x256.webp",
  ]).setArkhe("🟣"),
  [CharacterIds.Chiori]: CharacterClass.init([
    CharacterIds.Chiori,
    "Тиори",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "chiori-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.UrakuMisugiri),
  [CharacterIds.Chongyun]: CharacterClass.init([
    CharacterIds.Chongyun,
    "Чун Юнь",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "chongyun-256x256.webp",
  ]),
  [CharacterIds.Citlali]: CharacterClass.init([
    CharacterIds.Citlali,
    "Ситлали",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "citlali-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.StarcallersWatch),
  [CharacterIds.Clorinde]: CharacterClass.init([
    CharacterIds.Clorinde,
    "Клоринда",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "clorinde-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponKeys.Absolution),
  [CharacterIds.Collei]: CharacterClass.init([
    CharacterIds.Collei,
    "Коллеи",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "collei-256x256.webp",
  ]),
  [CharacterIds.Cyno]: CharacterClass.init([
    CharacterIds.Cyno,
    "Сайно", 5,
    WeaponTypeKeys.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "cyno-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.StaffOfTheScarletSands),
  [CharacterIds.Dahlia]: CharacterClass.init([
    CharacterIds.Dahlia,
    "Далия",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "dahlia-256x256.webp",
  ]),
  [CharacterIds.Dehya]: CharacterClass.init([
    CharacterIds.Dehya,
    "Дэхья",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "dehya-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.BeaconOfTheReedSea),
  [CharacterIds.Diluc]: CharacterClass.init([
    CharacterIds.Diluc,
    "Дилюк",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "diluc-256x256.webp",
  ]),
  [CharacterIds.Diona]: CharacterClass.init([
    CharacterIds.Diona,
    "Диона",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "diona-256x256.webp",
  ]),
  [CharacterIds.Dori]: CharacterClass.init([
    CharacterIds.Dori,
    "Дори",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "dori-256x256.webp",
  ]),
  [CharacterIds.Emilie]: CharacterClass.init([
    CharacterIds.Emilie,
    "Эмилия",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "emilie-256x256.webp",
  ]).setArkhe("🟡").setSignatureWeaponId(WeaponKeys.LumidouceElegy),
  [CharacterIds.Escoffier]: CharacterClass.init([
    CharacterIds.Escoffier,
    "Эскофье",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "escoffier-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponKeys.SymphonistOfScents),
  [CharacterIds.Eula]: CharacterClass.init([
    CharacterIds.Eula,
    "Эола",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "eula-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.SongOfBrokenPines),
  [CharacterIds.Faruzan]: CharacterClass.init([
    CharacterIds.Faruzan,
    "Фарузан",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "faruzan-256x256.webp",
  ]),
  [CharacterIds.Fischl]: CharacterClass.init([
    CharacterIds.Fischl,
    "Фишль",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "fischl-256x256.webp",
  ]),
  [CharacterIds.Freminet]: CharacterClass.init([
    CharacterIds.Freminet,
    "Фремине",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "freminet-256x256.webp",
  ]).setArkhe("🟡"),
  [CharacterIds.Furina]: CharacterClass.init([
    CharacterIds.Furina,
    "Фурина",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "furina-256x256.webp",
  ]).setArkhe("🟣🟡").setSignatureWeaponId(WeaponKeys.SplendorOfTranquilWaters),
  [CharacterIds.Gaming]: CharacterClass.init([
    CharacterIds.Gaming,
    "Ка Мин",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "gaming-256x256.webp",
  ]),
  [CharacterIds.Ganyu]: CharacterClass.init([
    CharacterIds.Ganyu,
    "Гань Юй",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "ganyu-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.AmosBow),
  [CharacterIds.Gorou]: CharacterClass.init([
    CharacterIds.Gorou,
    "Горо",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "gorou-256x256.webp",
  ]),
  [CharacterIds.HuTao]: CharacterClass.init([
    CharacterIds.HuTao,
    "Ху Тао",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "hu_tao-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.StaffOfHoma),
  [CharacterIds.Iansan]: CharacterClass.init([
    CharacterIds.Iansan,
    "Иансан",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "iansan-256x256.webp",
  ]),
  [CharacterIds.Ineffa]: CharacterClass.init([
    CharacterIds.Ineffa,
    "Инеффа",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "ineffa-256x256.webp",
  ]),
  [CharacterIds.Jean]: CharacterClass.init([
    CharacterIds.Jean,
    "Джинн",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "jean-256x256.webp",
  ]),
  [CharacterIds.Kachina]: CharacterClass.init([
    CharacterIds.Kachina,
    "Качина",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "kachina-256x256.webp",
  ]),
  [CharacterIds.KaedeharaKazuha]: CharacterClass.init([
    CharacterIds.KaedeharaKazuha,
    "Кадзуха",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "kaedehara_kazuha-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.FreedomSworn),
  [CharacterIds.Kaeya]: CharacterClass.init([
    CharacterIds.Kaeya,
    "Кэйа",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "kaeya-256x256.webp",
  ]),
  [CharacterIds.KamisatoAyaka]: CharacterClass.init([
    CharacterIds.KamisatoAyaka,
    "Аяка",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "kamisato_ayaka-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.MistsplitterReforged),
  [CharacterIds.KamisatoAyato]: CharacterClass.init([
    CharacterIds.KamisatoAyato,
    "Аято",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "kamisato_ayato-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.HaranGeppakuFutsu),
  [CharacterIds.Kaveh]: CharacterClass.init([
    CharacterIds.Kaveh,
    "Кавех",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "kaveh-256x256.webp",
  ]),
  [CharacterIds.Keqing]: CharacterClass.init([
    CharacterIds.Keqing,
    "Кэ Цин",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "keqing-256x256.webp",
  ]),
  [CharacterIds.Kinich]: CharacterClass.init([
    CharacterIds.Kinich,
    "Кинич",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "kinich-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.FangOfTheMountainKing),
  [CharacterIds.Kirara]: CharacterClass.init([
    CharacterIds.Kirara,
    "Кирара",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Dendro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "kirara-256x256.webp",
  ]),
  [CharacterIds.Klee]: CharacterClass.init([
    CharacterIds.Klee,
    "Кли",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "klee-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.LostPrayerToTheSacredWinds),
  [CharacterIds.KujouSara]: CharacterClass.init([
    CharacterIds.KujouSara,
    "Сара",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "kujou_sara-256x256.webp",
  ]),
  [CharacterIds.KukiShinobu]: CharacterClass.init([
    CharacterIds.KukiShinobu,
    "Синобу",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "kuki_shinobu-256x256.webp",
  ]),
  [CharacterIds.Layla]: CharacterClass.init([
    CharacterIds.Layla,
    "Лайла",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "layla-256x256.webp",
  ]),
  [CharacterIds.Lisa]: CharacterClass.init([
    CharacterIds.Lisa,
    "Лиза",
    4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "lisa-256x256.webp",
  ]),
  [CharacterIds.Lynette]: CharacterClass.init([
    CharacterIds.Lynette,
    "Линетт",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "lynette-256x256.webp",
  ]).setArkhe("🟣"),
  [CharacterIds.Lyney]: CharacterClass.init([
    CharacterIds.Lyney,
    "Лини",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "lyney-256x256.webp",
  ]).setArkhe("🟡").setSignatureWeaponId(WeaponKeys.TheFirstGreatMagic),
  [CharacterIds.Mavuika]: CharacterClass.init([
    CharacterIds.Mavuika,
    "Мавуика",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.OnField, CharacterRoleIds.Support],
    "mavuika-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.AThousandBlazingSuns),
  [CharacterIds.Mika]: CharacterClass.init([
    CharacterIds.Mika,
    "Мика",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "mika-256x256.webp",
  ]),
  [CharacterIds.Mona]: CharacterClass.init([
    CharacterIds.Mona,
    "Мона",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "mona-256x256.webp",
  ]),
  [CharacterIds.Mualani]: CharacterClass.init([
    CharacterIds.Mualani,
    "Муалани",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "mualani-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.SurfsUp),
  [CharacterIds.Nahida]: CharacterClass.init([
    CharacterIds.Nahida,
    "Нахида",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "nahida-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.AThousandFloatingDreams),
  [CharacterIds.Navia]: CharacterClass.init([
    CharacterIds.Navia,
    "Навия",
    5,
    WeaponTypeKeys.Claymore,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "navia-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.Verdict),
  [CharacterIds.Neuvillette]: CharacterClass.init([
    CharacterIds.Neuvillette,
    "Нёвиллет",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "neuvillette-256x256.webp",
  ]).setArkhe("🟡").setSignatureWeaponId(WeaponKeys.TomeOfTheEternalFlow),
  [CharacterIds.Nilou]: CharacterClass.init([
    CharacterIds.Nilou,
    "Нилу",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "nilou-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.KeyOfKhajNisut),
  [CharacterIds.Ningguang]: CharacterClass.init([
    CharacterIds.Ningguang,
    "Нин Гуан",
    4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "ningguang-256x256.webp",
  ]),
  [CharacterIds.Noelle]: CharacterClass.init([
    CharacterIds.Noelle,
    "Ноэлль",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField, CharacterRoleIds.Survivability],
    "noelle-256x256.webp",
  ]),
  [CharacterIds.Ororon]: CharacterClass.init([
    CharacterIds.Ororon,
    "Оророн",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "ororon-256x256.webp",
  ]),
  [CharacterIds.Qiqi]: CharacterClass.init([
    CharacterIds.Qiqi,
    "Ци Ци",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "qiqi-256x256.webp",
  ]),
  [CharacterIds.RaidenShogun]: CharacterClass.init([
    CharacterIds.RaidenShogun,
    "Райдэн",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField, CharacterRoleIds.Support],
    "raiden_shogun-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.EngulfingLightning),
  [CharacterIds.Razor]: CharacterClass.init([
    CharacterIds.Razor,
    "Рэйзор",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "razor-256x256.webp",
  ]),
  [CharacterIds.Rosaria]: CharacterClass.init([
    CharacterIds.Rosaria,
    "Розария",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "rosaria-256x256.webp",
  ]),
  [CharacterIds.SangonomiyaKokomi]: CharacterClass.init([
    CharacterIds.SangonomiyaKokomi,
    "Кокоми",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "sangonomiya_kokomi-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.EverlastingMoonglow),
  [CharacterIds.Sayu]: CharacterClass.init([
    CharacterIds.Sayu,
    "Саю",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "sayu-256x256.webp",
  ]),
  [CharacterIds.Sethos]: CharacterClass.init([
    CharacterIds.Sethos,
    "Сетос",
    4,
    WeaponTypeKeys.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "sethos-256x256.webp",
  ]),
  [CharacterIds.Shenhe]: CharacterClass.init([
    CharacterIds.Shenhe,
    "Шэнь Хэ",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "shenhe-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.CalamityQueller),
  [CharacterIds.ShikanoinHeizou]: CharacterClass.init([
    CharacterIds.ShikanoinHeizou,
    "Хэйдзо",
    4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "shikanoin_heizou-256x256.webp",
  ]),
  [CharacterIds.Sigewinne]: CharacterClass.init([
    CharacterIds.Sigewinne,
    "Сиджвин",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "sigewinne-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponKeys.SilvershowerHeartstrings),
  [CharacterIds.Skirk]: CharacterClass.init([
    CharacterIds.Skirk,
    "Скирк",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "skirk-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.Azurelight),
  [CharacterIds.Sucrose]: CharacterClass.init([
    CharacterIds.Sucrose,
    "Сахароза",
    4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "sucrose-256x256.webp",
  ]),
  [CharacterIds.Tartaglia]: CharacterClass.init([
    CharacterIds.Tartaglia,
    "Тарталья",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "tartaglia-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.PolarStar),
  [CharacterIds.Thoma]: CharacterClass.init([
    CharacterIds.Thoma,
    "Тома",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "thoma-256x256.webp",
  ]),
  [CharacterIds.Tighnari]: CharacterClass.init([
    CharacterIds.Tighnari,
    "Тигнари",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "tighnari-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.HuntersPath),
  [CharacterIds.TravelerAnemo]: CharacterClass.init([
    CharacterIds.TravelerAnemo,
    "Путешественник (Анемо)",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Anemo,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterIds.TravelerDendro]: CharacterClass.init([
    CharacterIds.TravelerDendro,
    "Путешественник (Дендро)",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Dendro,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterIds.TravelerElectro]: CharacterClass.init([
    CharacterIds.TravelerElectro,
    "Путешественник (Электро)",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Electro,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterIds.TravelerGeo]: CharacterClass.init([
    CharacterIds.TravelerGeo,
    "Путешественник (Гео)",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Geo,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterIds.TravelerHydro]: CharacterClass.init([
    CharacterIds.TravelerHydro,
    "Путешественник (Гидро)",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Hydro,
    undefined,
    "traveler-256x256.gif",
  ]).setArkhe("🟡"),
  [CharacterIds.TravelerPyro]: CharacterClass.init([
    CharacterIds.TravelerPyro,
    "Путешественник (Пиро)",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Pyro,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterIds.Varesa]: CharacterClass.init([
    CharacterIds.Varesa,
    "Вареса",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "varesa-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.VividNotions),
  [CharacterIds.Venti]: CharacterClass.init([
    CharacterIds.Venti,
    "Венти",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "venti-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.ElegyForTheEnd),
  [CharacterIds.Wanderer]: CharacterClass.init([
    CharacterIds.Wanderer,
    "Странник",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "wanderer-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.TulaytullahsRemembrance),
  [CharacterIds.Wriothesley]: CharacterClass.init([
    CharacterIds.Wriothesley,
    "Ризли",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "wriothesley-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponKeys.CashflowSupervision),
  [CharacterIds.Xiangling]: CharacterClass.init([
    CharacterIds.Xiangling,
    "Сян Лин",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "xiangling-256x256.webp",
  ]),
  [CharacterIds.Xianyun]: CharacterClass.init([
    CharacterIds.Xianyun,
    "Сянь Юнь",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "xianyun-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.CranesEchoingCall),
  [CharacterIds.Xiao]: CharacterClass.init([
    CharacterIds.Xiao,
    "Сяо",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "xiao-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.PrimordialJadeWingedSpear),
  [CharacterIds.Xilonen]: CharacterClass.init([
    CharacterIds.Xilonen,
    "Шилонен",
    5,
    WeaponTypeKeys.Sword,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "xilonen-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.PeakPatrolSong),
  [CharacterIds.Xingqiu]: CharacterClass.init([
    CharacterIds.Xingqiu,
    "Син Цю",
    4,
    WeaponTypeKeys.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "xingqiu-256x256.webp",
  ]),
  [CharacterIds.Xinyan]: CharacterClass.init([
    CharacterIds.Xinyan,
    "Синь Янь",
    4,
    WeaponTypeKeys.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "xinyan-256x256.webp",
  ]),
  [CharacterIds.YaeMiko]: CharacterClass.init([
    CharacterIds.YaeMiko,
    "Яэ Мико",
    5,
    WeaponTypeKeys.Catalyst,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "yae_miko-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.KagurasVerity),
  [CharacterIds.Yanfei]: CharacterClass.init([
    CharacterIds.Yanfei,
    "Янь Фэй",
    4,
    WeaponTypeKeys.Catalyst,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "yanfei-256x256.webp",
  ]),
  [CharacterIds.Yaoyao]: CharacterClass.init([
    CharacterIds.Yaoyao,
    "Яо Яо",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Dendro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
    "yaoyao-256x256.webp",
  ]),
  [CharacterIds.Yelan]: CharacterClass.init([
    CharacterIds.Yelan,
    "Е Лань",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
    "yelan-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.AquaSimulacra),
  [CharacterIds.Yoimiya]: CharacterClass.init([
    CharacterIds.Yoimiya,
    "Ёимия",
    5,
    WeaponTypeKeys.Bow,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
    "yoimiya-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.ThunderingPulse),
  [CharacterIds.YunJin]: CharacterClass.init([
    CharacterIds.YunJin,
    "Юнь Цзинь",
    4,
    WeaponTypeKeys.Polearm,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
    "yun_jin-256x256.webp",
  ]),
  [CharacterIds.Zhongli]: CharacterClass.init([
    CharacterIds.Zhongli,
    "Чжун Ли",
    5,
    WeaponTypeKeys.Polearm,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
    "zhongli-256x256.webp",
  ]).setSignatureWeaponId(WeaponKeys.VortexVanquisher),
} as Record<Character["id"], Character>;
