import type { Character } from "./types";
import { CharacterIds } from "./enums";
import { CharacterRoleIds } from "../character-roles/enums";
import { ElementIds } from "../elements/enums";
import { publicImageSrc } from "@/lib/utils";
import { WeaponIds } from "../weapons/enums";
import { WeaponTypeIds } from "../weapon-types/enums";

const CharacterArkhe = {
  "🟡": "Пневма",
  "🟣": "Усия",
  "🟣🟡": ["Усия", "Пневма"],
} as Record<string, NonNullable<Character["arkhe"]>>;

export class CharacterClass implements Character {
  readonly id: Character["id"];
  readonly image_src: Character["image_src"];
  readonly title: Character["title"];
  readonly rarity: Character["rarity"];
  readonly weapon_type_id: Character["weapon_type_id"];
  readonly element_id: Character["element_id"];
  protected _name: Character["name"];
  protected _arkhe: Character["arkhe"];
  readonly role_ids: Character["role_ids"];
  protected _signature_weapon_id: Character["signature_weapon_id"];

  static PATH = "characters";

  constructor(
    id: Character["id"],
    title: Character["title"],
    rarity: Character["rarity"],
    weaponTypeId: Character["weapon_type_id"],
    elementId: Character["element_id"],
    roleIds: Character["role_ids"],
  ) {
    const imageName = id.includes("Traveler_") ? "Traveler.gif" : `${id}.webp`;

    this.id = id;
    this.image_src = publicImageSrc(`${CharacterClass.PATH}/${imageName}`);
    this.title = title;
    this.rarity = rarity;
    this.weapon_type_id = weaponTypeId;
    this.element_id = elementId;
    this._name = title;
    this.role_ids = roleIds;
  }

  get arkhe() {
    return this._arkhe;
  }

  get name() {
    return this._name;
  }

  get signature_weapon_id() {
    return this._signature_weapon_id;
  }

  setArkhe(val: keyof typeof CharacterArkhe) {
    this._arkhe = CharacterArkhe[val];

    return this;
  }

  setName(val: NonNullable<Character["name"]>) {
    this._name = val;

    return this;
  }

  setSignatureWeaponId(val: NonNullable<Character["signature_weapon_id"]>) {
    this._signature_weapon_id = val;

    return this;
  }

  static init(params: ConstructorParameters<typeof CharacterClass>) {
    return new CharacterClass(...params);
  }
}

export default {
  [CharacterIds.Aino]: CharacterClass.init([
    CharacterIds.Aino,
    "Айно",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Hydro,
    undefined,
  ]),
  [CharacterIds.Albedo]: CharacterClass.init([
    CharacterIds.Albedo,
    "Альбедо",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.Alhaitham]: CharacterClass.init([
    CharacterIds.Alhaitham,
    "Аль-Хайтам",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.LightOfFoliarIncision),
  [CharacterIds.Amber]: CharacterClass.init([
    CharacterIds.Amber,
    "Эмбер",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.AratakiItto]: CharacterClass.init([
    CharacterIds.AratakiItto,
    "Итто",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setName("Аратаки Итто").setSignatureWeaponId(WeaponIds.RedhornStonethresher),
  [CharacterIds.Arlecchino]: CharacterClass.init([
    CharacterIds.Arlecchino,
    "Арлекино", 5,
    WeaponTypeIds.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.CrimsonMoonsSemblance),
  [CharacterIds.Baizhu]: CharacterClass.init([
    CharacterIds.Baizhu,
    "Бай Чжу",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Dendro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.JadefallsSplendor),
  [CharacterIds.Barbara]: CharacterClass.init([
    CharacterIds.Barbara,
    "Барбара", 4,
    WeaponTypeIds.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Beidou]: CharacterClass.init([
    CharacterIds.Beidou,
    "Бэй Доу",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Bennett]: CharacterClass.init([
    CharacterIds.Bennett,
    "Беннет",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Candace]: CharacterClass.init([
    CharacterIds.Candace,
    "Кандакия",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Charlotte]: CharacterClass.init([
    CharacterIds.Charlotte,
    "Шарлотта",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]).setArkhe("🟡"),
  [CharacterIds.Chevreuse]: CharacterClass.init([
    CharacterIds.Chevreuse,
    "Шеврёз",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setArkhe("🟣"),
  [CharacterIds.Chiori]: CharacterClass.init([
    CharacterIds.Chiori,
    "Тиори",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]).setSignatureWeaponId(WeaponIds.UrakuMisugiri),
  [CharacterIds.Chongyun]: CharacterClass.init([
    CharacterIds.Chongyun,
    "Чун Юнь",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Citlali]: CharacterClass.init([
    CharacterIds.Citlali,
    "Ситлали",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.StarcallersWatch),
  [CharacterIds.Clorinde]: CharacterClass.init([
    CharacterIds.Clorinde,
    "Клоринда",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponIds.Absolution),
  [CharacterIds.Collei]: CharacterClass.init([
    CharacterIds.Collei,
    "Коллеи",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.Cyno]: CharacterClass.init([
    CharacterIds.Cyno,
    "Сайно", 5,
    WeaponTypeIds.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.StaffOfTheScarletSands),
  [CharacterIds.Dahlia]: CharacterClass.init([
    CharacterIds.Dahlia,
    "Далия",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Dehya]: CharacterClass.init([
    CharacterIds.Dehya,
    "Дэхья",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.BeaconOfTheReedSea),
  [CharacterIds.Diluc]: CharacterClass.init([
    CharacterIds.Diluc,
    "Дилюк",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Diona]: CharacterClass.init([
    CharacterIds.Diona,
    "Диона",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Dori]: CharacterClass.init([
    CharacterIds.Dori,
    "Дори",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Emilie]: CharacterClass.init([
    CharacterIds.Emilie,
    "Эмилия",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]).setArkhe("🟡").setSignatureWeaponId(WeaponIds.LumidouceElegy),
  [CharacterIds.Escoffier]: CharacterClass.init([
    CharacterIds.Escoffier,
    "Эскофье",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponIds.SymphonistOfScents),
  [CharacterIds.Eula]: CharacterClass.init([
    CharacterIds.Eula,
    "Эола",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.SongOfBrokenPines),
  [CharacterIds.Faruzan]: CharacterClass.init([
    CharacterIds.Faruzan,
    "Фарузан",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Fischl]: CharacterClass.init([
    CharacterIds.Fischl,
    "Фишль",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.Freminet]: CharacterClass.init([
    CharacterIds.Freminet,
    "Фремине",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setArkhe("🟡"),
  [CharacterIds.Furina]: CharacterClass.init([
    CharacterIds.Furina,
    "Фурина",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setArkhe("🟣🟡").setSignatureWeaponId(WeaponIds.SplendorOfTranquilWaters),
  [CharacterIds.Gaming]: CharacterClass.init([
    CharacterIds.Gaming,
    "Ка Мин",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Ganyu]: CharacterClass.init([
    CharacterIds.Ganyu,
    "Гань Юй",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.AmosBow),
  [CharacterIds.Gorou]: CharacterClass.init([
    CharacterIds.Gorou,
    "Горо",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.HuTao]: CharacterClass.init([
    CharacterIds.HuTao,
    "Ху Тао",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.StaffOfHoma),
  [CharacterIds.Iansan]: CharacterClass.init([
    CharacterIds.Iansan,
    "Иансан",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Ifa]: CharacterClass.init([
    CharacterIds.Ifa,
    "Ифа",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.OnField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Ineffa]: CharacterClass.init([
    CharacterIds.Ineffa,
    "Инеффа",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.FracturedHalo),
  [CharacterIds.Jean]: CharacterClass.init([
    CharacterIds.Jean,
    "Джинн",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Kachina]: CharacterClass.init([
    CharacterIds.Kachina,
    "Качина",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.KaedeharaKazuha]: CharacterClass.init([
    CharacterIds.KaedeharaKazuha,
    "Кадзуха",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]).setName("Каэдэхара Кадзуха").setSignatureWeaponId(WeaponIds.FreedomSworn),
  [CharacterIds.Kaeya]: CharacterClass.init([
    CharacterIds.Kaeya,
    "Кэйа",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.KamisatoAyaka]: CharacterClass.init([
    CharacterIds.KamisatoAyaka,
    "Аяка",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setName("Камисато Аяка").setSignatureWeaponId(WeaponIds.MistsplitterReforged),
  [CharacterIds.KamisatoAyato]: CharacterClass.init([
    CharacterIds.KamisatoAyato,
    "Аято",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setName("Камисато Аято").setSignatureWeaponId(WeaponIds.HaranGeppakuFutsu),
  [CharacterIds.Kaveh]: CharacterClass.init([
    CharacterIds.Kaveh,
    "Кавех",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Keqing]: CharacterClass.init([
    CharacterIds.Keqing,
    "Кэ Цин",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Kinich]: CharacterClass.init([
    CharacterIds.Kinich,
    "Кинич",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.FangOfTheMountainKing),
  [CharacterIds.Kirara]: CharacterClass.init([
    CharacterIds.Kirara,
    "Кирара",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Dendro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Klee]: CharacterClass.init([
    CharacterIds.Klee,
    "Кли",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.LostPrayerToTheSacredWinds),
  [CharacterIds.KujouSara]: CharacterClass.init([
    CharacterIds.KujouSara,
    "Сара",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]).setName("Кудзё Сара"),
  [CharacterIds.KukiShinobu]: CharacterClass.init([
    CharacterIds.KukiShinobu,
    "Синобу",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Electro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]).setName("Куки Синобу"),
  [CharacterIds.KyryllChudomirovichFlins]: CharacterClass.init([
    CharacterIds.KyryllChudomirovichFlins,
    "Флинс",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Electro,
    undefined,
  ]).setName("Кирилл Чудомирович Флинс"),
  [CharacterIds.Lauma]: CharacterClass.init([
    CharacterIds.Lauma,
    "Лаума",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Dendro,
    undefined,
  ]).setSignatureWeaponId(WeaponIds.NightweaversLookingGlass),
  [CharacterIds.Layla]: CharacterClass.init([
    CharacterIds.Layla,
    "Лайла",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Lisa]: CharacterClass.init([
    CharacterIds.Lisa,
    "Лиза",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.Lynette]: CharacterClass.init([
    CharacterIds.Lynette,
    "Линетт",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]).setArkhe("🟣"),
  [CharacterIds.Lyney]: CharacterClass.init([
    CharacterIds.Lyney,
    "Лини",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setArkhe("🟡").setSignatureWeaponId(WeaponIds.TheFirstGreatMagic),
  [CharacterIds.Mavuika]: CharacterClass.init([
    CharacterIds.Mavuika,
    "Мавуика",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.OnField, CharacterRoleIds.Support],
  ]).setSignatureWeaponId(WeaponIds.AThousandBlazingSuns),
  [CharacterIds.Mika]: CharacterClass.init([
    CharacterIds.Mika,
    "Мика",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Mona]: CharacterClass.init([
    CharacterIds.Mona,
    "Мона",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Mualani]: CharacterClass.init([
    CharacterIds.Mualani,
    "Муалани",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.SurfsUp),
  [CharacterIds.Nahida]: CharacterClass.init([
    CharacterIds.Nahida,
    "Нахида",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]).setSignatureWeaponId(WeaponIds.AThousandFloatingDreams),
  [CharacterIds.Navia]: CharacterClass.init([
    CharacterIds.Navia,
    "Навия",
    5,
    WeaponTypeIds.Claymore,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.Verdict),
  [CharacterIds.Nefer]: CharacterClass.init([
    CharacterIds.Nefer,
    "Нефер",
    undefined,
    undefined,
    ElementIds.Dendro,
    undefined,
  ]),
  [CharacterIds.Neuvillette]: CharacterClass.init([
    CharacterIds.Neuvillette,
    "Нёвиллет",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setArkhe("🟡").setSignatureWeaponId(WeaponIds.TomeOfTheEternalFlow),
  [CharacterIds.Nilou]: CharacterClass.init([
    CharacterIds.Nilou,
    "Нилу",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]).setSignatureWeaponId(WeaponIds.KeyOfKhajNisut),
  [CharacterIds.Ningguang]: CharacterClass.init([
    CharacterIds.Ningguang,
    "Нин Гуан",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Noelle]: CharacterClass.init([
    CharacterIds.Noelle,
    "Ноэлль",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Geo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Ororon]: CharacterClass.init([
    CharacterIds.Ororon,
    "Оророн",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.Qiqi]: CharacterClass.init([
    CharacterIds.Qiqi,
    "Ци Ци",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.RaidenShogun]: CharacterClass.init([
    CharacterIds.RaidenShogun,
    "Райдэн",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField, CharacterRoleIds.Support],
  ]).setName("Сёгун Райдэн").setSignatureWeaponId(WeaponIds.EngulfingLightning),
  [CharacterIds.Razor]: CharacterClass.init([
    CharacterIds.Razor,
    "Рэйзор",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Rosaria]: CharacterClass.init([
    CharacterIds.Rosaria,
    "Розария",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.SangonomiyaKokomi]: CharacterClass.init([
    CharacterIds.SangonomiyaKokomi,
    "Кокоми",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setName("Сангономия Кокоми").setSignatureWeaponId(WeaponIds.EverlastingMoonglow),
  [CharacterIds.Sayu]: CharacterClass.init([
    CharacterIds.Sayu,
    "Саю",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Sethos]: CharacterClass.init([
    CharacterIds.Sethos,
    "Сетос",
    4,
    WeaponTypeIds.Bow,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Shenhe]: CharacterClass.init([
    CharacterIds.Shenhe,
    "Шэнь Хэ",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Cryo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]).setSignatureWeaponId(WeaponIds.CalamityQueller),
  [CharacterIds.ShikanoinHeizou]: CharacterClass.init([
    CharacterIds.ShikanoinHeizou,
    "Хэйдзо",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setName("Сиканоин Хэйдзо"),
  [CharacterIds.Sigewinne]: CharacterClass.init([
    CharacterIds.Sigewinne,
    "Сиджвин",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Hydro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponIds.SilvershowerHeartstrings),
  [CharacterIds.Skirk]: CharacterClass.init([
    CharacterIds.Skirk,
    "Скирк",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.Azurelight),
  [CharacterIds.Sucrose]: CharacterClass.init([
    CharacterIds.Sucrose,
    "Сахароза",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Tartaglia]: CharacterClass.init([
    CharacterIds.Tartaglia,
    "Тарталья",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.PolarStar),
  [CharacterIds.Thoma]: CharacterClass.init([
    CharacterIds.Thoma,
    "Тома",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Tighnari]: CharacterClass.init([
    CharacterIds.Tighnari,
    "Тигнари",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Dendro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.HuntersPath),
  [CharacterIds.TravelerAnemo]: CharacterClass.init([
    CharacterIds.TravelerAnemo,
    "Путешественник (Анемо)",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Anemo,
    undefined,
  ]).setName("Путешественник"),
  [CharacterIds.TravelerDendro]: CharacterClass.init([
    CharacterIds.TravelerDendro,
    "Путешественник (Дендро)",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Dendro,
    undefined,
  ]).setName("Путешественник"),
  [CharacterIds.TravelerElectro]: CharacterClass.init([
    CharacterIds.TravelerElectro,
    "Путешественник (Электро)",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Electro,
    undefined,
  ]).setName("Путешественник"),
  [CharacterIds.TravelerGeo]: CharacterClass.init([
    CharacterIds.TravelerGeo,
    "Путешественник (Гео)",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Geo,
    undefined,
  ]).setName("Путешественник"),
  [CharacterIds.TravelerHydro]: CharacterClass.init([
    CharacterIds.TravelerHydro,
    "Путешественник (Гидро)",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Hydro,
    undefined,
  ]).setArkhe("🟡").setName("Путешественник"),
  [CharacterIds.TravelerPyro]: CharacterClass.init([
    CharacterIds.TravelerPyro,
    "Путешественник (Пиро)",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Pyro,
    undefined,
  ]).setName("Путешественник"),
  [CharacterIds.Varesa]: CharacterClass.init([
    CharacterIds.Varesa,
    "Вареса",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.VividNotions),
  [CharacterIds.Venti]: CharacterClass.init([
    CharacterIds.Venti,
    "Венти",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]).setSignatureWeaponId(WeaponIds.ElegyForTheEnd),
  [CharacterIds.Wanderer]: CharacterClass.init([
    CharacterIds.Wanderer,
    "Странник",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.TulaytullahsRemembrance),
  [CharacterIds.Wriothesley]: CharacterClass.init([
    CharacterIds.Wriothesley,
    "Ризли",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Cryo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setArkhe("🟣").setSignatureWeaponId(WeaponIds.CashflowSupervision),
  [CharacterIds.Xiangling]: CharacterClass.init([
    CharacterIds.Xiangling,
    "Сян Лин",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]),
  [CharacterIds.Xianyun]: CharacterClass.init([
    CharacterIds.Xianyun,
    "Сянь Юнь",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.CranesEchoingCall),
  [CharacterIds.Xiao]: CharacterClass.init([
    CharacterIds.Xiao,
    "Сяо",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Anemo,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.PrimordialJadeWingedSpear),
  [CharacterIds.Xilonen]: CharacterClass.init([
    CharacterIds.Xilonen,
    "Шилонен",
    5,
    WeaponTypeIds.Sword,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.PeakPatrolSong),
  [CharacterIds.Xingqiu]: CharacterClass.init([
    CharacterIds.Xingqiu,
    "Син Цю",
    4,
    WeaponTypeIds.Sword,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Xinyan]: CharacterClass.init([
    CharacterIds.Xinyan,
    "Синь Янь",
    4,
    WeaponTypeIds.Claymore,
    ElementIds.Pyro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.YaeMiko]: CharacterClass.init([
    CharacterIds.YaeMiko,
    "Яэ Мико",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Electro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]).setSignatureWeaponId(WeaponIds.KagurasVerity),
  [CharacterIds.Yanfei]: CharacterClass.init([
    CharacterIds.Yanfei,
    "Янь Фэй",
    4,
    WeaponTypeIds.Catalyst,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]),
  [CharacterIds.Yaoyao]: CharacterClass.init([
    CharacterIds.Yaoyao,
    "Яо Яо",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Dendro,
    [CharacterRoleIds.OffField, CharacterRoleIds.Survivability],
  ]),
  [CharacterIds.Yelan]: CharacterClass.init([
    CharacterIds.Yelan,
    "Е Лань",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Hydro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OffField],
  ]).setSignatureWeaponId(WeaponIds.AquaSimulacra),
  [CharacterIds.Yoimiya]: CharacterClass.init([
    CharacterIds.Yoimiya,
    "Ёимия",
    5,
    WeaponTypeIds.Bow,
    ElementIds.Pyro,
    [CharacterRoleIds.Dps, CharacterRoleIds.OnField],
  ]).setSignatureWeaponId(WeaponIds.ThunderingPulse),
  [CharacterIds.YumemizukiMizuki]: CharacterClass.init([
    CharacterIds.YumemizukiMizuki,
    "Мидзуки",
    5,
    WeaponTypeIds.Catalyst,
    ElementIds.Anemo,
    [CharacterRoleIds.OnField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setName("Юмэмидзуки Мидзуки").setSignatureWeaponId(WeaponIds.SunnyMorningSleepIn),
  [CharacterIds.YunJin]: CharacterClass.init([
    CharacterIds.YunJin,
    "Юнь Цзинь",
    4,
    WeaponTypeIds.Polearm,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support],
  ]),
  [CharacterIds.Zhongli]: CharacterClass.init([
    CharacterIds.Zhongli,
    "Чжун Ли",
    5,
    WeaponTypeIds.Polearm,
    ElementIds.Geo,
    [CharacterRoleIds.OffField, CharacterRoleIds.Support, CharacterRoleIds.Survivability],
  ]).setSignatureWeaponId(WeaponIds.VortexVanquisher),
} as Record<Character["id"], Character>;
