import { ElementKeys } from "@/database/elements/enums";

export const CharacterIds = {
  /* Альбедо                  */ Albedo: "Albedo",
  /* Аль-Хайтам               */ Alhaitham: "Alhaitham",
  /* Эмбер                    */ Amber: "Amber",
  /* Итто                     */ AratakiItto: "AratakiItto",
  /* Арлекино                 */ Arlecchino: "Arlecchino",
  /* Бай Чжу                  */ Baizhu: "Baizhu",
  /* Барбара                  */ Barbara: "Barbara",
  /* Бэй Доу                  */ Beidou: "Beidou",
  /* Беннет                   */ Bennett: "Bennett",
  /* Кандакия                 */ Candace: "Candace",
  /* Шарлотта                 */ Charlotte: "Charlotte",
  /* Шеврёз                   */ Chevreuse: "Chevreuse",
  /* Тиори                    */ Chiori: "Chiori",
  /* Чун Юнь                  */ Chongyun: "Chongyun",
  /* Ситлали                  */ Citlali: "Citlali",
  /* Клоринда                 */ Clorinde: "Clorinde",
  /* Коллеи                   */ Collei: "Collei",
  /* Сайно                    */ Cyno: "Cyno",
  /* Далия                    */ Dahlia: "Dahlia",
  /* Дэхья                    */ Dehya: "Dehya",
  /* Дилюк                    */ Diluc: "Diluc",
  /* Диона                    */ Diona: "Diona",
  /* Дори                     */ Dori: "Dori",
  /* Эмилия                   */ Emilie: "Emilie",
  /* Эскофье                  */ Escoffier: "Escoffier",
  /* Эола                     */ Eula: "Eula",
  /* Фарузан                  */ Faruzan: "Faruzan",
  /* Фишль                    */ Fischl: "Fischl",
  /* Фремине                  */ Freminet: "Freminet",
  /* Фурина                   */ Furina: "Furina",
  /* Ка Мин                   */ Gaming: "Gaming",
  /* Гань Юй                  */ Ganyu: "Ganyu",
  /* Горо                     */ Gorou: "Gorou",
  /* Ху Тао                   */ HuTao: "HuTao",
  /* Иансан                   */ Iansan: "Iansan",
  /* Инеффа                   */ Ineffa: "Ineffa",
  /* Джинн                    */ Jean: "Jean",
  /* Качина                   */ Kachina: "Kachina",
  /* Кадзуха                  */ KaedeharaKazuha: "KaedeharaKazuha",
  /* Кэйа                     */ Kaeya: "Kaeya",
  /* Аяка                     */ KamisatoAyaka: "KamisatoAyaka",
  /* Аято                     */ KamisatoAyato: "KamisatoAyato",
  /* Кавех                    */ Kaveh: "Kaveh",
  /* Кэ Цин                   */ Keqing: "Keqing",
  /* Кинич                    */ Kinich: "Kinich",
  /* Кирара                   */ Kirara: "Kirara",
  /* Кли                      */ Klee: "Klee",
  /* Сара                     */ KujouSara: "KujouSara",
  /* Синобу                   */ KukiShinobu: "KukiShinobu",
  /* Лайла                    */ Layla: "Layla",
  /* Лиза                     */ Lisa: "Lisa",
  /* Линетт                   */ Lynette: "Lynette",
  /* Лини                     */ Lyney: "Lyney",
  /* Мавуика                  */ Mavuika: "Mavuika",
  /* Мика                     */ Mika: "Mika",
  /* Мона                     */ Mona: "Mona",
  /* Муалани                  */ Mualani: "Mualani",
  /* Нахида                   */ Nahida: "Nahida",
  /* Навия                    */ Navia: "Navia",
  /* Нёвиллет                 */ Neuvillette: "Neuvillette",
  /* Нилу                     */ Nilou: "Nilou",
  /* Нин Гуан                 */ Ningguang: "Ningguang",
  /* Ноэлль                   */ Noelle: "Noelle",
  /* Оророн                   */ Ororon: "Ororon",
  /* Ци Ци                    */ Qiqi: "Qiqi",
  /* Райдэн                   */ RaidenShogun: "RaidenShogun",
  /* Рэйзор                   */ Razor: "Razor",
  /* Розария                  */ Rosaria: "Rosaria",
  /* Кокоми                   */ SangonomiyaKokomi: "SangonomiyaKokomi",
  /* Саю                      */ Sayu: "Sayu",
  /* Сетос                    */ Sethos: "Sethos",
  /* Шэнь Хэ                  */ Shenhe: "Shenhe",
  /* Хэйдзо                   */ ShikanoinHeizou: "ShikanoinHeizou",
  /* Сиджвин                  */ Sigewinne: "Sigewinne",
  /* Скирк                    */ Skirk: "Skirk",
  /* Сахароза                 */ Sucrose: "Sucrose",
  /* Тарталья                 */ Tartaglia: "Tartaglia",
  /* Тома                     */ Thoma: "Thoma",
  /* Тигнари                  */ Tighnari: "Tighnari",
  /* Путешественник (Анемо)   */ TravelerAnemo: `Traveler_${ElementKeys.Anemo}`,
  /* Путешественник (Дендро)  */ TravelerDendro: `Traveler_${ElementKeys.Dendro}`,
  /* Путешественник (Электро) */ TravelerElectro: `Traveler_${ElementKeys.Electro}`,
  /* Путешественник (Гео)     */ TravelerGeo: `Traveler_${ElementKeys.Geo}`,
  /* Путешественник (Гидро)   */ TravelerHydro: `Traveler_${ElementKeys.Hydro}`,
  /* Путешественник (Пиро)    */ TravelerPyro: `Traveler_${ElementKeys.Pyro}`,
  /* Вареса                   */ Varesa: "Varesa",
  /* Венти                    */ Venti: "Venti",
  /* Странник                 */ Wanderer: "Wanderer",
  /* Ризли                    */ Wriothesley: "Wriothesley",
  /* Сян Лин                  */ Xiangling: "Xiangling",
  /* Сянь Юнь                 */ Xianyun: "Xianyun",
  /* Сяо                      */ Xiao: "Xiao",
  /* Шилонен                  */ Xilonen: "Xilonen",
  /* Син Цю                   */ Xingqiu: "Xingqiu",
  /* Синь Янь                 */ Xinyan: "Xinyan",
  /* Яэ Мико                  */ YaeMiko: "YaeMiko",
  /* Янь Фэй                  */ Yanfei: "Yanfei",
  /* Яо Яо                    */ Yaoyao: "Yaoyao",
  /* Е Лань                   */ Yelan: "Yelan",
  /* Ёимия                    */ Yoimiya: "Yoimiya",
  /* Юнь Цзинь                */ YunJin: "YunJin",
  /* Чжун Ли                  */ Zhongli: "Zhongli",
} as const;
