export const ArtifactSetIds = {
  /* Архаичный камень                       */ ArchaicPetra: "ArchaicPetra",
  /* Заблудший в метели                     */ BlizzardStrayer: "BlizzardStrayer",
  /* Рыцарь крови                           */ BloodstainedChivalry: "BloodstainedChivalry",
  /* Горящая алая ведьма                    */ CrimsonWitchOfFlames: "CrimsonWitchOfFlames",
  /* Воспоминания дремучего леса            */ DeepwoodMemories: "DeepwoodMemories",
  /* Хроники Чертогов в пустыне             */ DesertPavilionChronicle: "DesertPavilionChronicle",
  /* Отголоски подношения                   */ EchoesOfAnOffering: "EchoesOfAnOffering",
  /* Эмблема рассечённой судьбы             */ EmblemOfSeveredFate: "EmblemOfSeveredFate",
  /* Финал галерей глубин                   */ FinaleOfTheDeepGalleries: "FinaleOfTheDeepGalleries",
  /* Цветок потерянного рая                 */ FlowerOfParadiseLost: "FlowerOfParadiseLost",
  /* Фрагмент гармонической фантазии        */ FragmentOfHarmonicWhimsy: "FragmentOfHarmonicWhimsy",
  /* Позолоченные сны                       */ GildedDreams: "GildedDreams",
  /* Конец гладиатора                       */ GladiatorsFinale: "GladiatorsFinale",
  /* Золотая труппа                         */ GoldenTroupe: "GoldenTroupe",
  /* Сердце глубин                          */ HeartOfDepth: "HeartOfDepth",
  /* Кокон сладких грёз                     */ HuskOfOpulentDreams: "HuskOfOpulentDreams",
  /* Инструктор                             */ Instructor: "Instructor",
  /* Ступающий по лаве                      */ Lavawalker: "Lavawalker",
  /* Клятва долгой ночи                     */ LongNightsOath: "LongNightsOath",
  /* Возлюбленная юная дева                 */ MaidenBeloved: "MaidenBeloved",
  /* Охотник Сумеречного двора              */ MarechausseeHunter: "MarechausseeHunter",
  /* Ночной шёпот в Лесу откликающегося эха */ NighttimeWhispersInTheEchoingWoods: "NighttimeWhispersInTheEchoingWoods",
  /* Церемония древней знати                */ NoblesseOblige: "NoblesseOblige",
  /* Сон нимфы                              */ NymphsDream: "NymphsDream",
  /* Обсидиановый фолиант                   */ ObsidianCodex: "ObsidianCodex",
  /* Моллюск морских красок                 */ OceanHuedClam: "OceanHuedClam",
  /* Бледный огонь                          */ PaleFlame: "PaleFlame",
  /* Встречная комета                       */ RetracingBolide: "RetracingBolide",
  /* Свиток героя сожжённого города         */ ScrollOfTheHeroOfCinderCity: "ScrollOfTheHeroOfCinderCity",
  /* Воспоминания Симэнавы                  */ ShimenawasReminiscence: "ShimenawasReminiscence",
  /* Серенада шёлковой луны                 */ SilkenMoonsSerenade: "SilkenMoonsSerenade",
  /* Песнь былых времён                     */ SongOfDaysPast: "SongOfDaysPast",
  /* Стойкость Миллелита                    */ TenacityOfTheMillelith: "TenacityOfTheMillelith",
  /* Громогласный рёв ярости                */ ThunderingFury: "ThunderingFury",
  /* Усмиряющий гром                        */ Thundersoother: "Thundersoother",
  /* Киноварное загробье                    */ VermillionHereafter: "VermillionHereafter",
  /* Изумрудная тень                        */ ViridescentVenerer: "ViridescentVenerer",
  /* Сияние Вурукаши                        */ VourukashasGlow: "VourukashasGlow",
  /* Странствующий ансамбль                 */ WanderersTroupe: "WanderersTroupe",
} as const;
