export const WeaponIds = {
  /* Тысяча ослепительных солнц            */ AThousandBlazingSuns: "a_thousand_blazing_suns",
  /* Сновидения тысячи ночей               */ AThousandFloatingDreams: "a_thousand_floating_dreams",
  /* Отпущение грехов                      */ Absolution: "absolution",
  /* Акуомару                              */ Akuoumaru: "akuoumaru",
  /* Охотник во тьме                       */ AlleyHunter: "alley_hunter",
  /* Амэнома Кагэути                       */ AmenomaKageuchi: "amenoma_kageuchi",
  /* Лук Амоса                             */ AmosBow: "amos_bow",
  /* Аква симулякрум                       */ AquaSimulacra: "aqua_simulacra",
  /* Меч Сокола                            */ AquilaFavonia: "aquila_favonia",
  /* Пепельный рог                         */ AshGravenDrinkingHorn: "ash_graven_drinking_horn",
  /* Алое перо звёздного грифа             */ AstralVulturesCrimsonPlumage: "astral_vultures_crimson_plumage",
  /* Лазурное сияние                       */ Azurelight: "azurelight",
  /* Песнь необъятной лазури               */ BalladOfTheBoundlessBlue: "ballad_of_the_boundless_blue",
  /* Баллада фьордов                       */ BalladOfTheFjords: "ballad_of_the_fjords",
  /* Маяк тростникового моря               */ BeaconOfTheReedSea: "beacon_of_the_reed_sea",
  /* Чёрная кисть                          */ BlackTassel: "black_tassel",
  /* Черногорский агат                     */ BlackcliffAgate: "blackcliff_agate",
  /* Черногорский длинный меч              */ BlackcliffLongsword: "blackcliff_longsword",
  /* Черногорская пика                     */ BlackcliffPole: "blackcliff_pole",
  /* Черногорская бритва                   */ BlackcliffSlasher: "blackcliff_slasher",
  /* Черногорский боевой лук               */ BlackcliffWarbow: "blackcliff_warbow",
  /* Фонарь чёрной сердцевины              */ BlackmarrowLantern: "blackmarrow_lantern",
  /* Окровавленные руины                   */ BloodsoakedRuins: "bloodsoaked_ruins",
  /* Меч драконьей крови                   */ BloodtaintedGreatsword: "bloodtainted_greatsword",
  /* Бедствие Эшу                          */ CalamityOfEshu: "calamity_of_eshu",
  /* Усмиритель бед                        */ CalamityQueller: "calamity_queller",
  /* Казначейский надзор                   */ CashflowSupervision: "cashflow_supervision",
  /* Разбивающий цепи                      */ ChainBreaker: "chain_breaker",
  /* Киноварное веретено                   */ CinnabarSpindle: "cinnabar_spindle",
  /* Выкованный из облаков                 */ Cloudforged: "cloudforged",
  /* Составной лук                         */ CompoundBow: "compound_bow",
  /* Холодное лезвие                       */ CoolSteel: "cool_steel",
  /* Звонкий клич журавля                  */ CranesEchoingCall: "cranes_echoing_call",
  /* Пика полумесяца                       */ CrescentPike: "crescent_pike",
  /* Очертания алой луны                   */ CrimsonMoonsSemblance: "crimson_moons_semblance",
  /* Тёмный железный меч                   */ DarkIronSword: "dark_iron_sword",
  /* Рассветный иней                       */ DawningFrost: "dawning_frost",
  /* Смертельный бой                       */ Deathmatch: "deathmatch",
  /* Дубина переговоров                    */ DebateClub: "debate_club",
  /* Диалог пустынных мудрецов             */ DialoguesOfTheDesertSages: "dialogues_of_the_desert_sages",
  /* Истории Додоко                        */ DodocoTales: "dodoco_tales",
  /* Гроза драконов                        */ DragonsBane: "dragons_bane",
  /* Копьё Драконьего хребта               */ DragonspineSpear: "dragonspine_spear",
  /* Сотрясающий землю                     */ EarthShaker: "earth_shaker",
  /* Элегия погибели                       */ ElegyForTheEnd: "elegy_for_the_end",
  /* Изумрудный шар                        */ EmeraldOrb: "emerald_orb",
  /* Иссушитель                            */ EndOfTheLine: "end_of_the_line",
  /* Сияющая жатва                         */ EngulfingLightning: "engulfing_lightning",
  /* Лютня ткача света                     */ EtherlightSpindlelute: "etherlight_spindlelute",
  /* Вечное лунное сияние                  */ EverlastingMoonglow: "everlasting_moonglow",
  /* Око сознания                          */ EyeOfPerception: "eye_of_perception",
  /* Гаснущие сумерки                      */ FadingTwilight: "fading_twilight",
  /* Клык Горного короля                   */ FangOfTheMountainKing: "fang_of_the_mountain_king",
  /* Кодекс Фавония                        */ FavoniusCodex: "favonius_codex",
  /* Двуручный меч Фавония                 */ FavoniusGreatsword: "favonius_greatsword",
  /* Копьё Фавония                         */ FavoniusLance: "favonius_lance",
  /* Меч Фавония                           */ FavoniusSword: "favonius_sword",
  /* Боевой лук Фавония                    */ FavoniusWarbow: "favonius_warbow",
  /* Металлическая тень                    */ FerrousShadow: "ferrous_shadow",
  /* Осквернённое желание                  */ FesteringDesire: "festering_desire",
  /* Филейный нож                          */ FilletBlade: "fillet_blade",
  /* Грандиозный финал глубин              */ FinaleOfTheDeep: "finale_of_the_deep",
  /* Выкованное пламенем озарение          */ FlameForgedInsight: "flame_forged_insight",
  /* Перевозчик Флёв Сандр                 */ FleuveCendreFerryman: "fleuve_cendre_ferryman",
  /* Украшенные цветами перья              */ FlowerWreathedFeathers: "flower_wreathed_feathers",
  /* Сверкание чистых вод                  */ FlowingPurity: "flowing_purity",
  /* Флейта Эспицаль                       */ FluteOfEzpitzal: "flute_of_ezpitzal",
  /* След радуги                           */ FootprintOfTheRainbow: "footprint_of_the_rainbow",
  /* Регалия леса                          */ ForestRegalia: "forest_regalia",
  /* Расколотый ореол                      */ FracturedHalo: "fractured_halo",
  /* Клятва свободы                        */ FreedomSworn: "freedom_sworn",
  /* Плод вечной мерзлоты                  */ Frostbearer: "frostbearer",
  /* Плод восполнения                      */ FruitOfFulfillment: "fruit_of_fulfillment",
  /* Плодотворный крюк                     */ FruitfulHook: "fruitful_hook",
  /* Кольцо Хакусин                        */ HakushinRing: "hakushin_ring",
  /* Алебарда Миллелита                    */ Halberd: "halberd",
  /* Хамаюми                               */ Hamayumi: "hamayumi",
  /* Харан гэппаку фуцу                    */ HaranGeppakuFutsu: "haran_geppaku_futsu",
  /* Предвестник зари                      */ HarbingerOfDawn: "harbinger_of_dawn",
  /* Охотничья тропа                       */ HuntersPath: "hunters_path",
  /* Клюв ибиса                            */ IbisPiercer: "ibis_piercer",
  /* Стальное жало                         */ IronSting: "iron_sting",
  /* Великолепие лазурного свода           */ JadefallsSplendor: "jadefalls_splendor",
  /* Кагоцурубэ Иссин                      */ KagotsurubeIsshin: "kagotsurube_isshin",
  /* Истина кагура                         */ KagurasVerity: "kaguras_verity",
  /* Кацурагикири Нагамаса                 */ KatsuragikiriNagamasa: "katsuragikiri_nagamasa",
  /* Ключ Хадж-нисут                       */ KeyOfKhajNisut: "key_of_khaj_nisut",
  /* Приближённый короля                   */ KingsSquire: "kings_squire",
  /* Крест-копьё Китаин                    */ KitainCrossSpear: "kitain_cross_spear",
  /* Свет лиственного разреза              */ LightOfFoliarIncision: "light_of_foliar_incision",
  /* Драконий рык                          */ LionsRoar: "lions_roar",
  /* Каменный меч                          */ LithicBlade: "lithic_blade",
  /* Каменное копьё                        */ LithicSpear: "lithic_spear",
  /* Молитва святым ветрам                 */ LostPrayerToTheSacredWinds: "lost_prayer_to_the_sacred_winds",
  /* Элегия Люмидус                        */ LumidouceElegy: "lumidouce_elegy",
  /* Благодатный владыка вод               */ LuxuriousSeaLord: "luxurious_sea_lord",
  /* Руководство по магии                  */ MagicGuide: "magic_guide",
  /* Цветок в латах                        */ MailedFlower: "mailed_flower",
  /* Аквамарин Махайры                     */ MakhairaAquamarine: "makhaira_aquamarine",
  /* Морской атлас                         */ MappaMare: "mappa_mare",
  /* Мастер-ключ                           */ MasterKey: "master_key",
  /* Память о пыли                         */ MemoryOfDust: "memory_of_dust",
  /* Посыльный                             */ Messenger: "messenger",
  /* Копьё послания ветров                 */ MissiveWindspear: "missive_windspear",
  /* Рассекающий туман                     */ MistsplitterReforged: "mistsplitter_reforged",
  /* Вальс Нирваны Ночи                    */ MitternachtsWaltz: "mitternachts_waltz",
  /* Пронзающий луну                       */ Moonpiercer: "moonpiercer",
  /* Рассвет прядильщицы луны              */ MoonweaversDawn: "moonweavers_dawn",
  /* Крепящий горы шип                     */ MountainBracingBolt: "mountain_bracing_bolt",
  /* Луна Моун                             */ MouunsMoon: "mouuns_moon",
  /* Зеркало прядильщицы ночи              */ NightweaversLookingGlass: "nightweavers_looking_glass",
  /* Око клятвы                            */ OathswornEye: "oathsworn_eye",
  /* Потусторонняя история                 */ OtherworldlyStory: "otherworldly_story",
  /* Песнь патруля пиков                   */ PeakPatrolSong: "peak_patrol_song",
  /* Полярная звезда                       */ PolarStar: "polar_star",
  /* Переносная мотопила                   */ PortablePowerSaw: "portable_power_saw",
  /* Хищник                                */ Predator: "predator",
  /* Драгоценный омут                      */ PrimordialJadeCutter: "primordial_jade_cutter",
  /* Нефритовый коршун                     */ PrimordialJadeWingedSpear: "primordial_jade_winged_spear",
  /* Бур рудоискателя                      */ ProspectorsDrill: "prospectors_drill",
  /* Лопата старателя                      */ ProspectorsShovel: "prospectors_shovel",
  /* Прототип: Янтарь                      */ PrototypeAmber: "prototype_amber",
  /* Прототип: Архаичный                   */ PrototypeArchaic: "prototype_archaic",
  /* Прототип: Полумесяц                   */ PrototypeCrescent: "prototype_crescent",
  /* Прототип: Злоба                       */ PrototypeRancour: "prototype_rancour",
  /* Прототип: Звёздный блеск              */ PrototypeStarglitter: "prototype_starglitter",
  /* Дождерез                              */ Rainslasher: "rainslasher",
  /* Дальномер                             */ RangeGauge: "range_gauge",
  /* Лук ворона                            */ RavenBow: "raven_bow",
  /* Изогнутый лук                         */ RecurveBow: "recurve_bow",
  /* Краснорогий камнеруб                  */ RedhornStonethresher: "redhorn_stonethresher",
  /* Шкатулка истин                        */ ReliquaryOfTruth: "reliquary_of_truth",
  /* Справедливая награда                  */ RightfulReward: "rightful_reward",
  /* Кольцо Яшче                           */ RingOfYaxche: "ring_of_yaxche",
  /* Королевский лук                       */ RoyalBow: "royal_bow",
  /* Королевский двуручный меч             */ RoyalGreatsword: "royal_greatsword",
  /* Королевский гримуар                   */ RoyalGrimoire: "royal_grimoire",
  /* Меч аристократов                      */ RoyalLongsword: "royal_longsword",
  /* Королевское копьё                     */ RoyalSpear: "royal_spear",
  /* Ржавый лук                            */ Rust: "rust",
  /* Посох жертвующей                      */ SacrificersStaff: "sacrificers_staff",
  /* Церемониальный лук                    */ SacrificialBow: "sacrificial_bow",
  /* Церемониальные мемуары                */ SacrificialFragments: "sacrificial_fragments",
  /* Церемониальный двуручный меч          */ SacrificialGreatsword: "sacrificial_greatsword",
  /* Жертвенный нефрит                     */ SacrificialJade: "sacrificial_jade",
  /* Церемониальный меч                    */ SacrificialSword: "sacrificial_sword",
  /* Деревянный клинок                     */ SapwoodBlade: "sapwood_blade",
  /* Наследник слепящего солнца            */ ScionOfTheBlazingSun: "scion_of_the_blazing_sun",
  /* Каденция одиночества                  */ SequenceOfSolitude: "sequence_of_solitude",
  /* Зов безмятежности                     */ SerenitysCall: "serenitys_call",
  /* Меч драконьей кости                   */ SerpentSpine: "serpent_spine",
  /* Клятва стрелка                        */ SharpshootersOath: "sharpshooters_oath",
  /* Сердечные струны дождя                */ SilvershowerHeartstrings: "silvershower_heartstrings",
  /* Большой меч небесного всадника        */ SkyriderGreatsword: "skyrider_greatsword",
  /* Меч небесного всадника                */ SkyriderSword: "skyrider_sword",
  /* Небесный атлас                        */ SkywardAtlas: "skyward_atlas",
  /* Небесный меч                          */ SkywardBlade: "skyward_blade",
  /* Небесное крыло                        */ SkywardHarp: "skyward_harp",
  /* Небесное величие                      */ SkywardPride: "skyward_pride",
  /* Небесная ось                          */ SkywardSpine: "skyward_spine",
  /* Рогатка                               */ Slingshot: "slingshot",
  /* Крюк силка                            */ SnareHook: "snare_hook",
  /* Заснеженное звёздное серебро          */ SnowTombedStarsilver: "snow_tombed_starsilver",
  /* Солнечная жемчужина                   */ SolarPearl: "solar_pearl",
  /* Песнь разбитых сосен                  */ SongOfBrokenPines: "song_of_broken_pines",
  /* Мелодия покоя                         */ SongOfStillness: "song_of_stillness",
  /* Блеск тихих вод                       */ SplendorOfTranquilWaters: "splendor_of_tranquil_waters",
  /* Посох Хомы                            */ StaffOfHoma: "staff_of_homa",
  /* Посох алых песков                     */ StaffOfTheScarletSands: "staff_of_the_scarlet_sands",
  /* Бдение взывающего к звёздам           */ StarcallersWatch: "starcallers_watch",
  /* Крепкая кость                         */ SturdyBone: "sturdy_bone",
  /* Кромсатель пиков                      */ SummitShaper: "summit_shaper",
  /* Сон солнечным утром                   */ SunnyMorningSleepIn: "sunny_morning_sleep_in",
  /* Лови волну                            */ SurfsUp: "surfs_up",
  /* Меч нисхождения                       */ SwordOfDescension: "sword_of_descension",
  /* Меч Нарциссенкрейца                   */ SwordOfNarzissenkreuz: "sword_of_narzissenkreuz",
  /* Симфонист ароматов                    */ SymphonistOfScents: "symphonist_of_scents",
  /* Говорящая палица                      */ TalkingStick: "talking_stick",
  /* Тамаюратэй но оханаси                 */ TamayurateiNoOhanashi: "tamayuratei_no_ohanashi",
  /* Вспышка во тьме                       */ TheAlleyFlash: "the_alley_flash",
  /* Меч-колокол                           */ TheBell: "the_bell",
  /* Чёрный меч                            */ TheBlackSword: "the_black_sword",
  /* «Улов»                                */ TheCatch: "the_catch",
  /* Верфь                                 */ TheDockhandsAssistant: "the_dockhands_assistant",
  /* Первый великий фокус                  */ TheFirstGreatMagic: "the_first_great_magic",
  /* Меч-флейта                            */ TheFlute: "the_flute",
  /* Бесструнный                           */ TheStringless: "the_stringless",
  /* Некованый                             */ TheUnforged: "the_unforged",
  /* Зелёный лук                           */ TheViridescentHunt: "the_viridescent_hunt",
  /* Песнь странника                       */ TheWidsith: "the_widsith",
  /* Эпос о драконоборцах                  */ ThrillingTalesOfDragonSlayers: "thrilling_tales_of_dragon_slayers",
  /* Громовой пульс                        */ ThunderingPulse: "thundering_pulse",
  /* Тень волны                            */ TidalShadow: "tidal_shadow",
  /* Обряд вечного течения                 */ TomeOfTheEternalFlow: "tome_of_the_eternal_flow",
  /* Токабо сигурэ                         */ ToukabouShigure: "toukabou_shigure",
  /* Меч путешественника                   */ TravelersHandySword: "travelers_handy_sword",
  /* Воспоминания Тулайтуллы               */ TulaytullahsRemembrance: "tulaytullahs_remembrance",
  /* Парный нефрит                         */ TwinNephrite: "twin_nephrite",
  /* «Магический супермеч высшего владыки» */ UltimateOverlordsMegaMagicSword: "ultimate_overlords_mega_magic_sword",
  /* Ураку мисугири                        */ UrakuMisugiri: "uraku_misugiri",
  /* Вердикт                               */ Verdict: "verdict",
  /* Переливающиеся чаяния                 */ VividNotions: "vivid_notions",
  /* Покоритель вихря                      */ VortexVanquisher: "vortex_vanquisher",
  /* Скитающаяся звезда                    */ WanderingEvenstar: "wandering_evenstar",
  /* Режущий волны плавник                 */ WavebreakersFin: "wavebreakers_fin",
  /* Вихрь на волнах                       */ WaveridingWhirl: "waveriding_whirl",
  /* Меч из белого железа                  */ WhiteIronGreatsword: "white_iron_greatsword",
  /* Белая кисть                           */ WhiteTassel: "white_tassel",
  /* Белая тень                            */ Whiteblind: "whiteblind",
  /* Ода анемонии                          */ WindblumeOde: "windblume_ode",
  /* Вино и песни                          */ WineAndSong: "wine_and_song",
  /* Волчий клык                           */ WolfFang: "wolf_fang",
  /* Волчья погибель                       */ WolfsGravestone: "wolfs_gravestone",
  /* Лунное сияние ксифоса                 */ XiphosMoonlight: "xiphos_moonlight",
} as const;
