export const ARTIFACT_SETS = {
  ARCHAIC_PETRA: "ArchaicPetra",
  BLIZZARD_STRAYER: "BlizzardStrayer",
  BLOODSTAINED_CHIVALRY: "BloodstainedChivalry",
  CRIMSON_WITCH_OF_FLAMES: "CrimsonWitchOfFlames",
  DEEPWOOD_MEMORIES: "DeepwoodMemories",
  DESERT_PAVILION_CHRONICLE: "DesertPavilionChronicle",
  ECHOES_OF_AN_OFFERING: "EchoesOfAnOffering",
  EMBLEM_OF_SEVERED_FATE: "EmblemOfSeveredFate",
  FINALE_OF_THE_DEEP_GALLERIES: "FinaleOfTheDeepGalleries",
  FLOWER_OF_PARADISE_LOST: "FlowerOfParadiseLost",
  FRAGMENT_OF_HARMONIC_WHIMSY: "FragmentOfHarmonicWhimsy",
  GILDED_DREAMS: "GildedDreams",
  GLADIATORS_FINALE: "GladiatorsFinale",
  GOLDEN_TROUPE: "GoldenTroupe",
  HEART_OF_DEPTH: "HeartOfDepth",
  HUSK_OF_OPULENT_DREAMS: "HuskOfOpulentDreams",
  INSTRUCTOR: "Instructor",
  LAVAWALKER: "Lavawalker",
  LONG_NIGHTS_OATH: "LongNightsOath",
  MAIDEN_BELOVED: "MaidenBeloved",
  MARECHAUSSEE_HUNTER: "MarechausseeHunter",
  NIGHT_OF_THE_SKYS_UNVEILING: "NightOfTheSkysUnveiling",
  NIGHTTIME_WHISPERS_IN_THE_ECHOING_WOODS: "NighttimeWhispersInTheEchoingWoods",
  NOBLESSE_OBLIGE: "NoblesseOblige",
  NYMPHS_DREAM: "NymphsDream",
  OBSIDIAN_CODEX: "ObsidianCodex",
  OCEAN_HUED_CLAM: "OceanHuedClam",
  PALE_FLAME: "PaleFlame",
  RETRACING_BOLIDE: "RetracingBolide",
  SCROLL_OF_THE_HERO_OF_CINDER_CITY: "ScrollOfTheHeroOfCinderCity",
  SHIMENAWAS_REMINISCENCE: "ShimenawasReminiscence",
  SILKEN_MOONS_SERENADE: "SilkenMoonsSerenade",
  SONG_OF_DAYS_PAST: "SongOfDaysPast",
  TENACITY_OF_THE_MILLELITH: "TenacityOfTheMillelith",
  THUNDERING_FURY: "ThunderingFury",
  THUNDERSOOTHER: "Thundersoother",
  VERMILLION_HEREAFTER: "VermillionHereafter",
  VIRIDESCENT_VENERER: "ViridescentVenerer",
  VOURUKASHAS_GLOW: "VourukashasGlow",
  WANDERERS_TROUPE: "WanderersTroupe",
} as const;

export type ArtifactSet = typeof ARTIFACT_SETS[keyof typeof ARTIFACT_SETS];

export const ARTIFACT_SET_LABELS: Record<ArtifactSet, string> = {
  [ARTIFACT_SETS.ARCHAIC_PETRA]: "Архаичный камень",
  [ARTIFACT_SETS.BLIZZARD_STRAYER]: "Заблудший в метели",
  [ARTIFACT_SETS.BLOODSTAINED_CHIVALRY]: "Рыцарь крови",
  [ARTIFACT_SETS.CRIMSON_WITCH_OF_FLAMES]: "Горящая алая ведьма",
  [ARTIFACT_SETS.DEEPWOOD_MEMORIES]: "Воспоминания дремучего леса",
  [ARTIFACT_SETS.DESERT_PAVILION_CHRONICLE]: "Хроники Чертогов в пустыне",
  [ARTIFACT_SETS.ECHOES_OF_AN_OFFERING]: "Отголоски подношения",
  [ARTIFACT_SETS.EMBLEM_OF_SEVERED_FATE]: "Эмблема рассечённой судьбы",
  [ARTIFACT_SETS.FINALE_OF_THE_DEEP_GALLERIES]: "Финал галерей глубин",
  [ARTIFACT_SETS.FLOWER_OF_PARADISE_LOST]: "Цветок потерянного рая",
  [ARTIFACT_SETS.FRAGMENT_OF_HARMONIC_WHIMSY]: "Фрагмент гармонической фантазии",
  [ARTIFACT_SETS.GILDED_DREAMS]: "Позолоченные сны",
  [ARTIFACT_SETS.GLADIATORS_FINALE]: "Конец гладиатора",
  [ARTIFACT_SETS.GOLDEN_TROUPE]: "Золотая труппа",
  [ARTIFACT_SETS.HEART_OF_DEPTH]: "Сердце глубин",
  [ARTIFACT_SETS.HUSK_OF_OPULENT_DREAMS]: "Кокон сладких грёз",
  [ARTIFACT_SETS.INSTRUCTOR]: "Инструктор",
  [ARTIFACT_SETS.LAVAWALKER]: "Ступающий по лаве",
  [ARTIFACT_SETS.LONG_NIGHTS_OATH]: "Клятва долгой ночи",
  [ARTIFACT_SETS.MAIDEN_BELOVED]: "Возлюбленная юная дева",
  [ARTIFACT_SETS.MARECHAUSSEE_HUNTER]: "Охотник Сумеречного двора",
  [ARTIFACT_SETS.NIGHT_OF_THE_SKYS_UNVEILING]: "Ночь открытия неба",
  [ARTIFACT_SETS.NIGHTTIME_WHISPERS_IN_THE_ECHOING_WOODS]: "Ночной шёпот в Лесу откликающегося эха",
  [ARTIFACT_SETS.NOBLESSE_OBLIGE]: "Церемония древней знати",
  [ARTIFACT_SETS.NYMPHS_DREAM]: "Сон нимфы",
  [ARTIFACT_SETS.OBSIDIAN_CODEX]: "Обсидиановый фолиант",
  [ARTIFACT_SETS.OCEAN_HUED_CLAM]: "Моллюск морских красок",
  [ARTIFACT_SETS.PALE_FLAME]: "Бледный огонь",
  [ARTIFACT_SETS.RETRACING_BOLIDE]: "Встречная комета",
  [ARTIFACT_SETS.SCROLL_OF_THE_HERO_OF_CINDER_CITY]: "Свиток героя сожжённого города",
  [ARTIFACT_SETS.SHIMENAWAS_REMINISCENCE]: "Воспоминания Симэнавы",
  [ARTIFACT_SETS.SILKEN_MOONS_SERENADE]: "Серенада шёлковой луны",
  [ARTIFACT_SETS.SONG_OF_DAYS_PAST]: "Песнь былых времён",
  [ARTIFACT_SETS.TENACITY_OF_THE_MILLELITH]: "Стойкость Миллелита",
  [ARTIFACT_SETS.THUNDERING_FURY]: "Громогласный рёв ярости",
  [ARTIFACT_SETS.THUNDERSOOTHER]: "Усмиряющий гром",
  [ARTIFACT_SETS.VERMILLION_HEREAFTER]: "Киноварное загробье",
  [ARTIFACT_SETS.VIRIDESCENT_VENERER]: "Изумрудная тень",
  [ARTIFACT_SETS.VOURUKASHAS_GLOW]: "Сияние Вурукаши",
  [ARTIFACT_SETS.WANDERERS_TROUPE]: "Странствующий ансамбль",
} as const;
