import { ArtifactSetUidEnum } from "./enums/artifact-sets";
import { CharacterRoleUidEnum } from "./enums/character-roles";
import { CharacterUidEnum } from "./enums/characters";
import { ElementUidEnum } from "./enums/elements";
import { publicImageSrc } from "@/lib/utils";
import { RegionUidEnum } from "./enums/regions";
import { WeaponTypeUidEnum } from "./enums/weapon-types";
import { WeaponUidEnum } from "./enums/weapons";
import { WorldUidEnum } from "./enums/worlds";
import type { Characters } from "./types/characters";

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`characters/${src}`);

export const characters = {
  [CharacterUidEnum.Arlecchino]: {
    uid: CharacterUidEnum.Arlecchino,
    name: "Арлекино",
    small_image_src: imageSrc("arlecchino-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Snezhnaya,
    signature_weapon_uid: WeaponUidEnum.CrimsonMoonsSemblance,
  },
  [CharacterUidEnum.Bennett]: {
    uid: CharacterUidEnum.Bennett,
    name: "Беннет",
    small_image_src: imageSrc("bennett-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
  },
  [CharacterUidEnum.Varesa]: {
    uid: CharacterUidEnum.Varesa,
    name: "Вареса",
    small_image_src: imageSrc("varesa-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
    signature_weapon_uid: WeaponUidEnum.VividNotions,
  },
  [CharacterUidEnum.Dahlia]: {
    uid: CharacterUidEnum.Dahlia,
    name: "Далия",
    small_image_src: imageSrc("dahlia-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [CharacterRoleUidEnum.OffField],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
  },
  [CharacterUidEnum.Iansan]: {
    uid: CharacterUidEnum.Iansan,
    name: "Иансан",
    small_image_src: imageSrc("iansan-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
  },
  [CharacterUidEnum.Collei]: {
    uid: CharacterUidEnum.Collei,
    name: "Коллеи",
    small_image_src: imageSrc("collei-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Bow,
    element_uid: ElementUidEnum.Dendro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
  },
  [CharacterUidEnum.KukiShinobu]: {
    uid: CharacterUidEnum.KukiShinobu,
    name: "Куки Синобу",
    small_image_src: imageSrc("kuki_shinobu-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Inazuma,
  },
  [CharacterUidEnum.Layla]: {
    uid: CharacterUidEnum.Layla,
    name: "Лайла",
    small_image_src: imageSrc("layla-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
  },
  [CharacterUidEnum.Lyney]: {
    uid: CharacterUidEnum.Lyney,
    name: "Лини",
    small_image_src: imageSrc("lyney-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Bow,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
  },
  [CharacterUidEnum.Mavuika]: {
    uid: CharacterUidEnum.Mavuika,
    name: "Мавуика",
    small_image_src: imageSrc("mavuika-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Claymore,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [
      CharacterRoleUidEnum.OnField,
      CharacterRoleUidEnum.OffField,
      CharacterRoleUidEnum.DPS,
      CharacterRoleUidEnum.Support,
    ],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
  },
  [CharacterUidEnum.Mika]: {
    uid: CharacterUidEnum.Mika,
    name: "Мика",
    small_image_src: imageSrc("mika-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
  },
  [CharacterUidEnum.Nahida]: {
    uid: CharacterUidEnum.Nahida,
    name: "Нахида",
    small_image_src: imageSrc("nahida-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Dendro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS, CharacterRoleUidEnum.Support],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
  },
  [CharacterUidEnum.Neuvillette]: {
    uid: CharacterUidEnum.Neuvillette,
    name: "Нёвиллет",
    small_image_src: imageSrc("neuvillette-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    signature_weapon_uid: WeaponUidEnum.TomeOfTheEternalFlow,
  },
  [CharacterUidEnum.Wriothesley]: {
    uid: CharacterUidEnum.Wriothesley,
    name: "Ризли",
    small_image_src: imageSrc("wriothesley-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
  },
  [CharacterUidEnum.Rosaria]: {
    uid: CharacterUidEnum.Rosaria,
    name: "Розария",
    small_image_src: imageSrc("rosaria-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
  },
  [CharacterUidEnum.Cyno]: {
    uid: CharacterUidEnum.Cyno,
    name: "Сайно",
    small_image_src: imageSrc("cyno-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
  },
  [CharacterUidEnum.Sucrose]: {
    uid: CharacterUidEnum.Sucrose,
    name: "Сахароза",
    small_image_src: imageSrc("sucrose-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Anemo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
  },
  [CharacterUidEnum.Xingqiu]: {
    uid: CharacterUidEnum.Xingqiu,
    name: "Син Цю",
    small_image_src: imageSrc("xingqiu-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Liyue,
  },
  [CharacterUidEnum.Skirk]: {
    uid: CharacterUidEnum.Skirk,
    name: "Скирк",
    small_image_src: imageSrc("skirk-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Another,
    signature_weapon_uid: WeaponUidEnum.Azurelight,
    signature_artifact_set_uid: ArtifactSetUidEnum.FinaleOfTheDeepGalleries,
  },
  [CharacterUidEnum.Xiangling]: {
    uid: CharacterUidEnum.Xiangling,
    name: "Сян Лин",
    small_image_src: imageSrc("xiangling-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Liyue,
  },
  [CharacterUidEnum.Tartaglia]: {
    uid: CharacterUidEnum.Tartaglia,
    name: "Тарталья",
    small_image_src: imageSrc("tartaglia-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Bow,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Snezhnaya,
  },
  [CharacterUidEnum.Fischl]: {
    uid: CharacterUidEnum.Fischl,
    name: "Фишль",
    small_image_src: imageSrc("fischl-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Bow,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
  },
  [CharacterUidEnum.Furina]: {
    uid: CharacterUidEnum.Furina,
    name: "Фурина",
    small_image_src: imageSrc("furina-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [
      CharacterRoleUidEnum.OffField,
      CharacterRoleUidEnum.DPS,
      CharacterRoleUidEnum.Support,
      CharacterRoleUidEnum.Survivability,
    ],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    signature_weapon_uid: WeaponUidEnum.SplendorOfTranquilWaters,
  },
  [CharacterUidEnum.Qiqi]: {
    uid: CharacterUidEnum.Qiqi,
    name: "Ци Ци",
    small_image_src: imageSrc("qiqi-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Liyue,
  },
  [CharacterUidEnum.Chevreuse]: {
    uid: CharacterUidEnum.Chevreuse,
    name: "Шеврёз",
    small_image_src: imageSrc("chevreuse-small-106x106.png"),
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
  },
  [CharacterUidEnum.Xilonen]: {
    uid: CharacterUidEnum.Xilonen,
    name: "Шилонен",
    small_image_src: imageSrc("xilonen-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Geo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
    signature_weapon_uid: WeaponUidEnum.PeakPatrolSong,
  },
  [CharacterUidEnum.Escoffier]: {
    uid: CharacterUidEnum.Escoffier,
    name: "Эскофье",
    small_image_src: imageSrc("escoffier-small-106x106.png"),
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [
      CharacterRoleUidEnum.OffField,
      CharacterRoleUidEnum.DPS,
      CharacterRoleUidEnum.Support,
      CharacterRoleUidEnum.Survivability,
    ],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    signature_weapon_uid: WeaponUidEnum.SymphonistOfScents,
  },
} as Characters;
