import { ArtifactSetUidEnum } from "./enums/artifact-sets";
import { CharacterRoleUidEnum } from "./enums/character-roles";
import { CharacterUidEnum } from "./enums/characters";
import { ElementUidEnum } from "./enums/elements";
import { publicImageSrc } from "@/lib/utils";
import { RegionUidEnum } from "./enums/regions";
import { WeaponTypeUidEnum } from "./enums/weapon-types";
import { WeaponUidEnum } from "./enums/weapons";
import { WorldUidEnum } from "./enums/worlds";
import type { Characters } from "./types/characters";

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`characters/${src}`);

export const characters = {
  [CharacterUidEnum.Arlecchino]: {
    name: "Арлекино",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Snezhnaya,
    signature_weapon_uid: WeaponUidEnum.CrimsonMoonsSemblance,
    small_image_src: imageSrc("arlecchino-small-106x106.png"),
  },
  [CharacterUidEnum.Bennett]: {
    name: "Беннет",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
    small_image_src: imageSrc("bennett-small-106x106.png"),
  },
  [CharacterUidEnum.Varesa]: {
    name: "Вареса",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
    signature_weapon_uid: WeaponUidEnum.VividNotions,
    small_image_src: imageSrc("varesa-small-106x106.png"),
  },
  [CharacterUidEnum.Iansan]: {
    name: "Иансан",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
    small_image_src: imageSrc("iansan-small-106x106.png"),
  },
  [CharacterUidEnum.Collei]: {
    name: "Коллеи",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Bow,
    element_uid: ElementUidEnum.Dendro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
    small_image_src: imageSrc("collei-small-106x106.png"),
  },
  [CharacterUidEnum.KukiShinobu]: {
    name: "Куки Синобу",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Inazuma,
    small_image_src: imageSrc("kuki_shinobu-small-106x106.png"),
  },
  [CharacterUidEnum.Layla]: {
    name: "Лайла",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
    small_image_src: imageSrc("layla-small-106x106.png"),
  },
  [CharacterUidEnum.Mika]: {
    name: "Мика",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
    small_image_src: imageSrc("mika-small-106x106.png"),
  },
  [CharacterUidEnum.Nahida]: {
    name: "Нахида",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Dendro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS, CharacterRoleUidEnum.Support],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
    small_image_src: imageSrc("nahida-small-106x106.png"),
  },
  [CharacterUidEnum.Neuvillette]: {
    name: "Нёвиллет",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    signature_weapon_uid: WeaponUidEnum.TomeOfTheEternalFlow,
    small_image_src: imageSrc("neuvillette-small-106x106.png"),
  },
  [CharacterUidEnum.Cyno]: {
    name: "Сайно",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Sumeru,
    small_image_src: imageSrc("cyno-small-106x106.png"),
  },
  [CharacterUidEnum.Sucrose]: {
    name: "Сахароза",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Catalyst,
    element_uid: ElementUidEnum.Anemo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
    small_image_src: imageSrc("sucrose-small-106x106.png"),
  },
  [CharacterUidEnum.Xingqiu]: {
    name: "Син Цю",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Liyue,
    small_image_src: imageSrc("xingqiu-small-106x106.png"),
  },
  [CharacterUidEnum.Skirk]: {
    name: "Скирк",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OnField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Another,
    signature_weapon_uid: WeaponUidEnum.Azurelight,
    signature_artifact_set_uid: ArtifactSetUidEnum.FinaleOfTheDeepGalleries,
    small_image_src: imageSrc("skirk-small-106x106.png"),
  },
  [CharacterUidEnum.Xiangling]: {
    name: "Сян Лин",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Liyue,
    small_image_src: imageSrc("xiangling-small-106x106.png"),
  },
  [CharacterUidEnum.Fischl]: {
    name: "Фишль",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Bow,
    element_uid: ElementUidEnum.Electro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.DPS],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Mondstadt,
    small_image_src: imageSrc("fischl-small-106x106.png"),
  },
  [CharacterUidEnum.Furina]: {
    name: "Фурина",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Hydro,
    roles_uid: [
      CharacterRoleUidEnum.OffField,
      CharacterRoleUidEnum.DPS,
      CharacterRoleUidEnum.Support,
      CharacterRoleUidEnum.Survivability,
    ],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    signature_weapon_uid: WeaponUidEnum.SplendorOfTranquilWaters,
    small_image_src: imageSrc("furina-small-106x106.png"),
  },
  [CharacterUidEnum.Qiqi]: {
    name: "Ци Ци",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Liyue,
    small_image_src: imageSrc("qiqi-small-106x106.png"),
  },
  [CharacterUidEnum.Chevreuse]: {
    name: "Шеврёз",
    quality: 4,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Pyro,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    small_image_src: imageSrc("chevreuse-small-106x106.png"),
  },
  [CharacterUidEnum.Xilonen]: {
    name: "Шилонен",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Sword,
    element_uid: ElementUidEnum.Geo,
    roles_uid: [CharacterRoleUidEnum.OffField, CharacterRoleUidEnum.Support, CharacterRoleUidEnum.Survivability],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Natlan,
    signature_weapon_uid: WeaponUidEnum.PeakPatrolSong,
    small_image_src: imageSrc("xilonen-small-106x106.png"),
  },
  [CharacterUidEnum.Escoffier]: {
    name: "Эскофье",
    quality: 5,
    weapon_type_uid: WeaponTypeUidEnum.Polearm,
    element_uid: ElementUidEnum.Cryo,
    roles_uid: [
      CharacterRoleUidEnum.OffField,
      CharacterRoleUidEnum.DPS,
      CharacterRoleUidEnum.Support,
      CharacterRoleUidEnum.Survivability,
    ],
    world_uid: WorldUidEnum.Teyvat,
    region_uid: RegionUidEnum.Fontaine,
    signature_weapon_uid: WeaponUidEnum.SymphonistOfScents,
    small_image_src: imageSrc("escoffier-small-106x106.png"),
  },
} as Characters;
