import { ArtifactSetKeys } from "./enums/artifact-set";
import { CharacterKeys } from "./enums/character";
import { CharacterRoleKeys } from "./enums/character-role";
import { ElementKeys } from "./enums/element";
import { publicImageSrc } from "@/lib/utils";
import { WeaponKeys } from "./enums/weapon";
import { WeaponTypeKeys } from "./enums/weapon-type";
import type { Character, CharacterKey } from "./types/character";

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`characters/${src}`);

const traveler = {
  name: "Путешественник",
  rarity: 5,
  weapon_type_key: WeaponTypeKeys["⚔️"],
  image_src: imageSrc("traveler-256x256.gif"),
} as Omit<Character, "element_key" | "key">;

class _Character implements Character {
  readonly key: Character["key"];
  readonly name: Character["name"];
  readonly rarity: Character["rarity"];
  readonly weapon_type_key: Character["weapon_type_key"];
  readonly element_key: Character["element_key"];
  readonly arkhe: Character["arkhe"];
  readonly role_keys: Character["role_keys"];
  readonly image_src: Character["image_src"];
  readonly signature_weapon_key: Character["signature_weapon_key"];

  constructor(
    key: keyof typeof CharacterKeys,
    name: Character["name"],
    rarity: Character["rarity"],
    weaponTypeKey: keyof typeof WeaponTypeKeys,
    elementKey: keyof typeof ElementKeys,
    roleKeys: (keyof typeof CharacterRoleKeys)[],
    imageName: string,
    signatureWeaponKey?: keyof typeof WeaponKeys,
    arkhe?: Character["arkhe"],
  ) {
    this.key = CharacterKeys[key];
    this.name = name;
    this.rarity = rarity;
    this.weapon_type_key = WeaponTypeKeys[weaponTypeKey];
    this.element_key = ElementKeys[elementKey];
    this.role_keys = roleKeys.map(roleKey => CharacterRoleKeys[roleKey]);
    this.image_src = imageSrc(imageName);
    this.signature_weapon_key = signatureWeaponKey ? WeaponKeys[signatureWeaponKey] : undefined;
    this.arkhe = arkhe;
  }
}

export default {
  [CharacterKeys.Albedo]: new _Character("Albedo", "Альбедо", 5, "⚔️", "🪨", ["👥", "🗡️"], "albedo-256x256.webp"),
  [CharacterKeys.Alhaitham]: new _Character("Alhaitham", "Аль-Хайтам", 5, "⚔️", "🌿", ["👤", "🗡️"], "alhaitham-256x256.webp", "LightOfFoliarIncision"),
  [CharacterKeys.Amber]: new _Character("Amber", "Эмбер", 4, "🏹", "🔥", ["👥", "🗡️"], "amber-256x256.webp"),
  [CharacterKeys.AratakiItto]: new _Character("AratakiItto", "Итто", 5, "🗡️", "🪨", ["👤", "🗡️"], "arataki_itto-256x256.webp", "RedhornStonethresher"),
  [CharacterKeys.Arlecchino]: new _Character("Arlecchino", "Арлекино", 5, "🔱", "🔥", ["👤", "🗡️"], "arlecchino-256x256.webp", "CrimsonMoonsSemblance"),
  [CharacterKeys.Baizhu]: new _Character("Baizhu", "Бай Чжу", 5, "💥", "🌿", ["👥", "🤝", "🛡️"], "baizhu-256x256.webp", "JadefallsSplendor"),
  [CharacterKeys.Barbara]: new _Character("Barbara", "Барбара", 4, "💥", "💧", ["👥", "🛡️"], "barbara-256x256.webp"),
  [CharacterKeys.Beidou]: new _Character("Beidou", "Бэй Доу", 4, "🗡️", "⚡️", ["👥", "🗡️", "🛡️"], "beidou-256x256.webp"),
  [CharacterKeys.Bennett]: new _Character("Bennett", "Беннет", 4, "⚔️", "🔥", ["👥", "🤝", "🛡️"], "bennett-256x256.webp"),
  [CharacterKeys.Candace]: new _Character("Candace", "Кандакия", 4, "🔱", "💧", ["👥", "🤝"], "candace-256x256.webp"),
  [CharacterKeys.Charlotte]: new _Character("Charlotte", "Шарлотта", 4, "💥", "❄️", ["👥", "🛡️"], "charlotte-256x256.webp", undefined, "Пневма"),
  [CharacterKeys.Chevreuse]: new _Character("Chevreuse", "Шеврёз", 4, "🔱", "🔥", ["👥", "🤝", "🛡️"], "chevreuse-256x256.webp", undefined, "Усия"),
  [CharacterKeys.Chiori]: new _Character("Chiori", "Тиори", 5, "⚔️", "🪨", ["👥", "🗡️"], "chiori-256x256.webp", "UrakuMisugiri"),
  [CharacterKeys.Chongyun]: new _Character("Chongyun", "Чун Юнь", 4, "🗡️", "❄️", ["👥", "🗡️", "🤝"], "chongyun-256x256.webp"),
  [CharacterKeys.Citlali]: new _Character("Citlali", "Ситлали", 5, "💥", "❄️", ["👥", "🤝", "🛡️"], "citlali-256x256.webp", "StarcallersWatch"),
  [CharacterKeys.Clorinde]: new _Character("Clorinde", "Клоринда", 5, "⚔️", "⚡️", ["👤", "🗡️"], "clorinde-256x256.webp", "Absolution", "Усия"),
  [CharacterKeys.Collei]: new _Character("Collei", "Коллеи", 4, "🏹", "🌿", ["👥", "🗡️"], "collei-256x256.webp"),
  [CharacterKeys.Cyno]: new _Character("Cyno", "Сайно", 5, "🔱", "⚡️", ["👤", "🗡️"], "cyno-256x256.webp", "StaffOfTheScarletSands"),
  [CharacterKeys.Dahlia]: new _Character("Dahlia", "Далия", 4, "⚔️", "💧", ["👥", "🤝"], "dahlia-256x256.webp"),
  [CharacterKeys.Dehya]: new _Character("Dehya", "Дэхья", 5, "🗡️", "🔥", ["👥", "🗡️", "🛡️"], "dehya-256x256.webp", "BeaconOfTheReedSea"),
  [CharacterKeys.Diluc]: new _Character("Diluc", "Дилюк", 5, "🗡️", "🔥", ["👤", "🗡️"], "diluc-256x256.webp"),
  [CharacterKeys.Diona]: new _Character("Diona", "Диона", 4, "🏹", "❄️", ["👥", "🛡️"], "diona-256x256.webp"),
  [CharacterKeys.Dori]: new _Character("Dori", "Дори", 4, "🗡️", "⚡️", ["👥", "🛡️"], "dori-256x256.webp"),
  [CharacterKeys.Emilie]: new _Character("Emilie", "Эмилия", 5, "🔱", "🌿", ["👥", "🗡️"], "emilie-256x256.webp", "LumidouceElegy", "Пневма"),
  [CharacterKeys.Escoffier]: new _Character("Escoffier", "Эскофье", 5, "🔱", "❄️", ["👥", "🗡️", "🤝", "🛡️"], "escoffier-256x256.webp", "SymphonistOfScents", "Усия"),
  [CharacterKeys.Eula]: new _Character("Eula", "Эола", 5, "🗡️", "❄️", ["👤", "🗡️"], "eula-256x256.webp", "SongOfBrokenPines"),
  [CharacterKeys.Faruzan]: new _Character("Faruzan", "Фарузан", 4, "🏹", "🍃", ["👥", "🤝"], "faruzan-256x256.webp"),
  [CharacterKeys.Fischl]: new _Character("Fischl", "Фишль", 4, "🏹", "⚡️", ["👥", "🗡️"], "fischl-256x256.webp"),
  [CharacterKeys.Freminet]: new _Character("Freminet", "Фремине", 4, "🗡️", "❄️", ["👤", "🗡️"], "freminet-256x256.webp", undefined, "Пневма"),
  [CharacterKeys.Furina]: new _Character("Furina", "Фурина", 5, "⚔️", "💧", ["👥", "🗡️", "🤝", "🛡️"], "furina-256x256.webp", "SplendorOfTranquilWaters", ["Усия", "Пневма"]),
  [CharacterKeys.Gaming]: new _Character("Gaming", "Ка Мин", 4, "🗡️", "🔥", ["👤", "🗡️"], "gaming-256x256.webp"),
  [CharacterKeys.Ganyu]: new _Character("Ganyu", "Гань Юй", 5, "🏹", "❄️", ["👤", "🗡️"], "ganyu-256x256.webp", "AmosBow"),
  [CharacterKeys.Gorou]: new _Character("Gorou", "Горо", 4, "🏹", "🪨", ["👥", "🤝"], "gorou-256x256.webp"),
  [CharacterKeys.HuTao]: new _Character("HuTao", "Ху Тао", 5, "🔱", "🔥", ["👤", "🗡️"], "hu_tao-256x256.webp", "StaffOfHoma"),
  [CharacterKeys.Iansan]: new _Character("Iansan", "Иансан", 4, "🔱", "⚡️", ["👥", "🤝", "🛡️"], "iansan-256x256.webp"),
  [CharacterKeys.Ineffa]: new _Character("Ineffa", "Инеффа", 5, "🔱", "⚡️", ["👥", "🗡️", "🤝", "🛡️"], "ineffa-256x256.webp"),
  [CharacterKeys.Jean]: new _Character("Jean", "Джинн", 5, "⚔️", "🍃", ["👥", "🛡️"], "jean-256x256.webp"),
  [CharacterKeys.Kachina]: new _Character("Kachina", "Качина", 4, "🔱", "🪨", ["👥", "🗡️"], "kachina-256x256.webp"),
  [CharacterKeys.KaedeharaKazuha]: new _Character("KaedeharaKazuha", "Кадзуха", 5, "⚔️", "🍃", ["👥", "🤝"], "kaedehara_kazuha-256x256.webp", "FreedomSworn"),
  [CharacterKeys.Kaeya]: new _Character("Kaeya", "Кэйа", 3, "⚔️", "❄️", ["👥", "🗡️"], "kaeya-256x256.webp"),
  [CharacterKeys.KamisatoAyaka]: new _Character("KamisatoAyaka", "Аяка", 5, "⚔️", "❄️", ["👤", "🗡️"], "kamisato_ayaka-256x256.webp", "MistsplitterReforged"),
  [CharacterKeys.KamisatoAyato]: new _Character("KamisatoAyato", "Аято", 5, "⚔️", "💧", ["👤", "🗡️"], "kamisato_ayato-256x256.webp", "HaranGeppakuFutsu"),
  [CharacterKeys.Kaveh]: new _Character("Kaveh", "Кавех", 4, "🗡️", "🌿", ["👤", "🗡️"], "kaveh-256x256.webp"),
  [CharacterKeys.Keqing]: new _Character("Keqing", "Кэ Цин", 5, "⚔️", "⚡️", ["👤", "🗡️"], "keqing-256x256.webp"),
  [CharacterKeys.Kinich]: new _Character("Kinich", "Кинич", 5, "🗡️", "🌿", ["👤", "🗡️"], "kinich-256x256.webp", "FangOfTheMountainKing"),
  [CharacterKeys.Kirara]: new _Character("Kirara", "Кирара", 4, "⚔️", "🌿", ["👥", "🛡️"], "kirara-256x256.webp"),
  [CharacterKeys.Klee]: new _Character("Klee", "Кли", 5, "💥", "🔥", ["👤", "🗡️"], "klee-256x256.webp", "LostPrayerToTheSacredWinds"),
  [CharacterKeys.KujouSara]: new _Character("KujouSara", "Сара", 4, "🏹", "⚡️", ["👥", "🤝"], "kujou_sara-256x256.webp"),
  [CharacterKeys.KukiShinobu]: new _Character("KukiShinobu", "Синобу", 4, "⚔️", "⚡️", ["👥", "🛡️"], "kuki_shinobu-256x256.webp"),
  [CharacterKeys.Layla]: new _Character("Layla", "Лайла", 4, "⚔️", "❄️", ["👥", "🛡️"], "layla-256x256.webp"),
  [CharacterKeys.Lisa]: new _Character("Lisa", "Лиза", 4, "💥", "⚡️", ["👥", "🗡️"], "lisa-256x256.webp"),
  [CharacterKeys.Lynette]: new _Character("Lynette", "Линетт", 4, "⚔️", "🍃", ["👥", "🗡️"], "lynette-256x256.webp", undefined, "Усия"),
  [CharacterKeys.Lyney]: new _Character("Lyney", "Лини", 5, "🏹", "🔥", ["👤", "🗡️"], "lyney-256x256.webp", "TheFirstGreatMagic", "Пневма"),
  [CharacterKeys.Mavuika]: new _Character("Mavuika", "Мавуика", 5, "🗡️", "🔥", ["👤", "👥", "🗡️", "🤝"], "mavuika-256x256.webp", "AThousandBlazingSuns"),
  [CharacterKeys.Mika]: new _Character("Mika", "Мика", 4, "🔱", "❄️", ["👥", "🤝", "🛡️"], "mika-256x256.webp"),
  [CharacterKeys.Mona]: new _Character("Mona", "Мона", 5, "💥", "💧", ["👥", "🤝"], "mona-256x256.webp"),
  [CharacterKeys.Mualani]: new _Character("Mualani", "Муалани", 5, "💥", "💧", ["👤", "🗡️"], "mualani-256x256.webp", "SurfsUp"),
  [CharacterKeys.Nahida]: new _Character("Nahida", "Нахида", 5, "💥", "🌿", ["👥", "🗡️", "🤝"], "nahida-256x256.webp", "AThousandFloatingDreams"),
  [CharacterKeys.Navia]: new _Character("Navia", "Навия", 5, "🗡️", "🪨", ["👤", "🗡️"], "navia-256x256.webp", "Verdict"),
  [CharacterKeys.Neuvillette]: new _Character("Neuvillette", "Нёвиллет", 5, "💥", "💧", ["👤", "🗡️"], "neuvillette-256x256.webp", "TomeOfTheEternalFlow", "Пневма"),
  [CharacterKeys.Nilou]: new _Character("Nilou", "Нилу", 5, "⚔️", "💧", ["👥", "🗡️", "🤝"], "nilou-256x256.webp", "KeyOfKhajNisut"),
  [CharacterKeys.Ningguang]: new _Character("Ningguang", "Нин Гуан", 4, "💥", "🪨", ["👤", "🗡️"], "ningguang-256x256.webp"),
  [CharacterKeys.Noelle]: new _Character("Noelle", "Ноэлль", 4, "🗡️", "🪨", ["👤", "🗡️", "🛡️"], "noelle-256x256.webp"),
  [CharacterKeys.Ororon]: new _Character("Ororon", "Оророн", 4, "🏹", "⚡️", ["👥", "🗡️"], "ororon-256x256.webp"),

  [CharacterKeys.Qiqi]: {
    key: CharacterKeys.Qiqi,
    name: "Ци Ци",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["⚔️"],
    element_key: ElementKeys["❄️"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🛡️"]],
    image_src: imageSrc("qiqi-256x256.webp"),
  },
  [CharacterKeys.RaidenShogun]: {
    key: CharacterKeys.RaidenShogun,
    name: "Райдэн",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["⚡️"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"], CharacterRoleKeys["🤝"]],
    signature_weapon_key: WeaponKeys.EngulfingLightning,
    image_src: imageSrc("raiden_shogun-256x256.webp"),
  },
  [CharacterKeys.Razor]: {
    key: CharacterKeys.Razor,
    name: "Рэйзор",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🗡️"],
    element_key: ElementKeys["⚡️"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    image_src: imageSrc("razor-256x256.webp"),
  },
  [CharacterKeys.Rosaria]: {
    key: CharacterKeys.Rosaria,
    name: "Розария",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["❄️"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🗡️"]],
    image_src: imageSrc("rosaria-256x256.webp"),
  },
  [CharacterKeys.SangonomiyaKokomi]: {
    key: CharacterKeys.SangonomiyaKokomi,
    name: "Кокоми",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["💧"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"], CharacterRoleKeys["🛡️"]],
    signature_weapon_key: WeaponKeys.EverlastingMoonglow,
    image_src: imageSrc("sangonomiya_kokomi-256x256.webp"),
  },
  [CharacterKeys.Sayu]: {
    key: CharacterKeys.Sayu,
    name: "Саю",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🗡️"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🛡️"]],
    image_src: imageSrc("sayu-256x256.webp"),
  },
  [CharacterKeys.Sethos]: {
    key: CharacterKeys.Sethos,
    name: "Сетос",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["⚡️"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    image_src: imageSrc("sethos-256x256.webp"),
  },
  [CharacterKeys.Shenhe]: {
    key: CharacterKeys.Shenhe,
    name: "Шэнь Хэ",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["❄️"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"]],
    signature_weapon_key: WeaponKeys.CalamityQueller,
    image_src: imageSrc("shenhe-256x256.webp"),
  },
  [CharacterKeys.ShikanoinHeizou]: {
    key: CharacterKeys.ShikanoinHeizou,
    name: "Хэйдзо",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    image_src: imageSrc("shikanoin_heizou-256x256.webp"),
  },
  [CharacterKeys.Sigewinne]: {
    key: CharacterKeys.Sigewinne,
    name: "Сиджвин",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["💧"],
    arkhe: "Усия",
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"], CharacterRoleKeys["🛡️"]],
    signature_weapon_key: WeaponKeys.SilvershowerHeartstrings,
    image_src: imageSrc("sigewinne-256x256.webp"),
  },
  [CharacterKeys.Skirk]: {
    key: CharacterKeys.Skirk,
    name: "Скирк",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["⚔️"],
    element_key: ElementKeys["❄️"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_artifact_set_key: ArtifactSetKeys.FinaleOfTheDeepGalleries,
    signature_weapon_key: WeaponKeys.Azurelight,
    image_src: imageSrc("skirk-256x256.webp"),
  },
  [CharacterKeys.Sucrose]: {
    key: CharacterKeys.Sucrose,
    name: "Сахароза",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"]],
    image_src: imageSrc("sucrose-256x256.webp"),
  },
  [CharacterKeys.Tartaglia]: {
    key: CharacterKeys.Tartaglia,
    name: "Тарталья",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["💧"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.PolarStar,
    image_src: imageSrc("tartaglia-256x256.webp"),
  },
  [CharacterKeys.Thoma]: {
    key: CharacterKeys.Thoma,
    name: "Тома",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["🔥"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🛡️"]],
    image_src: imageSrc("thoma-256x256.webp"),
  },
  [CharacterKeys.Tighnari]: {
    key: CharacterKeys.Tighnari,
    name: "Тигнари",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["🌿"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.HuntersPath,
    image_src: imageSrc("tighnari-256x256.webp"),
  },
  [CharacterKeys.TravelerAnemo]: {
    ...traveler,
    key: CharacterKeys.TravelerAnemo,
    name: `${traveler.name} (Анемо)`,
    element_key: ElementKeys["🍃"],
  },
  [CharacterKeys.TravelerDendro]: {
    ...traveler,
    key: CharacterKeys.TravelerDendro,
    name: `${traveler.name} (Дендро)`,
    element_key: ElementKeys["🌿"],
  },
  [CharacterKeys.TravelerElectro]: {
    ...traveler,
    key: CharacterKeys.TravelerElectro,
    name: `${traveler.name} (Электро)`,
    element_key: ElementKeys["⚡️"],
  },
  [CharacterKeys.TravelerGeo]: {
    ...traveler,
    key: CharacterKeys.TravelerGeo,
    name: `${traveler.name} (Гео)`,
    element_key: ElementKeys["🪨"],
  },
  [CharacterKeys.TravelerHydro]: {
    ...traveler,
    key: CharacterKeys.TravelerHydro,
    name: `${traveler.name} (Гидро)`,
    element_key: ElementKeys["💧"],
    arkhe: "Пневма",
  },
  [CharacterKeys.TravelerPyro]: {
    ...traveler,
    key: CharacterKeys.TravelerPyro,
    name: `${traveler.name} (Пиро)`,
    element_key: ElementKeys["🔥"],
  },
  [CharacterKeys.Varesa]: {
    key: CharacterKeys.Varesa,
    name: "Вареса",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["⚡️"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.VividNotions,
    image_src: imageSrc("varesa-256x256.webp"),
  },
  [CharacterKeys.Venti]: {
    key: CharacterKeys.Venti,
    name: "Венти",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🗡️"], CharacterRoleKeys["🤝"]],
    signature_weapon_key: WeaponKeys.ElegyForTheEnd,
    image_src: imageSrc("venti-256x256.webp"),
  },
  [CharacterKeys.Wanderer]: {
    key: CharacterKeys.Wanderer,
    name: "Странник",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.TulaytullahsRemembrance,
    image_src: imageSrc("wanderer-256x256.webp"),
  },
  [CharacterKeys.Wriothesley]: {
    key: CharacterKeys.Wriothesley,
    name: "Ризли",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["❄️"],
    arkhe: "Усия",
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.CashflowSupervision,
    image_src: imageSrc("wriothesley-256x256.webp"),
  },
  [CharacterKeys.Xiangling]: {
    key: CharacterKeys.Xiangling,
    name: "Сян Лин",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["🔥"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🗡️"]],
    image_src: imageSrc("xiangling-256x256.webp"),
  },
  [CharacterKeys.Xianyun]: {
    key: CharacterKeys.Xianyun,
    name: "Сянь Юнь",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"], CharacterRoleKeys["🛡️"]],
    signature_weapon_key: WeaponKeys.CranesEchoingCall,
    image_src: imageSrc("xianyun-256x256.webp"),
  },
  [CharacterKeys.Xiao]: {
    key: CharacterKeys.Xiao,
    name: "Сяо",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["🍃"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.PrimordialJadeWingedSpear,
    image_src: imageSrc("xiao-256x256.webp"),
  },
  [CharacterKeys.Xilonen]: {
    key: CharacterKeys.Xilonen,
    name: "Шилонен",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["⚔️"],
    element_key: ElementKeys["🪨"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"], CharacterRoleKeys["🛡️"]],
    signature_weapon_key: WeaponKeys.PeakPatrolSong,
    image_src: imageSrc("xilonen-256x256.webp"),
  },
  [CharacterKeys.Xingqiu]: {
    key: CharacterKeys.Xingqiu,
    name: "Син Цю",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["⚔️"],
    element_key: ElementKeys["💧"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🗡️"], CharacterRoleKeys["🛡️"]],
    image_src: imageSrc("xingqiu-256x256.webp"),
  },
  [CharacterKeys.Xinyan]: {
    key: CharacterKeys.Xinyan,
    name: "Синь Янь",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🗡️"],
    element_key: ElementKeys["🔥"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🛡️"]],
    image_src: imageSrc("xinyan-256x256.webp"),
  },
  [CharacterKeys.YaeMiko]: {
    key: CharacterKeys.YaeMiko,
    name: "Яэ Мико",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["⚡️"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.KagurasVerity,
    image_src: imageSrc("yae_miko-256x256.webp"),
  },
  [CharacterKeys.Yanfei]: {
    key: CharacterKeys.Yanfei,
    name: "Янь Фэй",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["💥"],
    element_key: ElementKeys["🔥"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    image_src: imageSrc("yanfei-256x256.webp"),
  },
  [CharacterKeys.Yaoyao]: {
    key: CharacterKeys.Yaoyao,
    name: "Яо Яо",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["🌿"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🛡️"]],
    image_src: imageSrc("yaoyao-256x256.webp"),
  },
  [CharacterKeys.Yelan]: {
    key: CharacterKeys.Yelan,
    name: "Е Лань",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["💧"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.AquaSimulacra,
    image_src: imageSrc("yelan-256x256.webp"),
  },
  [CharacterKeys.Yoimiya]: {
    key: CharacterKeys.Yoimiya,
    name: "Ёимия",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🏹"],
    element_key: ElementKeys["🔥"],
    role_keys: [CharacterRoleKeys["👤"], CharacterRoleKeys["🗡️"]],
    signature_weapon_key: WeaponKeys.ThunderingPulse,
    image_src: imageSrc("yoimiya-256x256.webp"),
  },
  [CharacterKeys.YunJin]: {
    key: CharacterKeys.YunJin,
    name: "Юнь Цзинь",
    rarity: 4,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["🪨"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"]],
    image_src: imageSrc("yun_jin-256x256.webp"),
  },
  [CharacterKeys.Zhongli]: {
    key: CharacterKeys.Zhongli,
    name: "Чжун Ли",
    rarity: 5,
    weapon_type_key: WeaponTypeKeys["🔱"],
    element_key: ElementKeys["🪨"],
    role_keys: [CharacterRoleKeys["👥"], CharacterRoleKeys["🤝"], CharacterRoleKeys["🛡️"]],
    signature_weapon_key: WeaponKeys.VortexVanquisher,
    image_src: imageSrc("zhongli-256x256.webp"),
  },
} as Record<CharacterKey, Character>;
