import { StatKeys } from "./enums/stat";
import type { Stat, StatKey } from "./types/stat";

export default {
  [StatKeys.AnemoDMGBonus]: { key: StatKeys.AnemoDMGBonus, name: "Бонус Анемо урона" },
  [StatKeys.AnemoResistance]: { key: StatKeys.AnemoResistance, name: "Анемо сопротивление" },
  [StatKeys.ATK]: { key: StatKeys.ATK, name: "Сила атаки" },
  [StatKeys.ATKPercentage]: {
    key: StatKeys.ATKPercentage,
    name: "Процент от силы атаки",
    abbreviation: "Сила атаки %",
  },
  [StatKeys.CooldownReduction]: { key: StatKeys.CooldownReduction, name: "Снижение времени отката" },
  [StatKeys.CRITDMG]: { key: StatKeys.CRITDMG, name: "Крит. урон" },
  [StatKeys.CRITRate]: { key: StatKeys.CRITRate, name: "Шанс крит. попадания" },
  [StatKeys.CryoDMGBonus]: { key: StatKeys.CryoDMGBonus, name: "Бонус Крио урона" },
  [StatKeys.CryoResistance]: { key: StatKeys.CryoResistance, name: "Крио сопротивление" },
  [StatKeys.Defense]: { key: StatKeys.Defense, name: "Защита" },
  [StatKeys.DefensePercent]: { key: StatKeys.DefensePercent, name: "Процент от защиты", abbreviation: "Защита %" },
  [StatKeys.DendroDMGBonus]: { key: StatKeys.DendroDMGBonus, name: "Бонус Дендро урона" },
  [StatKeys.DendroResistance]: { key: StatKeys.DendroResistance, name: "Дендро сопротивление" },
  [StatKeys.ElectroDMGBonus]: { key: StatKeys.ElectroDMGBonus, name: "Бонус Электро урона" },
  [StatKeys.ElectroResistance]: { key: StatKeys.ElectroResistance, name: "Электро сопротивление" },
  [StatKeys.ElementalMastery]: { key: StatKeys.ElementalMastery, name: "Мастерство стихий" },
  [StatKeys.EnergyRecharge]: { key: StatKeys.EnergyRecharge, name: "Восст. энергии" },
  [StatKeys.GeoDMGBonus]: { key: StatKeys.GeoDMGBonus, name: "Бонус Гео урона" },
  [StatKeys.GeoResistance]: { key: StatKeys.GeoResistance, name: "Гео сопротивление" },
  [StatKeys.HealingBonus]: { key: StatKeys.HealingBonus, name: "Бонус лечения" },
  [StatKeys.HP]: { key: StatKeys.HP, name: "HP" },
  [StatKeys.HPPercentage]: { key: StatKeys.HPPercentage, name: "Процент от HP", abbreviation: "HP %" },
  [StatKeys.HydroDMGBonus]: { key: StatKeys.HydroDMGBonus, name: "Бонус Гидро урона" },
  [StatKeys.HydroResistance]: { key: StatKeys.HydroResistance, name: "Гидро сопротивление" },
  [StatKeys.IncomingHealingBonus]: { key: StatKeys.IncomingHealingBonus, name: "Бонус получаемого лечения" },
  [StatKeys.PhysicalDMGBonus]: { key: StatKeys.PhysicalDMGBonus, name: "Бонус физ. урона" },
  [StatKeys.PhysicalResistance]: { key: StatKeys.PhysicalResistance, name: "Физ. сопротивление" },
  [StatKeys.PyroDMGBonus]: { key: StatKeys.PyroDMGBonus, name: "Бонус Пиро урона" },
  [StatKeys.PyroResistance]: { key: StatKeys.PyroResistance, name: "Пиро сопротивление" },
  [StatKeys.ShieldStrength]: { key: StatKeys.ShieldStrength, name: "Прочность щита" },
  [StatKeys.Stamina]: { key: StatKeys.Stamina, name: "Выносливость" },
} as Record<StatKey, Stat>;
