import { StAtkeys } from "./enums/stat";
import { numberFormatPercent, publicImageSrc } from "@/lib/utils";
import { WeaponKeys } from "./enums/weapon";
import { WeaponTypeKeys } from "./enums/weapon-type";
import type { Weapon, WeaponKey } from "./types/weapon";

const WeaponSource = {
  BattlePass: "Выбираемая награда при достижении 30 уровня боевого пропуска (Жемчужный гимн)",
  Chests: "Сундуки",
  EventWishExclusive: "Эксклюзивное оружие Молитвы события",
  Forged: "Кузница",
  PaimonsBargains: "Обмен Звёздного блеска в магазине Паймон",
  Wish: "Молитвы",
} as const;

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`weapons/${src}`);

export default {
  [WeaponKeys.AThousandBlazingSuns]: {
    key: WeaponKeys.AThousandBlazingSuns,
    name: "Тысяча ослепительных солнц",
    image_src: imageSrc("a_thousand_blazing_suns-256x256.webp"),
    source: "Эксклюзивное оружие Молитвы события",
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: 49, max_value: 741 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.024, 1),
      max_value: numberFormatPercent(0.110, 1),
    },
  },
  [WeaponKeys.AThousandFloatingDreams]: {
    key: WeaponKeys.AThousandFloatingDreams,
    name: "Сновидения тысячи ночей",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("a_thousand_floating_dreams-256x256.webp"),
  },
  [WeaponKeys.Absolution]: {
    key: WeaponKeys.Absolution,
    name: "Отпущение грехов",
    image_src: imageSrc("absolution-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponKeys.Akuoumaru]: {
    key: WeaponKeys.Akuoumaru,
    name: "Акуомару",
    image_src: imageSrc("akuoumaru-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.AlleyHunter]: {
    key: WeaponKeys.AlleyHunter,
    name: "Охотник во тьме",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("alley_hunter-256x256.webp"),
  },
  [WeaponKeys.AmenomaKageuchi]: {
    key: WeaponKeys.AmenomaKageuchi,
    name: "Амэнома Кагэути",
    image_src: imageSrc("amenoma_kageuchi-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.AmosBow]: {
    key: WeaponKeys.AmosBow,
    name: "Лук Амоса",
    rarity: 5,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("amos_bow-256x256.webp"),
  },
  [WeaponKeys.AquaSimulacra]: {
    key: WeaponKeys.AquaSimulacra,
    name: "Аква симулякрум",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("aqua_simulacra-256x256.webp"),
  },
  [WeaponKeys.AquilaFavonia]: {
    key: WeaponKeys.AquilaFavonia,
    name: "Меч Сокола",
    image_src: imageSrc("aquila_favonia-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "6774" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.AshGravenDrinkingHorn]: {
    key: WeaponKeys.AshGravenDrinkingHorn,
    name: "Пепельный рог",
    rarity: 4,
    source: "Событие версии 5.0 «Следы мастерства»",
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("ash_graven_drinking_horn-256x256.webp"),
  },
  [WeaponKeys.AstralVulturesCrimsonPlumage]: {
    key: WeaponKeys.AstralVulturesCrimsonPlumage,
    name: "Алое перо звёздного грифа",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("astral_vultures_crimson_plumage-256x256.webp"),
  },
  [WeaponKeys.Azurelight]: {
    key: WeaponKeys.Azurelight,
    name: "Лазурное сияние",
    image_src: imageSrc("azurelight-256x256.webp"),
    source: "Эксклюзивное оружие Молитвы события",
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
  },
  [WeaponKeys.BalladOfTheBoundlessBlue]: {
    key: WeaponKeys.BalladOfTheBoundlessBlue,
    name: "Песнь необъятной лазури",
    rarity: 4,
    source: "Событие версии 4.1 «Поэзия вод»",
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("ballad_of_the_boundless_blue-256x256.webp"),
  },
  [WeaponKeys.BalladOfTheFjords]: {
    key: WeaponKeys.BalladOfTheFjords,
    name: "Баллада фьордов",
    image_src: imageSrc("ballad_of_the_fjords-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.BeaconOfTheReedSea]: {
    key: WeaponKeys.BeaconOfTheReedSea,
    name: "Маяк тростникового моря",
    image_src: imageSrc("beacon_of_the_reed_sea-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponKeys.BlackTassel]: {
    key: WeaponKeys.BlackTassel,
    name: "Чёрная кисть",
    image_src: imageSrc("black_tassel-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 3,
    base_Atk: { min_value: "38", max_value: "354" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "10.2%", max_value: "46.9%" },
  },
  [WeaponKeys.BlackcliffAgate]: {
    key: WeaponKeys.BlackcliffAgate,
    name: "Черногорский агат",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("blackcliff_agate-256x256.webp"),
  },
  [WeaponKeys.BlackcliffLongsword]: {
    key: WeaponKeys.BlackcliffLongsword,
    name: "Черногорский длинный меч",
    image_src: imageSrc("blackcliff_longsword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponKeys.BlackcliffPole]: {
    key: WeaponKeys.BlackcliffPole,
    name: "Черногорская пика",
    image_src: imageSrc("blackcliff_pole-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.BlackcliffSlasher]: {
    key: WeaponKeys.BlackcliffSlasher,
    name: "Черногорская бритва",
    image_src: imageSrc("blackcliff_slasher-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.BlackcliffWarbow]: {
    key: WeaponKeys.BlackcliffWarbow,
    name: "Черногорский боевой лук",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.080, 1),
      max_value: numberFormatPercent(0.368, 1),
    },
    image_src: imageSrc("blackcliff_warbow-256x256.webp"),
  },
  [WeaponKeys.BloodtaintedGreatsword]: {
    key: WeaponKeys.BloodtaintedGreatsword,
    name: "Меч драконьей крови",
    image_src: imageSrc("bloodtainted_greatsword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 3,
    base_Atk: { min_value: "38", max_value: "354" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "41", max_value: "187" },
  },
  [WeaponKeys.CalamityOfEshu]: {
    key: WeaponKeys.CalamityOfEshu,
    name: "Бедствие Эшу",
    image_src: imageSrc("calamity_of_eshu-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.CalamityQueller]: {
    key: WeaponKeys.CalamityQueller,
    name: "Усмиритель бед",
    image_src: imageSrc("calamity_queller-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "49", max_value: "741" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "3.6%", max_value: "16.5%" },
  },
  [WeaponKeys.CashflowSupervision]: {
    key: WeaponKeys.CashflowSupervision,
    name: "Казначейский надзор",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("cashflow_supervision-256x256.webp"),
  },
  [WeaponKeys.ChainBreaker]: {
    key: WeaponKeys.ChainBreaker,
    name: "Разбивающий цепи",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("chain_breaker-256x256.webp"),
  },
  [WeaponKeys.CinnabarSpindle]: {
    key: WeaponKeys.CinnabarSpindle,
    name: "Киноварное веретено",
    image_src: imageSrc("cinnabar_spindle-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.Def, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponKeys.Cloudforged]: {
    key: WeaponKeys.Cloudforged,
    name: "Выкованный из облаков",
    rarity: 4,
    source: "Событие версии 4.7 «Моделирование взаимного повышения безопасности»",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("cloudforged-256x256.webp"),
  },
  [WeaponKeys.CompoundBow]: {
    key: WeaponKeys.CompoundBow,
    name: "Составной лук",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.PhysicalDmgBonus,
      min_value: numberFormatPercent(0.150, 1),
      max_value: numberFormatPercent(0.690, 1),
    },
    image_src: imageSrc("compound_bow-256x256.webp"),
  },
  [WeaponKeys.CoolSteel]: {
    key: WeaponKeys.CoolSteel,
    name: "Холодное лезвие",
    image_src: imageSrc("cool_steel-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponKeys.CranesEchoingCall]: {
    key: WeaponKeys.CranesEchoingCall,
    name: "Звонкий клич журавля",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 49, max_value: 741 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.036, 1),
      max_value: numberFormatPercent(0.165, 1),
    },
    image_src: imageSrc("cranes_echoing_call-256x256.webp"),
  },
  [WeaponKeys.CrescentPike]: {
    key: WeaponKeys.CrescentPike,
    name: "Пика полумесяца",
    image_src: imageSrc("crescent_pike-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponKeys.CrimsonMoonsSemblance]: {
    key: WeaponKeys.CrimsonMoonsSemblance,
    name: "Очертания алой луны",
    image_src: imageSrc("crimson_moons_semblance-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponKeys.DarkIronSword]: {
    key: WeaponKeys.DarkIronSword,
    name: "Тёмный железный меч",
    image_src: imageSrc("dark_iron_sword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "31", max_value: "141" },
  },
  [WeaponKeys.Deathmatch]: {
    key: WeaponKeys.Deathmatch,
    name: "Смертельный бой",
    image_src: imageSrc("deathmatch-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponKeys.DebateClub]: {
    key: WeaponKeys.DebateClub,
    name: "Дубина переговоров",
    image_src: imageSrc("debate_club-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponKeys.DialoguesOfTheDesertSages]: {
    key: WeaponKeys.DialoguesOfTheDesertSages,
    name: "Диалог пустынных мудрецов",
    image_src: imageSrc("dialogues_of_the_desert_sages-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.DodocoTales]: {
    key: WeaponKeys.DodocoTales,
    name: "Истории Додоко",
    rarity: 4,
    source: "Событие версии 1.6 «Лето! Остров? Приключение!»",
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("dodoco_tales-256x256.webp"),
  },
  [WeaponKeys.DragonsBane]: {
    key: WeaponKeys.DragonsBane,
    name: "Гроза драконов",
    image_src: imageSrc("dragons_bane-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "48", max_value: "221" },
  },
  [WeaponKeys.DragonspineSpear]: {
    key: WeaponKeys.DragonspineSpear,
    name: "Копьё Драконьего хребта",
    image_src: imageSrc("dragonspine_spear-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponKeys.EarthShaker]: {
    key: WeaponKeys.EarthShaker,
    name: "Сотрясающий землю",
    image_src: imageSrc("earth_shaker-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.ElegyForTheEnd]: {
    key: WeaponKeys.ElegyForTheEnd,
    name: "Элегия погибели",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("elegy_for_the_end-256x256.webp"),
  },
  [WeaponKeys.EmeraldOrb]: {
    key: WeaponKeys.EmeraldOrb,
    name: "Изумрудный шар",
    rarity: 3,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 40, max_value: 448 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 20, max_value: 94 },
    image_src: imageSrc("emerald_orb-256x256.webp"),
  },
  [WeaponKeys.EndOfTheLine]: {
    key: WeaponKeys.EndOfTheLine,
    name: "Иссушитель",
    rarity: 4,
    source: "Ассоциация рыболовов Сумеру",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("end_of_the_line-256x256.webp"),
  },
  [WeaponKeys.EngulfingLightning]: {
    key: WeaponKeys.EngulfingLightning,
    name: "Сияющая жатва",
    image_src: imageSrc("engulfing_lightning-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.EverlastingMoonglow]: {
    key: WeaponKeys.EverlastingMoonglow,
    name: "Вечное лунное сияние",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("everlasting_moonglow-256x256.webp"),
  },
  [WeaponKeys.EyeOfPerception]: {
    key: WeaponKeys.EyeOfPerception,
    name: "Око сознания",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("eye_of_perception-256x256.webp"),
  },
  [WeaponKeys.FadingTwilight]: {
    key: WeaponKeys.FadingTwilight,
    name: "Гаснущие сумерки",
    rarity: 4,
    source: "Событие версии 2.7 «Опасная тропа»",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("fading_twilight-256x256.webp"),
  },
  [WeaponKeys.FangOfTheMountainKing]: {
    key: WeaponKeys.FangOfTheMountainKing,
    name: "Клык Горного короля",
    image_src: imageSrc("fang_of_the_mountain_king-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "49", max_value: "741" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "2.4%", max_value: "11.0%" },
  },
  [WeaponKeys.FavoniusCodex]: {
    key: WeaponKeys.FavoniusCodex,
    name: "Кодекс Фавония",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("favonius_codex-256x256.webp"),
  },
  [WeaponKeys.FavoniusGreatsword]: {
    key: WeaponKeys.FavoniusGreatsword,
    name: "Двуручный меч Фавония",
    image_src: imageSrc("favonius_greatsword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponKeys.FavoniusLance]: {
    key: WeaponKeys.FavoniusLance,
    name: "Копьё Фавония",
    image_src: imageSrc("favonius_lance-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponKeys.FavoniusSword]: {
    key: WeaponKeys.FavoniusSword,
    name: "Меч Фавония",
    image_src: imageSrc("favonius_sword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponKeys.FavoniusWarbow]: {
    key: WeaponKeys.FavoniusWarbow,
    name: "Боевой лук Фавония",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.133, 1),
      max_value: numberFormatPercent(0.613, 1),
    },
    image_src: imageSrc("favonius_warbow-256x256.webp"),
  },
  [WeaponKeys.FerrousShadow]: {
    key: WeaponKeys.FerrousShadow,
    name: "Металлическая тень",
    image_src: imageSrc("ferrous_shadow-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponKeys.FesteringDesire]: {
    key: WeaponKeys.FesteringDesire,
    name: "Осквернённое желание",
    image_src: imageSrc("festering_desire-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponKeys.FilletBlade]: {
    key: WeaponKeys.FilletBlade,
    name: "Филейный нож",
    image_src: imageSrc("fillet_blade-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponKeys.FinaleOfTheDeep]: {
    key: WeaponKeys.FinaleOfTheDeep,
    name: "Грандиозный финал глубин",
    image_src: imageSrc("finale_of_the_deep-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.FleuveCendreFerryman]: {
    key: WeaponKeys.FleuveCendreFerryman,
    name: "Перевозчик Флёв Сандр",
    image_src: imageSrc("fleuve_cendre_ferryman-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponKeys.FlowerWreathedFeathers]: {
    key: WeaponKeys.FlowerWreathedFeathers,
    name: "Украшенные цветами перья",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("flower_wreathed_feathers-256x256.webp"),
  },
  [WeaponKeys.FlowingPurity]: {
    key: WeaponKeys.FlowingPurity,
    name: "Сверкание чистых вод",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("flowing_purity-256x256.webp"),
  },
  [WeaponKeys.FluteOfEzpitzal]: {
    key: WeaponKeys.FluteOfEzpitzal,
    name: "Флейта Эспицаль",
    image_src: imageSrc("flute_of_ezpitzal-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.Def, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponKeys.FootprintOfTheRainbow]: {
    key: WeaponKeys.FootprintOfTheRainbow,
    name: "След радуги",
    image_src: imageSrc("footprint_of_the_rainbow-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Def, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponKeys.ForestRegalia]: {
    key: WeaponKeys.ForestRegalia,
    name: "Регалия леса",
    image_src: imageSrc("forest_regalia-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponKeys.FreedomSworn]: {
    key: WeaponKeys.FreedomSworn,
    name: "Клятва свободы",
    image_src: imageSrc("freedom_sworn-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "43", max_value: "198" },
  },
  [WeaponKeys.Frostbearer]: {
    key: WeaponKeys.Frostbearer,
    name: "Плод вечной мерзлоты",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("frostbearer-256x256.webp"),
  },
  [WeaponKeys.FruitOfFulfillment]: {
    key: WeaponKeys.FruitOfFulfillment,
    name: "Плод восполнения",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("fruit_of_fulfillment-256x256.webp"),
  },
  [WeaponKeys.FruitfulHook]: {
    key: WeaponKeys.FruitfulHook,
    name: "Плодотворный крюк",
    image_src: imageSrc("fruitful_hook-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.HakushinRing]: {
    key: WeaponKeys.HakushinRing,
    name: "Кольцо Хакусин",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("hakushin_ring-256x256.webp"),
  },
  [WeaponKeys.Halberd]: {
    key: WeaponKeys.Halberd,
    name: "Алебарда Миллелита",
    image_src: imageSrc("halberd-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 3,
    base_Atk: { min_value: "40", max_value: "448" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponKeys.Hamayumi]: {
    key: WeaponKeys.Hamayumi,
    name: "Хамаюми",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("hamayumi-256x256.webp"),
  },
  [WeaponKeys.HaranGeppakuFutsu]: {
    key: WeaponKeys.HaranGeppakuFutsu,
    name: "Харан гэппаку фуцу",
    image_src: imageSrc("haran_geppaku_futsu-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponKeys.HarbingerOfDawn]: {
    key: WeaponKeys.HarbingerOfDawn,
    name: "Предвестник зари",
    image_src: imageSrc("harbinger_of_dawn-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "10.2%", max_value: "46.9%" },
  },
  [WeaponKeys.HuntersPath]: {
    key: WeaponKeys.HuntersPath,
    name: "Охотничья тропа",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("hunters_path-256x256.webp"),
  },
  [WeaponKeys.IbisPiercer]: {
    key: WeaponKeys.IbisPiercer,
    name: "Клюв ибиса",
    rarity: 4,
    source: "Событие версии 3.7 «Дуэль! К вершинам карточного мастерства!»",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("ibis_piercer-256x256.webp"),
  },
  [WeaponKeys.IronSting]: {
    key: WeaponKeys.IronSting,
    name: "Стальное жало",
    image_src: imageSrc("iron_sting-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponKeys.JadefallsSplendor]: {
    key: WeaponKeys.JadefallsSplendor,
    name: "Великолепие лазурного свода",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("jadefalls_splendor-256x256.webp"),
  },
  [WeaponKeys.KagotsurubeIsshin]: {
    key: WeaponKeys.KagotsurubeIsshin,
    name: "Кагоцурубэ Иссин",
    image_src: imageSrc("kagotsurube_isshin-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.KagurasVerity]: {
    key: WeaponKeys.KagurasVerity,
    name: "Истина кагура",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("kaguras_verity-256x256.webp"),
  },
  [WeaponKeys.KatsuragikiriNagamasa]: {
    key: WeaponKeys.KatsuragikiriNagamasa,
    name: "Кацурагикири Нагамаса",
    image_src: imageSrc("katsuragikiri_nagamasa-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponKeys.KeyOfKhajNisut]: {
    key: WeaponKeys.KeyOfKhajNisut,
    name: "Ключ Хадж-нисут",
    image_src: imageSrc("key_of_khaj_nisut-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponKeys.KingsSquire]: {
    key: WeaponKeys.KingsSquire,
    name: "Приближённый короля",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("kings_squire-256x256.webp"),
  },
  [WeaponKeys.KitainCrossSpear]: {
    key: WeaponKeys.KitainCrossSpear,
    name: "Крест-копьё Китаин",
    image_src: imageSrc("kitain_cross_spear-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponKeys.LightOfFoliarIncision]: {
    key: WeaponKeys.LightOfFoliarIncision,
    name: "Свет лиственного разреза",
    image_src: imageSrc("light_of_foliar_incision-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponKeys.LionsRoar]: {
    key: WeaponKeys.LionsRoar,
    name: "Драконий рык",
    image_src: imageSrc("lions_roar-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.LithicBlade]: {
    key: WeaponKeys.LithicBlade,
    name: "Каменный меч",
    image_src: imageSrc("lithic_blade-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.LithicSpear]: {
    key: WeaponKeys.LithicSpear,
    name: "Каменное копьё",
    image_src: imageSrc("lithic_spear-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.LostPrayerToTheSacredWinds]: {
    key: WeaponKeys.LostPrayerToTheSacredWinds,
    name: "Молитва святым ветрам",
    rarity: 5,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("lost_prayer_to_the_sacred_winds-256x256.webp"),
  },
  [WeaponKeys.LumidouceElegy]: {
    key: WeaponKeys.LumidouceElegy,
    name: "Элегия Люмидус",
    image_src: imageSrc("lumidouce_elegy-512x512.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponKeys.LuxuriousSeaLord]: {
    key: WeaponKeys.LuxuriousSeaLord,
    name: "Благодатный владыка вод",
    image_src: imageSrc("luxurious_sea_lord-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.MagicGkeye]: {
    key: WeaponKeys.MagicGkeye,
    name: "Руководство по магии",
    rarity: 3,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 38, max_value: 354 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 41, max_value: 187 },
    image_src: imageSrc("magic_gkeye-256x256.webp"),
  },
  [WeaponKeys.MailedFlower]: {
    key: WeaponKeys.MailedFlower,
    name: "Цветок в латах",
    image_src: imageSrc("mailed_flower-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponKeys.MakhairaAquamarine]: {
    key: WeaponKeys.MakhairaAquamarine,
    name: "Аквамарин Махайры",
    image_src: imageSrc("makhaira_aquamarine-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponKeys.MappaMare]: {
    key: WeaponKeys.MappaMare,
    name: "Морской атлас",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 24, max_value: 110 },
    image_src: imageSrc("mappa_mare-256x256.webp"),
  },
  [WeaponKeys.MemoryOfDust]: {
    key: WeaponKeys.MemoryOfDust,
    name: "Память о пыли",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("memory_of_dust-256x256.webp"),
  },
  [WeaponKeys.Messenger]: {
    key: WeaponKeys.Messenger,
    name: "Посыльный",
    rarity: 3,
    source: WeaponSource.Chests,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 40, max_value: 448 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("messenger-256x256.webp"),
  },
  [WeaponKeys.MissiveWindspear]: {
    key: WeaponKeys.MissiveWindspear,
    name: "Копьё послания ветров",
    image_src: imageSrc("missive_windspear-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.MistsplitterReforged]: {
    key: WeaponKeys.MistsplitterReforged,
    name: "Рассекающий туман",
    image_src: imageSrc("mistsplitter_reforged-512x512.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponKeys.MitternachtsWaltz]: {
    key: WeaponKeys.MitternachtsWaltz,
    name: "Вальс Нирваны Ночи",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.PhysicalDmgBonus,
      min_value: numberFormatPercent(0.113, 1),
      max_value: numberFormatPercent(0.517, 1),
    },
    image_src: imageSrc("mitternachts_waltz-256x256.webp"),
  },
  [WeaponKeys.Moonpiercer]: {
    key: WeaponKeys.Moonpiercer,
    name: "Пронзающий луну",
    image_src: imageSrc("moonpiercer-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponKeys.MountainBracingBolt]: {
    key: WeaponKeys.MountainBracingBolt,
    name: "Крепящий горы шип",
    image_src: imageSrc("mountain_bracing_bolt-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponKeys.MouunsMoon]: {
    key: WeaponKeys.MouunsMoon,
    name: "Луна Моун",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("mouuns_moon-256x256.webp"),
  },
  [WeaponKeys.OathswornEye]: {
    key: WeaponKeys.OathswornEye,
    name: "Око клятвы",
    rarity: 4,
    source: "Событие версии 2.5 «Подношение врат трёх миров»",
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("oathsworn_eye-256x256.webp"),
  },
  [WeaponKeys.OtherworldlyStory]: {
    key: WeaponKeys.OtherworldlyStory,
    name: "Потусторонняя история",
    rarity: 3,
    source: WeaponSource.Chests,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.085, 1),
      max_value: numberFormatPercent(0.390, 1),
    },
    image_src: imageSrc("otherworldly_story-256x256.webp"),
  },
  [WeaponKeys.PeakPatrolSong]: {
    key: WeaponKeys.PeakPatrolSong,
    name: "Песнь патруля пиков",
    image_src: imageSrc("peak_patrol_song-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.Def, min_value: "18%", max_value: "82.7%" },
  },
  [WeaponKeys.PolarStar]: {
    key: WeaponKeys.PolarStar,
    name: "Полярная звезда",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("polar_star-256x256.webp"),
  },
  [WeaponKeys.PortablePowerSaw]: {
    key: WeaponKeys.PortablePowerSaw,
    name: "Переносная мотопила",
    image_src: imageSrc("portable_power_saw-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.Predator]: {
    key: WeaponKeys.Predator,
    name: "Хищник",
    rarity: 4,
    source: "Внутриигровая почта \"PlayStation Network\"",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("predator-512x512.webp"),
  },
  [WeaponKeys.PrimordialJadeCutter]: {
    key: WeaponKeys.PrimordialJadeCutter,
    name: "Драгоценный омут",
    image_src: imageSrc("primordial_jade_cutter-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponKeys.PrimordialJadeWingedSpear]: {
    key: WeaponKeys.PrimordialJadeWingedSpear,
    name: "Нефритовый коршун",
    image_src: imageSrc("primordial_jade_winged_spear-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponKeys.ProspectorsDrill]: {
    key: WeaponKeys.ProspectorsDrill,
    name: "Бур рудоискателя",
    image_src: imageSrc("prospectors_drill-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.PrototypeAmber]: {
    key: WeaponKeys.PrototypeAmber,
    name: "Прототип: Янтарь",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("prototype_amber-256x256.webp"),
  },
  [WeaponKeys.PrototypeArchaic]: {
    key: WeaponKeys.PrototypeArchaic,
    name: "Прототип: Архаичный",
    image_src: imageSrc("prototype_archaic-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.PrototypeCrescent]: {
    key: WeaponKeys.PrototypeCrescent,
    name: "Прототип: Полумесяц",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("prototype_crescent-256x256.webp"),
  },
  [WeaponKeys.PrototypeRancour]: {
    key: WeaponKeys.PrototypeRancour,
    name: "Прототип: Злоба",
    image_src: imageSrc("prototype_rancour-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponKeys.PrototypeStarglitter]: {
    key: WeaponKeys.PrototypeStarglitter,
    name: "Прототип: Звёздный блеск",
    image_src: imageSrc("prototype_starglitter-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponKeys.Rainslasher]: {
    key: WeaponKeys.Rainslasher,
    name: "Дождерез",
    image_src: imageSrc("rainslasher-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponKeys.RangeGauge]: {
    key: WeaponKeys.RangeGauge,
    name: "Дальномер",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("range_gauge-256x256.webp"),
  },
  [WeaponKeys.RavenBow]: {
    key: WeaponKeys.RavenBow,
    name: "Лук ворона",
    rarity: 3,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 40, max_value: 448 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 20, max_value: 94 },
    image_src: imageSrc("raven_bow-256x256.webp"),
  },
  [WeaponKeys.RecurveBow]: {
    key: WeaponKeys.RecurveBow,
    name: "Изогнутый лук",
    rarity: 3,
    source: WeaponSource.Chests,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 38, max_value: 354 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("recurve_bow-256x256.webp"),
  },
  [WeaponKeys.RedhornStonethresher]: {
    key: WeaponKeys.RedhornStonethresher,
    name: "Краснорогий камнеруб",
    image_src: imageSrc("redhorn_stonethresher-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponKeys.RightfulReward]: {
    key: WeaponKeys.RightfulReward,
    name: "Справедливая награда",
    image_src: imageSrc("rightful_reward-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.RingOfYaxche]: {
    key: WeaponKeys.RingOfYaxche,
    name: "Кольцо Яшче",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("ring_of_yaxche-256x256.webp"),
  },
  [WeaponKeys.RoyalBow]: {
    key: WeaponKeys.RoyalBow,
    name: "Королевский лук",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("royal_bow-256x256.webp"),
  },
  [WeaponKeys.RoyalGreatsword]: {
    key: WeaponKeys.RoyalGreatsword,
    name: "Королевский двуручный меч",
    image_src: imageSrc("royal_greatsword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.RoyalGrimoire]: {
    key: WeaponKeys.RoyalGrimoire,
    name: "Королевский гримуар",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("royal_grimoire-256x256.webp"),
  },
  [WeaponKeys.RoyalLongsword]: {
    key: WeaponKeys.RoyalLongsword,
    name: "Меч аристократов",
    image_src: imageSrc("royal_longsword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.RoyalSpear]: {
    key: WeaponKeys.RoyalSpear,
    name: "Королевское копьё",
    image_src: imageSrc("royal_spear-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.Rust]: {
    key: WeaponKeys.Rust,
    name: "Ржавый лук",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("rust-256x256.webp"),
  },
  [WeaponKeys.SacrificialBow]: {
    key: WeaponKeys.SacrificialBow,
    name: "Церемониальный лук",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("sacrificial_bow-256x256.webp"),
  },
  [WeaponKeys.SacrificialFragments]: {
    key: WeaponKeys.SacrificialFragments,
    name: "Церемониальные мемуары",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 48, max_value: 221 },
    image_src: imageSrc("sacrificial_fragments-256x256.webp"),
  },
  [WeaponKeys.SacrificialGreatsword]: {
    key: WeaponKeys.SacrificialGreatsword,
    name: "Церемониальный двуручный меч",
    image_src: imageSrc("sacrificial_greatsword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponKeys.SacrificialJade]: {
    key: WeaponKeys.SacrificialJade,
    name: "Жертвенный нефрит",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.080, 1),
      max_value: numberFormatPercent(0.368, 1),
    },
    image_src: imageSrc("sacrificial_jade-256x256.webp"),
  },
  [WeaponKeys.SacrificialSword]: {
    key: WeaponKeys.SacrificialSword,
    name: "Церемониальный меч",
    image_src: imageSrc("sacrificial_sword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "41", max_value: "454" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponKeys.SapwoodBlade]: {
    key: WeaponKeys.SapwoodBlade,
    name: "Деревянный клинок",
    image_src: imageSrc("sapwood_blade-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponKeys.ScionOfTheBlazingSun]: {
    key: WeaponKeys.ScionOfTheBlazingSun,
    name: "Наследник слепящего солнца",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.040, 1),
      max_value: numberFormatPercent(0.184, 1),
    },
    image_src: imageSrc("scion_of_the_blazing_sun-256x256.webp"),
  },
  [WeaponKeys.SequenceOfSolitude]: {
    key: WeaponKeys.SequenceOfSolitude,
    name: "Каденция одиночества",
    rarity: 4,
    source: "Событие версии 5.6 «Кружащийся вальс»",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("sequence_of_solitude-256x256.webp"),
  },
  [WeaponKeys.SerpentSpine]: {
    key: WeaponKeys.SerpentSpine,
    name: "Меч драконьей кости",
    image_src: imageSrc("serpent_spine-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.SharpshootersOath]: {
    key: WeaponKeys.SharpshootersOath,
    name: "Клятва стрелка",
    rarity: 3,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("sharpshooters_oath-256x256.webp"),
  },
  [WeaponKeys.SilvershowerHeartstrings]: {
    key: WeaponKeys.SilvershowerHeartstrings,
    name: "Сердечные струны дождя",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("silvershower_heartstrings-256x256.webp"),
  },
  [WeaponKeys.SkyriderGreatsword]: {
    key: WeaponKeys.SkyriderGreatsword,
    name: "Большой меч небесного всадника",
    image_src: imageSrc("skyrider_greatsword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponKeys.SkyriderSword]: {
    key: WeaponKeys.SkyriderSword,
    name: "Меч небесного всадника",
    image_src: imageSrc("skyrider_sword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 3,
    base_Atk: { min_value: "38", max_value: "354" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponKeys.SkywardAtlas]: {
    key: WeaponKeys.SkywardAtlas,
    name: "Небесный атлас",
    rarity: 5,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("skyward_atlas-256x256.webp"),
  },
  [WeaponKeys.SkywardBlade]: {
    key: WeaponKeys.SkywardBlade,
    name: "Небесный меч",
    image_src: imageSrc("skyward_blade-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponKeys.SkywardHarp]: {
    key: WeaponKeys.SkywardHarp,
    name: "Небесное крыло",
    rarity: 5,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("skyward_harp-256x256.webp"),
  },
  [WeaponKeys.SkywardPride]: {
    key: WeaponKeys.SkywardPride,
    name: "Небесное величие",
    image_src: imageSrc("skyward_pride-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponKeys.SkywardSpine]: {
    key: WeaponKeys.SkywardSpine,
    name: "Небесная ось",
    image_src: imageSrc("skyward_spine-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponKeys.Slingshot]: {
    key: WeaponKeys.Slingshot,
    name: "Рогатка",
    rarity: 3,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 38, max_value: 354 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("slingshot-256x256.webp"),
  },
  [WeaponKeys.SnowTombedStarsilver]: {
    key: WeaponKeys.SnowTombedStarsilver,
    name: "Заснеженное звёздное серебро",
    image_src: imageSrc("snow_tombed_starsilver-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponKeys.SolarPearl]: {
    key: WeaponKeys.SolarPearl,
    name: "Солнечная жемчужина",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("solar_pearl-256x256.webp"),
  },
  [WeaponKeys.SongOfBrokenPines]: {
    key: WeaponKeys.SongOfBrokenPines,
    name: "Песнь разбитых сосен",
    image_src: imageSrc("song_of_broken_pines-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "49", max_value: "741" },
    secondary_stats: { key: StAtkeys.PhysicalDmgBonus, min_value: "4.5%", max_value: "20.7%" },
  },
  [WeaponKeys.SongOfStillness]: {
    key: WeaponKeys.SongOfStillness,
    name: "Мелодия покоя",
    rarity: 4,
    source: WeaponSource.Forged,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("song_of_stillness-256x256.webp"),
  },
  [WeaponKeys.SplendorOfTranquilWaters]: {
    key: WeaponKeys.SplendorOfTranquilWaters,
    name: "Блеск тихих вод",
    image_src: imageSrc("splendor_of_tranquil_waters-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponKeys.StaffOfHoma]: {
    key: WeaponKeys.StaffOfHoma,
    name: "Посох Хомы",
    image_src: imageSrc("staff_of_homa-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponKeys.StaffOfTheScarletSands]: {
    key: WeaponKeys.StaffOfTheScarletSands,
    name: "Посох алых песков",
    image_src: imageSrc("staff_of_the_scarlet_sands-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponKeys.StarcallersWatch]: {
    key: WeaponKeys.StarcallersWatch,
    name: "Бдение взывающего к звёздам",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("starcallers_watch-256x256.webp"),
  },
  [WeaponKeys.SturdyBone]: {
    key: WeaponKeys.SturdyBone,
    name: "Крепкая кость",
    image_src: imageSrc("sturdy_bone-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.SummitShaper]: {
    key: WeaponKeys.SummitShaper,
    name: "Кромсатель пиков",
    image_src: imageSrc("summit_shaper-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponKeys.SunnyMorningSleepIn]: {
    key: WeaponKeys.SunnyMorningSleepIn,
    name: "Сон солнечным утром",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("sunny_morning_sleep_in-256x256.webp"),
  },
  [WeaponKeys.SurfsUp]: {
    key: WeaponKeys.SurfsUp,
    name: "Лови волну",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("surfs_up-256x256.webp"),
  },
  [WeaponKeys.SwordOfDescension]: {
    key: WeaponKeys.SwordOfDescension,
    name: "Меч нисхождения",
    image_src: imageSrc("sword_of_descension-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "39", max_value: "440" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponKeys.SwordOfNarzissenkreuz]: {
    key: WeaponKeys.SwordOfNarzissenkreuz,
    name: "Меч Нарциссенкрейца",
    image_src: imageSrc("sword_of_narzissenkreuz_pneuma-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.SymphonistOfScents]: {
    key: WeaponKeys.SymphonistOfScents,
    name: "Симфонист ароматов",
    image_src: imageSrc("symphonist_of_scents-256x256.webp"),
    source: "Эксклюзивное оружие Молитвы события",
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
  },
  [WeaponKeys.TalkingStick]: {
    key: WeaponKeys.TalkingStick,
    name: "Говорящая палица",
    image_src: imageSrc("talking_stick-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "4%", max_value: "18.4%" },
  },
  [WeaponKeys.TamayurateiNoOhanashi]: {
    key: WeaponKeys.TamayurateiNoOhanashi,
    name: "Тамаюратэй но оханаси",
    image_src: imageSrc("tamayuratei_no_ohanashi-256x256.webp"),
    source: "Событие версии 5.4 «Чудесные истории фестиваля Микавы»",
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
  },
  [WeaponKeys.TheAlleyFlash]: {
    key: WeaponKeys.TheAlleyFlash,
    name: "Вспышка во тьме",
    image_src: imageSrc("the_alley_flash-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "45", max_value: "620" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "12", max_value: "55" },
  },
  [WeaponKeys.TheBell]: {
    key: WeaponKeys.TheBell,
    name: "Меч-колокол",
    image_src: imageSrc("the_bell-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.TheBlackSword]: {
    key: WeaponKeys.TheBlackSword,
    name: "Чёрный меч",
    image_src: imageSrc("the_black_sword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.TheCatch]: {
    key: WeaponKeys.TheCatch,
    name: "«Улов»",
    image_src: imageSrc("the_catch-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponKeys.TheDockhandsAssistant]: {
    key: WeaponKeys.TheDockhandsAssistant,
    name: "Верфь",
    image_src: imageSrc("the_dockhands_assistant-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Hp, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.TheFirstGreatMagic]: {
    key: WeaponKeys.TheFirstGreatMagic,
    name: "Первый великий фокус",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("the_first_great_magic-256x256.webp"),
  },
  [WeaponKeys.TheFlute]: {
    key: WeaponKeys.TheFlute,
    name: "Меч-флейта",
    image_src: imageSrc("the_flute-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.TheStringless]: {
    key: WeaponKeys.TheStringless,
    name: "Бесструнный",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("the_stringless-256x256.webp"),
  },
  [WeaponKeys.TheUnforged]: {
    key: WeaponKeys.TheUnforged,
    name: "Некованый",
    image_src: imageSrc("the_unforged-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponKeys.TheViridescentHunt]: {
    key: WeaponKeys.TheViridescentHunt,
    name: "Зелёный лук",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("the_viridescent_hunt-256x256.webp"),
  },
  [WeaponKeys.TheWidsith]: {
    key: WeaponKeys.TheWidsith,
    name: "Песнь странника",
    rarity: 4,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("the_widsith-256x256.webp"),
  },
  [WeaponKeys.ThrillingTalesOfDragonSlayers]: {
    key: WeaponKeys.ThrillingTalesOfDragonSlayers,
    name: "Эпос о драконоборцах",
    rarity: 3,
    source: WeaponSource.Wish,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      key: StAtkeys.HpPercentage,
      min_value: numberFormatPercent(0.077, 1),
      max_value: numberFormatPercent(0.352, 1),
    },
    image_src: imageSrc("thrilling_tales_of_dragon_slayers-256x256.webp"),
  },
  [WeaponKeys.ThunderingPulse]: {
    key: WeaponKeys.ThunderingPulse,
    name: "Громовой пульс",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("thundering_pulse-256x256.webp"),
  },
  [WeaponKeys.TidalShadow]: {
    key: WeaponKeys.TidalShadow,
    name: "Тень волны",
    image_src: imageSrc("tidal_shadow-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponKeys.TomeOfTheEternalFlow]: {
    key: WeaponKeys.TomeOfTheEternalFlow,
    name: "Обряд вечного течения",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("tome_of_the_eternal_flow-256x256.webp"),
  },
  [WeaponKeys.ToukabouShigure]: {
    key: WeaponKeys.ToukabouShigure,
    name: "Токабо сигурэ",
    image_src: imageSrc("toukabou_shigure-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponKeys.TravelersHandySword]: {
    key: WeaponKeys.TravelersHandySword,
    name: "Меч путешественника",
    image_src: imageSrc("travelers_handy_sword-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 3,
    base_Atk: { min_value: "40", max_value: "448" },
    secondary_stats: { key: StAtkeys.Def, min_value: "6.4%", max_value: "29.3%" },
  },
  [WeaponKeys.TulaytullahsRemembrance]: {
    key: WeaponKeys.TulaytullahsRemembrance,
    name: "Воспоминания Тулайтуллы",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("tulaytullahs_remembrance-256x256.webp"),
  },
  [WeaponKeys.TwinNephrite]: {
    key: WeaponKeys.TwinNephrite,
    name: "Парный нефрит",
    rarity: 3,
    source: WeaponSource.Chests,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 40, max_value: 448 },
    secondary_stats: {
      key: StAtkeys.CritRate,
      min_value: numberFormatPercent(0.034, 1),
      max_value: numberFormatPercent(0.156, 1),
    },
    image_src: imageSrc("twin_nephrite-256x256.webp"),
  },
  [WeaponKeys.UltimateOverlordsMegaMagicSword]: {
    key: WeaponKeys.UltimateOverlordsMegaMagicSword,
    name: "«Магический супермеч высшего владыки»",
    image_src: imageSrc("ultimate_overlords_mega_magic_sword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "44", max_value: "565" },
    secondary_stats: { key: StAtkeys.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponKeys.UrakuMisugiri]: {
    key: WeaponKeys.UrakuMisugiri,
    name: "Ураку мисугири",
    image_src: imageSrc("uraku_misugiri-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 5,
    base_Atk: { min_value: "44", max_value: "542" },
    secondary_stats: { key: StAtkeys.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponKeys.Verdict]: {
    key: WeaponKeys.Verdict,
    name: "Вердикт",
    image_src: imageSrc("verdict-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "48", max_value: "674" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponKeys.VividNotions]: {
    key: WeaponKeys.VividNotions,
    name: "Переливающиеся чаяния",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      key: StAtkeys.CritDMG,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("vivid_notions-256x256.webp"),
  },
  [WeaponKeys.VortexVanquisher]: {
    key: WeaponKeys.VortexVanquisher,
    name: "Покоритель вихря",
    image_src: imageSrc("vortex_vanquisher-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponKeys.WanderingEvenstar]: {
    key: WeaponKeys.WanderingEvenstar,
    name: "Скитающаяся звезда",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("wandering_evenstar-256x256.webp"),
  },
  [WeaponKeys.WavebreakersFin]: {
    key: WeaponKeys.WavebreakersFin,
    name: "Режущий волны плавник",
    image_src: imageSrc("wavebreakers_fin-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 4,
    base_Atk: { min_value: "45", max_value: "620" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "3%", max_value: "13.8%" },
  },
  [WeaponKeys.WaveridingWhirl]: {
    key: WeaponKeys.WaveridingWhirl,
    name: "Вихрь на волнах",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.133, 1),
      max_value: numberFormatPercent(0.613, 1),
    },
    image_src: imageSrc("waveriding_whirl-256x256.webp"),
  },
  [WeaponKeys.WhiteIronGreatsword]: {
    key: WeaponKeys.WhiteIronGreatsword,
    name: "Меч из белого железа",
    image_src: imageSrc("white_iron_greatsword-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.Def, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponKeys.WhiteTassel]: {
    key: WeaponKeys.WhiteTassel,
    name: "Белая кисть",
    image_src: imageSrc("white_tassel-256x256.png"),
    type_key: WeaponTypeKeys["🔱"],
    rarity: 3,
    base_Atk: { min_value: "39", max_value: "401" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponKeys.Whiteblind]: {
    key: WeaponKeys.Whiteblind,
    name: "Белая тень",
    image_src: imageSrc("whiteblind-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.Def, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponKeys.WindblumeOde]: {
    key: WeaponKeys.WindblumeOde,
    name: "Ода анемонии",
    rarity: 4,
    source: "Событие версии 1.4 «Приглашение ветряных цветов»",
    type_key: WeaponTypeKeys["🏹"],
    base_Atk: { min_value: 42, max_value: 510 },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("windblume_ode-256x256.webp"),
  },
  [WeaponKeys.WineAndSong]: {
    key: WeaponKeys.WineAndSong,
    name: "Вино и песни",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_key: WeaponTypeKeys["💥"],
    base_Atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      key: StAtkeys.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("wine_and_song-256x256.webp"),
  },
  [WeaponKeys.WolfFang]: {
    key: WeaponKeys.WolfFang,
    name: "Волчий клык",
    image_src: imageSrc("wolf_fang-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponKeys.WolfsGravestone]: {
    key: WeaponKeys.WolfsGravestone,
    name: "Волчья погибель",
    image_src: imageSrc("wolfs_gravestone-256x256.png"),
    type_key: WeaponTypeKeys["🗡️"],
    rarity: 5,
    base_Atk: { min_value: "46", max_value: "608" },
    secondary_stats: { key: StAtkeys.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponKeys.XiphosMoonlight]: {
    key: WeaponKeys.XiphosMoonlight,
    name: "Лунное сияние ксифоса",
    image_src: imageSrc("xiphos_moonlight-256x256.png"),
    type_key: WeaponTypeKeys["⚔️"],
    rarity: 4,
    base_Atk: { min_value: "42", max_value: "510" },
    secondary_stats: { key: StAtkeys.ElementalMastery, min_value: "36", max_value: "165" },
  },
} as Record<WeaponKey, Weapon>;
