import { AttributeUidEnum } from "./enums/attribute";
import { numberFormatPercent, publicImageSrc } from "@/lib/utils";
import { WeaponTypeUidEnum } from "./enums/weapon-type";
import { WeaponUidEnum } from "./enums/weapon";
import type { Weapon, WeaponUid } from "./types/weapon";

const WeaponSource = {
  BattlePass: "Выбираемая награда при достижении 30 уровня боевого пропуска (Жемчужный гимн)",
  Chests: "Сундуки",
  EventWishExclusive: "Эксклюзивное оружие Молитвы события",
  Forged: "Кузница",
  PaimonsBargains: "Обмен Звёздного блеска в магазине Паймон",
  Wish: "Молитвы",
} as const;

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`weapons/${src}`);

export default {
  [WeaponUidEnum.AThousandBlazingSuns]: {
    uid: WeaponUidEnum.AThousandBlazingSuns,
    name: "Тысяча ослепительных солнц",
    image_src: imageSrc("a_thousand_blazing_suns-256x256.webp"),
    source: "Эксклюзивное оружие Молитвы события",
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: 49, max_value: 741 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.024, 1),
      max_value: numberFormatPercent(0.110, 1),
    },
  },
  [WeaponUidEnum.AThousandFloatingDreams]: {
    uid: WeaponUidEnum.AThousandFloatingDreams,
    name: "Сновидения тысячи ночей",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("a_thousand_floating_dreams-256x256.webp"),
  },
  [WeaponUidEnum.Absolution]: {
    uid: WeaponUidEnum.Absolution,
    name: "Отпущение грехов",
    image_src: imageSrc("absolution-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponUidEnum.Akuoumaru]: {
    uid: WeaponUidEnum.Akuoumaru,
    name: "Акуомару",
    image_src: imageSrc("akuoumaru-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.AlleyHunter]: {
    uid: WeaponUidEnum.AlleyHunter,
    name: "Охотник во тьме",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("alley_hunter-256x256.webp"),
  },
  [WeaponUidEnum.AmenomaKageuchi]: {
    uid: WeaponUidEnum.AmenomaKageuchi,
    name: "Амэнома Кагэути",
    image_src: imageSrc("amenoma_kageuchi-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.AmosBow]: {
    uid: WeaponUidEnum.AmosBow,
    name: "Лук Амоса",
    quality: 5,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("amos_bow-256x256.webp"),
  },
  [WeaponUidEnum.AquaSimulacra]: {
    uid: WeaponUidEnum.AquaSimulacra,
    name: "Аква симулякрум",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("aqua_simulacra-256x256.webp"),
  },
  [WeaponUidEnum.AquilaFavonia]: {
    uid: WeaponUidEnum.AquilaFavonia,
    name: "Меч Сокола",
    image_src: imageSrc("aquila_favonia-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "48", max_value: "6774" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.AshGravenDrinkingHorn]: {
    uid: WeaponUidEnum.AshGravenDrinkingHorn,
    name: "Пепельный рог",
    quality: 4,
    source: "Событие версии 5.0 «Следы мастерства»",
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("ash_graven_drinking_horn-256x256.webp"),
  },
  [WeaponUidEnum.AstralVulturesCrimsonPlumage]: {
    uid: WeaponUidEnum.AstralVulturesCrimsonPlumage,
    name: "Алое перо звёздного грифа",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("astral_vultures_crimson_plumage-256x256.webp"),
  },
  [WeaponUidEnum.Azurelight]: {
    uid: WeaponUidEnum.Azurelight,
    name: "Лазурное сияние",
    image_src: imageSrc("azurelight-256x256.webp"),
    source: "Эксклюзивное оружие Молитвы события",
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
  },
  [WeaponUidEnum.BalladOfTheBoundlessBlue]: {
    uid: WeaponUidEnum.BalladOfTheBoundlessBlue,
    name: "Песнь необъятной лазури",
    quality: 4,
    source: "Событие версии 4.1 «Поэзия вод»",
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("ballad_of_the_boundless_blue-256x256.webp"),
  },
  [WeaponUidEnum.BalladOfTheFjords]: {
    uid: WeaponUidEnum.BalladOfTheFjords,
    name: "Баллада фьордов",
    image_src: imageSrc("ballad_of_the_fjords-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.BeaconOfTheReedSea]: {
    uid: WeaponUidEnum.BeaconOfTheReedSea,
    name: "Маяк тростникового моря",
    image_src: imageSrc("beacon_of_the_reed_sea-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponUidEnum.BlackTassel]: {
    uid: WeaponUidEnum.BlackTassel,
    name: "Чёрная кисть",
    image_src: imageSrc("black_tassel-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "10.2%", max_value: "46.9%" },
  },
  [WeaponUidEnum.BlackcliffAgate]: {
    uid: WeaponUidEnum.BlackcliffAgate,
    name: "Черногорский агат",
    quality: 4,
    source: WeaponSource.PaimonsBargains,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("blackcliff_agate-256x256.webp"),
  },
  [WeaponUidEnum.BlackcliffLongsword]: {
    uid: WeaponUidEnum.BlackcliffLongsword,
    name: "Черногорский длинный меч",
    image_src: imageSrc("blackcliff_longsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponUidEnum.BlackcliffPole]: {
    uid: WeaponUidEnum.BlackcliffPole,
    name: "Черногорская пика",
    image_src: imageSrc("blackcliff_pole-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.BlackcliffSlasher]: {
    uid: WeaponUidEnum.BlackcliffSlasher,
    name: "Черногорская бритва",
    image_src: imageSrc("blackcliff_slasher-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.BlackcliffWarbow]: {
    uid: WeaponUidEnum.BlackcliffWarbow,
    name: "Черногорский боевой лук",
    quality: 4,
    source: WeaponSource.PaimonsBargains,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.080, 1),
      max_value: numberFormatPercent(0.368, 1),
    },
    image_src: imageSrc("blackcliff_warbow-256x256.webp"),
  },
  [WeaponUidEnum.BloodtaintedGreatsword]: {
    uid: WeaponUidEnum.BloodtaintedGreatsword,
    name: "Меч драконьей крови",
    image_src: imageSrc("bloodtainted_greatsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "41", max_value: "187" },
  },
  [WeaponUidEnum.CalamityOfEshu]: {
    uid: WeaponUidEnum.CalamityOfEshu,
    name: "Бедствие Эшу",
    image_src: imageSrc("calamity_of_eshu-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.CalamityQueller]: {
    uid: WeaponUidEnum.CalamityQueller,
    name: "Усмиритель бед",
    image_src: imageSrc("calamity_queller-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "3.6%", max_value: "16.5%" },
  },
  [WeaponUidEnum.CashflowSupervision]: {
    uid: WeaponUidEnum.CashflowSupervision,
    name: "Казначейский надзор",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("cashflow_supervision-256x256.webp"),
  },
  [WeaponUidEnum.ChainBreaker]: {
    uid: WeaponUidEnum.ChainBreaker,
    name: "Разбивающий цепи",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("chain_breaker-256x256.webp"),
  },
  [WeaponUidEnum.CinnabarSpindle]: {
    uid: WeaponUidEnum.CinnabarSpindle,
    name: "Киноварное веретено",
    image_src: imageSrc("cinnabar_spindle-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponUidEnum.Cloudforged]: {
    uid: WeaponUidEnum.Cloudforged,
    name: "Выкованный из облаков",
    quality: 4,
    source: "Событие версии 4.7 «Моделирование взаимного повышения безопасности»",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("cloudforged-256x256.webp"),
  },
  [WeaponUidEnum.CompoundBow]: {
    uid: WeaponUidEnum.CompoundBow,
    name: "Составной лук",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.PhysicalDMGBonus,
      min_value: numberFormatPercent(0.150, 1),
      max_value: numberFormatPercent(0.690, 1),
    },
    image_src: imageSrc("compound_bow-256x256.webp"),
  },
  [WeaponUidEnum.CoolSteel]: {
    uid: WeaponUidEnum.CoolSteel,
    name: "Холодное лезвие",
    image_src: imageSrc("cool_steel-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponUidEnum.CranesEchoingCall]: {
    uid: WeaponUidEnum.CranesEchoingCall,
    name: "Звонкий клич журавля",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 49, max_value: 741 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.036, 1),
      max_value: numberFormatPercent(0.165, 1),
    },
    image_src: imageSrc("cranes_echoing_call-256x256.webp"),
  },
  [WeaponUidEnum.CrescentPike]: {
    uid: WeaponUidEnum.CrescentPike,
    name: "Пика полумесяца",
    image_src: imageSrc("crescent_pike-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponUidEnum.CrimsonMoonsSemblance]: {
    uid: WeaponUidEnum.CrimsonMoonsSemblance,
    name: "Очертания алой луны",
    image_src: imageSrc("crimson_moons_semblance-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponUidEnum.DarkIronSword]: {
    uid: WeaponUidEnum.DarkIronSword,
    name: "Тёмный железный меч",
    image_src: imageSrc("dark_iron_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "31", max_value: "141" },
  },
  [WeaponUidEnum.Deathmatch]: {
    uid: WeaponUidEnum.Deathmatch,
    name: "Смертельный бой",
    image_src: imageSrc("deathmatch-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponUidEnum.DebateClub]: {
    uid: WeaponUidEnum.DebateClub,
    name: "Дубина переговоров",
    image_src: imageSrc("debate_club-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponUidEnum.DialoguesOfTheDesertSages]: {
    uid: WeaponUidEnum.DialoguesOfTheDesertSages,
    name: "Диалог пустынных мудрецов",
    image_src: imageSrc("dialogues_of_the_desert_sages-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.DodocoTales]: {
    uid: WeaponUidEnum.DodocoTales,
    name: "Истории Додоко",
    quality: 4,
    source: "Событие версии 1.6 «Лето! Остров? Приключение!»",
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("dodoco_tales-256x256.webp"),
  },
  [WeaponUidEnum.DragonsBane]: {
    uid: WeaponUidEnum.DragonsBane,
    name: "Гроза драконов",
    image_src: imageSrc("dragons_bane-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "48", max_value: "221" },
  },
  [WeaponUidEnum.DragonspineSpear]: {
    uid: WeaponUidEnum.DragonspineSpear,
    name: "Копьё Драконьего хребта",
    image_src: imageSrc("dragonspine_spear-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponUidEnum.EarthShaker]: {
    uid: WeaponUidEnum.EarthShaker,
    name: "Сотрясающий землю",
    image_src: imageSrc("earth_shaker-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.ElegyForTheEnd]: {
    uid: WeaponUidEnum.ElegyForTheEnd,
    name: "Элегия погибели",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("elegy_for_the_end-256x256.webp"),
  },
  [WeaponUidEnum.EmeraldOrb]: {
    uid: WeaponUidEnum.EmeraldOrb,
    name: "Изумрудный шар",
    quality: 3,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 20, max_value: 94 },
    image_src: imageSrc("emerald_orb-256x256.webp"),
  },
  [WeaponUidEnum.EndOfTheLine]: {
    uid: WeaponUidEnum.EndOfTheLine,
    name: "Иссушитель",
    quality: 4,
    source: "Ассоциация рыболовов Сумеру",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("end_of_the_line-256x256.webp"),
  },
  [WeaponUidEnum.EngulfingLightning]: {
    uid: WeaponUidEnum.EngulfingLightning,
    name: "Сияющая жатва",
    image_src: imageSrc("engulfing_lightning-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.EverlastingMoonglow]: {
    uid: WeaponUidEnum.EverlastingMoonglow,
    name: "Вечное лунное сияние",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("everlasting_moonglow-256x256.webp"),
  },
  [WeaponUidEnum.EyeOfPerception]: {
    uid: WeaponUidEnum.EyeOfPerception,
    name: "Око сознания",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("eye_of_perception-256x256.webp"),
  },
  [WeaponUidEnum.FadingTwilight]: {
    uid: WeaponUidEnum.FadingTwilight,
    name: "Гаснущие сумерки",
    quality: 4,
    source: "Событие версии 2.7 «Опасная тропа»",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("fading_twilight-256x256.webp"),
  },
  [WeaponUidEnum.FangOfTheMountainKing]: {
    uid: WeaponUidEnum.FangOfTheMountainKing,
    name: "Клык Горного короля",
    image_src: imageSrc("fang_of_the_mountain_king-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "2.4%", max_value: "11.0%" },
  },
  [WeaponUidEnum.FavoniusCodex]: {
    uid: WeaponUidEnum.FavoniusCodex,
    name: "Кодекс Фавония",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("favonius_codex-256x256.webp"),
  },
  [WeaponUidEnum.FavoniusGreatsword]: {
    uid: WeaponUidEnum.FavoniusGreatsword,
    name: "Двуручный меч Фавония",
    image_src: imageSrc("favonius_greatsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponUidEnum.FavoniusLance]: {
    uid: WeaponUidEnum.FavoniusLance,
    name: "Копьё Фавония",
    image_src: imageSrc("favonius_lance-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponUidEnum.FavoniusSword]: {
    uid: WeaponUidEnum.FavoniusSword,
    name: "Меч Фавония",
    image_src: imageSrc("favonius_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponUidEnum.FavoniusWarbow]: {
    uid: WeaponUidEnum.FavoniusWarbow,
    name: "Боевой лук Фавония",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.133, 1),
      max_value: numberFormatPercent(0.613, 1),
    },
    image_src: imageSrc("favonius_warbow-256x256.webp"),
  },
  [WeaponUidEnum.FerrousShadow]: {
    uid: WeaponUidEnum.FerrousShadow,
    name: "Металлическая тень",
    image_src: imageSrc("ferrous_shadow-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponUidEnum.FesteringDesire]: {
    uid: WeaponUidEnum.FesteringDesire,
    name: "Осквернённое желание",
    image_src: imageSrc("festering_desire-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponUidEnum.FilletBlade]: {
    uid: WeaponUidEnum.FilletBlade,
    name: "Филейный нож",
    image_src: imageSrc("fillet_blade-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponUidEnum.FinaleOfTheDeep]: {
    uid: WeaponUidEnum.FinaleOfTheDeep,
    name: "Грандиозный финал глубин",
    image_src: imageSrc("finale_of_the_deep-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.FleuveCendreFerryman]: {
    uid: WeaponUidEnum.FleuveCendreFerryman,
    name: "Перевозчик Флёв Сандр",
    image_src: imageSrc("fleuve_cendre_ferryman-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponUidEnum.FlowerWreathedFeathers]: {
    uid: WeaponUidEnum.FlowerWreathedFeathers,
    name: "Украшенные цветами перья",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("flower_wreathed_feathers-256x256.webp"),
  },
  [WeaponUidEnum.FlowingPurity]: {
    uid: WeaponUidEnum.FlowingPurity,
    name: "Сверкание чистых вод",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("flowing_purity-256x256.webp"),
  },
  [WeaponUidEnum.FluteOfEzpitzal]: {
    uid: WeaponUidEnum.FluteOfEzpitzal,
    name: "Флейта Эспицаль",
    image_src: imageSrc("flute_of_ezpitzal-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponUidEnum.FootprintOfTheRainbow]: {
    uid: WeaponUidEnum.FootprintOfTheRainbow,
    name: "След радуги",
    image_src: imageSrc("footprint_of_the_rainbow-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponUidEnum.ForestRegalia]: {
    uid: WeaponUidEnum.ForestRegalia,
    name: "Регалия леса",
    image_src: imageSrc("forest_regalia-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponUidEnum.FreedomSworn]: {
    uid: WeaponUidEnum.FreedomSworn,
    name: "Клятва свободы",
    image_src: imageSrc("freedom_sworn-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "43", max_value: "198" },
  },
  [WeaponUidEnum.Frostbearer]: {
    uid: WeaponUidEnum.Frostbearer,
    name: "Плод вечной мерзлоты",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("frostbearer-256x256.webp"),
  },
  [WeaponUidEnum.FruitOfFulfillment]: {
    uid: WeaponUidEnum.FruitOfFulfillment,
    name: "Плод восполнения",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("fruit_of_fulfillment-256x256.webp"),
  },
  [WeaponUidEnum.FruitfulHook]: {
    uid: WeaponUidEnum.FruitfulHook,
    name: "Плодотворный крюк",
    image_src: imageSrc("fruitful_hook-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.HakushinRing]: {
    uid: WeaponUidEnum.HakushinRing,
    name: "Кольцо Хакусин",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("hakushin_ring-256x256.webp"),
  },
  [WeaponUidEnum.Halberd]: {
    uid: WeaponUidEnum.Halberd,
    name: "Алебарда Миллелита",
    image_src: imageSrc("halberd-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 3,
    base_atk: { min_value: "40", max_value: "448" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponUidEnum.Hamayumi]: {
    uid: WeaponUidEnum.Hamayumi,
    name: "Хамаюми",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("hamayumi-256x256.webp"),
  },
  [WeaponUidEnum.HaranGeppakuFutsu]: {
    uid: WeaponUidEnum.HaranGeppakuFutsu,
    name: "Харан гэппаку фуцу",
    image_src: imageSrc("haran_geppaku_futsu-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponUidEnum.HarbingerOfDawn]: {
    uid: WeaponUidEnum.HarbingerOfDawn,
    name: "Предвестник зари",
    image_src: imageSrc("harbinger_of_dawn-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "10.2%", max_value: "46.9%" },
  },
  [WeaponUidEnum.HuntersPath]: {
    uid: WeaponUidEnum.HuntersPath,
    name: "Охотничья тропа",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("hunters_path-256x256.webp"),
  },
  [WeaponUidEnum.IbisPiercer]: {
    uid: WeaponUidEnum.IbisPiercer,
    name: "Клюв ибиса",
    quality: 4,
    source: "Событие версии 3.7 «Дуэль! К вершинам карточного мастерства!»",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("ibis_piercer-256x256.webp"),
  },
  [WeaponUidEnum.IronSting]: {
    uid: WeaponUidEnum.IronSting,
    name: "Стальное жало",
    image_src: imageSrc("iron_sting-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponUidEnum.JadefallsSplendor]: {
    uid: WeaponUidEnum.JadefallsSplendor,
    name: "Великолепие лазурного свода",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("jadefalls_splendor-256x256.webp"),
  },
  [WeaponUidEnum.KagotsurubeIsshin]: {
    uid: WeaponUidEnum.KagotsurubeIsshin,
    name: "Кагоцурубэ Иссин",
    image_src: imageSrc("kagotsurube_isshin-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.KagurasVerity]: {
    uid: WeaponUidEnum.KagurasVerity,
    name: "Истина кагура",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("kaguras_verity-256x256.webp"),
  },
  [WeaponUidEnum.KatsuragikiriNagamasa]: {
    uid: WeaponUidEnum.KatsuragikiriNagamasa,
    name: "Кацурагикири Нагамаса",
    image_src: imageSrc("katsuragikiri_nagamasa-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponUidEnum.KeyOfKhajNisut]: {
    uid: WeaponUidEnum.KeyOfKhajNisut,
    name: "Ключ Хадж-нисут",
    image_src: imageSrc("key_of_khaj_nisut-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponUidEnum.KingsSquire]: {
    uid: WeaponUidEnum.KingsSquire,
    name: "Приближённый короля",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("kings_squire-256x256.webp"),
  },
  [WeaponUidEnum.KitainCrossSpear]: {
    uid: WeaponUidEnum.KitainCrossSpear,
    name: "Крест-копьё Китаин",
    image_src: imageSrc("kitain_cross_spear-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponUidEnum.LightOfFoliarIncision]: {
    uid: WeaponUidEnum.LightOfFoliarIncision,
    name: "Свет лиственного разреза",
    image_src: imageSrc("light_of_foliar_incision-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponUidEnum.LionsRoar]: {
    uid: WeaponUidEnum.LionsRoar,
    name: "Драконий рык",
    image_src: imageSrc("lions_roar-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.LithicBlade]: {
    uid: WeaponUidEnum.LithicBlade,
    name: "Каменный меч",
    image_src: imageSrc("lithic_blade-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.LithicSpear]: {
    uid: WeaponUidEnum.LithicSpear,
    name: "Каменное копьё",
    image_src: imageSrc("lithic_spear-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.LostPrayerToTheSacredWinds]: {
    uid: WeaponUidEnum.LostPrayerToTheSacredWinds,
    name: "Молитва святым ветрам",
    quality: 5,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("lost_prayer_to_the_sacred_winds-256x256.webp"),
  },
  [WeaponUidEnum.LumidouceElegy]: {
    uid: WeaponUidEnum.LumidouceElegy,
    name: "Элегия Люмидус",
    image_src: imageSrc("lumidouce_elegy-512x512.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponUidEnum.LuxuriousSeaLord]: {
    uid: WeaponUidEnum.LuxuriousSeaLord,
    name: "Благодатный владыка вод",
    image_src: imageSrc("luxurious_sea_lord-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.MagicGuide]: {
    uid: WeaponUidEnum.MagicGuide,
    name: "Руководство по магии",
    quality: 3,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 41, max_value: 187 },
    image_src: imageSrc("magic_guide-256x256.webp"),
  },
  [WeaponUidEnum.MailedFlower]: {
    uid: WeaponUidEnum.MailedFlower,
    name: "Цветок в латах",
    image_src: imageSrc("mailed_flower-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponUidEnum.MakhairaAquamarine]: {
    uid: WeaponUidEnum.MakhairaAquamarine,
    name: "Аквамарин Махайры",
    image_src: imageSrc("makhaira_aquamarine-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponUidEnum.MappaMare]: {
    uid: WeaponUidEnum.MappaMare,
    name: "Морской атлас",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 24, max_value: 110 },
    image_src: imageSrc("mappa_mare-256x256.webp"),
  },
  [WeaponUidEnum.MemoryOfDust]: {
    uid: WeaponUidEnum.MemoryOfDust,
    name: "Память о пыли",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("memory_of_dust-256x256.webp"),
  },
  [WeaponUidEnum.Messenger]: {
    uid: WeaponUidEnum.Messenger,
    name: "Посыльный",
    quality: 3,
    source: WeaponSource.Chests,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("messenger-256x256.webp"),
  },
  [WeaponUidEnum.MissiveWindspear]: {
    uid: WeaponUidEnum.MissiveWindspear,
    name: "Копьё послания ветров",
    image_src: imageSrc("missive_windspear-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.MistsplitterReforged]: {
    uid: WeaponUidEnum.MistsplitterReforged,
    name: "Рассекающий туман",
    image_src: imageSrc("mistsplitter_reforged-512x512.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponUidEnum.MitternachtsWaltz]: {
    uid: WeaponUidEnum.MitternachtsWaltz,
    name: "Вальс Нирваны Ночи",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.PhysicalDMGBonus,
      min_value: numberFormatPercent(0.113, 1),
      max_value: numberFormatPercent(0.517, 1),
    },
    image_src: imageSrc("mitternachts_waltz-256x256.webp"),
  },
  [WeaponUidEnum.Moonpiercer]: {
    uid: WeaponUidEnum.Moonpiercer,
    name: "Пронзающий луну",
    image_src: imageSrc("moonpiercer-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponUidEnum.MountainBracingBolt]: {
    uid: WeaponUidEnum.MountainBracingBolt,
    name: "Крепящий горы шип",
    image_src: imageSrc("mountain_bracing_bolt-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponUidEnum.MouunsMoon]: {
    uid: WeaponUidEnum.MouunsMoon,
    name: "Луна Моун",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("mouuns_moon-256x256.webp"),
  },
  [WeaponUidEnum.OathswornEye]: {
    uid: WeaponUidEnum.OathswornEye,
    name: "Око клятвы",
    quality: 4,
    source: "Событие версии 2.5 «Подношение врат трёх миров»",
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("oathsworn_eye-256x256.webp"),
  },
  [WeaponUidEnum.OtherworldlyStory]: {
    uid: WeaponUidEnum.OtherworldlyStory,
    name: "Потусторонняя история",
    quality: 3,
    source: WeaponSource.Chests,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.085, 1),
      max_value: numberFormatPercent(0.390, 1),
    },
    image_src: imageSrc("otherworldly_story-256x256.webp"),
  },
  [WeaponUidEnum.PeakPatrolSong]: {
    uid: WeaponUidEnum.PeakPatrolSong,
    name: "Песнь патруля пиков",
    image_src: imageSrc("peak_patrol_song-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "18%", max_value: "82.7%" },
  },
  [WeaponUidEnum.PolarStar]: {
    uid: WeaponUidEnum.PolarStar,
    name: "Полярная звезда",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("polar_star-256x256.webp"),
  },
  [WeaponUidEnum.PortablePowerSaw]: {
    uid: WeaponUidEnum.PortablePowerSaw,
    name: "Переносная мотопила",
    image_src: imageSrc("portable_power_saw-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.Predator]: {
    uid: WeaponUidEnum.Predator,
    name: "Хищник",
    quality: 4,
    source: "Внутриигровая почта \"PlayStation Network\"",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("predator-512x512.webp"),
  },
  [WeaponUidEnum.PrimordialJadeCutter]: {
    uid: WeaponUidEnum.PrimordialJadeCutter,
    name: "Драгоценный омут",
    image_src: imageSrc("primordial_jade_cutter-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponUidEnum.PrimordialJadeWingedSpear]: {
    uid: WeaponUidEnum.PrimordialJadeWingedSpear,
    name: "Нефритовый коршун",
    image_src: imageSrc("primordial_jade_winged_spear-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponUidEnum.ProspectorsDrill]: {
    uid: WeaponUidEnum.ProspectorsDrill,
    name: "Бур рудоискателя",
    image_src: imageSrc("prospectors_drill-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.PrototypeAmber]: {
    uid: WeaponUidEnum.PrototypeAmber,
    name: "Прототип: Янтарь",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("prototype_amber-256x256.webp"),
  },
  [WeaponUidEnum.PrototypeArchaic]: {
    uid: WeaponUidEnum.PrototypeArchaic,
    name: "Прототип: Архаичный",
    image_src: imageSrc("prototype_archaic-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.PrototypeCrescent]: {
    uid: WeaponUidEnum.PrototypeCrescent,
    name: "Прототип: Полумесяц",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("prototype_crescent-256x256.webp"),
  },
  [WeaponUidEnum.PrototypeRancour]: {
    uid: WeaponUidEnum.PrototypeRancour,
    name: "Прототип: Злоба",
    image_src: imageSrc("prototype_rancour-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponUidEnum.PrototypeStarglitter]: {
    uid: WeaponUidEnum.PrototypeStarglitter,
    name: "Прототип: Звёздный блеск",
    image_src: imageSrc("prototype_starglitter-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponUidEnum.Rainslasher]: {
    uid: WeaponUidEnum.Rainslasher,
    name: "Дождерез",
    image_src: imageSrc("rainslasher-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponUidEnum.RangeGauge]: {
    uid: WeaponUidEnum.RangeGauge,
    name: "Дальномер",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("range_gauge-256x256.webp"),
  },
  [WeaponUidEnum.RavenBow]: {
    uid: WeaponUidEnum.RavenBow,
    name: "Лук ворона",
    quality: 3,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 20, max_value: 94 },
    image_src: imageSrc("raven_bow-256x256.webp"),
  },
  [WeaponUidEnum.RecurveBow]: {
    uid: WeaponUidEnum.RecurveBow,
    name: "Изогнутый лук",
    quality: 3,
    source: WeaponSource.Chests,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("recurve_bow-256x256.webp"),
  },
  [WeaponUidEnum.RedhornStonethresher]: {
    uid: WeaponUidEnum.RedhornStonethresher,
    name: "Краснорогий камнеруб",
    image_src: imageSrc("redhorn_stonethresher-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponUidEnum.RightfulReward]: {
    uid: WeaponUidEnum.RightfulReward,
    name: "Справедливая награда",
    image_src: imageSrc("rightful_reward-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.RingOfYaxche]: {
    uid: WeaponUidEnum.RingOfYaxche,
    name: "Кольцо Яшче",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("ring_of_yaxche-256x256.webp"),
  },
  [WeaponUidEnum.RoyalBow]: {
    uid: WeaponUidEnum.RoyalBow,
    name: "Королевский лук",
    quality: 4,
    source: WeaponSource.PaimonsBargains,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("royal_bow-256x256.webp"),
  },
  [WeaponUidEnum.RoyalGreatsword]: {
    uid: WeaponUidEnum.RoyalGreatsword,
    name: "Королевский двуручный меч",
    image_src: imageSrc("royal_greatsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.RoyalGrimoire]: {
    uid: WeaponUidEnum.RoyalGrimoire,
    name: "Королевский гримуар",
    quality: 4,
    source: WeaponSource.PaimonsBargains,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("royal_grimoire-256x256.webp"),
  },
  [WeaponUidEnum.RoyalLongsword]: {
    uid: WeaponUidEnum.RoyalLongsword,
    name: "Меч аристократов",
    image_src: imageSrc("royal_longsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.RoyalSpear]: {
    uid: WeaponUidEnum.RoyalSpear,
    name: "Королевское копьё",
    image_src: imageSrc("royal_spear-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.Rust]: {
    uid: WeaponUidEnum.Rust,
    name: "Ржавый лук",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("rust-256x256.webp"),
  },
  [WeaponUidEnum.SacrificialBow]: {
    uid: WeaponUidEnum.SacrificialBow,
    name: "Церемониальный лук",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("sacrificial_bow-256x256.webp"),
  },
  [WeaponUidEnum.SacrificialFragments]: {
    uid: WeaponUidEnum.SacrificialFragments,
    name: "Церемониальные мемуары",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 48, max_value: 221 },
    image_src: imageSrc("sacrificial_fragments-256x256.webp"),
  },
  [WeaponUidEnum.SacrificialGreatsword]: {
    uid: WeaponUidEnum.SacrificialGreatsword,
    name: "Церемониальный двуручный меч",
    image_src: imageSrc("sacrificial_greatsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponUidEnum.SacrificialJade]: {
    uid: WeaponUidEnum.SacrificialJade,
    name: "Жертвенный нефрит",
    quality: 4,
    source: WeaponSource.BattlePass,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.080, 1),
      max_value: numberFormatPercent(0.368, 1),
    },
    image_src: imageSrc("sacrificial_jade-256x256.webp"),
  },
  [WeaponUidEnum.SacrificialSword]: {
    uid: WeaponUidEnum.SacrificialSword,
    name: "Церемониальный меч",
    image_src: imageSrc("sacrificial_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponUidEnum.SapwoodBlade]: {
    uid: WeaponUidEnum.SapwoodBlade,
    name: "Деревянный клинок",
    image_src: imageSrc("sapwood_blade-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponUidEnum.ScionOfTheBlazingSun]: {
    uid: WeaponUidEnum.ScionOfTheBlazingSun,
    name: "Наследник слепящего солнца",
    quality: 4,
    source: WeaponSource.BattlePass,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.040, 1),
      max_value: numberFormatPercent(0.184, 1),
    },
    image_src: imageSrc("scion_of_the_blazing_sun-256x256.webp"),
  },
  [WeaponUidEnum.SequenceOfSolitude]: {
    uid: WeaponUidEnum.SequenceOfSolitude,
    name: "Каденция одиночества",
    quality: 4,
    source: "Событие версии 5.6 «Кружащийся вальс»",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("sequence_of_solitude-256x256.webp"),
  },
  [WeaponUidEnum.SerpentSpine]: {
    uid: WeaponUidEnum.SerpentSpine,
    name: "Меч драконьей кости",
    image_src: imageSrc("serpent_spine-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.SharpshootersOath]: {
    uid: WeaponUidEnum.SharpshootersOath,
    name: "Клятва стрелка",
    quality: 3,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("sharpshooters_oath-256x256.webp"),
  },
  [WeaponUidEnum.SilvershowerHeartstrings]: {
    uid: WeaponUidEnum.SilvershowerHeartstrings,
    name: "Сердечные струны дождя",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("silvershower_heartstrings-256x256.webp"),
  },
  [WeaponUidEnum.SkyriderGreatsword]: {
    uid: WeaponUidEnum.SkyriderGreatsword,
    name: "Большой меч небесного всадника",
    image_src: imageSrc("skyrider_greatsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponUidEnum.SkyriderSword]: {
    uid: WeaponUidEnum.SkyriderSword,
    name: "Меч небесного всадника",
    image_src: imageSrc("skyrider_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponUidEnum.SkywardAtlas]: {
    uid: WeaponUidEnum.SkywardAtlas,
    name: "Небесный атлас",
    quality: 5,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("skyward_atlas-256x256.webp"),
  },
  [WeaponUidEnum.SkywardBlade]: {
    uid: WeaponUidEnum.SkywardBlade,
    name: "Небесный меч",
    image_src: imageSrc("skyward_blade-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponUidEnum.SkywardHarp]: {
    uid: WeaponUidEnum.SkywardHarp,
    name: "Небесное крыло",
    quality: 5,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("skyward_harp-256x256.webp"),
  },
  [WeaponUidEnum.SkywardPride]: {
    uid: WeaponUidEnum.SkywardPride,
    name: "Небесное величие",
    image_src: imageSrc("skyward_pride-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponUidEnum.SkywardSpine]: {
    uid: WeaponUidEnum.SkywardSpine,
    name: "Небесная ось",
    image_src: imageSrc("skyward_spine-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponUidEnum.Slingshot]: {
    uid: WeaponUidEnum.Slingshot,
    name: "Рогатка",
    quality: 3,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("slingshot-256x256.webp"),
  },
  [WeaponUidEnum.SnowTombedStarsilver]: {
    uid: WeaponUidEnum.SnowTombedStarsilver,
    name: "Заснеженное звёздное серебро",
    image_src: imageSrc("snow_tombed_starsilver-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponUidEnum.SolarPearl]: {
    uid: WeaponUidEnum.SolarPearl,
    name: "Солнечная жемчужина",
    quality: 4,
    source: WeaponSource.BattlePass,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("solar_pearl-256x256.webp"),
  },
  [WeaponUidEnum.SongOfBrokenPines]: {
    uid: WeaponUidEnum.SongOfBrokenPines,
    name: "Песнь разбитых сосен",
    image_src: imageSrc("song_of_broken_pines-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_attributes: { uid: AttributeUidEnum.PhysicalDMGBonus, min_value: "4.5%", max_value: "20.7%" },
  },
  [WeaponUidEnum.SongOfStillness]: {
    uid: WeaponUidEnum.SongOfStillness,
    name: "Мелодия покоя",
    quality: 4,
    source: WeaponSource.Forged,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.ATKPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("song_of_stillness-256x256.webp"),
  },
  [WeaponUidEnum.SplendorOfTranquilWaters]: {
    uid: WeaponUidEnum.SplendorOfTranquilWaters,
    name: "Блеск тихих вод",
    image_src: imageSrc("splendor_of_tranquil_waters-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponUidEnum.StaffOfHoma]: {
    uid: WeaponUidEnum.StaffOfHoma,
    name: "Посох Хомы",
    image_src: imageSrc("staff_of_homa-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponUidEnum.StaffOfTheScarletSands]: {
    uid: WeaponUidEnum.StaffOfTheScarletSands,
    name: "Посох алых песков",
    image_src: imageSrc("staff_of_the_scarlet_sands-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponUidEnum.StarcallersWatch]: {
    uid: WeaponUidEnum.StarcallersWatch,
    name: "Бдение взывающего к звёздам",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("starcallers_watch-256x256.webp"),
  },
  [WeaponUidEnum.SturdyBone]: {
    uid: WeaponUidEnum.SturdyBone,
    name: "Крепкая кость",
    image_src: imageSrc("sturdy_bone-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.SummitShaper]: {
    uid: WeaponUidEnum.SummitShaper,
    name: "Кромсатель пиков",
    image_src: imageSrc("summit_shaper-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponUidEnum.SunnyMorningSleepIn]: {
    uid: WeaponUidEnum.SunnyMorningSleepIn,
    name: "Сон солнечным утром",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("sunny_morning_sleep_in-256x256.webp"),
  },
  [WeaponUidEnum.SurfsUp]: {
    uid: WeaponUidEnum.SurfsUp,
    name: "Лови волну",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("surfs_up-256x256.webp"),
  },
  [WeaponUidEnum.SwordOfDescension]: {
    uid: WeaponUidEnum.SwordOfDescension,
    name: "Меч нисхождения",
    image_src: imageSrc("sword_of_descension-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "39", max_value: "440" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponUidEnum.SwordOfNarzissenkreuz]: {
    uid: WeaponUidEnum.SwordOfNarzissenkreuz,
    name: "Меч Нарциссенкрейца",
    image_src: imageSrc("sword_of_narzissenkreuz_pneuma-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.SymphonistOfScents]: {
    uid: WeaponUidEnum.SymphonistOfScents,
    name: "Симфонист ароматов",
    image_src: imageSrc("symphonist_of_scents-256x256.webp"),
    source: "Эксклюзивное оружие Молитвы события",
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
  },
  [WeaponUidEnum.TalkingStick]: {
    uid: WeaponUidEnum.TalkingStick,
    name: "Говорящая палица",
    image_src: imageSrc("talking_stick-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "4%", max_value: "18.4%" },
  },
  [WeaponUidEnum.TamayurateiNoOhanashi]: {
    uid: WeaponUidEnum.TamayurateiNoOhanashi,
    name: "Тамаюратэй но оханаси",
    image_src: imageSrc("tamayuratei_no_ohanashi-256x256.webp"),
    source: "Событие версии 5.4 «Чудесные истории фестиваля Микавы»",
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
  },
  [WeaponUidEnum.TheAlleyFlash]: {
    uid: WeaponUidEnum.TheAlleyFlash,
    name: "Вспышка во тьме",
    image_src: imageSrc("the_alley_flash-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "45", max_value: "620" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "12", max_value: "55" },
  },
  [WeaponUidEnum.TheBell]: {
    uid: WeaponUidEnum.TheBell,
    name: "Меч-колокол",
    image_src: imageSrc("the_bell-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.TheBlackSword]: {
    uid: WeaponUidEnum.TheBlackSword,
    name: "Чёрный меч",
    image_src: imageSrc("the_black_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.TheCatch]: {
    uid: WeaponUidEnum.TheCatch,
    name: "«Улов»",
    image_src: imageSrc("the_catch-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponUidEnum.TheDockhandsAssistant]: {
    uid: WeaponUidEnum.TheDockhandsAssistant,
    name: "Верфь",
    image_src: imageSrc("the_dockhands_assistant-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.HP, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.TheFirstGreatMagic]: {
    uid: WeaponUidEnum.TheFirstGreatMagic,
    name: "Первый великий фокус",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("the_first_great_magic-256x256.webp"),
  },
  [WeaponUidEnum.TheFlute]: {
    uid: WeaponUidEnum.TheFlute,
    name: "Меч-флейта",
    image_src: imageSrc("the_flute-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.TheStringless]: {
    uid: WeaponUidEnum.TheStringless,
    name: "Бесструнный",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("the_stringless-256x256.webp"),
  },
  [WeaponUidEnum.TheUnforged]: {
    uid: WeaponUidEnum.TheUnforged,
    name: "Некованый",
    image_src: imageSrc("the_unforged-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponUidEnum.TheViridescentHunt]: {
    uid: WeaponUidEnum.TheViridescentHunt,
    name: "Зелёный лук",
    quality: 4,
    source: WeaponSource.BattlePass,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("the_viridescent_hunt-256x256.webp"),
  },
  [WeaponUidEnum.TheWidsith]: {
    uid: WeaponUidEnum.TheWidsith,
    name: "Песнь странника",
    quality: 4,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("the_widsith-256x256.webp"),
  },
  [WeaponUidEnum.ThrillingTalesOfDragonSlayers]: {
    uid: WeaponUidEnum.ThrillingTalesOfDragonSlayers,
    name: "Эпос о драконоборцах",
    quality: 3,
    source: WeaponSource.Wish,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_attributes: {
      uid: AttributeUidEnum.HPPercentage,
      min_value: numberFormatPercent(0.077, 1),
      max_value: numberFormatPercent(0.352, 1),
    },
    image_src: imageSrc("thrilling_tales_of_dragon_slayers-256x256.webp"),
  },
  [WeaponUidEnum.ThunderingPulse]: {
    uid: WeaponUidEnum.ThunderingPulse,
    name: "Громовой пульс",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("thundering_pulse-256x256.webp"),
  },
  [WeaponUidEnum.TidalShadow]: {
    uid: WeaponUidEnum.TidalShadow,
    name: "Тень волны",
    image_src: imageSrc("tidal_shadow-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponUidEnum.TomeOfTheEternalFlow]: {
    uid: WeaponUidEnum.TomeOfTheEternalFlow,
    name: "Обряд вечного течения",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("tome_of_the_eternal_flow-256x256.webp"),
  },
  [WeaponUidEnum.ToukabouShigure]: {
    uid: WeaponUidEnum.ToukabouShigure,
    name: "Токабо сигурэ",
    image_src: imageSrc("toukabou_shigure-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponUidEnum.TravelersHandySword]: {
    uid: WeaponUidEnum.TravelersHandySword,
    name: "Меч путешественника",
    image_src: imageSrc("travelers_handy_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 3,
    base_atk: { min_value: "40", max_value: "448" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "6.4%", max_value: "29.3%" },
  },
  [WeaponUidEnum.TulaytullahsRemembrance]: {
    uid: WeaponUidEnum.TulaytullahsRemembrance,
    name: "Воспоминания Тулайтуллы",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("tulaytullahs_remembrance-256x256.webp"),
  },
  [WeaponUidEnum.TwinNephrite]: {
    uid: WeaponUidEnum.TwinNephrite,
    name: "Парный нефрит",
    quality: 3,
    source: WeaponSource.Chests,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITRate,
      min_value: numberFormatPercent(0.034, 1),
      max_value: numberFormatPercent(0.156, 1),
    },
    image_src: imageSrc("twin_nephrite-256x256.webp"),
  },
  [WeaponUidEnum.UltimateOverlordsMegaMagicSword]: {
    uid: WeaponUidEnum.UltimateOverlordsMegaMagicSword,
    name: "«Магический супермеч высшего владыки»",
    image_src: imageSrc("ultimate_overlords_mega_magic_sword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_attributes: { uid: AttributeUidEnum.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponUidEnum.UrakuMisugiri]: {
    uid: WeaponUidEnum.UrakuMisugiri,
    name: "Ураку мисугири",
    image_src: imageSrc("uraku_misugiri-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_attributes: { uid: AttributeUidEnum.CRITDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponUidEnum.Verdict]: {
    uid: WeaponUidEnum.Verdict,
    name: "Вердикт",
    image_src: imageSrc("verdict-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponUidEnum.VividNotions]: {
    uid: WeaponUidEnum.VividNotions,
    name: "Переливающиеся чаяния",
    quality: 5,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_attributes: {
      uid: AttributeUidEnum.CRITDMG,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("vivid_notions-256x256.webp"),
  },
  [WeaponUidEnum.VortexVanquisher]: {
    uid: WeaponUidEnum.VortexVanquisher,
    name: "Покоритель вихря",
    image_src: imageSrc("vortex_vanquisher-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponUidEnum.WanderingEvenstar]: {
    uid: WeaponUidEnum.WanderingEvenstar,
    name: "Скитающаяся звезда",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("wandering_evenstar-256x256.webp"),
  },
  [WeaponUidEnum.WavebreakersFin]: {
    uid: WeaponUidEnum.WavebreakersFin,
    name: "Режущий волны плавник",
    image_src: imageSrc("wavebreakers_fin-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 4,
    base_atk: { min_value: "45", max_value: "620" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "3%", max_value: "13.8%" },
  },
  [WeaponUidEnum.WaveridingWhirl]: {
    uid: WeaponUidEnum.WaveridingWhirl,
    name: "Вихрь на волнах",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.133, 1),
      max_value: numberFormatPercent(0.613, 1),
    },
    image_src: imageSrc("waveriding_whirl-256x256.webp"),
  },
  [WeaponUidEnum.WhiteIronGreatsword]: {
    uid: WeaponUidEnum.WhiteIronGreatsword,
    name: "Меч из белого железа",
    image_src: imageSrc("white_iron_greatsword-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponUidEnum.WhiteTassel]: {
    uid: WeaponUidEnum.WhiteTassel,
    name: "Белая кисть",
    image_src: imageSrc("white_tassel-256x256.png"),
    type_uid: WeaponTypeUidEnum.Polearm,
    quality: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponUidEnum.Whiteblind]: {
    uid: WeaponUidEnum.Whiteblind,
    name: "Белая тень",
    image_src: imageSrc("whiteblind-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.Defense, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponUidEnum.WindblumeOde]: {
    uid: WeaponUidEnum.WindblumeOde,
    name: "Ода анемонии",
    quality: 4,
    source: "Событие версии 1.4 «Приглашение ветряных цветов»",
    type_uid: WeaponTypeUidEnum.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("windblume_ode-256x256.webp"),
  },
  [WeaponUidEnum.WineAndSong]: {
    uid: WeaponUidEnum.WineAndSong,
    name: "Вино и песни",
    quality: 4,
    source: WeaponSource.EventWishExclusive,
    type_uid: WeaponTypeUidEnum.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_attributes: {
      uid: AttributeUidEnum.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("wine_and_song-256x256.webp"),
  },
  [WeaponUidEnum.WolfFang]: {
    uid: WeaponUidEnum.WolfFang,
    name: "Волчий клык",
    image_src: imageSrc("wolf_fang-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.CRITRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponUidEnum.WolfsGravestone]: {
    uid: WeaponUidEnum.WolfsGravestone,
    name: "Волчья погибель",
    image_src: imageSrc("wolfs_gravestone-256x256.png"),
    type_uid: WeaponTypeUidEnum.Claymore,
    quality: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_attributes: { uid: AttributeUidEnum.ATK, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponUidEnum.XiphosMoonlight]: {
    uid: WeaponUidEnum.XiphosMoonlight,
    name: "Лунное сияние ксифоса",
    image_src: imageSrc("xiphos_moonlight-256x256.png"),
    type_uid: WeaponTypeUidEnum.Sword,
    quality: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_attributes: { uid: AttributeUidEnum.ElementalMastery, min_value: "36", max_value: "165" },
  },
} as Record<WeaponUid, Weapon>;
