import { publicImageSrc } from "@/lib/utils";
import { WeaponTypeUidEnum } from "./enums/weapon-types";
import { WeaponUidEnum } from "./enums/weapons";
import type { Weapons } from "./types/weapons";

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`weapons/${src}`);

export const weapons = {
  [WeaponUidEnum.BalladOfTheFjords]: {
    name: "Баллада фьордов",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("ballad_of_the_fjords-256x256.png"),
  },
  [WeaponUidEnum.CalamityOfEshu]: {
    name: "Бедствие Эшу",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("calamity_of_eshu-256x256.png"),
  },
  [WeaponUidEnum.WhiteTassel]: {
    name: "Белая кисть",
    type: WeaponTypeUidEnum.Polearm,
    quality: 3,
    image_src: imageSrc("white_tassel-256x256.png"),
  },
  [WeaponUidEnum.TheStringless]: {
    name: "Бесструнный",
    type: WeaponTypeUidEnum.Bow,
    quality: 4,
    image_src: imageSrc("the_stringless-256x256.png"),
  },
  [WeaponUidEnum.SplendorOfTranquilWaters]: {
    name: "Блеск тихих вод",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("splendor_of_tranquil_waters-256x256.png"),
  },
  [WeaponUidEnum.JadefallsSplendor]: {
    name: "Великолепие лазурного свода",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("jadefalls_splendor-256x256.png"),
  },
  [WeaponUidEnum.TheDockhandsAssistant]: {
    name: "Верфь",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("the_dockhands_assistant-256x256.png"),
  },
  [WeaponUidEnum.EverlastingMoonglow]: {
    name: "Вечное лунное сияние",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("everlasting_moonglow-256x256.png"),
  },
  [WeaponUidEnum.WolfFang]: {
    name: "Волчий клык",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("wolf_fang-256x256.png"),
  },
  [WeaponUidEnum.TulaytullahsRemembrance]: {
    name: "Воспоминания Тулайтуллы",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("tulaytullahs_remembrance-256x256.png"),
  },
  [WeaponUidEnum.FinaleOfTheDeep]: {
    name: "Грандиозный финал глубин",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("finale_of_the_deep-256x256.png"),
  },
  [WeaponUidEnum.DragonsBane]: {
    name: "Гроза драконов",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("dragons_bane-256x256.png"),
  },
  [WeaponUidEnum.SapwoodBlade]: {
    name: "Деревянный клинок",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("sapwood_blade-256x256.png"),
  },
  [WeaponUidEnum.PrimordialJadeCutter]: {
    name: "Драгоценный омут",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("primordial_jade_cutter-256x256.png"),
  },
  [WeaponUidEnum.SacrificialJade]: {
    name: "Жертвенный нефрит",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 4,
    image_src: imageSrc("sacrificial_jade-256x256.png"),
  },
  [WeaponUidEnum.KagurasVerity]: {
    name: "Истина кагура",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("kaguras_verity-256x256.png"),
  },
  [WeaponUidEnum.CashflowSupervision]: {
    name: "Казначейский надзор",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("cashflow_supervision-256x256.png"),
  },
  [WeaponUidEnum.LithicSpear]: {
    name: "Каменное копье",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("lithic_spear-256x256.png"),
  },
  [WeaponUidEnum.KeyOfKhajNisut]: {
    name: "Ключ Хадж-нисут",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("key_of_khaj_nisut-256x256.png"),
  },
  [WeaponUidEnum.RingOfYaxche]: {
    name: "Кольцо Яшче",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 4,
    image_src: imageSrc("ring_of_yaxche-256x256.png"),
  },
  [WeaponUidEnum.MissiveWindspear]: {
    name: "Копьё послания ветров",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("missive_windspear-256x256.png"),
  },
  [WeaponUidEnum.FavoniusLance]: {
    name: "Копьё Фавония",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("favonius_lance-256x256.png"),
  },
  [WeaponUidEnum.SummitShaper]: {
    name: "Кромсатель пиков",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("summit_shaper-256x256.png"),
  },
  [WeaponUidEnum.Azurelight]: {
    name: "Лазурное сияние",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("azurelight-256x256.png"),
  },
  [WeaponUidEnum.SurfsUp]: {
    name: "Лови волну",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("surfs_up-256x256.png"),
  },
  [WeaponUidEnum.XiphosMoonlight]: {
    name: "Лунное сияние ксифоса",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("xiphos_moonlight-256x256.png"),
  },
  [WeaponUidEnum.FavoniusSword]: {
    name: "Меч Фавония",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("favonius_sword-256x256.png"),
  },
  [WeaponUidEnum.LostPrayerToTheSacredWinds]: {
    name: "Молитва святым ветрам",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("lost_prayer_to_the_sacred_winds-256x256.png"),
  },
  [WeaponUidEnum.SkywardSpine]: {
    name: "Небесная ось",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("skyward_spine-256x256.png"),
  },
  [WeaponUidEnum.PrimordialJadeWingedSpear]: {
    name: "Нефритовый коршун",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("primordial_jade_winged_spear-256x256.png"),
  },
  [WeaponUidEnum.TomeOfTheEternalFlow]: {
    name: "Обряд вечного течения",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("tome_of_the_eternal_flow-256x256.png"),
  },
  [WeaponUidEnum.FesteringDesire]: {
    name: "Осквернённое желание",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("festering_desire-256x256.png"),
  },
  [WeaponUidEnum.Absolution]: {
    name: "Отпущение грехов",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("absolution-256x256.png"),
  },
  [WeaponUidEnum.CrimsonMoonsSemblance]: {
    name: "Очертания алой луны",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("crimson_moons_semblance-256x256.png"),
  },
  [WeaponUidEnum.AshGravenDrinkingHorn]: {
    name: "Пепельный рог",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 4,
    image_src: imageSrc("ash_graven_drinking_horn-256x256.png"),
  },
  [WeaponUidEnum.FleuveCendreFerryman]: {
    name: "Перевозчик Флёв Сандр",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("fleuve_cendre_ferryman-256x256.png"),
  },
  [WeaponUidEnum.VividNotions]: {
    name: "Переливающиеся чаяния",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 5,
    image_src: imageSrc("vivid_notions-256x256.png"),
  },
  [WeaponUidEnum.TheWidsith]: {
    name: "Песнь странника",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 4,
    image_src: imageSrc("the_widsith-256x256.png"),
  },
  [WeaponUidEnum.VortexVanquisher]: {
    name: "Покоритель вихря",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("vortex_vanquisher-256x256.png"),
  },
  [WeaponUidEnum.StaffOfTheScarletSands]: {
    name: "Посох алых песков",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("staff_of_the_scarlet_sands-256x256.png"),
  },
  [WeaponUidEnum.StaffOfHoma]: {
    name: "Посох Хомы",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("staff_of_homa-256x256.png"),
  },
  [WeaponUidEnum.HarbingerOfDawn]: {
    name: "Предвестник зари",
    type: WeaponTypeUidEnum.Sword,
    quality: 3,
    image_src: imageSrc("harbinger_of_dawn-256x256.png"),
  },
  [WeaponUidEnum.PrototypeAmber]: {
    name: "Прототип: Янтарь",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 4,
    image_src: imageSrc("prototype_amber-256x256.png"),
  },
  [WeaponUidEnum.MistsplitterReforged]: {
    name: "Рассекающий туман",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("mistsplitter_reforged-512x512.png"),
  },
  [WeaponUidEnum.FlowingPurity]: {
    name: "Сверкание чистых вод",
    type: WeaponTypeUidEnum.Catalyst,
    quality: 4,
    image_src: imageSrc("flowing_purity-256x256.png"),
  },
  [WeaponUidEnum.LightOfFoliarIncision]: {
    name: "Свет лиственного разреза",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("light_of_foliar_incision-256x256.png"),
  },
  [WeaponUidEnum.EngulfingLightning]: {
    name: "Сияющая жатва",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("engulfing_lightning-256x256.png"),
  },
  [WeaponUidEnum.Deathmatch]: {
    name: "Смертельный бой",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("deathmatch-256x256.png"),
  },
  [WeaponUidEnum.TamayurateiNoOhanashi]: {
    name: "Тамаюратэй но оханаси",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("tamayuratei_no_ohanashi-256x256.png"),
  },
  [WeaponUidEnum.UrakuMisugiri]: {
    name: "Ураку мисугири",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("uraku_misugiri-256x256.png"),
  },
  [WeaponUidEnum.CalamityQueller]: {
    name: "Усмиритель бед",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("calamity_queller-256x256.png"),
  },
  [WeaponUidEnum.HaranGeppakuFutsu]: {
    name: "Харан гэппаку фуцу",
    type: WeaponTypeUidEnum.Sword,
    quality: 5,
    image_src: imageSrc("haran_geppaku_futsu-256x256.png"),
  },
  [WeaponUidEnum.SacrificialSword]: {
    name: "Церемониальный меч",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("sacrificial_sword-256x256.png"),
  },
  [WeaponUidEnum.BlackcliffPole]: {
    name: "Черногорская пика",
    type: WeaponTypeUidEnum.Polearm,
    quality: 4,
    image_src: imageSrc("blackcliff_pole-256x256.png"),
  },
  [WeaponUidEnum.BlackcliffLongsword]: {
    name: "Черногорский длинный меч",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("blackcliff_longsword-256x256.png"),
  },
  [WeaponUidEnum.TheBlackSword]: {
    name: "Чёрный меч",
    type: WeaponTypeUidEnum.Sword,
    quality: 4,
    image_src: imageSrc("the_black_sword-256x256.png"),
  },
  [WeaponUidEnum.LumidouceElegy]: {
    name: "Элегия Люмидус",
    type: WeaponTypeUidEnum.Polearm,
    quality: 5,
    image_src: imageSrc("lumidouce_elegy-512x512.png"),
  },
} as Weapons;
