import type { ICharacter } from "./types";
import { CCharacter } from "./classes";
import { CharacterKeys } from "./enums";

export default {
  [CharacterKeys.Albedo]: new CCharacter("Albedo", "Альбедо", 5, "⚔️", "🏔️", "albedo-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.Alhaitham]: new CCharacter("Alhaitham", "Аль-Хайтам", 5, "⚔️", "🌿", "alhaitham-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("LightOfFoliarIncision"),
  [CharacterKeys.Amber]: new CCharacter("Amber", "Эмбер", 4, "🏹", "🔥", "amber-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.AratakiItto]: new CCharacter("AratakiItto", "Итто", 5, "🗡️", "🏔️", "arataki_itto-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("RedhornStonethresher"),
  [CharacterKeys.Arlecchino]: new CCharacter("Arlecchino", "Арлекино", 5, "🔱", "🔥", "arlecchino-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("CrimsonMoonsSemblance"),
  [CharacterKeys.Baizhu]: new CCharacter("Baizhu", "Бай Чжу", 5, "💥", "🌿", "baizhu-256x256.webp").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("JadefallsSplendor"),
  [CharacterKeys.Barbara]: new CCharacter("Barbara", "Барбара", 4, "💥", "💧", "barbara-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Beidou]: new CCharacter("Beidou", "Бэй Доу", 4, "🗡️", "⚡️", "beidou-256x256.webp").setRoleKeys("👥🗡️🛡️"),
  [CharacterKeys.Bennett]: new CCharacter("Bennett", "Беннет", 4, "⚔️", "🔥", "bennett-256x256.webp").setRoleKeys("👥🤝🛡️"),
  [CharacterKeys.Candace]: new CCharacter("Candace", "Кандакия", 4, "🔱", "💧", "candace-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.Charlotte]: new CCharacter("Charlotte", "Шарлотта", 4, "💥", "❄️", "charlotte-256x256.webp").setArkhe("🟡").setRoleKeys("👥🛡️"),
  [CharacterKeys.Chevreuse]: new CCharacter("Chevreuse", "Шеврёз", 4, "🔱", "🔥", "chevreuse-256x256.webp").setArkhe("🟣").setRoleKeys("👥🤝🛡️"),
  [CharacterKeys.Chiori]: new CCharacter("Chiori", "Тиори", 5, "⚔️", "🏔️", "chiori-256x256.webp").setRoleKeys("👥🗡️").setSignatureWeaponKey("UrakuMisugiri"),
  [CharacterKeys.Chongyun]: new CCharacter("Chongyun", "Чун Юнь", 4, "🗡️", "❄️", "chongyun-256x256.webp").setRoleKeys("👥🗡️🤝"),
  [CharacterKeys.Citlali]: new CCharacter("Citlali", "Ситлали", 5, "💥", "❄️", "citlali-256x256.webp").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("StarcallersWatch"),
  [CharacterKeys.Clorinde]: new CCharacter("Clorinde", "Клоринда", 5, "⚔️", "⚡️", "clorinde-256x256.webp").setArkhe("🟣").setRoleKeys("👤🗡️").setSignatureWeaponKey("Absolution"),
  [CharacterKeys.Collei]: new CCharacter("Collei", "Коллеи", 4, "🏹", "🌿", "collei-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.Cyno]: new CCharacter("Cyno", "Сайно", 5, "🔱", "⚡️", "cyno-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("StaffOfTheScarletSands"),
  [CharacterKeys.Dahlia]: new CCharacter("Dahlia", "Далия", 4, "⚔️", "💧", "dahlia-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.Dehya]: new CCharacter("Dehya", "Дэхья", 5, "🗡️", "🔥", "dehya-256x256.webp").setRoleKeys("👥🗡️🛡️").setSignatureWeaponKey("BeaconOfTheReedSea"),
  [CharacterKeys.Diluc]: new CCharacter("Diluc", "Дилюк", 5, "🗡️", "🔥", "diluc-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Diona]: new CCharacter("Diona", "Диона", 4, "🏹", "❄️", "diona-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Dori]: new CCharacter("Dori", "Дори", 4, "🗡️", "⚡️", "dori-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Emilie]: new CCharacter("Emilie", "Эмилия", 5, "🔱", "🌿", "emilie-256x256.webp").setArkhe("🟡").setRoleKeys("👥🗡️").setSignatureWeaponKey("LumidouceElegy"),
  [CharacterKeys.Escoffier]: new CCharacter("Escoffier", "Эскофье", 5, "🔱", "❄️", "escoffier-256x256.webp").setArkhe("🟣").setRoleKeys("👥🗡️🤝🛡️").setSignatureWeaponKey("SymphonistOfScents"),
  [CharacterKeys.Eula]: new CCharacter("Eula", "Эола", 5, "🗡️", "❄️", "eula-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("SongOfBrokenPines"),
  [CharacterKeys.Faruzan]: new CCharacter("Faruzan", "Фарузан", 4, "🏹", "🌪️", "faruzan-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.Fischl]: new CCharacter("Fischl", "Фишль", 4, "🏹", "⚡️", "fischl-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.Freminet]: new CCharacter("Freminet", "Фремине", 4, "🗡️", "❄️", "freminet-256x256.webp").setArkhe("🟡").setRoleKeys("👤🗡️"),
  [CharacterKeys.Furina]: new CCharacter("Furina", "Фурина", 5, "⚔️", "💧", "furina-256x256.webp").setArkhe("🟣🟡").setRoleKeys("👥🗡️🤝🛡️").setSignatureWeaponKey("SplendorOfTranquilWaters"),
  [CharacterKeys.Gaming]: new CCharacter("Gaming", "Ка Мин", 4, "🗡️", "🔥", "gaming-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Ganyu]: new CCharacter("Ganyu", "Гань Юй", 5, "🏹", "❄️", "ganyu-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("AmosBow"),
  [CharacterKeys.Gorou]: new CCharacter("Gorou", "Горо", 4, "🏹", "🏔️", "gorou-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.HuTao]: new CCharacter("HuTao", "Ху Тао", 5, "🔱", "🔥", "hu_tao-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("StaffOfHoma"),
  [CharacterKeys.Iansan]: new CCharacter("Iansan", "Иансан", 4, "🔱", "⚡️", "iansan-256x256.webp").setRoleKeys("👥🤝🛡️"),
  [CharacterKeys.Ineffa]: new CCharacter("Ineffa", "Инеффа", 5, "🔱", "⚡️", "ineffa-256x256.webp").setRoleKeys("👥🗡️🤝🛡️"),
  [CharacterKeys.Jean]: new CCharacter("Jean", "Джинн", 5, "⚔️", "🌪️", "jean-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Kachina]: new CCharacter("Kachina", "Качина", 4, "🔱", "🏔️", "kachina-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.KaedeharaKazuha]: new CCharacter("KaedeharaKazuha", "Кадзуха", 5, "⚔️", "🌪️", "kaedehara_kazuha-256x256.webp").setRoleKeys("👥🤝").setSignatureWeaponKey("FreedomSworn"),
  [CharacterKeys.Kaeya]: new CCharacter("Kaeya", "Кэйа", 3, "⚔️", "❄️", "kaeya-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.KamisatoAyaka]: new CCharacter("KamisatoAyaka", "Аяка", 5, "⚔️", "❄️", "kamisato_ayaka-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("MistsplitterReforged"),
  [CharacterKeys.KamisatoAyato]: new CCharacter("KamisatoAyato", "Аято", 5, "⚔️", "💧", "kamisato_ayato-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("HaranGeppakuFutsu"),
  [CharacterKeys.Kaveh]: new CCharacter("Kaveh", "Кавех", 4, "🗡️", "🌿", "kaveh-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Keqing]: new CCharacter("Keqing", "Кэ Цин", 5, "⚔️", "⚡️", "keqing-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Kinich]: new CCharacter("Kinich", "Кинич", 5, "🗡️", "🌿", "kinich-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("FangOfTheMountainKing"),
  [CharacterKeys.Kirara]: new CCharacter("Kirara", "Кирара", 4, "⚔️", "🌿", "kirara-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Klee]: new CCharacter("Klee", "Кли", 5, "💥", "🔥", "klee-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("LostPrayerToTheSacredWinds"),
  [CharacterKeys.KujouSara]: new CCharacter("KujouSara", "Сара", 4, "🏹", "⚡️", "kujou_sara-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.KukiShinobu]: new CCharacter("KukiShinobu", "Синобу", 4, "⚔️", "⚡️", "kuki_shinobu-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Layla]: new CCharacter("Layla", "Лайла", 4, "⚔️", "❄️", "layla-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Lisa]: new CCharacter("Lisa", "Лиза", 4, "💥", "⚡️", "lisa-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.Lynette]: new CCharacter("Lynette", "Линетт", 4, "⚔️", "🌪️", "lynette-256x256.webp").setArkhe("🟣").setRoleKeys("👥🗡️"),
  [CharacterKeys.Lyney]: new CCharacter("Lyney", "Лини", 5, "🏹", "🔥", "lyney-256x256.webp").setArkhe("🟡").setRoleKeys("👤🗡️").setSignatureWeaponKey("TheFirstGreatMagic"),
  [CharacterKeys.Mavuika]: new CCharacter("Mavuika", "Мавуика", 5, "🗡️", "🔥", "mavuika-256x256.webp").setRoleKeys("👤👥🗡️🤝").setSignatureWeaponKey("AThousandBlazingSuns"),
  [CharacterKeys.Mika]: new CCharacter("Mika", "Мика", 4, "🔱", "❄️", "mika-256x256.webp").setRoleKeys("👥🤝🛡️"),
  [CharacterKeys.Mona]: new CCharacter("Mona", "Мона", 5, "💥", "💧", "mona-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.Mualani]: new CCharacter("Mualani", "Муалани", 5, "💥", "💧", "mualani-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("SurfsUp"),
  [CharacterKeys.Nahida]: new CCharacter("Nahida", "Нахида", 5, "💥", "🌿", "nahida-256x256.webp").setRoleKeys("👥🗡️🤝").setSignatureWeaponKey("AThousandFloatingDreams"),
  [CharacterKeys.Navia]: new CCharacter("Navia", "Навия", 5, "🗡️", "🏔️", "navia-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("Verdict"),
  [CharacterKeys.Neuvillette]: new CCharacter("Neuvillette", "Нёвиллет", 5, "💥", "💧", "neuvillette-256x256.webp").setArkhe("🟡").setRoleKeys("👤🗡️").setSignatureWeaponKey("TomeOfTheEternalFlow"),
  [CharacterKeys.Nilou]: new CCharacter("Nilou", "Нилу", 5, "⚔️", "💧", "nilou-256x256.webp").setRoleKeys("👥🗡️🤝").setSignatureWeaponKey("KeyOfKhajNisut"),
  [CharacterKeys.Ningguang]: new CCharacter("Ningguang", "Нин Гуан", 4, "💥", "🏔️", "ningguang-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Noelle]: new CCharacter("Noelle", "Ноэлль", 4, "🗡️", "🏔️", "noelle-256x256.webp").setRoleKeys("👤🗡️🛡️"),
  [CharacterKeys.Ororon]: new CCharacter("Ororon", "Оророн", 4, "🏹", "⚡️", "ororon-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.Qiqi]: new CCharacter("Qiqi", "Ци Ци", 5, "⚔️", "❄️", "qiqi-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.RaidenShogun]: new CCharacter("RaidenShogun", "Райдэн", 5, "🔱", "⚡️", "raiden_shogun-256x256.webp").setRoleKeys("👤🗡️🤝").setSignatureWeaponKey("EngulfingLightning"),
  [CharacterKeys.Razor]: new CCharacter("Razor", "Рэйзор", 4, "🗡️", "⚡️", "razor-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Rosaria]: new CCharacter("Rosaria", "Розария", 4, "🔱", "❄️", "rosaria-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.SangonomiyaKokomi]: new CCharacter("SangonomiyaKokomi", "Кокоми", 5, "💥", "💧", "sangonomiya_kokomi-256x256.webp").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("EverlastingMoonglow"),
  [CharacterKeys.Sayu]: new CCharacter("Sayu", "Саю", 4, "🗡️", "🌪️", "sayu-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Sethos]: new CCharacter("Sethos", "Сетос", 4, "🏹", "⚡️", "sethos-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Shenhe]: new CCharacter("Shenhe", "Шэнь Хэ", 5, "🔱", "❄️", "shenhe-256x256.webp").setRoleKeys("👥🤝").setSignatureWeaponKey("CalamityQueller"),
  [CharacterKeys.ShikanoinHeizou]: new CCharacter("ShikanoinHeizou", "Хэйдзо", 4, "💥", "🌪️", "shikanoin_heizou-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Sigewinne]: new CCharacter("Sigewinne", "Сиджвин", 5, "🏹", "💧", "sigewinne-256x256.webp").setArkhe("🟣").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("SilvershowerHeartstrings"),
  [CharacterKeys.Skirk]: new CCharacter("Skirk", "Скирк", 5, "⚔️", "❄️", "skirk-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("Azurelight"),
  [CharacterKeys.Sucrose]: new CCharacter("Sucrose", "Сахароза", 4, "💥", "🌪️", "sucrose-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.Tartaglia]: new CCharacter("Tartaglia", "Тарталья", 5, "🏹", "💧", "tartaglia-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("PolarStar"),
  [CharacterKeys.Thoma]: new CCharacter("Thoma", "Тома", 4, "🔱", "🔥", "thoma-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Tighnari]: new CCharacter("Tighnari", "Тигнари", 5, "🏹", "🌿", "tighnari-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("HuntersPath"),
  [CharacterKeys["Traveler🌪️"]]: new CCharacter("Traveler🌪️", "Путешественник (Анемо)", 5, "⚔️", "🌪️", "traveler-256x256.gif"),
  [CharacterKeys["Traveler🌿"]]: new CCharacter("Traveler🌿", "Путешественник (Дендро)", 5, "⚔️", "🌿", "traveler-256x256.gif"),
  [CharacterKeys["Traveler⚡️"]]: new CCharacter("Traveler⚡️", "Путешественник (Электро)", 5, "⚔️", "⚡️", "traveler-256x256.gif"),
  [CharacterKeys["Traveler🏔️"]]: new CCharacter("Traveler🏔️", "Путешественник (Гео)", 5, "⚔️", "🏔️", "traveler-256x256.gif"),
  [CharacterKeys["Traveler💧"]]: new CCharacter("Traveler💧", "Путешественник (Гидро)", 5, "⚔️", "💧", "traveler-256x256.gif").setArkhe("🟡"),
  [CharacterKeys["Traveler🔥"]]: new CCharacter("Traveler🔥", "Путешественник (Пиро)", 5, "⚔️", "🔥", "traveler-256x256.gif"),
  [CharacterKeys.Varesa]: new CCharacter("Varesa", "Вареса", 5, "💥", "⚡️", "varesa-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("VividNotions"),
  [CharacterKeys.Venti]: new CCharacter("Venti", "Венти", 5, "🏹", "🌪️", "venti-256x256.webp").setRoleKeys("👥🗡️🤝").setSignatureWeaponKey("ElegyForTheEnd"),
  [CharacterKeys.Wanderer]: new CCharacter("Wanderer", "Странник", 5, "💥", "🌪️", "wanderer-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("TulaytullahsRemembrance"),
  [CharacterKeys.Wriothesley]: new CCharacter("Wriothesley", "Ризли", 5, "💥", "❄️", "wriothesley-256x256.webp").setArkhe("🟣").setRoleKeys("👤🗡️").setSignatureWeaponKey("CashflowSupervision"),
  [CharacterKeys.Xiangling]: new CCharacter("Xiangling", "Сян Лин", 4, "🔱", "🔥", "xiangling-256x256.webp").setRoleKeys("👥🗡️"),
  [CharacterKeys.Xianyun]: new CCharacter("Xianyun", "Сянь Юнь", 5, "💥", "🌪️", "xianyun-256x256.webp").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("CranesEchoingCall"),
  [CharacterKeys.Xiao]: new CCharacter("Xiao", "Сяо", 5, "🔱", "🌪️", "xiao-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("PrimordialJadeWingedSpear"),
  [CharacterKeys.Xilonen]: new CCharacter("Xilonen", "Шилонен", 5, "⚔️", "🏔️", "xilonen-256x256.webp").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("PeakPatrolSong"),
  [CharacterKeys.Xingqiu]: new CCharacter("Xingqiu", "Син Цю", 4, "⚔️", "💧", "xingqiu-256x256.webp").setRoleKeys("👥🗡️🛡️"),
  [CharacterKeys.Xinyan]: new CCharacter("Xinyan", "Синь Янь", 4, "🗡️", "🔥", "xinyan-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.YaeMiko]: new CCharacter("YaeMiko", "Яэ Мико", 5, "💥", "⚡️", "yae_miko-256x256.webp").setRoleKeys("👥🗡️").setSignatureWeaponKey("KagurasVerity"),
  [CharacterKeys.Yanfei]: new CCharacter("Yanfei", "Янь Фэй", 4, "💥", "🔥", "yanfei-256x256.webp").setRoleKeys("👤🗡️"),
  [CharacterKeys.Yaoyao]: new CCharacter("Yaoyao", "Яо Яо", 4, "🔱", "🌿", "yaoyao-256x256.webp").setRoleKeys("👥🛡️"),
  [CharacterKeys.Yelan]: new CCharacter("Yelan", "Е Лань", 5, "🏹", "💧", "yelan-256x256.webp").setRoleKeys("👥🗡️").setSignatureWeaponKey("AquaSimulacra"),
  [CharacterKeys.Yoimiya]: new CCharacter("Yoimiya", "Ёимия", 5, "🏹", "🔥", "yoimiya-256x256.webp").setRoleKeys("👤🗡️").setSignatureWeaponKey("ThunderingPulse"),
  [CharacterKeys.YunJin]: new CCharacter("YunJin", "Юнь Цзинь", 4, "🔱", "🏔️", "yun_jin-256x256.webp").setRoleKeys("👥🤝"),
  [CharacterKeys.Zhongli]: new CCharacter("Zhongli", "Чжун Ли", 5, "🔱", "🏔️", "zhongli-256x256.webp").setRoleKeys("👥🤝🛡️").setSignatureWeaponKey("VortexVanquisher"),
} as Record<ICharacter["key"], ICharacter>;
