import type { ICharacter } from "./types";
import { CCharacter } from "./classes";
import { CharacterKeys } from "./enums";
import { CharacterRoleKeys } from "../character-roles/enums";
import { ElementKeys } from "../elements/enums";
import { WeaponKeys } from "../weapons/enums";
import { WeaponTypeKeys } from "../weapon-types/enums";

export default {
  [CharacterKeys.Albedo]: CCharacter.init([
    CharacterKeys.Albedo,
    "Альбедо",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "albedo-256x256.webp",
  ]),
  [CharacterKeys.Alhaitham]: CCharacter.init([
    CharacterKeys.Alhaitham,
    "Аль-Хайтам",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "alhaitham-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.LightOfFoliarIncision),
  [CharacterKeys.Amber]: CCharacter.init([
    CharacterKeys.Amber,
    "Эмбер",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "amber-256x256.webp",
  ]),
  [CharacterKeys.AratakiItto]: CCharacter.init([
    CharacterKeys.AratakiItto,
    "Итто",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "arataki_itto-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.RedhornStonethresher),
  [CharacterKeys.Arlecchino]: CCharacter.init([
    CharacterKeys.Arlecchino,
    "Арлекино", 5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "arlecchino-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.CrimsonMoonsSemblance),
  [CharacterKeys.Baizhu]: CCharacter.init([
    CharacterKeys.Baizhu,
    "Бай Чжу",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Dendro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "baizhu-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.JadefallsSplendor),
  [CharacterKeys.Barbara]: CCharacter.init([
    CharacterKeys.Barbara,
    "Барбара", 4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Hydro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "barbara-256x256.webp",
  ]),
  [CharacterKeys.Beidou]: CCharacter.init([
    CharacterKeys.Beidou,
    "Бэй Доу",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "beidou-256x256.webp",
  ]),
  [CharacterKeys.Bennett]: CCharacter.init([
    CharacterKeys.Bennett,
    "Беннет",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Pyro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "bennett-256x256.webp",
  ]),
  [CharacterKeys.Candace]: CCharacter.init([
    CharacterKeys.Candace,
    "Кандакия",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Hydro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "candace-256x256.webp",
  ]),
  [CharacterKeys.Charlotte]: CCharacter.init([
    CharacterKeys.Charlotte,
    "Шарлотта",
    4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "charlotte-256x256.webp",
  ]).setArkhe("🟡"),
  [CharacterKeys.Chevreuse]: CCharacter.init([
    CharacterKeys.Chevreuse,
    "Шеврёз",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Pyro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "chevreuse-256x256.webp",
  ]).setArkhe("🟣"),
  [CharacterKeys.Chiori]: CCharacter.init([
    CharacterKeys.Chiori,
    "Тиори",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "chiori-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.UrakuMisugiri),
  [CharacterKeys.Chongyun]: CCharacter.init([
    CharacterKeys.Chongyun,
    "Чун Юнь",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "chongyun-256x256.webp",
  ]),
  [CharacterKeys.Citlali]: CCharacter.init([
    CharacterKeys.Citlali,
    "Ситлали",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "citlali-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.StarcallersWatch),
  [CharacterKeys.Clorinde]: CCharacter.init([
    CharacterKeys.Clorinde,
    "Клоринда",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "clorinde-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponKey(WeaponKeys.Absolution),
  [CharacterKeys.Collei]: CCharacter.init([
    CharacterKeys.Collei,
    "Коллеи",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "collei-256x256.webp",
  ]),
  [CharacterKeys.Cyno]: CCharacter.init([
    CharacterKeys.Cyno,
    "Сайно", 5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "cyno-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.StaffOfTheScarletSands),
  [CharacterKeys.Dahlia]: CCharacter.init([
    CharacterKeys.Dahlia,
    "Далия",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Hydro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "dahlia-256x256.webp",
  ]),
  [CharacterKeys.Dehya]: CCharacter.init([
    CharacterKeys.Dehya,
    "Дэхья",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "dehya-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.BeaconOfTheReedSea),
  [CharacterKeys.Diluc]: CCharacter.init([
    CharacterKeys.Diluc,
    "Дилюк",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "diluc-256x256.webp",
  ]),
  [CharacterKeys.Diona]: CCharacter.init([
    CharacterKeys.Diona,
    "Диона",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "diona-256x256.webp",
  ]),
  [CharacterKeys.Dori]: CCharacter.init([
    CharacterKeys.Dori,
    "Дори",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Electro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "dori-256x256.webp",
  ]),
  [CharacterKeys.Emilie]: CCharacter.init([
    CharacterKeys.Emilie,
    "Эмилия",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "emilie-256x256.webp",
  ]).setArkhe("🟡").setSignatureWeaponKey(WeaponKeys.LumidouceElegy),
  [CharacterKeys.Escoffier]: CCharacter.init([
    CharacterKeys.Escoffier,
    "Эскофье",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "escoffier-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponKey(WeaponKeys.SymphonistOfScents),
  [CharacterKeys.Eula]: CCharacter.init([
    CharacterKeys.Eula,
    "Эола",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "eula-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.SongOfBrokenPines),
  [CharacterKeys.Faruzan]: CCharacter.init([
    CharacterKeys.Faruzan,
    "Фарузан",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Anemo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "faruzan-256x256.webp",
  ]),
  [CharacterKeys.Fischl]: CCharacter.init([
    CharacterKeys.Fischl,
    "Фишль",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "fischl-256x256.webp",
  ]),
  [CharacterKeys.Freminet]: CCharacter.init([
    CharacterKeys.Freminet,
    "Фремине",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "freminet-256x256.webp",
  ]).setArkhe("🟡"),
  [CharacterKeys.Furina]: CCharacter.init([
    CharacterKeys.Furina,
    "Фурина",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "furina-256x256.webp",
  ]).setArkhe("🟣🟡").setSignatureWeaponKey(WeaponKeys.SplendorOfTranquilWaters),
  [CharacterKeys.Gaming]: CCharacter.init([
    CharacterKeys.Gaming,
    "Ка Мин",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "gaming-256x256.webp",
  ]),
  [CharacterKeys.Ganyu]: CCharacter.init([
    CharacterKeys.Ganyu,
    "Гань Юй",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "ganyu-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.AmosBow),
  [CharacterKeys.Gorou]: CCharacter.init([
    CharacterKeys.Gorou,
    "Горо",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Geo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "gorou-256x256.webp",
  ]),
  [CharacterKeys.HuTao]: CCharacter.init([
    CharacterKeys.HuTao,
    "Ху Тао",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "hu_tao-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.StaffOfHoma),
  [CharacterKeys.Iansan]: CCharacter.init([
    CharacterKeys.Iansan,
    "Иансан",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Electro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "iansan-256x256.webp",
  ]),
  [CharacterKeys.Ineffa]: CCharacter.init([
    CharacterKeys.Ineffa,
    "Инеффа",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "ineffa-256x256.webp",
  ]),
  [CharacterKeys.Jean]: CCharacter.init([
    CharacterKeys.Jean,
    "Джинн",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Anemo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "jean-256x256.webp",
  ]),
  [CharacterKeys.Kachina]: CCharacter.init([
    CharacterKeys.Kachina,
    "Качина",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "kachina-256x256.webp",
  ]),
  [CharacterKeys.KaedeharaKazuha]: CCharacter.init([
    CharacterKeys.KaedeharaKazuha,
    "Кадзуха",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Anemo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "kaedehara_kazuha-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.FreedomSworn),
  [CharacterKeys.Kaeya]: CCharacter.init([
    CharacterKeys.Kaeya,
    "Кэйа",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "kaeya-256x256.webp",
  ]),
  [CharacterKeys.KamisatoAyaka]: CCharacter.init([
    CharacterKeys.KamisatoAyaka,
    "Аяка",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "kamisato_ayaka-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.MistsplitterReforged),
  [CharacterKeys.KamisatoAyato]: CCharacter.init([
    CharacterKeys.KamisatoAyato,
    "Аято",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "kamisato_ayato-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.HaranGeppakuFutsu),
  [CharacterKeys.Kaveh]: CCharacter.init([
    CharacterKeys.Kaveh,
    "Кавех",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "kaveh-256x256.webp",
  ]),
  [CharacterKeys.Keqing]: CCharacter.init([
    CharacterKeys.Keqing,
    "Кэ Цин",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "keqing-256x256.webp",
  ]),
  [CharacterKeys.Kinich]: CCharacter.init([
    CharacterKeys.Kinich,
    "Кинич",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "kinich-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.FangOfTheMountainKing),
  [CharacterKeys.Kirara]: CCharacter.init([
    CharacterKeys.Kirara,
    "Кирара",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Dendro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "kirara-256x256.webp",
  ]),
  [CharacterKeys.Klee]: CCharacter.init([
    CharacterKeys.Klee,
    "Кли",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "klee-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.LostPrayerToTheSacredWinds),
  [CharacterKeys.KujouSara]: CCharacter.init([
    CharacterKeys.KujouSara,
    "Сара",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Electro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "kujou_sara-256x256.webp",
  ]),
  [CharacterKeys.KukiShinobu]: CCharacter.init([
    CharacterKeys.KukiShinobu,
    "Синобу",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Electro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "kuki_shinobu-256x256.webp",
  ]),
  [CharacterKeys.Layla]: CCharacter.init([
    CharacterKeys.Layla,
    "Лайла",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "layla-256x256.webp",
  ]),
  [CharacterKeys.Lisa]: CCharacter.init([
    CharacterKeys.Lisa,
    "Лиза",
    4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "lisa-256x256.webp",
  ]),
  [CharacterKeys.Lynette]: CCharacter.init([
    CharacterKeys.Lynette,
    "Линетт",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Anemo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "lynette-256x256.webp",
  ]).setArkhe("🟣"),
  [CharacterKeys.Lyney]: CCharacter.init([
    CharacterKeys.Lyney,
    "Лини",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "lyney-256x256.webp",
  ]).setArkhe("🟡").setSignatureWeaponKey(WeaponKeys.TheFirstGreatMagic),
  [CharacterKeys.Mavuika]: CCharacter.init([
    CharacterKeys.Mavuika,
    "Мавуика",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.OnField, CharacterRoleKeys.Support],
    "mavuika-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.AThousandBlazingSuns),
  [CharacterKeys.Mika]: CCharacter.init([
    CharacterKeys.Mika,
    "Мика",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "mika-256x256.webp",
  ]),
  [CharacterKeys.Mona]: CCharacter.init([
    CharacterKeys.Mona,
    "Мона",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Hydro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "mona-256x256.webp",
  ]),
  [CharacterKeys.Mualani]: CCharacter.init([
    CharacterKeys.Mualani,
    "Муалани",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "mualani-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.SurfsUp),
  [CharacterKeys.Nahida]: CCharacter.init([
    CharacterKeys.Nahida,
    "Нахида",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "nahida-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.AThousandFloatingDreams),
  [CharacterKeys.Navia]: CCharacter.init([
    CharacterKeys.Navia,
    "Навия",
    5,
    WeaponTypeKeys.Claymore,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "navia-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.Verdict),
  [CharacterKeys.Neuvillette]: CCharacter.init([
    CharacterKeys.Neuvillette,
    "Нёвиллет",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "neuvillette-256x256.webp",
  ]).setArkhe("🟡").setSignatureWeaponKey(WeaponKeys.TomeOfTheEternalFlow),
  [CharacterKeys.Nilou]: CCharacter.init([
    CharacterKeys.Nilou,
    "Нилу",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "nilou-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.KeyOfKhajNisut),
  [CharacterKeys.Ningguang]: CCharacter.init([
    CharacterKeys.Ningguang,
    "Нин Гуан",
    4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "ningguang-256x256.webp",
  ]),
  [CharacterKeys.Noelle]: CCharacter.init([
    CharacterKeys.Noelle,
    "Ноэлль",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Geo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField, CharacterRoleKeys.Survivability],
    "noelle-256x256.webp",
  ]),
  [CharacterKeys.Ororon]: CCharacter.init([
    CharacterKeys.Ororon,
    "Оророн",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "ororon-256x256.webp",
  ]),
  [CharacterKeys.Qiqi]: CCharacter.init([
    CharacterKeys.Qiqi,
    "Ци Ци",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "qiqi-256x256.webp",
  ]),
  [CharacterKeys.RaidenShogun]: CCharacter.init([
    CharacterKeys.RaidenShogun,
    "Райдэн",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField, CharacterRoleKeys.Support],
    "raiden_shogun-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.EngulfingLightning),
  [CharacterKeys.Razor]: CCharacter.init([
    CharacterKeys.Razor,
    "Рэйзор",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "razor-256x256.webp",
  ]),
  [CharacterKeys.Rosaria]: CCharacter.init([
    CharacterKeys.Rosaria,
    "Розария",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "rosaria-256x256.webp",
  ]),
  [CharacterKeys.SangonomiyaKokomi]: CCharacter.init([
    CharacterKeys.SangonomiyaKokomi,
    "Кокоми",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Hydro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "sangonomiya_kokomi-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.EverlastingMoonglow),
  [CharacterKeys.Sayu]: CCharacter.init([
    CharacterKeys.Sayu,
    "Саю",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Anemo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "sayu-256x256.webp",
  ]),
  [CharacterKeys.Sethos]: CCharacter.init([
    CharacterKeys.Sethos,
    "Сетос",
    4,
    WeaponTypeKeys.Bow,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "sethos-256x256.webp",
  ]),
  [CharacterKeys.Shenhe]: CCharacter.init([
    CharacterKeys.Shenhe,
    "Шэнь Хэ",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Cryo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "shenhe-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.CalamityQueller),
  [CharacterKeys.ShikanoinHeizou]: CCharacter.init([
    CharacterKeys.ShikanoinHeizou,
    "Хэйдзо",
    4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Anemo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "shikanoin_heizou-256x256.webp",
  ]),
  [CharacterKeys.Sigewinne]: CCharacter.init([
    CharacterKeys.Sigewinne,
    "Сиджвин",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Hydro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "sigewinne-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponKey(WeaponKeys.SilvershowerHeartstrings),
  [CharacterKeys.Skirk]: CCharacter.init([
    CharacterKeys.Skirk,
    "Скирк",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "skirk-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.Azurelight),
  [CharacterKeys.Sucrose]: CCharacter.init([
    CharacterKeys.Sucrose,
    "Сахароза",
    4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Anemo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "sucrose-256x256.webp",
  ]),
  [CharacterKeys.Tartaglia]: CCharacter.init([
    CharacterKeys.Tartaglia,
    "Тарталья",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "tartaglia-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.PolarStar),
  [CharacterKeys.Thoma]: CCharacter.init([
    CharacterKeys.Thoma,
    "Тома",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Pyro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "thoma-256x256.webp",
  ]),
  [CharacterKeys.Tighnari]: CCharacter.init([
    CharacterKeys.Tighnari,
    "Тигнари",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Dendro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "tighnari-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.HuntersPath),
  [CharacterKeys.TravelerAnemo]: CCharacter.init([
    CharacterKeys.TravelerAnemo,
    "Путешественник (Анемо)",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Anemo,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterKeys.TravelerDendro]: CCharacter.init([
    CharacterKeys.TravelerDendro,
    "Путешественник (Дендро)",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Dendro,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterKeys.TravelerElectro]: CCharacter.init([
    CharacterKeys.TravelerElectro,
    "Путешественник (Электро)",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Electro,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterKeys.TravelerGeo]: CCharacter.init([
    CharacterKeys.TravelerGeo,
    "Путешественник (Гео)",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Geo,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterKeys.TravelerHydro]: CCharacter.init([
    CharacterKeys.TravelerHydro,
    "Путешественник (Гидро)",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Hydro,
    undefined,
    "traveler-256x256.gif",
  ]).setArkhe("🟡"),
  [CharacterKeys.TravelerPyro]: CCharacter.init([
    CharacterKeys.TravelerPyro,
    "Путешественник (Пиро)",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Pyro,
    undefined,
    "traveler-256x256.gif",
  ]),
  [CharacterKeys.Varesa]: CCharacter.init([
    CharacterKeys.Varesa,
    "Вареса",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "varesa-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.VividNotions),
  [CharacterKeys.Venti]: CCharacter.init([
    CharacterKeys.Venti,
    "Венти",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Anemo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "venti-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.ElegyForTheEnd),
  [CharacterKeys.Wanderer]: CCharacter.init([
    CharacterKeys.Wanderer,
    "Странник",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Anemo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "wanderer-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.TulaytullahsRemembrance),
  [CharacterKeys.Wriothesley]: CCharacter.init([
    CharacterKeys.Wriothesley,
    "Ризли",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Cryo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "wriothesley-256x256.webp",
  ]).setArkhe("🟣").setSignatureWeaponKey(WeaponKeys.CashflowSupervision),
  [CharacterKeys.Xiangling]: CCharacter.init([
    CharacterKeys.Xiangling,
    "Сян Лин",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "xiangling-256x256.webp",
  ]),
  [CharacterKeys.Xianyun]: CCharacter.init([
    CharacterKeys.Xianyun,
    "Сянь Юнь",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Anemo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "xianyun-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.CranesEchoingCall),
  [CharacterKeys.Xiao]: CCharacter.init([
    CharacterKeys.Xiao,
    "Сяо",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Anemo,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "xiao-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.PrimordialJadeWingedSpear),
  [CharacterKeys.Xilonen]: CCharacter.init([
    CharacterKeys.Xilonen,
    "Шилонен",
    5,
    WeaponTypeKeys.Sword,
    ElementKeys.Geo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "xilonen-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.PeakPatrolSong),
  [CharacterKeys.Xingqiu]: CCharacter.init([
    CharacterKeys.Xingqiu,
    "Син Цю",
    4,
    WeaponTypeKeys.Sword,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "xingqiu-256x256.webp",
  ]),
  [CharacterKeys.Xinyan]: CCharacter.init([
    CharacterKeys.Xinyan,
    "Синь Янь",
    4,
    WeaponTypeKeys.Claymore,
    ElementKeys.Pyro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "xinyan-256x256.webp",
  ]),
  [CharacterKeys.YaeMiko]: CCharacter.init([
    CharacterKeys.YaeMiko,
    "Яэ Мико",
    5,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Electro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "yae_miko-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.KagurasVerity),
  [CharacterKeys.Yanfei]: CCharacter.init([
    CharacterKeys.Yanfei,
    "Янь Фэй",
    4,
    WeaponTypeKeys.Catalyst,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "yanfei-256x256.webp",
  ]),
  [CharacterKeys.Yaoyao]: CCharacter.init([
    CharacterKeys.Yaoyao,
    "Яо Яо",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Dendro,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Survivability],
    "yaoyao-256x256.webp",
  ]),
  [CharacterKeys.Yelan]: CCharacter.init([
    CharacterKeys.Yelan,
    "Е Лань",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Hydro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OffField],
    "yelan-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.AquaSimulacra),
  [CharacterKeys.Yoimiya]: CCharacter.init([
    CharacterKeys.Yoimiya,
    "Ёимия",
    5,
    WeaponTypeKeys.Bow,
    ElementKeys.Pyro,
    [CharacterRoleKeys.Dps, CharacterRoleKeys.OnField],
    "yoimiya-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.ThunderingPulse),
  [CharacterKeys.YunJin]: CCharacter.init([
    CharacterKeys.YunJin,
    "Юнь Цзинь",
    4,
    WeaponTypeKeys.Polearm,
    ElementKeys.Geo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support],
    "yun_jin-256x256.webp",
  ]),
  [CharacterKeys.Zhongli]: CCharacter.init([
    CharacterKeys.Zhongli,
    "Чжун Ли",
    5,
    WeaponTypeKeys.Polearm,
    ElementKeys.Geo,
    [CharacterRoleKeys.OffField, CharacterRoleKeys.Support, CharacterRoleKeys.Survivability],
    "zhongli-256x256.webp",
  ]).setSignatureWeaponKey(WeaponKeys.VortexVanquisher),
} as Record<ICharacter["key"], ICharacter>;
