import { ElementKeys } from "../enums/element";

export const CharacterKeys = {
  /* Альбедо                  */ "Albedo": "albedo",
  /* Аль-Хайтам               */ "Alhaitham": "alhaitham",
  /* Эмбер                    */ "Amber": "amber",
  /* Итто                     */ "AratakiItto": "arataki_itto",
  /* Арлекино                 */ "Arlecchino": "arlecchino",
  /* Бай Чжу                  */ "Baizhu": "baizhu",
  /* Барбара                  */ "Barbara": "barbara",
  /* Бэй Доу                  */ "Beidou": "beidou",
  /* Беннет                   */ "Bennett": "bennett",
  /* Кандакия                 */ "Candace": "candace",
  /* Шарлотта                 */ "Charlotte": "charlotte",
  /* Шеврёз                   */ "Chevreuse": "chevreuse",
  /* Тиори                    */ "Chiori": "chiori",
  /* Чун Юнь                  */ "Chongyun": "chongyun",
  /* Ситлали                  */ "Citlali": "citlali",
  /* Клоринда                 */ "Clorinde": "clorinde",
  /* Коллеи                   */ "Collei": "collei",
  /* Сайно                    */ "Cyno": "cyno",
  /* Далия                    */ "Dahlia": "dahlia",
  /* Дэхья                    */ "Dehya": "dehya",
  /* Дилюк                    */ "Diluc": "diluc",
  /* Диона                    */ "Diona": "diona",
  /* Дори                     */ "Dori": "dori",
  /* Эмилия                   */ "Emilie": "emilie",
  /* Эскофье                  */ "Escoffier": "Escoffier",
  /* Эола                     */ "Eula": "eula",
  /* Фарузан                  */ "Faruzan": "faruzan",
  /* Фишль                    */ "Fischl": "fischl",
  /* Фремине                  */ "Freminet": "freminet",
  /* Фурина                   */ "Furina": "furina",
  /* Ка Мин                   */ "Gaming": "gaming",
  /* Гань Юй                  */ "Ganyu": "ganyu",
  /* Горо                     */ "Gorou": "gorou",
  /* Ху Тао                   */ "HuTao": "hu_tao",
  /* Иансан                   */ "Iansan": "iansan",
  /* Инеффа                   */ "Ineffa": "ineffa",
  /* Джинн                    */ "Jean": "jean",
  /* Качина                   */ "Kachina": "kachina",
  /* Кадзуха                  */ "KaedeharaKazuha": "kaedehara_kazuha",
  /* Кэйа                     */ "Kaeya": "kaeya",
  /* Аяка                     */ "KamisatoAyaka": "kamisato_ayaka",
  /* Аято                     */ "KamisatoAyato": "kamisato_ayato",
  /* Кавех                    */ "Kaveh": "kaveh",
  /* Кэ Цин                   */ "Keqing": "keqing",
  /* Кинич                    */ "Kinich": "kinich",
  /* Кирара                   */ "Kirara": "kirara",
  /* Кли                      */ "Klee": "klee",
  /* Сара                     */ "KujouSara": "kujou_sara",
  /* Синобу                   */ "KukiShinobu": "kuki_shinobu",
  /* Лайла                    */ "Layla": "layla",
  /* Лиза                     */ "Lisa": "lisa",
  /* Линетт                   */ "Lynette": "lynette",
  /* Лини                     */ "Lyney": "lyney",
  /* Мавуика                  */ "Mavuika": "mavuika",
  /* Мика                     */ "Mika": "mika",
  /* Мона                     */ "Mona": "mona",
  /* Муалани                  */ "Mualani": "mualani",
  /* Нахида                   */ "Nahida": "nahida",
  /* Навия                    */ "Navia": "navia",
  /* Нёвиллет                 */ "Neuvillette": "neuvillette",
  /* Нилу                     */ "Nilou": "nilou",
  /* Нин Гуан                 */ "Ningguang": "ningguang",
  /* Ноэлль                   */ "Noelle": "noelle",
  /* Оророн                   */ "Ororon": "ororon",
  /* Ци Ци                    */ "Qiqi": "qiqi",
  /* Райдэн                   */ "RaidenShogun": "raiden_shogun",
  /* Рэйзор                   */ "Razor": "razor",
  /* Розария                  */ "Rosaria": "rosaria",
  /* Кокоми                   */ "SangonomiyaKokomi": "sangonomiya_kokomi",
  /* Саю                      */ "Sayu": "sayu",
  /* Сетос                    */ "Sethos": "sethos",
  /* Шэнь Хэ                  */ "Shenhe": "shenhe",
  /* Хэйдзо                   */ "ShikanoinHeizou": "shikanoin_heizou",
  /* Сиджвин                  */ "Sigewinne": "sigewinne",
  /* Скирк                    */ "Skirk": "Skirk",
  /* Сахароза                 */ "Sucrose": "sucrose",
  /* Тарталья                 */ "Tartaglia": "tartaglia",
  /* Тома                     */ "Thoma": "thoma",
  /* Тигнари                  */ "Tighnari": "tighnari",
  /* Путешественник (Анемо)   */ "Traveler🌪️": `traveler_${ElementKeys["🌪️"]}`,
  /* Путешественник (Дендро)  */ "Traveler🌿": `traveler_${ElementKeys["🌿"]}`,
  /* Путешественник (Электро) */ "Traveler⚡️": `traveler_${ElementKeys["⚡️"]}`,
  /* Путешественник (Гео)     */ "Traveler🏔️": `traveler_${ElementKeys["🏔️"]}`,
  /* Путешественник (Гидро)   */ "Traveler💧": `traveler_${ElementKeys["💧"]}`,
  /* Путешественник (Пиро)    */ "Traveler🔥": `traveler_${ElementKeys["🔥"]}`,
  /* Вареса                   */ "Varesa": "varesa",
  /* Венти                    */ "Venti": "venti",
  /* Странник                 */ "Wanderer": "wanderer",
  /* Ризли                    */ "Wriothesley": "wriothesley",
  /* Сян Лин                  */ "Xiangling": "xiangling",
  /* Сянь Юнь                 */ "Xianyun": "xianyun",
  /* Сяо                      */ "Xiao": "xiao",
  /* Шилонен                  */ "Xilonen": "Xilonen",
  /* Син Цю                   */ "Xingqiu": "xingqiu",
  /* Синь Янь                 */ "Xinyan": "xinyan",
  /* Яэ Мико                  */ "YaeMiko": "yae_miko",
  /* Янь Фэй                  */ "Yanfei": "yanfei",
  /* Яо Яо                    */ "Yaoyao": "yaoyao",
  /* Е Лань                   */ "Yelan": "yelan",
  /* Ёимия                    */ "Yoimiya": "yoimiya",
  /* Юнь Цзинь                */ "YunJin": "yun_jin",
  /* Чжун Ли                  */ "Zhongli": "zhongli",
} as const;
