import type { Weapon } from "./types";
import { numberFormatPercent, publicImageSrc } from "@/lib/utils";
import { StatIds } from "../stats/enums";
import { WeaponIds } from "./enums";
import { WeaponTypeIds } from "../weapon-types/enums";

class WeaponClass implements Weapon {
  readonly id: Weapon["id"];
  readonly name: Weapon["name"];
  readonly rarity: Weapon["rarity"];
  readonly source: Weapon["source"];
  readonly type_id: Weapon["type_id"];
  readonly base_atk: Weapon["base_atk"];
  readonly secondary_stats: Weapon["secondary_stats"];
  readonly image_src: Weapon["image_src"];

  static PATH = "weapons";

  constructor(
    id: Weapon["id"],
    name: Weapon["name"],
    rarity: Weapon["rarity"],
    source: Weapon["source"],
    typeId: Weapon["type_id"],
    baseAtk: Weapon["base_atk"],
    secondaryStatsId: Weapon["secondary_stats"]["id"],
    secondaryStats: Omit<Weapon["secondary_stats"], "id">,
    imageName: string,
  ) {
    this.id = id;
    this.name = name;
    this.rarity = rarity;
    this.source = source;
    this.type_id = typeId;
    this.base_atk = baseAtk;
    this.secondary_stats = { id: secondaryStatsId, ...secondaryStats };
    this.image_src = publicImageSrc(`${WeaponClass.PATH}/${imageName}`);
  }

  static init(params: ConstructorParameters<typeof WeaponClass>) {
    return new WeaponClass(...params);
  }
}

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`weapons/${src}`);
const WeaponSource = {
  BattlePass: "Выбираемая награда при достижении 30 уровня боевого пропуска (Жемчужный гимн)",
  Chests: "Сундуки",
  EventWishExclusive: "Эксклюзивное оружие Молитвы события",
  Forged: "Кузница",
  PaimonsBargains: "Обмен Звёздного блеска в магазине Паймон",
  Wish: "Молитвы",
} as const;

export default {
  [WeaponIds.AThousandBlazingSuns]: WeaponClass.init([
    WeaponIds.AThousandBlazingSuns,
    "Тысяча ослепительных солнц",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 49, max_value: 741 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.024, 1), max_value: numberFormatPercent(0.110, 1) },
    "a_thousand_blazing_suns-256x256.webp",
  ]),
  [WeaponIds.AThousandFloatingDreams]: WeaponClass.init([
    WeaponIds.AThousandFloatingDreams,
    "Сновидения тысячи ночей",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
    "a_thousand_floating_dreams-256x256.webp",
  ]),
  [WeaponIds.Absolution]: WeaponClass.init([
    WeaponIds.Absolution,
    "Отпущение грехов",
    5,
    undefined,
    WeaponTypeIds.Sword,
    { min_value: "48", max_value: "674" },
    StatIds.CritDMG,
    { min_value: "9.6%", max_value: "44.1%" },
    "absolution-256x256.png",
  ]),
  [WeaponIds.Akuoumaru]: {
    id: WeaponIds.Akuoumaru,
    name: "Акуомару",
    image_src: imageSrc("akuoumaru-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.AlleyHunter]: {
    id: WeaponIds.AlleyHunter,
    name: "Охотник во тьме",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("alley_hunter-256x256.webp"),
  },
  [WeaponIds.AmenomaKageuchi]: {
    id: WeaponIds.AmenomaKageuchi,
    name: "Амэнома Кагэути",
    image_src: imageSrc("amenoma_kageuchi-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.Atk, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.AmosBow]: {
    id: WeaponIds.AmosBow,
    name: "Лук Амоса",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("amos_bow-256x256.webp"),
  },
  [WeaponIds.AquaSimulacra]: {
    id: WeaponIds.AquaSimulacra,
    name: "Аква симулякрум",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("aqua_simulacra-256x256.webp"),
  },
  [WeaponIds.AquilaFavonia]: {
    id: WeaponIds.AquilaFavonia,
    name: "Меч Сокола",
    image_src: imageSrc("aquila_favonia-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "6774" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.AshGravenDrinkingHorn]: {
    id: WeaponIds.AshGravenDrinkingHorn,
    name: "Пепельный рог",
    rarity: 4,
    source: "Событие версии 5.0 «Следы мастерства»",
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("ash_graven_drinking_horn-256x256.webp"),
  },
  [WeaponIds.AstralVulturesCrimsonPlumage]: {
    id: WeaponIds.AstralVulturesCrimsonPlumage,
    name: "Алое перо звёздного грифа",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("astral_vultures_crimson_plumage-256x256.webp"),
  },
  [WeaponIds.Azurelight]: {
    id: WeaponIds.Azurelight,
    name: "Лазурное сияние",
    image_src: imageSrc("azurelight-256x256.webp"),
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
  },
  [WeaponIds.BalladOfTheBoundlessBlue]: {
    id: WeaponIds.BalladOfTheBoundlessBlue,
    name: "Песнь необъятной лазури",
    rarity: 4,
    source: "Событие версии 4.1 «Поэзия вод»",
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("ballad_of_the_boundless_blue-256x256.webp"),
  },
  [WeaponIds.BalladOfTheFjords]: {
    id: WeaponIds.BalladOfTheFjords,
    name: "Баллада фьордов",
    image_src: imageSrc("ballad_of_the_fjords-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.BeaconOfTheReedSea]: {
    id: WeaponIds.BeaconOfTheReedSea,
    name: "Маяк тростникового моря",
    image_src: imageSrc("beacon_of_the_reed_sea-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponIds.BlackTassel]: {
    id: WeaponIds.BlackTassel,
    name: "Чёрная кисть",
    image_src: imageSrc("black_tassel-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_stats: { id: StatIds.Hp, min_value: "10.2%", max_value: "46.9%" },
  },
  [WeaponIds.BlackcliffAgate]: {
    id: WeaponIds.BlackcliffAgate,
    name: "Черногорский агат",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("blackcliff_agate-256x256.webp"),
  },
  [WeaponIds.BlackcliffLongsword]: {
    id: WeaponIds.BlackcliffLongsword,
    name: "Черногорский длинный меч",
    image_src: imageSrc("blackcliff_longsword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.BlackcliffPole]: {
    id: WeaponIds.BlackcliffPole,
    name: "Черногорская пика",
    image_src: imageSrc("blackcliff_pole-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.BlackcliffSlasher]: {
    id: WeaponIds.BlackcliffSlasher,
    name: "Черногорская бритва",
    image_src: imageSrc("blackcliff_slasher-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.BlackcliffWarbow]: {
    id: WeaponIds.BlackcliffWarbow,
    name: "Черногорский боевой лук",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.080, 1),
      max_value: numberFormatPercent(0.368, 1),
    },
    image_src: imageSrc("blackcliff_warbow-256x256.webp"),
  },
  [WeaponIds.BloodtaintedGreatsword]: {
    id: WeaponIds.BloodtaintedGreatsword,
    name: "Меч драконьей крови",
    image_src: imageSrc("bloodtainted_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "41", max_value: "187" },
  },
  [WeaponIds.CalamityOfEshu]: {
    id: WeaponIds.CalamityOfEshu,
    name: "Бедствие Эшу",
    image_src: imageSrc("calamity_of_eshu-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.CalamityQueller]: {
    id: WeaponIds.CalamityQueller,
    name: "Усмиритель бед",
    image_src: imageSrc("calamity_queller-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_stats: { id: StatIds.Atk, min_value: "3.6%", max_value: "16.5%" },
  },
  [WeaponIds.CashflowSupervision]: {
    id: WeaponIds.CashflowSupervision,
    name: "Казначейский надзор",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("cashflow_supervision-256x256.webp"),
  },
  [WeaponIds.ChainBreaker]: {
    id: WeaponIds.ChainBreaker,
    name: "Разбивающий цепи",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("chain_breaker-256x256.webp"),
  },
  [WeaponIds.CinnabarSpindle]: {
    id: WeaponIds.CinnabarSpindle,
    name: "Киноварное веретено",
    image_src: imageSrc("cinnabar_spindle-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.Def, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponIds.Cloudforged]: {
    id: WeaponIds.Cloudforged,
    name: "Выкованный из облаков",
    rarity: 4,
    source: "Событие версии 4.7 «Моделирование взаимного повышения безопасности»",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("cloudforged-256x256.webp"),
  },
  [WeaponIds.CompoundBow]: {
    id: WeaponIds.CompoundBow,
    name: "Составной лук",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.PhysicalDmgBonus,
      min_value: numberFormatPercent(0.150, 1),
      max_value: numberFormatPercent(0.690, 1),
    },
    image_src: imageSrc("compound_bow-256x256.webp"),
  },
  [WeaponIds.CoolSteel]: {
    id: WeaponIds.CoolSteel,
    name: "Холодное лезвие",
    image_src: imageSrc("cool_steel-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.CranesEchoingCall]: {
    id: WeaponIds.CranesEchoingCall,
    name: "Звонкий клич журавля",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 49, max_value: 741 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.036, 1),
      max_value: numberFormatPercent(0.165, 1),
    },
    image_src: imageSrc("cranes_echoing_call-256x256.webp"),
  },
  [WeaponIds.CrescentPike]: {
    id: WeaponIds.CrescentPike,
    name: "Пика полумесяца",
    image_src: imageSrc("crescent_pike-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponIds.CrimsonMoonsSemblance]: {
    id: WeaponIds.CrimsonMoonsSemblance,
    name: "Очертания алой луны",
    image_src: imageSrc("crimson_moons_semblance-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponIds.DarkIronSword]: {
    id: WeaponIds.DarkIronSword,
    name: "Тёмный железный меч",
    image_src: imageSrc("dark_iron_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "31", max_value: "141" },
  },
  [WeaponIds.Deathmatch]: {
    id: WeaponIds.Deathmatch,
    name: "Смертельный бой",
    image_src: imageSrc("deathmatch-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.CritRate, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.DebateClub]: {
    id: WeaponIds.DebateClub,
    name: "Дубина переговоров",
    image_src: imageSrc("debate_club-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.DialoguesOfTheDesertSages]: {
    id: WeaponIds.DialoguesOfTheDesertSages,
    name: "Диалог пустынных мудрецов",
    image_src: imageSrc("dialogues_of_the_desert_sages-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Hp, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.DodocoTales]: {
    id: WeaponIds.DodocoTales,
    name: "Истории Додоко",
    rarity: 4,
    source: "Событие версии 1.6 «Лето! Остров? Приключение!»",
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("dodoco_tales-256x256.webp"),
  },
  [WeaponIds.DragonsBane]: {
    id: WeaponIds.DragonsBane,
    name: "Гроза драконов",
    image_src: imageSrc("dragons_bane-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "48", max_value: "221" },
  },
  [WeaponIds.DragonspineSpear]: {
    id: WeaponIds.DragonspineSpear,
    name: "Копьё Драконьего хребта",
    image_src: imageSrc("dragonspine_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponIds.EarthShaker]: {
    id: WeaponIds.EarthShaker,
    name: "Сотрясающий землю",
    image_src: imageSrc("earth_shaker-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.ElegyForTheEnd]: {
    id: WeaponIds.ElegyForTheEnd,
    name: "Элегия погибели",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("elegy_for_the_end-256x256.webp"),
  },
  [WeaponIds.EmeraldOrb]: {
    id: WeaponIds.EmeraldOrb,
    name: "Изумрудный шар",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 20, max_value: 94 },
    image_src: imageSrc("emerald_orb-256x256.webp"),
  },
  [WeaponIds.EndOfTheLine]: {
    id: WeaponIds.EndOfTheLine,
    name: "Иссушитель",
    rarity: 4,
    source: "Ассоциация рыболовов Сумеру",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("end_of_the_line-256x256.webp"),
  },
  [WeaponIds.EngulfingLightning]: {
    id: WeaponIds.EngulfingLightning,
    name: "Сияющая жатва",
    image_src: imageSrc("engulfing_lightning-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.EverlastingMoonglow]: {
    id: WeaponIds.EverlastingMoonglow,
    name: "Вечное лунное сияние",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("everlasting_moonglow-256x256.webp"),
  },
  [WeaponIds.EyeOfPerception]: {
    id: WeaponIds.EyeOfPerception,
    name: "Око сознания",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("eye_of_perception-256x256.webp"),
  },
  [WeaponIds.FadingTwilight]: {
    id: WeaponIds.FadingTwilight,
    name: "Гаснущие сумерки",
    rarity: 4,
    source: "Событие версии 2.7 «Опасная тропа»",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("fading_twilight-256x256.webp"),
  },
  [WeaponIds.FangOfTheMountainKing]: {
    id: WeaponIds.FangOfTheMountainKing,
    name: "Клык Горного короля",
    image_src: imageSrc("fang_of_the_mountain_king-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_stats: { id: StatIds.CritRate, min_value: "2.4%", max_value: "11.0%" },
  },
  [WeaponIds.FavoniusCodex]: {
    id: WeaponIds.FavoniusCodex,
    name: "Кодекс Фавония",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("favonius_codex-256x256.webp"),
  },
  [WeaponIds.FavoniusGreatsword]: {
    id: WeaponIds.FavoniusGreatsword,
    name: "Двуручный меч Фавония",
    image_src: imageSrc("favonius_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponIds.FavoniusLance]: {
    id: WeaponIds.FavoniusLance,
    name: "Копьё Фавония",
    image_src: imageSrc("favonius_lance-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.FavoniusSword]: {
    id: WeaponIds.FavoniusSword,
    name: "Меч Фавония",
    image_src: imageSrc("favonius_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponIds.FavoniusWarbow]: {
    id: WeaponIds.FavoniusWarbow,
    name: "Боевой лук Фавония",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.133, 1),
      max_value: numberFormatPercent(0.613, 1),
    },
    image_src: imageSrc("favonius_warbow-256x256.webp"),
  },
  [WeaponIds.FerrousShadow]: {
    id: WeaponIds.FerrousShadow,
    name: "Металлическая тень",
    image_src: imageSrc("ferrous_shadow-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Hp, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.FesteringDesire]: {
    id: WeaponIds.FesteringDesire,
    name: "Осквернённое желание",
    image_src: imageSrc("festering_desire-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.FilletBlade]: {
    id: WeaponIds.FilletBlade,
    name: "Филейный нож",
    image_src: imageSrc("fillet_blade-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.FinaleOfTheDeep]: {
    id: WeaponIds.FinaleOfTheDeep,
    name: "Грандиозный финал глубин",
    image_src: imageSrc("finale_of_the_deep-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.FleuveCendreFerryman]: {
    id: WeaponIds.FleuveCendreFerryman,
    name: "Перевозчик Флёв Сандр",
    image_src: imageSrc("fleuve_cendre_ferryman-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.FlowerWreathedFeathers]: {
    id: WeaponIds.FlowerWreathedFeathers,
    name: "Украшенные цветами перья",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("flower_wreathed_feathers-256x256.webp"),
  },
  [WeaponIds.FlowingPurity]: {
    id: WeaponIds.FlowingPurity,
    name: "Сверкание чистых вод",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("flowing_purity-256x256.webp"),
  },
  [WeaponIds.FluteOfEzpitzal]: {
    id: WeaponIds.FluteOfEzpitzal,
    name: "Флейта Эспицаль",
    image_src: imageSrc("flute_of_ezpitzal-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.Def, min_value: "15%", max_value: "69.0%" },
  },
  [WeaponIds.FootprintOfTheRainbow]: {
    id: WeaponIds.FootprintOfTheRainbow,
    name: "След радуги",
    image_src: imageSrc("footprint_of_the_rainbow-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Def, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponIds.ForestRegalia]: {
    id: WeaponIds.ForestRegalia,
    name: "Регалия леса",
    image_src: imageSrc("forest_regalia-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.FreedomSworn]: {
    id: WeaponIds.FreedomSworn,
    name: "Клятва свободы",
    image_src: imageSrc("freedom_sworn-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "43", max_value: "198" },
  },
  [WeaponIds.Frostbearer]: {
    id: WeaponIds.Frostbearer,
    name: "Плод вечной мерзлоты",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("frostbearer-256x256.webp"),
  },
  [WeaponIds.FruitOfFulfillment]: {
    id: WeaponIds.FruitOfFulfillment,
    name: "Плод восполнения",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.100, 1),
      max_value: numberFormatPercent(0.459, 1),
    },
    image_src: imageSrc("fruit_of_fulfillment-256x256.webp"),
  },
  [WeaponIds.FruitfulHook]: {
    id: WeaponIds.FruitfulHook,
    name: "Плодотворный крюк",
    image_src: imageSrc("fruitful_hook-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.HakushinRing]: {
    id: WeaponIds.HakushinRing,
    name: "Кольцо Хакусин",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("hakushin_ring-256x256.webp"),
  },
  [WeaponIds.Halberd]: {
    id: WeaponIds.Halberd,
    name: "Алебарда Миллелита",
    image_src: imageSrc("halberd-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 3,
    base_atk: { min_value: "40", max_value: "448" },
    secondary_stats: { id: StatIds.Atk, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponIds.Hamayumi]: {
    id: WeaponIds.Hamayumi,
    name: "Хамаюми",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("hamayumi-256x256.webp"),
  },
  [WeaponIds.HaranGeppakuFutsu]: {
    id: WeaponIds.HaranGeppakuFutsu,
    name: "Харан гэппаку фуцу",
    image_src: imageSrc("haran_geppaku_futsu-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponIds.HarbingerOfDawn]: {
    id: WeaponIds.HarbingerOfDawn,
    name: "Предвестник зари",
    image_src: imageSrc("harbinger_of_dawn-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "10.2%", max_value: "46.9%" },
  },
  [WeaponIds.HuntersPath]: {
    id: WeaponIds.HuntersPath,
    name: "Охотничья тропа",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("hunters_path-256x256.webp"),
  },
  [WeaponIds.IbisPiercer]: {
    id: WeaponIds.IbisPiercer,
    name: "Клюв ибиса",
    rarity: 4,
    source: "Событие версии 3.7 «Дуэль! К вершинам карточного мастерства!»",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("ibis_piercer-256x256.webp"),
  },
  [WeaponIds.IronSting]: {
    id: WeaponIds.IronSting,
    name: "Стальное жало",
    image_src: imageSrc("iron_sting-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponIds.JadefallsSplendor]: {
    id: WeaponIds.JadefallsSplendor,
    name: "Великолепие лазурного свода",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("jadefalls_splendor-256x256.webp"),
  },
  [WeaponIds.KagotsurubeIsshin]: {
    id: WeaponIds.KagotsurubeIsshin,
    name: "Кагоцурубэ Иссин",
    image_src: imageSrc("kagotsurube_isshin-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.KagurasVerity]: {
    id: WeaponIds.KagurasVerity,
    name: "Истина кагура",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("kaguras_verity-256x256.webp"),
  },
  [WeaponIds.KatsuragikiriNagamasa]: {
    id: WeaponIds.KatsuragikiriNagamasa,
    name: "Кацурагикири Нагамаса",
    image_src: imageSrc("katsuragikiri_nagamasa-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.KeyOfKhajNisut]: {
    id: WeaponIds.KeyOfKhajNisut,
    name: "Ключ Хадж-нисут",
    image_src: imageSrc("id_of_khaj_nisut-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.Hp, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponIds.KingsSquire]: {
    id: WeaponIds.KingsSquire,
    name: "Приближённый короля",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("kings_squire-256x256.webp"),
  },
  [WeaponIds.KitainCrossSpear]: {
    id: WeaponIds.KitainCrossSpear,
    name: "Крест-копьё Китаин",
    image_src: imageSrc("kitain_cross_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponIds.LightOfFoliarIncision]: {
    id: WeaponIds.LightOfFoliarIncision,
    name: "Свет лиственного разреза",
    image_src: imageSrc("light_of_foliar_incision-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponIds.LionsRoar]: {
    id: WeaponIds.LionsRoar,
    name: "Драконий рык",
    image_src: imageSrc("lions_roar-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.LithicBlade]: {
    id: WeaponIds.LithicBlade,
    name: "Каменный меч",
    image_src: imageSrc("lithic_blade-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.LithicSpear]: {
    id: WeaponIds.LithicSpear,
    name: "Каменное копьё",
    image_src: imageSrc("lithic_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.LostPrayerToTheSacredWinds]: {
    id: WeaponIds.LostPrayerToTheSacredWinds,
    name: "Молитва святым ветрам",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("lost_prayer_to_the_sacred_winds-256x256.webp"),
  },
  [WeaponIds.LumidouceElegy]: {
    id: WeaponIds.LumidouceElegy,
    name: "Элегия Люмидус",
    image_src: imageSrc("lumidouce_elegy-512x512.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponIds.LuxuriousSeaLord]: {
    id: WeaponIds.LuxuriousSeaLord,
    name: "Благодатный владыка вод",
    image_src: imageSrc("luxurious_sea_lord-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.Atk, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.MagicGuide]: {
    id: WeaponIds.MagicGuide,
    name: "Руководство по магии",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 41, max_value: 187 },
    image_src: imageSrc("magic_guide-256x256.webp"),
  },
  [WeaponIds.MailedFlower]: {
    id: WeaponIds.MailedFlower,
    name: "Цветок в латах",
    image_src: imageSrc("mailed_flower-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponIds.MakhairaAquamarine]: {
    id: WeaponIds.MakhairaAquamarine,
    name: "Аквамарин Махайры",
    image_src: imageSrc("makhaira_aquamarine-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponIds.MappaMare]: {
    id: WeaponIds.MappaMare,
    name: "Морской атлас",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 24, max_value: 110 },
    image_src: imageSrc("mappa_mare-256x256.webp"),
  },
  [WeaponIds.MemoryOfDust]: {
    id: WeaponIds.MemoryOfDust,
    name: "Память о пыли",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("memory_of_dust-256x256.webp"),
  },
  [WeaponIds.Messenger]: {
    id: WeaponIds.Messenger,
    name: "Посыльный",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("messenger-256x256.webp"),
  },
  [WeaponIds.MissiveWindspear]: {
    id: WeaponIds.MissiveWindspear,
    name: "Копьё послания ветров",
    image_src: imageSrc("missive_windspear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.MistsplitterReforged]: {
    id: WeaponIds.MistsplitterReforged,
    name: "Рассекающий туман",
    image_src: imageSrc("mistsplitter_reforged-512x512.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponIds.MitternachtsWaltz]: {
    id: WeaponIds.MitternachtsWaltz,
    name: "Вальс Нирваны Ночи",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.PhysicalDmgBonus,
      min_value: numberFormatPercent(0.113, 1),
      max_value: numberFormatPercent(0.517, 1),
    },
    image_src: imageSrc("mitternachts_waltz-256x256.webp"),
  },
  [WeaponIds.Moonpiercer]: {
    id: WeaponIds.Moonpiercer,
    name: "Пронзающий луну",
    image_src: imageSrc("moonpiercer-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponIds.MountainBracingBolt]: {
    id: WeaponIds.MountainBracingBolt,
    name: "Крепящий горы шип",
    image_src: imageSrc("mountain_bracing_bolt-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.MouunsMoon]: {
    id: WeaponIds.MouunsMoon,
    name: "Луна Моун",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("mouuns_moon-256x256.webp"),
  },
  [WeaponIds.OathswornEye]: {
    id: WeaponIds.OathswornEye,
    name: "Око клятвы",
    rarity: 4,
    source: "Событие версии 2.5 «Подношение врат трёх миров»",
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("oathsworn_eye-256x256.webp"),
  },
  [WeaponIds.OtherworldlyStory]: {
    id: WeaponIds.OtherworldlyStory,
    name: "Потусторонняя история",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.085, 1),
      max_value: numberFormatPercent(0.390, 1),
    },
    image_src: imageSrc("otherworldly_story-256x256.webp"),
  },
  [WeaponIds.PeakPatrolSong]: {
    id: WeaponIds.PeakPatrolSong,
    name: "Песнь патруля пиков",
    image_src: imageSrc("peak_patrol_song-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.Def, min_value: "18%", max_value: "82.7%" },
  },
  [WeaponIds.PolarStar]: {
    id: WeaponIds.PolarStar,
    name: "Полярная звезда",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("polar_star-256x256.webp"),
  },
  [WeaponIds.PortablePowerSaw]: {
    id: WeaponIds.PortablePowerSaw,
    name: "Переносная мотопила",
    image_src: imageSrc("portable_power_saw-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.Hp, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.Predator]: {
    id: WeaponIds.Predator,
    name: "Хищник",
    rarity: 4,
    source: "Внутриигровая почта \"PlayStation Network\"",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("predator-512x512.webp"),
  },
  [WeaponIds.PrimordialJadeCutter]: {
    id: WeaponIds.PrimordialJadeCutter,
    name: "Драгоценный омут",
    image_src: imageSrc("primordial_jade_cutter-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponIds.PrimordialJadeWingedSpear]: {
    id: WeaponIds.PrimordialJadeWingedSpear,
    name: "Нефритовый коршун",
    image_src: imageSrc("primordial_jade_winged_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponIds.ProspectorsDrill]: {
    id: WeaponIds.ProspectorsDrill,
    name: "Бур рудоискателя",
    image_src: imageSrc("prospectors_drill-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.PrototypeAmber]: {
    id: WeaponIds.PrototypeAmber,
    name: "Прототип: Янтарь",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("prototype_amber-256x256.webp"),
  },
  [WeaponIds.PrototypeArchaic]: {
    id: WeaponIds.PrototypeArchaic,
    name: "Прототип: Архаичный",
    image_src: imageSrc("prototype_archaic-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.PrototypeCrescent]: {
    id: WeaponIds.PrototypeCrescent,
    name: "Прототип: Полумесяц",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("prototype_crescent-256x256.webp"),
  },
  [WeaponIds.PrototypeRancour]: {
    id: WeaponIds.PrototypeRancour,
    name: "Прототип: Злоба",
    image_src: imageSrc("prototype_rancour-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponIds.PrototypeStarglitter]: {
    id: WeaponIds.PrototypeStarglitter,
    name: "Прототип: Звёздный блеск",
    image_src: imageSrc("prototype_starglitter-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.Rainslasher]: {
    id: WeaponIds.Rainslasher,
    name: "Дождерез",
    image_src: imageSrc("rainslasher-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponIds.RangeGauge]: {
    id: WeaponIds.RangeGauge,
    name: "Дальномер",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("range_gauge-256x256.webp"),
  },
  [WeaponIds.RavenBow]: {
    id: WeaponIds.RavenBow,
    name: "Лук ворона",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 20, max_value: 94 },
    image_src: imageSrc("raven_bow-256x256.webp"),
  },
  [WeaponIds.RecurveBow]: {
    id: WeaponIds.RecurveBow,
    name: "Изогнутый лук",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("recurve_bow-256x256.webp"),
  },
  [WeaponIds.RedhornStonethresher]: {
    id: WeaponIds.RedhornStonethresher,
    name: "Краснорогий камнеруб",
    image_src: imageSrc("redhorn_stonethresher-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponIds.RightfulReward]: {
    id: WeaponIds.RightfulReward,
    name: "Справедливая награда",
    image_src: imageSrc("rightful_reward-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Hp, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.RingOfYaxche]: {
    id: WeaponIds.RingOfYaxche,
    name: "Кольцо Яшче",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("ring_of_yaxche-256x256.webp"),
  },
  [WeaponIds.RoyalBow]: {
    id: WeaponIds.RoyalBow,
    name: "Королевский лук",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("royal_bow-256x256.webp"),
  },
  [WeaponIds.RoyalGreatsword]: {
    id: WeaponIds.RoyalGreatsword,
    name: "Королевский двуручный меч",
    image_src: imageSrc("royal_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.RoyalGrimoire]: {
    id: WeaponIds.RoyalGrimoire,
    name: "Королевский гримуар",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("royal_grimoire-256x256.webp"),
  },
  [WeaponIds.RoyalLongsword]: {
    id: WeaponIds.RoyalLongsword,
    name: "Меч аристократов",
    image_src: imageSrc("royal_longsword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.RoyalSpear]: {
    id: WeaponIds.RoyalSpear,
    name: "Королевское копьё",
    image_src: imageSrc("royal_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.Rust]: {
    id: WeaponIds.Rust,
    name: "Ржавый лук",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("rust-256x256.webp"),
  },
  [WeaponIds.SacrificialBow]: {
    id: WeaponIds.SacrificialBow,
    name: "Церемониальный лук",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("sacrificial_bow-256x256.webp"),
  },
  [WeaponIds.SacrificialFragments]: {
    id: WeaponIds.SacrificialFragments,
    name: "Церемониальные мемуары",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 48, max_value: 221 },
    image_src: imageSrc("sacrificial_fragments-256x256.webp"),
  },
  [WeaponIds.SacrificialGreatsword]: {
    id: WeaponIds.SacrificialGreatsword,
    name: "Церемониальный двуручный меч",
    image_src: imageSrc("sacrificial_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.SacrificialJade]: {
    id: WeaponIds.SacrificialJade,
    name: "Жертвенный нефрит",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.080, 1),
      max_value: numberFormatPercent(0.368, 1),
    },
    image_src: imageSrc("sacrificial_jade-256x256.webp"),
  },
  [WeaponIds.SacrificialSword]: {
    id: WeaponIds.SacrificialSword,
    name: "Церемониальный меч",
    image_src: imageSrc("sacrificial_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponIds.SapwoodBlade]: {
    id: WeaponIds.SapwoodBlade,
    name: "Деревянный клинок",
    image_src: imageSrc("sapwood_blade-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.ScionOfTheBlazingSun]: {
    id: WeaponIds.ScionOfTheBlazingSun,
    name: "Наследник слепящего солнца",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.040, 1),
      max_value: numberFormatPercent(0.184, 1),
    },
    image_src: imageSrc("scion_of_the_blazing_sun-256x256.webp"),
  },
  [WeaponIds.SequenceOfSolitude]: {
    id: WeaponIds.SequenceOfSolitude,
    name: "Каденция одиночества",
    rarity: 4,
    source: "Событие версии 5.6 «Кружащийся вальс»",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("sequence_of_solitude-256x256.webp"),
  },
  [WeaponIds.SerpentSpine]: {
    id: WeaponIds.SerpentSpine,
    name: "Меч драконьей кости",
    image_src: imageSrc("serpent_spine-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.SharpshootersOath]: {
    id: WeaponIds.SharpshootersOath,
    name: "Клятва стрелка",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("sharpshooters_oath-256x256.webp"),
  },
  [WeaponIds.SilvershowerHeartstrings]: {
    id: WeaponIds.SilvershowerHeartstrings,
    name: "Сердечные струны дождя",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("silvershower_heartstrings-256x256.webp"),
  },
  [WeaponIds.SkyriderGreatsword]: {
    id: WeaponIds.SkyriderGreatsword,
    name: "Большой меч небесного всадника",
    image_src: imageSrc("skyrider_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponIds.SkyriderSword]: {
    id: WeaponIds.SkyriderSword,
    name: "Меч небесного всадника",
    image_src: imageSrc("skyrider_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponIds.SkywardAtlas]: {
    id: WeaponIds.SkywardAtlas,
    name: "Небесный атлас",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("skyward_atlas-256x256.webp"),
  },
  [WeaponIds.SkywardBlade]: {
    id: WeaponIds.SkywardBlade,
    name: "Небесный меч",
    image_src: imageSrc("skyward_blade-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.SkywardHarp]: {
    id: WeaponIds.SkywardHarp,
    name: "Небесное крыло",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("skyward_harp-256x256.webp"),
  },
  [WeaponIds.SkywardPride]: {
    id: WeaponIds.SkywardPride,
    name: "Небесное величие",
    image_src: imageSrc("skyward_pride-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.SkywardSpine]: {
    id: WeaponIds.SkywardSpine,
    name: "Небесная ось",
    image_src: imageSrc("skyward_spine-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.Slingshot]: {
    id: WeaponIds.Slingshot,
    name: "Рогатка",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("slingshot-256x256.webp"),
  },
  [WeaponIds.SnowTombedStarsilver]: {
    id: WeaponIds.SnowTombedStarsilver,
    name: "Заснеженное звёздное серебро",
    image_src: imageSrc("snow_tombed_starsilver-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponIds.SolarPearl]: {
    id: WeaponIds.SolarPearl,
    name: "Солнечная жемчужина",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("solar_pearl-256x256.webp"),
  },
  [WeaponIds.SongOfBrokenPines]: {
    id: WeaponIds.SongOfBrokenPines,
    name: "Песнь разбитых сосен",
    image_src: imageSrc("song_of_broken_pines-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "4.5%", max_value: "20.7%" },
  },
  [WeaponIds.SongOfStillness]: {
    id: WeaponIds.SongOfStillness,
    name: "Мелодия покоя",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("song_of_stillness-256x256.webp"),
  },
  [WeaponIds.SplendorOfTranquilWaters]: {
    id: WeaponIds.SplendorOfTranquilWaters,
    name: "Блеск тихих вод",
    image_src: imageSrc("splendor_of_tranquil_waters-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponIds.StaffOfHoma]: {
    id: WeaponIds.StaffOfHoma,
    name: "Посох Хомы",
    image_src: imageSrc("staff_of_homa-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponIds.StaffOfTheScarletSands]: {
    id: WeaponIds.StaffOfTheScarletSands,
    name: "Посох алых песков",
    image_src: imageSrc("staff_of_the_scarlet_sands-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponIds.StarcallersWatch]: {
    id: WeaponIds.StarcallersWatch,
    name: "Бдение взывающего к звёздам",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("starcallers_watch-256x256.webp"),
  },
  [WeaponIds.SturdyBone]: {
    id: WeaponIds.SturdyBone,
    name: "Крепкая кость",
    image_src: imageSrc("sturdy_bone-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.SummitShaper]: {
    id: WeaponIds.SummitShaper,
    name: "Кромсатель пиков",
    image_src: imageSrc("summit_shaper-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.SunnyMorningSleepIn]: {
    id: WeaponIds.SunnyMorningSleepIn,
    name: "Сон солнечным утром",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 58, max_value: 265 },
    image_src: imageSrc("sunny_morning_sleep_in-256x256.webp"),
  },
  [WeaponIds.SurfsUp]: {
    id: WeaponIds.SurfsUp,
    name: "Лови волну",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("surfs_up-256x256.webp"),
  },
  [WeaponIds.SwordOfDescension]: {
    id: WeaponIds.SwordOfDescension,
    name: "Меч нисхождения",
    image_src: imageSrc("sword_of_descension-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "39", max_value: "440" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.SwordOfNarzissenkreuz]: {
    id: WeaponIds.SwordOfNarzissenkreuz,
    name: "Меч Нарциссенкрейца",
    image_src: imageSrc("sword_of_narzissenkreuz_pneuma-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.SymphonistOfScents]: {
    id: WeaponIds.SymphonistOfScents,
    name: "Симфонист ароматов",
    image_src: imageSrc("symphonist_of_scents-256x256.webp"),
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
  },
  [WeaponIds.TalkingStick]: {
    id: WeaponIds.TalkingStick,
    name: "Говорящая палица",
    image_src: imageSrc("talking_stick-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.CritRate, min_value: "4%", max_value: "18.4%" },
  },
  [WeaponIds.TamayurateiNoOhanashi]: {
    id: WeaponIds.TamayurateiNoOhanashi,
    name: "Тамаюратэй но оханаси",
    image_src: imageSrc("tamayuratei_no_ohanashi-256x256.webp"),
    source: "Событие версии 5.4 «Чудесные истории фестиваля Микавы»",
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
  },
  [WeaponIds.TheAlleyFlash]: {
    id: WeaponIds.TheAlleyFlash,
    name: "Вспышка во тьме",
    image_src: imageSrc("the_alley_flash-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "45", max_value: "620" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "12", max_value: "55" },
  },
  [WeaponIds.TheBell]: {
    id: WeaponIds.TheBell,
    name: "Меч-колокол",
    image_src: imageSrc("the_bell-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Hp, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.TheBlackSword]: {
    id: WeaponIds.TheBlackSword,
    name: "Чёрный меч",
    image_src: imageSrc("the_black_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.TheCatch]: {
    id: WeaponIds.TheCatch,
    name: "«Улов»",
    image_src: imageSrc("the_catch-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.TheDockhandsAssistant]: {
    id: WeaponIds.TheDockhandsAssistant,
    name: "Верфь",
    image_src: imageSrc("the_dockhands_assistant-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Hp, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.TheFirstGreatMagic]: {
    id: WeaponIds.TheFirstGreatMagic,
    name: "Первый великий фокус",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("the_first_great_magic-256x256.webp"),
  },
  [WeaponIds.TheFlute]: {
    id: WeaponIds.TheFlute,
    name: "Меч-флейта",
    image_src: imageSrc("the_flute-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.TheStringless]: {
    id: WeaponIds.TheStringless,
    name: "Бесструнный",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("the_stringless-256x256.webp"),
  },
  [WeaponIds.TheUnforged]: {
    id: WeaponIds.TheUnforged,
    name: "Некованый",
    image_src: imageSrc("the_unforged-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.TheViridescentHunt]: {
    id: WeaponIds.TheViridescentHunt,
    name: "Зелёный лук",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("the_viridescent_hunt-256x256.webp"),
  },
  [WeaponIds.TheWidsith]: {
    id: WeaponIds.TheWidsith,
    name: "Песнь странника",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("the_widsith-256x256.webp"),
  },
  [WeaponIds.ThrillingTalesOfDragonSlayers]: {
    id: WeaponIds.ThrillingTalesOfDragonSlayers,
    name: "Эпос о драконоборцах",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.077, 1),
      max_value: numberFormatPercent(0.352, 1),
    },
    image_src: imageSrc("thrilling_tales_of_dragon_slayers-256x256.webp"),
  },
  [WeaponIds.ThunderingPulse]: {
    id: WeaponIds.ThunderingPulse,
    name: "Громовой пульс",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("thundering_pulse-256x256.webp"),
  },
  [WeaponIds.TidalShadow]: {
    id: WeaponIds.TidalShadow,
    name: "Тень волны",
    image_src: imageSrc("tidal_shadow-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.TomeOfTheEternalFlow]: {
    id: WeaponIds.TomeOfTheEternalFlow,
    name: "Обряд вечного течения",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 542 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.192, 1),
      max_value: numberFormatPercent(0.882, 1),
    },
    image_src: imageSrc("tome_of_the_eternal_flow-256x256.webp"),
  },
  [WeaponIds.ToukabouShigure]: {
    id: WeaponIds.ToukabouShigure,
    name: "Токабо сигурэ",
    image_src: imageSrc("toukabou_shigure-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "36", max_value: "165" },
  },
  [WeaponIds.TravelersHandySword]: {
    id: WeaponIds.TravelersHandySword,
    name: "Меч путешественника",
    image_src: imageSrc("travelers_handy_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "40", max_value: "448" },
    secondary_stats: { id: StatIds.Def, min_value: "6.4%", max_value: "29.3%" },
  },
  [WeaponIds.TulaytullahsRemembrance]: {
    id: WeaponIds.TulaytullahsRemembrance,
    name: "Воспоминания Тулайтуллы",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("tulaytullahs_remembrance-256x256.webp"),
  },
  [WeaponIds.TwinNephrite]: {
    id: WeaponIds.TwinNephrite,
    name: "Парный нефрит",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.034, 1),
      max_value: numberFormatPercent(0.156, 1),
    },
    image_src: imageSrc("twin_nephrite-256x256.webp"),
  },
  [WeaponIds.UltimateOverlordsMegaMagicSword]: {
    id: WeaponIds.UltimateOverlordsMegaMagicSword,
    name: "«Магический супермеч высшего владыки»",
    image_src: imageSrc("ultimate_overlords_mega_magic_sword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.UrakuMisugiri]: {
    id: WeaponIds.UrakuMisugiri,
    name: "Ураку мисугири",
    image_src: imageSrc("uraku_misugiri-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "19.2%", max_value: "88.2%" },
  },
  [WeaponIds.Verdict]: {
    id: WeaponIds.Verdict,
    name: "Вердикт",
    image_src: imageSrc("verdict-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponIds.VividNotions]: {
    id: WeaponIds.VividNotions,
    name: "Переливающиеся чаяния",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.096, 1),
      max_value: numberFormatPercent(0.441, 1),
    },
    image_src: imageSrc("vivid_notions-256x256.webp"),
  },
  [WeaponIds.VortexVanquisher]: {
    id: WeaponIds.VortexVanquisher,
    name: "Покоритель вихря",
    image_src: imageSrc("vortex_vanquisher-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.WanderingEvenstar]: {
    id: WeaponIds.WanderingEvenstar,
    name: "Скитающаяся звезда",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("wandering_evenstar-256x256.webp"),
  },
  [WeaponIds.WavebreakersFin]: {
    id: WeaponIds.WavebreakersFin,
    name: "Режущий волны плавник",
    image_src: imageSrc("wavebreakers_fin-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "45", max_value: "620" },
    secondary_stats: { id: StatIds.Atk, min_value: "3%", max_value: "13.8%" },
  },
  [WeaponIds.WaveridingWhirl]: {
    id: WeaponIds.WaveridingWhirl,
    name: "Вихрь на волнах",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.133, 1),
      max_value: numberFormatPercent(0.613, 1),
    },
    image_src: imageSrc("waveriding_whirl-256x256.webp"),
  },
  [WeaponIds.WhiteIronGreatsword]: {
    id: WeaponIds.WhiteIronGreatsword,
    name: "Меч из белого железа",
    image_src: imageSrc("white_iron_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Def, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponIds.WhiteTassel]: {
    id: WeaponIds.WhiteTassel,
    name: "Белая кисть",
    image_src: imageSrc("white_tassel-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.CritRate, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponIds.Whiteblind]: {
    id: WeaponIds.Whiteblind,
    name: "Белая тень",
    image_src: imageSrc("whiteblind-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Def, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponIds.WindblumeOde]: {
    id: WeaponIds.WindblumeOde,
    name: "Ода анемонии",
    rarity: 4,
    source: "Событие версии 1.4 «Приглашение ветряных цветов»",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 36, max_value: 165 },
    image_src: imageSrc("windblume_ode-256x256.webp"),
  },
  [WeaponIds.WineAndSong]: {
    id: WeaponIds.WineAndSong,
    name: "Вино и песни",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("wine_and_song-256x256.webp"),
  },
  [WeaponIds.WolfFang]: {
    id: WeaponIds.WolfFang,
    name: "Волчий клык",
    image_src: imageSrc("wolf_fang-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.CritRate, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.WolfsGravestone]: {
    id: WeaponIds.WolfsGravestone,
    name: "Волчья погибель",
    image_src: imageSrc("wolfs_gravestone-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.XiphosMoonlight]: {
    id: WeaponIds.XiphosMoonlight,
    name: "Лунное сияние ксифоса",
    image_src: imageSrc("xiphos_moonlight-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "36", max_value: "165" },
  },
} as Record<Weapon["id"], Weapon>;
