import type { Weapon } from "./types";
import { numberFormatPercent, publicImageSrc } from "@/lib/utils";
import { StatIds } from "../stats/enums";
import { WeaponIds } from "./enums";
import { WeaponTypeIds } from "../weapon-types/enums";

class WeaponClass implements Weapon {
  readonly id: Weapon["id"];
  readonly image_src: Weapon["image_src"];
  readonly title: Weapon["title"];
  readonly rarity: Weapon["rarity"];
  readonly source: Weapon["source"];
  readonly type_id: Weapon["type_id"];
  readonly base_atk: Weapon["base_atk"];
  readonly secondary_stats: Weapon["secondary_stats"];

  static PATH = "weapons";

  constructor(
    id: Weapon["id"],
    title: Weapon["title"],
    rarity: Weapon["rarity"],
    source: Weapon["source"],
    typeId: Weapon["type_id"],
    baseAtk: Weapon["base_atk"],
    secondaryStatsId: Weapon["secondary_stats"]["id"],
    secondaryStats: Omit<Weapon["secondary_stats"], "id">,
  ) {
    this.id = id;
    this.image_src = publicImageSrc(`${WeaponClass.PATH}/${id}.webp`);
    this.title = title;
    this.rarity = rarity;
    this.source = source;
    this.type_id = typeId;
    this.base_atk = baseAtk;
    this.secondary_stats = { id: secondaryStatsId, ...secondaryStats };
  }

  static init(params: ConstructorParameters<typeof WeaponClass>) {
    return new WeaponClass(...params);
  }
}

const imageSrc: typeof publicImageSrc = src => publicImageSrc(`weapons/${src}`);
const WeaponSource = {
  BattlePass: "Выбираемая награда при достижении 30 уровня боевого пропуска (Жемчужный гимн)",
  Chests: "Сундуки",
  EventWishExclusive: "Эксклюзивное оружие Молитвы события",
  Forged: "Кузница",
  PaimonsBargains: "Обмен Звёздного блеска в магазине Паймон",
  Wish: "Молитвы",
} as const;

export default {
  [WeaponIds.AThousandBlazingSuns]: WeaponClass.init([
    WeaponIds.AThousandBlazingSuns,
    "Тысяча ослепительных солнц",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 49, max_value: 741 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.024, 1), max_value: numberFormatPercent(0.110, 1) },
  ]),
  [WeaponIds.AThousandFloatingDreams]: WeaponClass.init([
    WeaponIds.AThousandFloatingDreams,
    "Сновидения тысячи ночей",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.Absolution]: WeaponClass.init([
    WeaponIds.Absolution,
    "Отпущение грехов",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.Akuoumaru]: {
    id: WeaponIds.Akuoumaru,
    title: "Акуомару",
    image_src: imageSrc("akuoumaru-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.AlleyHunter]: {
    id: WeaponIds.AlleyHunter,
    title: "Охотник во тьме",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("alley_hunter-256x256.webp"),
  },
  [WeaponIds.AmenomaKageuchi]: {
    id: WeaponIds.AmenomaKageuchi,
    title: "Амэнома Кагэути",
    image_src: imageSrc("amenoma_kageuchi-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.Atk, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.AmosBow]: WeaponClass.init([
    WeaponIds.AmosBow,
    "Лук Амоса",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.AquaSimulacra]: WeaponClass.init([
    WeaponIds.AquaSimulacra,
    "Аква симулякрум",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.AquilaFavonia]: WeaponClass.init([
    WeaponIds.AquilaFavonia,
    "Меч Сокола",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.AshGravenDrinkingHorn]: WeaponClass.init([
    WeaponIds.AshGravenDrinkingHorn,
    "Пепельный рог",
    4,
    "Событие версии 5.0 «Следы мастерства»",
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.AstralVulturesCrimsonPlumage]: WeaponClass.init([
    WeaponIds.AstralVulturesCrimsonPlumage,
    "Алое перо звёздного грифа",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.Azurelight]: WeaponClass.init([
    WeaponIds.Azurelight,
    "Лазурное сияние",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.BalladOfTheBoundlessBlue]: WeaponClass.init([
    WeaponIds.BalladOfTheBoundlessBlue,
    "Песнь необъятной лазури",
    4,
    "Событие версии 4.1 «Поэзия вод»",
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.BalladOfTheFjords]: WeaponClass.init([
    WeaponIds.BalladOfTheFjords,
    "Баллада фьордов",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.BeaconOfTheReedSea]: WeaponClass.init([
    WeaponIds.BeaconOfTheReedSea,
    "Маяк тростникового моря",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.BlackTassel]: WeaponClass.init([
    WeaponIds.BlackTassel,
    "Чёрная кисть",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 38, max_value: 354 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.102, 1), max_value: numberFormatPercent(0.469, 1) },
  ]),
  [WeaponIds.BlackcliffAgate]: WeaponClass.init([
    WeaponIds.BlackcliffAgate,
    "Черногорский агат",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.BlackcliffLongsword]: WeaponClass.init([
    WeaponIds.BlackcliffLongsword,
    "Черногорский длинный меч",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.BlackcliffPole]: WeaponClass.init([
    WeaponIds.BlackcliffPole,
    "Черногорская пика",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.BlackcliffSlasher]: WeaponClass.init([
    WeaponIds.BlackcliffSlasher,
    "Черногорская бритва",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.BlackcliffWarbow]: WeaponClass.init([
    WeaponIds.BlackcliffWarbow,
    "Черногорский боевой лук",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.BlackmarrowLantern]: WeaponClass.init([
    WeaponIds.BlackmarrowLantern,
    "Фонарь чёрной сердцевины",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.ElementalMastery,
    { min_value: 48, max_value: 221 },
  ]),
  [WeaponIds.BloodtaintedGreatsword]: {
    id: WeaponIds.BloodtaintedGreatsword,
    title: "Меч драконьей крови",
    image_src: imageSrc("bloodtainted_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "38", max_value: "354" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "41", max_value: "187" },
  },
  [WeaponIds.CalamityOfEshu]: WeaponClass.init([
    WeaponIds.CalamityOfEshu,
    "Бедствие Эшу",
    4,
    "Событие версии 5.2 «Свитки поиска духов Иктоми»",
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.CalamityQueller]: {
    id: WeaponIds.CalamityQueller,
    title: "Усмиритель бед",
    image_src: imageSrc("calamity_queller-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_stats: { id: StatIds.Atk, min_value: "3.6%", max_value: "16.5%" },
  },
  [WeaponIds.CashflowSupervision]: WeaponClass.init([
    WeaponIds.CashflowSupervision,
    "Казначейский надзор",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.ChainBreaker]: WeaponClass.init([
    WeaponIds.ChainBreaker,
    "Разбивающий цепи",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.CinnabarSpindle]: WeaponClass.init([
    WeaponIds.CinnabarSpindle,
    "Киноварное веретено",
    4,
    "Событие версии 2.3 «Белая пыль и снежная тень»",
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.Cloudforged]: WeaponClass.init([
    WeaponIds.Cloudforged,
    "Выкованный из облаков",
    4,
    "Событие версии 4.7 «Моделирование взаимного повышения безопасности»",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.CompoundBow]: WeaponClass.init([
    WeaponIds.CompoundBow,
    "Составной лук",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.CoolSteel]: {
    id: WeaponIds.CoolSteel,
    title: "Холодное лезвие",
    image_src: imageSrc("cool_steel-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.CranesEchoingCall]: WeaponClass.init([
    WeaponIds.CranesEchoingCall,
    "Звонкий клич журавля",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 49, max_value: 741 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.036, 1), max_value: numberFormatPercent(0.165, 1) },
  ]),
  [WeaponIds.CrescentPike]: {
    id: WeaponIds.CrescentPike,
    title: "Пика полумесяца",
    image_src: imageSrc("crescent_pike-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "7.5%", max_value: "34.5%" },
  },
  [WeaponIds.CrimsonMoonsSemblance]: WeaponClass.init([
    WeaponIds.CrimsonMoonsSemblance,
    "Очертания алой луны",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.DarkIronSword]: {
    id: WeaponIds.DarkIronSword,
    title: "Тёмный железный меч",
    image_src: imageSrc("dark_iron_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "31", max_value: "141" },
  },
  [WeaponIds.Deathmatch]: {
    id: WeaponIds.Deathmatch,
    title: "Смертельный бой",
    image_src: imageSrc("deathmatch-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.CritRate, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.DebateClub]: {
    id: WeaponIds.DebateClub,
    title: "Дубина переговоров",
    image_src: imageSrc("debate_club-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.DialoguesOfTheDesertSages]: WeaponClass.init([
    WeaponIds.DialoguesOfTheDesertSages,
    "Диалог пустынных мудрецов",
    4,
    "Событие версии 4.5 «Алхимический прорыв»",
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.DodocoTales]: {
    id: WeaponIds.DodocoTales,
    title: "Истории Додоко",
    rarity: 4,
    source: "Событие версии 1.6 «Лето! Остров? Приключение!»",
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("dodoco_tales-256x256.webp"),
  },
  [WeaponIds.DragonsBane]: {
    id: WeaponIds.DragonsBane,
    title: "Гроза драконов",
    image_src: imageSrc("dragons_bane-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "48", max_value: "221" },
  },
  [WeaponIds.DragonspineSpear]: WeaponClass.init([
    WeaponIds.DragonspineSpear,
    "Копьё Драконьего хребта",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 41, max_value: 454 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.EarthShaker]: WeaponClass.init([
    WeaponIds.EarthShaker,
    "Сотрясающий землю",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.ElegyForTheEnd]: WeaponClass.init([
    WeaponIds.ElegyForTheEnd,
    "Элегия погибели",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.EmeraldOrb]: WeaponClass.init([
    WeaponIds.EmeraldOrb,
    "Изумрудный шар",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 40, max_value: 448 },
    StatIds.ElementalMastery,
    { min_value: 20, max_value: 94 },
  ]),
  [WeaponIds.EndOfTheLine]: WeaponClass.init([
    WeaponIds.EndOfTheLine,
    "Иссушитель",
    4,
    "Ассоциация рыболовов Сумеру",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.EngulfingLightning]: WeaponClass.init([
    WeaponIds.EngulfingLightning,
    "Сияющая жатва",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.EverlastingMoonglow]: {
    id: WeaponIds.EverlastingMoonglow,
    title: "Вечное лунное сияние",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("everlasting_moonglow-256x256.webp"),
  },
  [WeaponIds.EyeOfPerception]: {
    id: WeaponIds.EyeOfPerception,
    title: "Око сознания",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("eye_of_perception-256x256.webp"),
  },
  [WeaponIds.FadingTwilight]: WeaponClass.init([
    WeaponIds.FadingTwilight,
    "Гаснущие сумерки",
    4,
    "Событие версии 2.7 «Опасная тропа»",
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.FangOfTheMountainKing]: WeaponClass.init([
    WeaponIds.FangOfTheMountainKing,
    "Клык Горного короля",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 49, max_value: 741 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.024, 1), max_value: numberFormatPercent(0.110, 1) },
  ]),
  [WeaponIds.FavoniusCodex]: WeaponClass.init([
    WeaponIds.FavoniusCodex,
    "Кодекс Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FavoniusGreatsword]: WeaponClass.init([
    WeaponIds.FavoniusGreatsword,
    "Двуручный меч Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.FavoniusLance]: WeaponClass.init([
    WeaponIds.FavoniusLance,
    "Копьё Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.FavoniusSword]: WeaponClass.init([
    WeaponIds.FavoniusSword,
    "Меч Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.FavoniusWarbow]: WeaponClass.init([
    WeaponIds.FavoniusWarbow,
    "Боевой лук Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.FerrousShadow]: WeaponClass.init([
    WeaponIds.FerrousShadow,
    "Металлическая тень",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 39, max_value: 401 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.FesteringDesire]: WeaponClass.init([
    WeaponIds.FesteringDesire,
    "Осквернённое желание",
    4,
    "Событие версии 1.2 «Принц мела и дракон»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FilletBlade]: {
    id: WeaponIds.FilletBlade,
    title: "Филейный нож",
    image_src: imageSrc("fillet_blade-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Atk, min_value: "7.7%", max_value: "35.2%" },
  },
  [WeaponIds.FinaleOfTheDeep]: WeaponClass.init([
    WeaponIds.FinaleOfTheDeep,
    "Грандиозный финал глубин",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.FlameForgedInsight]: WeaponClass.init([
    WeaponIds.FlameForgedInsight,
    "Выкованное пламенем озарение",
    4,
    "Событие версии 5.8 «Лето! Жара? Курорт!»",
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.FleuveCendreFerryman]: WeaponClass.init([
    WeaponIds.FleuveCendreFerryman,
    "Перевозчик Флёв Сандр",
    4,
    "Обмен в Ассоциации рыболовов Фонтейна",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FlowerWreathedFeathers]: WeaponClass.init([
    WeaponIds.FlowerWreathedFeathers,
    "Украшенные цветами перья",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.FlowingPurity]: WeaponClass.init([
    WeaponIds.FlowingPurity,
    "Сверкание чистых вод",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.FluteOfEzpitzal]: WeaponClass.init([
    WeaponIds.FluteOfEzpitzal,
    "Флейта Эспицаль",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.FootprintOfTheRainbow]: WeaponClass.init([
    WeaponIds.FootprintOfTheRainbow,
    "След радуги",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.113, 1), max_value: numberFormatPercent(0.517, 1) },
  ]),
  [WeaponIds.ForestRegalia]: WeaponClass.init([
    WeaponIds.ForestRegalia,
    "Регалия леса",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.FracturedHalo]: WeaponClass.init([
    WeaponIds.FracturedHalo,
    "Расколотый ореол",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.FreedomSworn]: WeaponClass.init([
    WeaponIds.FreedomSworn,
    "Клятва свободы",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 46, max_value: 608 },
    StatIds.ElementalMastery,
    { min_value: 43, max_value: 198 },
  ]),
  [WeaponIds.Frostbearer]: {
    id: WeaponIds.Frostbearer,
    title: "Плод вечной мерзлоты",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("frostbearer-256x256.webp"),
  },
  [WeaponIds.FruitOfFulfillment]: WeaponClass.init([
    WeaponIds.FruitOfFulfillment,
    "Плод восполнения",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FruitfulHook]: WeaponClass.init([
    WeaponIds.FruitfulHook,
    "Плодотворный крюк",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.HakushinRing]: {
    id: WeaponIds.HakushinRing,
    title: "Кольцо Хакусин",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("hakushin_ring-256x256.webp"),
  },
  [WeaponIds.Halberd]: WeaponClass.init([
    WeaponIds.Halberd,
    "Алебарда Миллелита",
    3,
    "Сундуки Ли Юэ",
    WeaponTypeIds.Polearm,
    { min_value: 40, max_value: 448 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.051, 1), max_value: numberFormatPercent(0.235, 1) },
  ]),
  [WeaponIds.Hamayumi]: {
    id: WeaponIds.Hamayumi,
    title: "Хамаюми",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("hamayumi-256x256.webp"),
  },
  [WeaponIds.HaranGeppakuFutsu]: {
    id: WeaponIds.HaranGeppakuFutsu,
    title: "Харан гэппаку фуцу",
    image_src: imageSrc("haran_geppaku_futsu-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.CritRate, min_value: "7.2%", max_value: "33.1%" },
  },
  [WeaponIds.HarbingerOfDawn]: WeaponClass.init([
    WeaponIds.HarbingerOfDawn,
    "Предвестник зари",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 401 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.102, 1), max_value: numberFormatPercent(0.469, 1) },
  ]),
  [WeaponIds.HuntersPath]: WeaponClass.init([
    WeaponIds.HuntersPath,
    "Охотничья тропа",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 542 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.IbisPiercer]: WeaponClass.init([
    WeaponIds.IbisPiercer,
    "Клюв ибиса",
    4,
    "Событие версии 3.7 «Дуэль! К вершинам карточного мастерства!»",
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.IronSting]: WeaponClass.init([
    WeaponIds.IronSting,
    "Стальное жало",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.JadefallsSplendor]: WeaponClass.init([
    WeaponIds.JadefallsSplendor,
    "Великолепие лазурного свода",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 46, max_value: 608 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.KagotsurubeIsshin]: WeaponClass.init([
    WeaponIds.KagotsurubeIsshin,
    "Кагоцурубэ Иссин",
    4,
    "Задание легенд Кадзухи «Рыжий клён. Глава I. Странная безлюдная дорога»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.KagurasVerity]: {
    id: WeaponIds.KagurasVerity,
    title: "Истина кагура",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.144, 1),
      max_value: numberFormatPercent(0.662, 1),
    },
    image_src: imageSrc("kaguras_verity-256x256.webp"),
  },
  [WeaponIds.KatsuragikiriNagamasa]: {
    id: WeaponIds.KatsuragikiriNagamasa,
    title: "Кацурагикири Нагамаса",
    image_src: imageSrc("katsuragikiri_nagamasa-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.KeyOfKhajNisut]: WeaponClass.init([
    WeaponIds.KeyOfKhajNisut,
    "Ключ Хадж-нисут",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.KingsSquire]: WeaponClass.init([
    WeaponIds.KingsSquire,
    "Приближённый короля",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.KitainCrossSpear]: {
    id: WeaponIds.KitainCrossSpear,
    title: "Крест-копьё Китаин",
    image_src: imageSrc("kitain_cross_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "24", max_value: "110" },
  },
  [WeaponIds.LightOfFoliarIncision]: WeaponClass.init([
    WeaponIds.LightOfFoliarIncision,
    "Свет лиственного разреза",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.LightweaversLute]: WeaponClass.init([
    WeaponIds.LightweaversLute,
    "Лютня ткача света",
    4,
    undefined,
    WeaponTypeIds.Catalyst,
    { min_value: 510, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.459, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.LionsRoar]: {
    id: WeaponIds.LionsRoar,
    title: "Драконий рык",
    image_src: imageSrc("lions_roar-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.LithicBlade]: {
    id: WeaponIds.LithicBlade,
    title: "Каменный меч",
    image_src: imageSrc("lithic_blade-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.LithicSpear]: {
    id: WeaponIds.LithicSpear,
    title: "Каменное копьё",
    image_src: imageSrc("lithic_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.LostPrayerToTheSacredWinds]: {
    id: WeaponIds.LostPrayerToTheSacredWinds,
    title: "Молитва святым ветрам",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("lost_prayer_to_the_sacred_winds-256x256.webp"),
  },
  [WeaponIds.LumidouceElegy]: WeaponClass.init([
    WeaponIds.LumidouceElegy,
    "Элегия Люмидус",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.LuxuriousSeaLord]: WeaponClass.init([
    WeaponIds.LuxuriousSeaLord,
    "Благодатный владыка вод",
    4,
    "Событие версии 2.1 «Лунное утешение»",
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.MagicGuide]: WeaponClass.init([
    WeaponIds.MagicGuide,
    "Руководство по магии",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 38, max_value: 354 },
    StatIds.ElementalMastery,
    { min_value: 41, max_value: 187 },
  ]),
  [WeaponIds.MailedFlower]: WeaponClass.init([
    WeaponIds.MailedFlower,
    "Цветок в латах",
    4,
    "Событие версии 3.5 «Дыхание анемонии»",
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.ElementalMastery,
    { min_value: 24, max_value: 110 },
  ]),
  [WeaponIds.MakhairaAquamarine]: WeaponClass.init([
    WeaponIds.MakhairaAquamarine,
    "Аквамарин Махайры",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.MappaMare]: {
    id: WeaponIds.MappaMare,
    title: "Морской атлас",
    rarity: 4,
    source: WeaponSource.Forged,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 24, max_value: 110 },
    image_src: imageSrc("mappa_mare-256x256.webp"),
  },
  [WeaponIds.MasterKey]: WeaponClass.init([
    WeaponIds.MasterKey,
    "Мастер-ключ",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.MemoryOfDust]: {
    id: WeaponIds.MemoryOfDust,
    title: "Память о пыли",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.108, 1),
      max_value: numberFormatPercent(0.496, 1),
    },
    image_src: imageSrc("memory_of_dust-256x256.webp"),
  },
  [WeaponIds.Messenger]: {
    id: WeaponIds.Messenger,
    title: "Посыльный",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("messenger-256x256.webp"),
  },
  [WeaponIds.MissiveWindspear]: WeaponClass.init([
    WeaponIds.MissiveWindspear,
    "Копьё послания ветров",
    4,
    "Событие версии 3.1 «О балладах и кубках»",
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.MistsplitterReforged]: WeaponClass.init([
    WeaponIds.MistsplitterReforged,
    "Рассекающий туман",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.MitternachtsWaltz]: {
    id: WeaponIds.MitternachtsWaltz,
    title: "Вальс Нирваны Ночи",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.PhysicalDmgBonus,
      min_value: numberFormatPercent(0.113, 1),
      max_value: numberFormatPercent(0.517, 1),
    },
    image_src: imageSrc("mitternachts_waltz-256x256.webp"),
  },
  [WeaponIds.Moonpiercer]: WeaponClass.init([
    WeaponIds.Moonpiercer,
    "Пронзающий луну",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.ElementalMastery,
    { min_value: 24, max_value: 110 },
  ]),
  [WeaponIds.MoonweaversDawn]: WeaponClass.init([
    WeaponIds.MoonweaversDawn,
    "Рассвет прядильщицы луны",
    4,
    "Задание мира «Полька под луной»",
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.MountainBracingBolt]: WeaponClass.init([
    WeaponIds.MountainBracingBolt,
    "Крепящий горы шип",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.MouunsMoon]: {
    id: WeaponIds.MouunsMoon,
    title: "Луна Моун",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("mouuns_moon-256x256.webp"),
  },
  [WeaponIds.NightweaversLookingGlass]: WeaponClass.init([
    WeaponIds.NightweaversLookingGlass,
    "Зеркало прядильщицы ночи",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.OathswornEye]: WeaponClass.init([
    WeaponIds.OathswornEye,
    "Око клятвы",
    4,
    "Событие версии 2.5 «Подношение врат трёх миров»",
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.OtherworldlyStory]: {
    id: WeaponIds.OtherworldlyStory,
    title: "Потусторонняя история",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.085, 1),
      max_value: numberFormatPercent(0.390, 1),
    },
    image_src: imageSrc("otherworldly_story-256x256.webp"),
  },
  [WeaponIds.PeakPatrolSong]: WeaponClass.init([
    WeaponIds.PeakPatrolSong,
    "Песнь патруля пиков",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.180, 1), max_value: numberFormatPercent(0.827, 1) },
  ]),
  [WeaponIds.PolarStar]: {
    id: WeaponIds.PolarStar,
    title: "Полярная звезда",
    rarity: 5,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 46, max_value: 608 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("polar_star-256x256.webp"),
  },
  [WeaponIds.PortablePowerSaw]: WeaponClass.init([
    WeaponIds.PortablePowerSaw,
    "Переносная мотопила",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.Predator]: {
    id: WeaponIds.Predator,
    title: "Хищник",
    rarity: 4,
    source: "Внутриигровая почта \"PlayStation Network\"",
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("predator-512x512.webp"),
  },
  [WeaponIds.PrimordialJadeCutter]: {
    id: WeaponIds.PrimordialJadeCutter,
    title: "Драгоценный омут",
    image_src: imageSrc("primordial_jade_cutter-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "44", max_value: "542" },
    secondary_stats: { id: StatIds.CritRate, min_value: "9.6%", max_value: "44.1%" },
  },
  [WeaponIds.PrimordialJadeWingedSpear]: {
    id: WeaponIds.PrimordialJadeWingedSpear,
    title: "Нефритовый коршун",
    image_src: imageSrc("primordial_jade_winged_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.CritRate, min_value: "4.8%", max_value: "22.1%" },
  },
  [WeaponIds.ProspectorsDrill]: WeaponClass.init([
    WeaponIds.ProspectorsDrill,
    "Бур рудоискателя",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.ProspectorsShovel]: WeaponClass.init([
    WeaponIds.ProspectorsShovel,
    "Лопата старателя",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrototypeAmber]: WeaponClass.init([
    WeaponIds.PrototypeAmber,
    "Прототип: Янтарь",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrototypeArchaic]: WeaponClass.init([
    WeaponIds.PrototypeArchaic,
    "Прототип: Архаичный",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.PrototypeCrescent]: WeaponClass.init([
    WeaponIds.PrototypeCrescent,
    "Прототип: Полумесяц",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrototypeRancour]: WeaponClass.init([
    WeaponIds.PrototypeRancour,
    "Прототип: Злоба",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.075, 1), max_value: numberFormatPercent(0.345, 1) },
  ]),
  [WeaponIds.PrototypeStarglitter]: WeaponClass.init([
    WeaponIds.PrototypeStarglitter,
    "Прототип: Звёздный блеск",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.Rainslasher]: WeaponClass.init([
    WeaponIds.Rainslasher,
    "Дождерез",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.RangeGauge]: WeaponClass.init([
    WeaponIds.RangeGauge,
    "Дальномер",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.RavenBow]: WeaponClass.init([
    WeaponIds.RavenBow,
    "Лук ворона",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 40, max_value: 448 },
    StatIds.ElementalMastery,
    { min_value: 20, max_value: 94 },
  ]),
  [WeaponIds.RecurveBow]: {
    id: WeaponIds.RecurveBow,
    title: "Изогнутый лук",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_stats: {
      id: StatIds.HpPercentage,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("recurve_bow-256x256.webp"),
  },
  [WeaponIds.RedhornStonethresher]: WeaponClass.init([
    WeaponIds.RedhornStonethresher,
    "Краснорогий камнеруб",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.RightfulReward]: WeaponClass.init([
    WeaponIds.RightfulReward,
    "Справедливая награда",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.RingOfYaxche]: WeaponClass.init([
    WeaponIds.RingOfYaxche,
    "Кольцо Яшче",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.RoyalBow]: {
    id: WeaponIds.RoyalBow,
    title: "Королевский лук",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("royal_bow-256x256.webp"),
  },
  [WeaponIds.RoyalGreatsword]: {
    id: WeaponIds.RoyalGreatsword,
    title: "Королевский двуручный меч",
    image_src: imageSrc("royal_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.RoyalGrimoire]: {
    id: WeaponIds.RoyalGrimoire,
    title: "Королевский гримуар",
    rarity: 4,
    source: WeaponSource.PaimonsBargains,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("royal_grimoire-256x256.webp"),
  },
  [WeaponIds.RoyalLongsword]: {
    id: WeaponIds.RoyalLongsword,
    title: "Меч аристократов",
    image_src: imageSrc("royal_longsword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Atk, min_value: "9%", max_value: "41.3%" },
  },
  [WeaponIds.RoyalSpear]: {
    id: WeaponIds.RoyalSpear,
    title: "Королевское копьё",
    image_src: imageSrc("royal_spear-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.Atk, min_value: "6%", max_value: "27.6%" },
  },
  [WeaponIds.Rust]: {
    id: WeaponIds.Rust,
    title: "Ржавый лук",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.090, 1),
      max_value: numberFormatPercent(0.413, 1),
    },
    image_src: imageSrc("rust-256x256.webp"),
  },
  [WeaponIds.SacrificialBow]: {
    id: WeaponIds.SacrificialBow,
    title: "Церемониальный лук",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("sacrificial_bow-256x256.webp"),
  },
  [WeaponIds.SacrificialFragments]: {
    id: WeaponIds.SacrificialFragments,
    title: "Церемониальные мемуары",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 41, max_value: 454 },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: 48, max_value: 221 },
    image_src: imageSrc("sacrificial_fragments-256x256.webp"),
  },
  [WeaponIds.SacrificialGreatsword]: {
    id: WeaponIds.SacrificialGreatsword,
    title: "Церемониальный двуручный меч",
    image_src: imageSrc("sacrificial_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "44", max_value: "565" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "6.7%", max_value: "30.6%" },
  },
  [WeaponIds.SacrificialJade]: WeaponClass.init([
    WeaponIds.SacrificialJade,
    "Жертвенный нефрит",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.SacrificialSword]: {
    id: WeaponIds.SacrificialSword,
    title: "Церемониальный меч",
    image_src: imageSrc("sacrificial_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "41", max_value: "454" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "13.3%", max_value: "61.3%" },
  },
  [WeaponIds.SapwoodBlade]: WeaponClass.init([
    WeaponIds.SapwoodBlade,
    "Деревянный клинок",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.ScionOfTheBlazingSun]: WeaponClass.init([
    WeaponIds.ScionOfTheBlazingSun,
    "Наследник слепящего солнца",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.040, 1), max_value: numberFormatPercent(0.184, 1) },
  ]),
  [WeaponIds.SequenceOfSolitude]: WeaponClass.init([
    WeaponIds.SequenceOfSolitude,
    "Каденция одиночества",
    4,
    "Событие версии 5.6 «Кружащийся вальс»",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SerenitysCall]: WeaponClass.init([
    WeaponIds.SerenitysCall,
    "Зов безмятежности",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.SerpentSpine]: WeaponClass.init([
    WeaponIds.SerpentSpine,
    "Меч драконьей кости",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.SharpshootersOath]: {
    id: WeaponIds.SharpshootersOath,
    title: "Клятва стрелка",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 39, max_value: 401 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.102, 1),
      max_value: numberFormatPercent(0.469, 1),
    },
    image_src: imageSrc("sharpshooters_oath-256x256.webp"),
  },
  [WeaponIds.SilvershowerHeartstrings]: WeaponClass.init([
    WeaponIds.SilvershowerHeartstrings,
    "Сердечные струны дождя",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 542 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.SkyriderGreatsword]: WeaponClass.init([
    WeaponIds.SkyriderGreatsword,
    "Большой меч небесного всадника",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Claymore,
    { min_value: 39, max_value: 401 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.439, 1) },
  ]),
  [WeaponIds.SkyriderSword]: WeaponClass.init([
    WeaponIds.SkyriderSword,
    "Меч небесного всадника",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 38, max_value: 354 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.113, 1), max_value: numberFormatPercent(0.521, 1) },
  ]),
  [WeaponIds.SkywardAtlas]: {
    id: WeaponIds.SkywardAtlas,
    title: "Небесный атлас",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.AtkPercentage,
      min_value: numberFormatPercent(0.072, 1),
      max_value: numberFormatPercent(0.331, 1),
    },
    image_src: imageSrc("skyward_atlas-256x256.webp"),
  },
  [WeaponIds.SkywardBlade]: {
    id: WeaponIds.SkywardBlade,
    title: "Небесный меч",
    image_src: imageSrc("skyward_blade-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "12%", max_value: "55.1%" },
  },
  [WeaponIds.SkywardHarp]: {
    id: WeaponIds.SkywardHarp,
    title: "Небесное крыло",
    rarity: 5,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 48, max_value: 674 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.048, 1),
      max_value: numberFormatPercent(0.221, 1),
    },
    image_src: imageSrc("skyward_harp-256x256.webp"),
  },
  [WeaponIds.SkywardPride]: {
    id: WeaponIds.SkywardPride,
    title: "Небесное величие",
    image_src: imageSrc("skyward_pride-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.SkywardSpine]: {
    id: WeaponIds.SkywardSpine,
    title: "Небесная ось",
    image_src: imageSrc("skyward_spine-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "48", max_value: "674" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "8%", max_value: "36.8%" },
  },
  [WeaponIds.Slingshot]: {
    id: WeaponIds.Slingshot,
    title: "Рогатка",
    rarity: 3,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Bow,
    base_atk: { min_value: 38, max_value: 354 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.068, 1),
      max_value: numberFormatPercent(0.312, 1),
    },
    image_src: imageSrc("slingshot-256x256.webp"),
  },
  [WeaponIds.SnareHook]: WeaponClass.init([
    WeaponIds.SnareHook,
    "Крюк силка",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.SnowTombedStarsilver]: WeaponClass.init([
    WeaponIds.SnowTombedStarsilver,
    "Заснеженное звёздное серебро",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.075, 1), max_value: numberFormatPercent(0.345, 1) },
  ]),
  [WeaponIds.SolarPearl]: {
    id: WeaponIds.SolarPearl,
    title: "Солнечная жемчужина",
    rarity: 4,
    source: WeaponSource.BattlePass,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.060, 1),
      max_value: numberFormatPercent(0.276, 1),
    },
    image_src: imageSrc("solar_pearl-256x256.webp"),
  },
  [WeaponIds.SongOfBrokenPines]: {
    id: WeaponIds.SongOfBrokenPines,
    title: "Песнь разбитых сосен",
    image_src: imageSrc("song_of_broken_pines-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "49", max_value: "741" },
    secondary_stats: { id: StatIds.PhysicalDmgBonus, min_value: "4.5%", max_value: "20.7%" },
  },
  [WeaponIds.SongOfStillness]: WeaponClass.init([
    WeaponIds.SongOfStillness,
    "Мелодия покоя",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SplendorOfTranquilWaters]: WeaponClass.init([
    WeaponIds.SplendorOfTranquilWaters,
    "Блеск тихих вод",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.StaffOfHoma]: {
    id: WeaponIds.StaffOfHoma,
    title: "Посох Хомы",
    image_src: imageSrc("staff_of_homa-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.CritDMG, min_value: "14.4%", max_value: "66.2%" },
  },
  [WeaponIds.StaffOfTheScarletSands]: WeaponClass.init([
    WeaponIds.StaffOfTheScarletSands,
    "Посох алых песков",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 542 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.StarcallersWatch]: WeaponClass.init([
    WeaponIds.StarcallersWatch,
    "Бдение взывающего к звёздам",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.SturdyBone]: WeaponClass.init([
    WeaponIds.SturdyBone,
    "Крепкая кость",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.SummitShaper]: {
    id: WeaponIds.SummitShaper,
    title: "Кромсатель пиков",
    image_src: imageSrc("summit_shaper-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.SunnyMorningSleepIn]: WeaponClass.init([
    WeaponIds.SunnyMorningSleepIn,
    "Сон солнечным утром",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.SurfsUp]: WeaponClass.init([
    WeaponIds.SurfsUp,
    "Лови волну",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.SwordOfDescension]: WeaponClass.init([
    WeaponIds.SwordOfDescension,
    "Меч нисхождения",
    4,
    "Внутриигровая почта \"PlayStation Network\"",
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 440 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.SwordOfNarzissenkreuz]: WeaponClass.init([
    WeaponIds.SwordOfNarzissenkreuz,
    "Меч Нарциссенкрейца",
    4,
    "Серия заданий мира «По следам Нарцисса»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SymphonistOfScents]: WeaponClass.init([
    WeaponIds.SymphonistOfScents,
    "Симфонист ароматов",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.TalkingStick]: WeaponClass.init([
    WeaponIds.TalkingStick,
    "Говорящая палица",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.040, 1), max_value: numberFormatPercent(0.184, 1) },
  ]),
  [WeaponIds.TamayurateiNoOhanashi]: WeaponClass.init([
    WeaponIds.TamayurateiNoOhanashi,
    "Тамаюратэй но оханаси",
    4,
    "Событие версии 5.4 «Чудесные истории фестиваля Микавы»",
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.TheAlleyFlash]: {
    id: WeaponIds.TheAlleyFlash,
    title: "Вспышка во тьме",
    image_src: imageSrc("the_alley_flash-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 4,
    base_atk: { min_value: "45", max_value: "620" },
    secondary_stats: { id: StatIds.ElementalMastery, min_value: "12", max_value: "55" },
  },
  [WeaponIds.TheBell]: WeaponClass.init([
    WeaponIds.TheBell,
    "Меч-колокол",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TheBlackSword]: WeaponClass.init([
    WeaponIds.TheBlackSword,
    "Чёрный меч",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.TheCatch]: {
    id: WeaponIds.TheCatch,
    title: "«Улов»",
    image_src: imageSrc("the_catch-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.EnergyRecharge, min_value: "10.0%", max_value: "45.9%" },
  },
  [WeaponIds.TheDockhandsAssistant]: WeaponClass.init([
    WeaponIds.TheDockhandsAssistant,
    "Верфь",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TheFirstGreatMagic]: WeaponClass.init([
    WeaponIds.TheFirstGreatMagic,
    "Первый великий фокус",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.TheFlute]: WeaponClass.init([
    WeaponIds.TheFlute,
    "Меч-флейта",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TheStringless]: WeaponClass.init([
    WeaponIds.TheStringless,
    "Бесструнный",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.TheUnforged]: {
    id: WeaponIds.TheUnforged,
    title: "Некованый",
    image_src: imageSrc("the_unforged-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.TheViridescentHunt]: WeaponClass.init([
    WeaponIds.TheViridescentHunt,
    "Зелёный лук",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.TheWidsith]: {
    id: WeaponIds.TheWidsith,
    title: "Песнь странника",
    rarity: 4,
    source: WeaponSource.Wish,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 42, max_value: 510 },
    secondary_stats: {
      id: StatIds.CritDMG,
      min_value: numberFormatPercent(0.120, 1),
      max_value: numberFormatPercent(0.551, 1),
    },
    image_src: imageSrc("the_widsith-256x256.webp"),
  },
  [WeaponIds.ThrillingTalesOfDragonSlayers]: WeaponClass.init([
    WeaponIds.ThrillingTalesOfDragonSlayers,
    "Эпос о драконоборцах",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 39, max_value: 401 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.ThunderingPulse]: WeaponClass.init([
    WeaponIds.ThunderingPulse,
    "Громовой пульс",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.TidalShadow]: WeaponClass.init([
    WeaponIds.TidalShadow,
    "Тень волны",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TomeOfTheEternalFlow]: WeaponClass.init([
    WeaponIds.TomeOfTheEternalFlow,
    "Обряд вечного течения",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.ToukabouShigure]: WeaponClass.init([
    WeaponIds.ToukabouShigure,
    "Токабо сигурэ",
    4,
    "Событие версии 3.3 «Акицу Кимодамэси»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.TravelersHandySword]: {
    id: WeaponIds.TravelersHandySword,
    title: "Меч путешественника",
    image_src: imageSrc("travelers_handy_sword-256x256.png"),
    type_id: WeaponTypeIds.Sword,
    rarity: 3,
    base_atk: { min_value: "40", max_value: "448" },
    secondary_stats: { id: StatIds.Def, min_value: "6.4%", max_value: "29.3%" },
  },
  [WeaponIds.TulaytullahsRemembrance]: WeaponClass.init([
    WeaponIds.TulaytullahsRemembrance,
    "Воспоминания Тулайтуллы",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.TwinNephrite]: {
    id: WeaponIds.TwinNephrite,
    title: "Парный нефрит",
    rarity: 3,
    source: WeaponSource.Chests,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 40, max_value: 448 },
    secondary_stats: {
      id: StatIds.CritRate,
      min_value: numberFormatPercent(0.034, 1),
      max_value: numberFormatPercent(0.156, 1),
    },
    image_src: imageSrc("twin_nephrite-256x256.webp"),
  },
  [WeaponIds.UltimateOverlordsMegaMagicSword]: WeaponClass.init([
    WeaponIds.UltimateOverlordsMegaMagicSword,
    "«Магический супермеч высшего владыки»",
    4,
    "Событие версии 4.3 «Розы и мушкеты»",
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.UrakuMisugiri]: WeaponClass.init([
    WeaponIds.UrakuMisugiri,
    "Ураку мисугири",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.Verdict]: WeaponClass.init([
    WeaponIds.Verdict,
    "Вердикт",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.VividNotions]: WeaponClass.init([
    WeaponIds.VividNotions,
    "Переливающиеся чаяния",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.VortexVanquisher]: WeaponClass.init([
    WeaponIds.VortexVanquisher,
    "Покоритель вихря",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.WanderingEvenstar]: WeaponClass.init([
    WeaponIds.WanderingEvenstar,
    "Скитающаяся звезда",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.WavebreakersFin]: {
    id: WeaponIds.WavebreakersFin,
    title: "Режущий волны плавник",
    image_src: imageSrc("wavebreakers_fin-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 4,
    base_atk: { min_value: "45", max_value: "620" },
    secondary_stats: { id: StatIds.Atk, min_value: "3%", max_value: "13.8%" },
  },
  [WeaponIds.WaveridingWhirl]: WeaponClass.init([
    WeaponIds.WaveridingWhirl,
    "Вихрь на волнах",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.WhiteIronGreatsword]: {
    id: WeaponIds.WhiteIronGreatsword,
    title: "Меч из белого железа",
    image_src: imageSrc("white_iron_greatsword-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.Def, min_value: "9.6%", max_value: "43.9%" },
  },
  [WeaponIds.WhiteTassel]: {
    id: WeaponIds.WhiteTassel,
    title: "Белая кисть",
    image_src: imageSrc("white_tassel-256x256.png"),
    type_id: WeaponTypeIds.Polearm,
    rarity: 3,
    base_atk: { min_value: "39", max_value: "401" },
    secondary_stats: { id: StatIds.CritRate, min_value: "5.1%", max_value: "23.4%" },
  },
  [WeaponIds.Whiteblind]: {
    id: WeaponIds.Whiteblind,
    title: "Белая тень",
    image_src: imageSrc("whiteblind-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 4,
    base_atk: { min_value: "42", max_value: "510" },
    secondary_stats: { id: StatIds.Def, min_value: "11.3%", max_value: "51.7%" },
  },
  [WeaponIds.WindblumeOde]: WeaponClass.init([
    WeaponIds.WindblumeOde,
    "Ода анемонии",
    4,
    "Событие версии 1.4 «Приглашение ветряных цветов»",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.WineAndSong]: {
    id: WeaponIds.WineAndSong,
    title: "Вино и песни",
    rarity: 4,
    source: WeaponSource.EventWishExclusive,
    type_id: WeaponTypeIds.Catalyst,
    base_atk: { min_value: 44, max_value: 565 },
    secondary_stats: {
      id: StatIds.EnergyRecharge,
      min_value: numberFormatPercent(0.067, 1),
      max_value: numberFormatPercent(0.306, 1),
    },
    image_src: imageSrc("wine_and_song-256x256.webp"),
  },
  [WeaponIds.WolfFang]: WeaponClass.init([
    WeaponIds.WolfFang,
    "Волчий клык",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.WolfsGravestone]: {
    id: WeaponIds.WolfsGravestone,
    title: "Волчья погибель",
    image_src: imageSrc("wolfs_gravestone-256x256.png"),
    type_id: WeaponTypeIds.Claymore,
    rarity: 5,
    base_atk: { min_value: "46", max_value: "608" },
    secondary_stats: { id: StatIds.Atk, min_value: "10.8%", max_value: "49.6%" },
  },
  [WeaponIds.XiphosMoonlight]: WeaponClass.init([
    WeaponIds.XiphosMoonlight,
    "Лунное сияние ксифоса",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
} as Record<Weapon["id"], Weapon>;
