import type { Weapon } from "./types";
import { numberFormatPercent, publicImageSrc } from "@/lib/utils";
import { StatIds } from "../stats/enums";
import { WeaponIds } from "./enums";
import { WeaponTypeIds } from "../weapon-types/enums";

class WeaponClass implements Weapon {
  readonly id: Weapon["id"];
  readonly image_src: Weapon["image_src"];
  readonly title: Weapon["title"];
  readonly rarity: Weapon["rarity"];
  readonly source: Weapon["source"];
  readonly type_id: Weapon["type_id"];
  readonly base_atk: Weapon["base_atk"];
  readonly secondary_stats_id: Weapon["secondary_stats_id"];
  readonly secondary_stats: Weapon["secondary_stats"];

  static PATH = "weapons";

  constructor(
    id: Weapon["id"],
    title: Weapon["title"],
    rarity: Weapon["rarity"],
    source: Weapon["source"],
    typeId: Weapon["type_id"],
    baseAtk: Weapon["base_atk"],
    secondaryStatsId: Weapon["secondary_stats_id"],
    secondaryStats: Weapon["secondary_stats"],
  ) {
    this.id = id;
    this.image_src = publicImageSrc(`${WeaponClass.PATH}/${id}.webp`);
    this.title = title;
    this.rarity = rarity;
    this.source = source;
    this.type_id = typeId;
    this.base_atk = baseAtk;
    this.secondary_stats_id = secondaryStatsId;
    this.secondary_stats = secondaryStats;
  }

  static init(params: ConstructorParameters<typeof WeaponClass>) {
    return new WeaponClass(...params);
  }
}

const WeaponSource = {
  BattlePass: "Выбираемая награда при достижении 30 уровня боевого пропуска (Жемчужный гимн)",
  Chests: "Сундуки",
  EventWishExclusive: "Эксклюзивное оружие Молитвы события",
  Forged: "Кузница",
  PaimonsBargains: "Обмен Звёздного блеска в магазине Паймон",
  Wish: "Молитвы",
} as const;

export default {
  [WeaponIds.AThousandBlazingSuns]: WeaponClass.init([
    WeaponIds.AThousandBlazingSuns,
    "Тысяча ослепительных солнц",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 49, max_value: 741 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.024, 1), max_value: numberFormatPercent(0.110, 1) },
  ]),
  [WeaponIds.AThousandFloatingDreams]: WeaponClass.init([
    WeaponIds.AThousandFloatingDreams,
    "Сновидения тысячи ночей",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.Absolution]: WeaponClass.init([
    WeaponIds.Absolution,
    "Отпущение грехов",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.Akuoumaru]: WeaponClass.init([
    WeaponIds.Akuoumaru,
    "Акуомару",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.AlleyHunter]: WeaponClass.init([
    WeaponIds.AlleyHunter,
    "Охотник во тьме",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.AmenomaKageuchi]: WeaponClass.init([
    WeaponIds.AmenomaKageuchi,
    "Амэнома Кагэути",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.AmosBow]: WeaponClass.init([
    WeaponIds.AmosBow,
    "Лук Амоса",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.AquaSimulacra]: WeaponClass.init([
    WeaponIds.AquaSimulacra,
    "Аква симулякрум",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.AquilaFavonia]: WeaponClass.init([
    WeaponIds.AquilaFavonia,
    "Меч Сокола",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.AshGravenDrinkingHorn]: WeaponClass.init([
    WeaponIds.AshGravenDrinkingHorn,
    "Пепельный рог",
    4,
    "Событие версии 5.0 «Следы мастерства»",
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.AstralVulturesCrimsonPlumage]: WeaponClass.init([
    WeaponIds.AstralVulturesCrimsonPlumage,
    "Алое перо звёздного грифа",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.Azurelight]: WeaponClass.init([
    WeaponIds.Azurelight,
    "Лазурное сияние",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.BalladOfTheBoundlessBlue]: WeaponClass.init([
    WeaponIds.BalladOfTheBoundlessBlue,
    "Песнь необъятной лазури",
    4,
    "Событие версии 4.1 «Поэзия вод»",
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.BalladOfTheFjords]: WeaponClass.init([
    WeaponIds.BalladOfTheFjords,
    "Баллада фьордов",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.BeaconOfTheReedSea]: WeaponClass.init([
    WeaponIds.BeaconOfTheReedSea,
    "Маяк тростникового моря",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.BlackTassel]: WeaponClass.init([
    WeaponIds.BlackTassel,
    "Чёрная кисть",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 38, max_value: 354 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.102, 1), max_value: numberFormatPercent(0.469, 1) },
  ]),
  [WeaponIds.BlackcliffAgate]: WeaponClass.init([
    WeaponIds.BlackcliffAgate,
    "Черногорский агат",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.BlackcliffLongsword]: WeaponClass.init([
    WeaponIds.BlackcliffLongsword,
    "Черногорский длинный меч",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.BlackcliffPole]: WeaponClass.init([
    WeaponIds.BlackcliffPole,
    "Черногорская пика",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.BlackcliffSlasher]: WeaponClass.init([
    WeaponIds.BlackcliffSlasher,
    "Черногорская бритва",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.BlackcliffWarbow]: WeaponClass.init([
    WeaponIds.BlackcliffWarbow,
    "Черногорский боевой лук",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.BlackmarrowLantern]: WeaponClass.init([
    WeaponIds.BlackmarrowLantern,
    "Фонарь чёрной сердцевины",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.ElementalMastery,
    { min_value: 48, max_value: 221 },
  ]),
  [WeaponIds.BloodtaintedGreatsword]: WeaponClass.init([
    WeaponIds.BloodtaintedGreatsword,
    "Меч драконьей крови",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 38, max_value: 354 },
    StatIds.ElementalMastery,
    { min_value: 41, max_value: 187 },
  ]),
  [WeaponIds.CalamityOfEshu]: WeaponClass.init([
    WeaponIds.CalamityOfEshu,
    "Бедствие Эшу",
    4,
    "Событие версии 5.2 «Свитки поиска духов Иктоми»",
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.CalamityQueller]: WeaponClass.init([
    WeaponIds.CalamityQueller,
    "Усмиритель бед",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 49, max_value: 741 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.036, 1), max_value: numberFormatPercent(0.165, 1) },
  ]),
  [WeaponIds.CashflowSupervision]: WeaponClass.init([
    WeaponIds.CashflowSupervision,
    "Казначейский надзор",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.ChainBreaker]: WeaponClass.init([
    WeaponIds.ChainBreaker,
    "Разбивающий цепи",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.CinnabarSpindle]: WeaponClass.init([
    WeaponIds.CinnabarSpindle,
    "Киноварное веретено",
    4,
    "Событие версии 2.3 «Белая пыль и снежная тень»",
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.Cloudforged]: WeaponClass.init([
    WeaponIds.Cloudforged,
    "Выкованный из облаков",
    4,
    "Событие версии 4.7 «Моделирование взаимного повышения безопасности»",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.CompoundBow]: WeaponClass.init([
    WeaponIds.CompoundBow,
    "Составной лук",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.CoolSteel]: WeaponClass.init([
    WeaponIds.CoolSteel,
    "Холодное лезвие",
    3,
    [WeaponSource.Chests, WeaponSource.Wish],
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 401 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.CranesEchoingCall]: WeaponClass.init([
    WeaponIds.CranesEchoingCall,
    "Звонкий клич журавля",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 49, max_value: 741 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.036, 1), max_value: numberFormatPercent(0.165, 1) },
  ]),
  [WeaponIds.CrescentPike]: WeaponClass.init([
    WeaponIds.CrescentPike,
    "Пика полумесяца",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.075, 1), max_value: numberFormatPercent(0.345, 1) },
  ]),
  [WeaponIds.CrimsonMoonsSemblance]: WeaponClass.init([
    WeaponIds.CrimsonMoonsSemblance,
    "Очертания алой луны",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.DarkIronSword]: WeaponClass.init([
    WeaponIds.DarkIronSword,
    "Тёмный железный меч",
    3,
    ["Поговорить с Острым Чэнем в гавани Ли Юэ", "Обычный сундук в зале Ваншань"],
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 401 },
    StatIds.ElementalMastery,
    { min_value: 31, max_value: 141 },
  ]),
  [WeaponIds.Deathmatch]: WeaponClass.init([
    WeaponIds.Deathmatch,
    "Смертельный бой",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Polearm,
    { min_value: 41, max_value: 454 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.DebateClub]: WeaponClass.init([
    WeaponIds.DebateClub,
    "Дубина переговоров",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 39, max_value: 401 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.DialoguesOfTheDesertSages]: WeaponClass.init([
    WeaponIds.DialoguesOfTheDesertSages,
    "Диалог пустынных мудрецов",
    4,
    "Событие версии 4.5 «Алхимический прорыв»",
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.DodocoTales]: WeaponClass.init([
    WeaponIds.DodocoTales,
    "Истории Додоко",
    4,
    "Событие версии 1.6 «Лето! Остров? Приключение!»",
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.DragonsBane]: WeaponClass.init([
    WeaponIds.DragonsBane,
    "Гроза драконов",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 41, max_value: 454 },
    StatIds.ElementalMastery,
    { min_value: 48, max_value: 221 },
  ]),
  [WeaponIds.DragonspineSpear]: WeaponClass.init([
    WeaponIds.DragonspineSpear,
    "Копьё Драконьего хребта",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 41, max_value: 454 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.EarthShaker]: WeaponClass.init([
    WeaponIds.EarthShaker,
    "Сотрясающий землю",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.ElegyForTheEnd]: WeaponClass.init([
    WeaponIds.ElegyForTheEnd,
    "Элегия погибели",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.EmeraldOrb]: WeaponClass.init([
    WeaponIds.EmeraldOrb,
    "Изумрудный шар",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 40, max_value: 448 },
    StatIds.ElementalMastery,
    { min_value: 20, max_value: 94 },
  ]),
  [WeaponIds.EndOfTheLine]: WeaponClass.init([
    WeaponIds.EndOfTheLine,
    "Иссушитель",
    4,
    "Ассоциация рыболовов Сумеру",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.EngulfingLightning]: WeaponClass.init([
    WeaponIds.EngulfingLightning,
    "Сияющая жатва",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.EtherlightSpindlelute]: WeaponClass.init([
    WeaponIds.EtherlightSpindlelute,
    "Лютня ткача света",
    4,
    "Событие версии Луна I «Дзынь-Клац битва»",
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.EverlastingMoonglow]: WeaponClass.init([
    WeaponIds.EverlastingMoonglow,
    "Вечное лунное сияние",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 46, max_value: 608 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.EyeOfPerception]: WeaponClass.init([
    WeaponIds.EyeOfPerception,
    "Око сознания",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.FadingTwilight]: WeaponClass.init([
    WeaponIds.FadingTwilight,
    "Гаснущие сумерки",
    4,
    "Событие версии 2.7 «Опасная тропа»",
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.FangOfTheMountainKing]: WeaponClass.init([
    WeaponIds.FangOfTheMountainKing,
    "Клык Горного короля",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 49, max_value: 741 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.024, 1), max_value: numberFormatPercent(0.110, 1) },
  ]),
  [WeaponIds.FavoniusCodex]: WeaponClass.init([
    WeaponIds.FavoniusCodex,
    "Кодекс Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FavoniusGreatsword]: WeaponClass.init([
    WeaponIds.FavoniusGreatsword,
    "Двуручный меч Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.FavoniusLance]: WeaponClass.init([
    WeaponIds.FavoniusLance,
    "Копьё Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.FavoniusSword]: WeaponClass.init([
    WeaponIds.FavoniusSword,
    "Меч Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.FavoniusWarbow]: WeaponClass.init([
    WeaponIds.FavoniusWarbow,
    "Боевой лук Фавония",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.FerrousShadow]: WeaponClass.init([
    WeaponIds.FerrousShadow,
    "Металлическая тень",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 39, max_value: 401 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.FesteringDesire]: WeaponClass.init([
    WeaponIds.FesteringDesire,
    "Осквернённое желание",
    4,
    "Событие версии 1.2 «Принц мела и дракон»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FilletBlade]: WeaponClass.init([
    WeaponIds.FilletBlade,
    "Филейный нож",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 401 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.FinaleOfTheDeep]: WeaponClass.init([
    WeaponIds.FinaleOfTheDeep,
    "Грандиозный финал глубин",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.FlameForgedInsight]: WeaponClass.init([
    WeaponIds.FlameForgedInsight,
    "Выкованное пламенем озарение",
    4,
    "Событие версии 5.8 «Лето! Жара? Курорт!»",
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.FleuveCendreFerryman]: WeaponClass.init([
    WeaponIds.FleuveCendreFerryman,
    "Перевозчик Флёв Сандр",
    4,
    "Обмен в Ассоциации рыболовов Фонтейна",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FlowerWreathedFeathers]: WeaponClass.init([
    WeaponIds.FlowerWreathedFeathers,
    "Украшенные цветами перья",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.FlowingPurity]: WeaponClass.init([
    WeaponIds.FlowingPurity,
    "Сверкание чистых вод",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.FluteOfEzpitzal]: WeaponClass.init([
    WeaponIds.FluteOfEzpitzal,
    "Флейта Эспицаль",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.150, 1), max_value: numberFormatPercent(0.690, 1) },
  ]),
  [WeaponIds.FootprintOfTheRainbow]: WeaponClass.init([
    WeaponIds.FootprintOfTheRainbow,
    "След радуги",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.113, 1), max_value: numberFormatPercent(0.517, 1) },
  ]),
  [WeaponIds.ForestRegalia]: WeaponClass.init([
    WeaponIds.ForestRegalia,
    "Регалия леса",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.FracturedHalo]: WeaponClass.init([
    WeaponIds.FracturedHalo,
    "Расколотый ореол",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.FreedomSworn]: WeaponClass.init([
    WeaponIds.FreedomSworn,
    "Клятва свободы",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 46, max_value: 608 },
    StatIds.ElementalMastery,
    { min_value: 43, max_value: 198 },
  ]),
  [WeaponIds.Frostbearer]: WeaponClass.init([
    WeaponIds.Frostbearer,
    "Плод вечной мерзлоты",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.FruitOfFulfillment]: WeaponClass.init([
    WeaponIds.FruitOfFulfillment,
    "Плод восполнения",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.FruitfulHook]: WeaponClass.init([
    WeaponIds.FruitfulHook,
    "Плодотворный крюк",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.HakushinRing]: WeaponClass.init([
    WeaponIds.HakushinRing,
    "Кольцо Хакусин",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.Halberd]: WeaponClass.init([
    WeaponIds.Halberd,
    "Алебарда Миллелита",
    3,
    "Сундуки Ли Юэ",
    WeaponTypeIds.Polearm,
    { min_value: 40, max_value: 448 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.051, 1), max_value: numberFormatPercent(0.235, 1) },
  ]),
  [WeaponIds.Hamayumi]: WeaponClass.init([
    WeaponIds.Hamayumi,
    "Хамаюми",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.HaranGeppakuFutsu]: WeaponClass.init([
    WeaponIds.HaranGeppakuFutsu,
    "Харан гэппаку фуцу",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.HarbingerOfDawn]: WeaponClass.init([
    WeaponIds.HarbingerOfDawn,
    "Предвестник зари",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 401 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.102, 1), max_value: numberFormatPercent(0.469, 1) },
  ]),
  [WeaponIds.HuntersPath]: WeaponClass.init([
    WeaponIds.HuntersPath,
    "Охотничья тропа",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 542 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.IbisPiercer]: WeaponClass.init([
    WeaponIds.IbisPiercer,
    "Клюв ибиса",
    4,
    "Событие версии 3.7 «Дуэль! К вершинам карточного мастерства!»",
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.IronSting]: WeaponClass.init([
    WeaponIds.IronSting,
    "Стальное жало",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.JadefallsSplendor]: WeaponClass.init([
    WeaponIds.JadefallsSplendor,
    "Великолепие лазурного свода",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 46, max_value: 608 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.KagotsurubeIsshin]: WeaponClass.init([
    WeaponIds.KagotsurubeIsshin,
    "Кагоцурубэ Иссин",
    4,
    "Задание легенд Кадзухи «Рыжий клён. Глава I. Странная безлюдная дорога»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.KagurasVerity]: WeaponClass.init([
    WeaponIds.KagurasVerity,
    "Истина кагура",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.KatsuragikiriNagamasa]: WeaponClass.init([
    WeaponIds.KatsuragikiriNagamasa,
    "Кацурагикири Нагамаса",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.KeyOfKhajNisut]: WeaponClass.init([
    WeaponIds.KeyOfKhajNisut,
    "Ключ Хадж-нисут",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.KingsSquire]: WeaponClass.init([
    WeaponIds.KingsSquire,
    "Приближённый короля",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.KitainCrossSpear]: WeaponClass.init([
    WeaponIds.KitainCrossSpear,
    "Крест-копьё Китаин",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.ElementalMastery,
    { min_value: 24, max_value: 110 },
  ]),
  [WeaponIds.LightOfFoliarIncision]: WeaponClass.init([
    WeaponIds.LightOfFoliarIncision,
    "Свет лиственного разреза",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.LionsRoar]: WeaponClass.init([
    WeaponIds.LionsRoar,
    "Драконий рык",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.LithicBlade]: WeaponClass.init([
    WeaponIds.LithicBlade,
    "Каменный меч",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.LithicSpear]: WeaponClass.init([
    WeaponIds.LithicSpear,
    "Каменное копьё",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.LostPrayerToTheSacredWinds]: WeaponClass.init([
    WeaponIds.LostPrayerToTheSacredWinds,
    "Молитва святым ветрам",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.LumidouceElegy]: WeaponClass.init([
    WeaponIds.LumidouceElegy,
    "Элегия Люмидус",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.LuxuriousSeaLord]: WeaponClass.init([
    WeaponIds.LuxuriousSeaLord,
    "Благодатный владыка вод",
    4,
    "Событие версии 2.1 «Лунное утешение»",
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.MagicGuide]: WeaponClass.init([
    WeaponIds.MagicGuide,
    "Руководство по магии",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 38, max_value: 354 },
    StatIds.ElementalMastery,
    { min_value: 41, max_value: 187 },
  ]),
  [WeaponIds.MailedFlower]: WeaponClass.init([
    WeaponIds.MailedFlower,
    "Цветок в латах",
    4,
    "Событие версии 3.5 «Дыхание анемонии»",
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.ElementalMastery,
    { min_value: 24, max_value: 110 },
  ]),
  [WeaponIds.MakhairaAquamarine]: WeaponClass.init([
    WeaponIds.MakhairaAquamarine,
    "Аквамарин Махайры",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.MappaMare]: WeaponClass.init([
    WeaponIds.MappaMare,
    "Морской атлас",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.ElementalMastery,
    { min_value: 24, max_value: 110 },
  ]),
  [WeaponIds.MasterKey]: WeaponClass.init([
    WeaponIds.MasterKey,
    "Мастер-ключ",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.MemoryOfDust]: WeaponClass.init([
    WeaponIds.MemoryOfDust,
    "Память о пыли",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.Messenger]: WeaponClass.init([
    WeaponIds.Messenger,
    "Посыльный",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Bow,
    { min_value: 40, max_value: 448 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.068, 1), max_value: numberFormatPercent(0.312, 1) },
  ]),
  [WeaponIds.MissiveWindspear]: WeaponClass.init([
    WeaponIds.MissiveWindspear,
    "Копьё послания ветров",
    4,
    "Событие версии 3.1 «О балладах и кубках»",
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.MistsplitterReforged]: WeaponClass.init([
    WeaponIds.MistsplitterReforged,
    "Рассекающий туман",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.MitternachtsWaltz]: WeaponClass.init([
    WeaponIds.MitternachtsWaltz,
    "Вальс Нирваны Ночи",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.113, 1), max_value: numberFormatPercent(0.517, 1) },
  ]),
  [WeaponIds.Moonpiercer]: WeaponClass.init([
    WeaponIds.Moonpiercer,
    "Пронзающий луну",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.ElementalMastery,
    { min_value: 24, max_value: 110 },
  ]),
  [WeaponIds.MoonweaversDawn]: WeaponClass.init([
    WeaponIds.MoonweaversDawn,
    "Рассвет прядильщицы луны",
    4,
    "Задание мира «Полька под луной»",
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.MountainBracingBolt]: WeaponClass.init([
    WeaponIds.MountainBracingBolt,
    "Крепящий горы шип",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.MouunsMoon]: WeaponClass.init([
    WeaponIds.MouunsMoon,
    "Луна Моун",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.NightweaversLookingGlass]: WeaponClass.init([
    WeaponIds.NightweaversLookingGlass,
    "Зеркало прядильщицы ночи",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.OathswornEye]: WeaponClass.init([
    WeaponIds.OathswornEye,
    "Око клятвы",
    4,
    "Событие версии 2.5 «Подношение врат трёх миров»",
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.OtherworldlyStory]: WeaponClass.init([
    WeaponIds.OtherworldlyStory,
    "Потусторонняя история",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Catalyst,
    { min_value: 39, max_value: 401 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.085, 1), max_value: numberFormatPercent(0.390, 1) },
  ]),
  [WeaponIds.PeakPatrolSong]: WeaponClass.init([
    WeaponIds.PeakPatrolSong,
    "Песнь патруля пиков",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.180, 1), max_value: numberFormatPercent(0.827, 1) },
  ]),
  [WeaponIds.PolarStar]: WeaponClass.init([
    WeaponIds.PolarStar,
    "Полярная звезда",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.PortablePowerSaw]: WeaponClass.init([
    WeaponIds.PortablePowerSaw,
    "Переносная мотопила",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 41, max_value: 454 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.Predator]: WeaponClass.init([
    WeaponIds.Predator,
    "Хищник",
    4,
    "Внутриигровая почта \"PlayStation Network\"",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrimordialJadeCutter]: WeaponClass.init([
    WeaponIds.PrimordialJadeCutter,
    "Драгоценный омут",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.PrimordialJadeWingedSpear]: WeaponClass.init([
    WeaponIds.PrimordialJadeWingedSpear,
    "Нефритовый коршун",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.ProspectorsDrill]: WeaponClass.init([
    WeaponIds.ProspectorsDrill,
    "Бур рудоискателя",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.ProspectorsShovel]: WeaponClass.init([
    WeaponIds.ProspectorsShovel,
    "Лопата старателя",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrototypeAmber]: WeaponClass.init([
    WeaponIds.PrototypeAmber,
    "Прототип: Янтарь",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrototypeArchaic]: WeaponClass.init([
    WeaponIds.PrototypeArchaic,
    "Прототип: Архаичный",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.PrototypeCrescent]: WeaponClass.init([
    WeaponIds.PrototypeCrescent,
    "Прототип: Полумесяц",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.PrototypeRancour]: WeaponClass.init([
    WeaponIds.PrototypeRancour,
    "Прототип: Злоба",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.075, 1), max_value: numberFormatPercent(0.345, 1) },
  ]),
  [WeaponIds.PrototypeStarglitter]: WeaponClass.init([
    WeaponIds.PrototypeStarglitter,
    "Прототип: Звёздный блеск",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.Rainslasher]: WeaponClass.init([
    WeaponIds.Rainslasher,
    "Дождерез",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.RangeGauge]: WeaponClass.init([
    WeaponIds.RangeGauge,
    "Дальномер",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.RavenBow]: WeaponClass.init([
    WeaponIds.RavenBow,
    "Лук ворона",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 40, max_value: 448 },
    StatIds.ElementalMastery,
    { min_value: 20, max_value: 94 },
  ]),
  [WeaponIds.RecurveBow]: WeaponClass.init([
    WeaponIds.RecurveBow,
    "Изогнутый лук",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Bow,
    { min_value: 38, max_value: 354 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.102, 1), max_value: numberFormatPercent(0.469, 1) },
  ]),
  [WeaponIds.RedhornStonethresher]: WeaponClass.init([
    WeaponIds.RedhornStonethresher,
    "Краснорогий камнеруб",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.RightfulReward]: WeaponClass.init([
    WeaponIds.RightfulReward,
    "Справедливая награда",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.RingOfYaxche]: WeaponClass.init([
    WeaponIds.RingOfYaxche,
    "Кольцо Яшче",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.RoyalBow]: WeaponClass.init([
    WeaponIds.RoyalBow,
    "Королевский лук",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.RoyalGreatsword]: WeaponClass.init([
    WeaponIds.RoyalGreatsword,
    "Королевский двуручный меч",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.RoyalGrimoire]: WeaponClass.init([
    WeaponIds.RoyalGrimoire,
    "Королевский гримуар",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.RoyalLongsword]: WeaponClass.init([
    WeaponIds.RoyalLongsword,
    "Меч аристократов",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.RoyalSpear]: WeaponClass.init([
    WeaponIds.RoyalSpear,
    "Королевское копьё",
    4,
    WeaponSource.PaimonsBargains,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.Rust]: WeaponClass.init([
    WeaponIds.Rust,
    "Ржавый лук",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SacrificialBow]: WeaponClass.init([
    WeaponIds.SacrificialBow,
    "Церемониальный лук",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.SacrificialFragments]: WeaponClass.init([
    WeaponIds.SacrificialFragments,
    "Церемониальные мемуары",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.ElementalMastery,
    { min_value: 48, max_value: 221 },
  ]),
  [WeaponIds.SacrificialGreatsword]: WeaponClass.init([
    WeaponIds.SacrificialGreatsword,
    "Церемониальный двуручный меч",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.SacrificialJade]: WeaponClass.init([
    WeaponIds.SacrificialJade,
    "Жертвенный нефрит",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.SacrificialSword]: WeaponClass.init([
    WeaponIds.SacrificialSword,
    "Церемониальный меч",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.SapwoodBlade]: WeaponClass.init([
    WeaponIds.SapwoodBlade,
    "Деревянный клинок",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.ScionOfTheBlazingSun]: WeaponClass.init([
    WeaponIds.ScionOfTheBlazingSun,
    "Наследник слепящего солнца",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 565 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.040, 1), max_value: numberFormatPercent(0.184, 1) },
  ]),
  [WeaponIds.SequenceOfSolitude]: WeaponClass.init([
    WeaponIds.SequenceOfSolitude,
    "Каденция одиночества",
    4,
    "Событие версии 5.6 «Кружащийся вальс»",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SerenitysCall]: WeaponClass.init([
    WeaponIds.SerenitysCall,
    "Зов безмятежности",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Sword,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.SerpentSpine]: WeaponClass.init([
    WeaponIds.SerpentSpine,
    "Меч драконьей кости",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.SharpshootersOath]: WeaponClass.init([
    WeaponIds.SharpshootersOath,
    "Клятва стрелка",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 39, max_value: 401 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.102, 1), max_value: numberFormatPercent(0.469, 1) },
  ]),
  [WeaponIds.SilvershowerHeartstrings]: WeaponClass.init([
    WeaponIds.SilvershowerHeartstrings,
    "Сердечные струны дождя",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 44, max_value: 542 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.SkyriderGreatsword]: WeaponClass.init([
    WeaponIds.SkyriderGreatsword,
    "Большой меч небесного всадника",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Claymore,
    { min_value: 39, max_value: 401 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.439, 1) },
  ]),
  [WeaponIds.SkyriderSword]: WeaponClass.init([
    WeaponIds.SkyriderSword,
    "Меч небесного всадника",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 38, max_value: 354 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.113, 1), max_value: numberFormatPercent(0.521, 1) },
  ]),
  [WeaponIds.SkywardAtlas]: WeaponClass.init([
    WeaponIds.SkywardAtlas,
    "Небесный атлас",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.072, 1), max_value: numberFormatPercent(0.331, 1) },
  ]),
  [WeaponIds.SkywardBlade]: WeaponClass.init([
    WeaponIds.SkywardBlade,
    "Небесный меч",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 46, max_value: 608 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.SkywardHarp]: WeaponClass.init([
    WeaponIds.SkywardHarp,
    "Небесное крыло",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.SkywardPride]: WeaponClass.init([
    WeaponIds.SkywardPride,
    "Небесное величие",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 48, max_value: 674 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.SkywardSpine]: WeaponClass.init([
    WeaponIds.SkywardSpine,
    "Небесная ось",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Polearm,
    { min_value: 48, max_value: 674 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.080, 1), max_value: numberFormatPercent(0.368, 1) },
  ]),
  [WeaponIds.Slingshot]: WeaponClass.init([
    WeaponIds.Slingshot,
    "Рогатка",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 38, max_value: 354 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.068, 1), max_value: numberFormatPercent(0.312, 1) },
  ]),
  [WeaponIds.SnareHook]: WeaponClass.init([
    WeaponIds.SnareHook,
    "Крюк силка",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.SnowTombedStarsilver]: WeaponClass.init([
    WeaponIds.SnowTombedStarsilver,
    "Заснеженное звёздное серебро",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.075, 1), max_value: numberFormatPercent(0.345, 1) },
  ]),
  [WeaponIds.SolarPearl]: WeaponClass.init([
    WeaponIds.SolarPearl,
    "Солнечная жемчужина",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.SongOfBrokenPines]: WeaponClass.init([
    WeaponIds.SongOfBrokenPines,
    "Песнь разбитых сосен",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 49, max_value: 741 },
    StatIds.PhysicalDmgBonus,
    { min_value: numberFormatPercent(0.045, 1), max_value: numberFormatPercent(0.207, 1) },
  ]),
  [WeaponIds.SongOfStillness]: WeaponClass.init([
    WeaponIds.SongOfStillness,
    "Мелодия покоя",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SplendorOfTranquilWaters]: WeaponClass.init([
    WeaponIds.SplendorOfTranquilWaters,
    "Блеск тихих вод",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.StaffOfHoma]: WeaponClass.init([
    WeaponIds.StaffOfHoma,
    "Посох Хомы",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.StaffOfTheScarletSands]: WeaponClass.init([
    WeaponIds.StaffOfTheScarletSands,
    "Посох алых песков",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 542 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.StarcallersWatch]: WeaponClass.init([
    WeaponIds.StarcallersWatch,
    "Бдение взывающего к звёздам",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.SturdyBone]: WeaponClass.init([
    WeaponIds.SturdyBone,
    "Крепкая кость",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 565 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.SummitShaper]: WeaponClass.init([
    WeaponIds.SummitShaper,
    "Кромсатель пиков",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.SunnyMorningSleepIn]: WeaponClass.init([
    WeaponIds.SunnyMorningSleepIn,
    "Сон солнечным утром",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.ElementalMastery,
    { min_value: 58, max_value: 265 },
  ]),
  [WeaponIds.SurfsUp]: WeaponClass.init([
    WeaponIds.SurfsUp,
    "Лови волну",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.SwordOfDescension]: WeaponClass.init([
    WeaponIds.SwordOfDescension,
    "Меч нисхождения",
    4,
    "Внутриигровая почта \"PlayStation Network\"",
    WeaponTypeIds.Sword,
    { min_value: 39, max_value: 440 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.SwordOfNarzissenkreuz]: WeaponClass.init([
    WeaponIds.SwordOfNarzissenkreuz,
    "Меч Нарциссенкрейца",
    4,
    "Серия заданий мира «По следам Нарцисса»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.SymphonistOfScents]: WeaponClass.init([
    WeaponIds.SymphonistOfScents,
    "Симфонист ароматов",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.TalkingStick]: WeaponClass.init([
    WeaponIds.TalkingStick,
    "Говорящая палица",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.040, 1), max_value: numberFormatPercent(0.184, 1) },
  ]),
  [WeaponIds.TamayurateiNoOhanashi]: WeaponClass.init([
    WeaponIds.TamayurateiNoOhanashi,
    "Тамаюратэй но оханаси",
    4,
    "Событие версии 5.4 «Чудесные истории фестиваля Микавы»",
    WeaponTypeIds.Polearm,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.TheAlleyFlash]: WeaponClass.init([
    WeaponIds.TheAlleyFlash,
    "Вспышка во тьме",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 45, max_value: 620 },
    StatIds.ElementalMastery,
    { min_value: 12, max_value: 55 },
  ]),
  [WeaponIds.TheBell]: WeaponClass.init([
    WeaponIds.TheBell,
    "Меч-колокол",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TheBlackSword]: WeaponClass.init([
    WeaponIds.TheBlackSword,
    "Чёрный меч",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.TheCatch]: WeaponClass.init([
    WeaponIds.TheCatch,
    "«Улов»",
    4,
    "Ассоциация рыболовов Инадзумы",
    WeaponTypeIds.Polearm,
    { min_value: 42, max_value: 510 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.100, 1), max_value: numberFormatPercent(0.459, 1) },
  ]),
  [WeaponIds.TheDockhandsAssistant]: WeaponClass.init([
    WeaponIds.TheDockhandsAssistant,
    "Верфь",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TheFirstGreatMagic]: WeaponClass.init([
    WeaponIds.TheFirstGreatMagic,
    "Первый великий фокус",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.TheFlute]: WeaponClass.init([
    WeaponIds.TheFlute,
    "Меч-флейта",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TheStringless]: WeaponClass.init([
    WeaponIds.TheStringless,
    "Бесструнный",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.TheUnforged]: WeaponClass.init([
    WeaponIds.TheUnforged,
    "Некованый",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.TheViridescentHunt]: WeaponClass.init([
    WeaponIds.TheViridescentHunt,
    "Зелёный лук",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.TheWidsith]: WeaponClass.init([
    WeaponIds.TheWidsith,
    "Песнь странника",
    4,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.120, 1), max_value: numberFormatPercent(0.551, 1) },
  ]),
  [WeaponIds.ThrillingTalesOfDragonSlayers]: WeaponClass.init([
    WeaponIds.ThrillingTalesOfDragonSlayers,
    "Эпос о драконоборцах",
    3,
    WeaponSource.Wish,
    WeaponTypeIds.Catalyst,
    { min_value: 39, max_value: 401 },
    StatIds.HpPercentage,
    { min_value: numberFormatPercent(0.077, 1), max_value: numberFormatPercent(0.352, 1) },
  ]),
  [WeaponIds.ThunderingPulse]: WeaponClass.init([
    WeaponIds.ThunderingPulse,
    "Громовой пульс",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Bow,
    { min_value: 46, max_value: 608 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.144, 1), max_value: numberFormatPercent(0.662, 1) },
  ]),
  [WeaponIds.TidalShadow]: WeaponClass.init([
    WeaponIds.TidalShadow,
    "Тень волны",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.090, 1), max_value: numberFormatPercent(0.413, 1) },
  ]),
  [WeaponIds.TomeOfTheEternalFlow]: WeaponClass.init([
    WeaponIds.TomeOfTheEternalFlow,
    "Обряд вечного течения",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.ToukabouShigure]: WeaponClass.init([
    WeaponIds.ToukabouShigure,
    "Токабо сигурэ",
    4,
    "Событие версии 3.3 «Акицу Кимодамэси»",
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.TravelersHandySword]: WeaponClass.init([
    WeaponIds.TravelersHandySword,
    "Меч путешественника",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Sword,
    { min_value: 40, max_value: 448 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.064, 1), max_value: numberFormatPercent(0.293, 1) },
  ]),
  [WeaponIds.TulaytullahsRemembrance]: WeaponClass.init([
    WeaponIds.TulaytullahsRemembrance,
    "Воспоминания Тулайтуллы",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.TwinNephrite]: WeaponClass.init([
    WeaponIds.TwinNephrite,
    "Парный нефрит",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Catalyst,
    { min_value: 40, max_value: 448 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.034, 1), max_value: numberFormatPercent(0.156, 1) },
  ]),
  [WeaponIds.UltimateOverlordsMegaMagicSword]: WeaponClass.init([
    WeaponIds.UltimateOverlordsMegaMagicSword,
    "«Магический супермеч высшего владыки»",
    4,
    "Событие версии 4.3 «Розы и мушкеты»",
    WeaponTypeIds.Claymore,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.UrakuMisugiri]: WeaponClass.init([
    WeaponIds.UrakuMisugiri,
    "Ураку мисугири",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 44, max_value: 542 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.192, 1), max_value: numberFormatPercent(0.882, 1) },
  ]),
  [WeaponIds.Verdict]: WeaponClass.init([
    WeaponIds.Verdict,
    "Вердикт",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Claymore,
    { min_value: 48, max_value: 674 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.048, 1), max_value: numberFormatPercent(0.221, 1) },
  ]),
  [WeaponIds.VividNotions]: WeaponClass.init([
    WeaponIds.VividNotions,
    "Переливающиеся чаяния",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 48, max_value: 674 },
    StatIds.CritDMG,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.441, 1) },
  ]),
  [WeaponIds.VortexVanquisher]: WeaponClass.init([
    WeaponIds.VortexVanquisher,
    "Покоритель вихря",
    5,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.WanderingEvenstar]: WeaponClass.init([
    WeaponIds.WanderingEvenstar,
    "Скитающаяся звезда",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.WavebreakersFin]: WeaponClass.init([
    WeaponIds.WavebreakersFin,
    "Режущий волны плавник",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Polearm,
    { min_value: 45, max_value: 620 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.030, 1), max_value: numberFormatPercent(0.138, 1) },
  ]),
  [WeaponIds.WaveridingWhirl]: WeaponClass.init([
    WeaponIds.WaveridingWhirl,
    "Вихрь на волнах",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 41, max_value: 454 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.133, 1), max_value: numberFormatPercent(0.613, 1) },
  ]),
  [WeaponIds.WhiteIronGreatsword]: WeaponClass.init([
    WeaponIds.WhiteIronGreatsword,
    "Меч из белого железа",
    3,
    WeaponSource.Chests,
    WeaponTypeIds.Claymore,
    { min_value: 39, max_value: 401 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.096, 1), max_value: numberFormatPercent(0.439, 1) },
  ]),
  [WeaponIds.WhiteTassel]: WeaponClass.init([
    WeaponIds.WhiteTassel,
    "Белая кисть",
    3,
    "Сундуки Ли Юэ",
    WeaponTypeIds.Polearm,
    { min_value: 39, max_value: 401 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.051, 1), max_value: numberFormatPercent(0.234, 1) },
  ]),
  [WeaponIds.Whiteblind]: WeaponClass.init([
    WeaponIds.Whiteblind,
    "Белая тень",
    4,
    WeaponSource.Forged,
    WeaponTypeIds.Claymore,
    { min_value: 42, max_value: 510 },
    StatIds.DefPercentage,
    { min_value: numberFormatPercent(0.113, 1), max_value: numberFormatPercent(0.517, 1) },
  ]),
  [WeaponIds.WindblumeOde]: WeaponClass.init([
    WeaponIds.WindblumeOde,
    "Ода анемонии",
    4,
    "Событие версии 1.4 «Приглашение ветряных цветов»",
    WeaponTypeIds.Bow,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
  [WeaponIds.WineAndSong]: WeaponClass.init([
    WeaponIds.WineAndSong,
    "Вино и песни",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Catalyst,
    { min_value: 44, max_value: 565 },
    StatIds.EnergyRecharge,
    { min_value: numberFormatPercent(0.067, 1), max_value: numberFormatPercent(0.306, 1) },
  ]),
  [WeaponIds.WolfFang]: WeaponClass.init([
    WeaponIds.WolfFang,
    "Волчий клык",
    4,
    WeaponSource.BattlePass,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.CritRate,
    { min_value: numberFormatPercent(0.060, 1), max_value: numberFormatPercent(0.276, 1) },
  ]),
  [WeaponIds.WolfsGravestone]: WeaponClass.init([
    WeaponIds.WolfsGravestone,
    "Волчья погибель",
    5,
    WeaponSource.Wish,
    WeaponTypeIds.Claymore,
    { min_value: 46, max_value: 608 },
    StatIds.AtkPercentage,
    { min_value: numberFormatPercent(0.108, 1), max_value: numberFormatPercent(0.496, 1) },
  ]),
  [WeaponIds.XiphosMoonlight]: WeaponClass.init([
    WeaponIds.XiphosMoonlight,
    "Лунное сияние ксифоса",
    4,
    WeaponSource.EventWishExclusive,
    WeaponTypeIds.Sword,
    { min_value: 42, max_value: 510 },
    StatIds.ElementalMastery,
    { min_value: 36, max_value: 165 },
  ]),
} as Record<Weapon["id"], Weapon>;
